### ISSUE TITLE
Error with asp.net core RTM

### ISSUE THREAD

**Issue by MoxxNull** [aspnet-contrib/AspNet.Security.OAuth.Providers#102]
Using "app.UseOAuthValidation();" 

`              var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(dir)                  
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();
`

throws:

> An unhandled exception of type 'System.TypeLoadException' occurred in mscorlib.dll
> 
> Additional information: Der Typ "Microsoft.AspNetCore.DataProtection.DataProtectionExtensions" in der Assembly "Microsoft.AspNetCore.DataProtection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" konnte nicht geladen werden.

UPDATE: My bad, sorry, using a newer version of your library fixed it :)  1.0.0-alpha3-0181 is fine.

**Comment by mtaanquist** [comment]
I am seeing the same issue using the latest BattleNet provider. The error doesn't occur until you attempt to add the service to Startup.cs and add in the ClientId/ClientSecret in the options.

**Comment by PinpointTownes** [comment]
> I am seeing the same issue using the latest BattleNet provider.

You need to use the `1.0.0-beta1-final` version, available on the MyGet feed. It should be pushed to NuGet.org soon.

**Comment by PinpointTownes** [comment]
FYI, the aspnet-contrib OAuth2/OpenID2 providers for ASP.NET Core are now on NuGet.org
