### ISSUE TITLE
Add Google provider

### ISSUE THREAD

**Issue by Alber70g** [aspnet-contrib/AspNet.Security.OAuth.Providers#105]

**Comment by PinpointTownes** [comment]
FYI, the Google provider is maintained by the ASP.NET Core team: https://github.com/aspnet/Security/tree/dev/src/Microsoft.AspNetCore.Authentication.Google

Is this something you had in mind?

**Comment by Alber70g** [comment]
Yes it is. I wasn't aware of this one. Thanks a lot!
