### ISSUE TITLE
Samples project doesn't build on VSCode Linux

### ISSUE THREAD

**Issue by fearlesscoder** [aspnet-contrib/AspNet.Security.OAuth.Providers#111]
Project AspNet.Security.OAuth.ArcGIS (.NETFramework,Version=v4.5.1) will be compiled because expected outputs are missing
Compiling AspNet.Security.OAuth.ArcGIS for .NETFramework,Version=v4.5.1
/ssd/src/netcore/AspNet.Security.OAuth.Providers/src/AspNet.Security.OAuth.ArcGIS/project.json(41,15): error DOTNET1012: The reference assemblies directory was not specified. You can set the location using the DOTNET_REFERENCE_ASSEMBLIES_PATH environment variable.
/ssd/src/netcore/AspNet.Security.OAuth.Providers/src/AspNet.Security.OAuth.ArcGIS/project.json(35,41): error NU1001: The dependency mscorlib could not be resolved.
/ssd/src/netcore/AspNet.Security.OAuth.Providers/src/AspNet.Security.OAuth.ArcGIS/project.json(37,56): error NU1001: The dependency System could not be resolved.
/ssd/src/netcore/AspNet.Security.OAuth.Providers/src/AspNet.Security.OAuth.ArcGIS/project.json(36,30): error NU1001: The dependency System could not be resolved.
/ssd/src/netcore/AspNet.Security.OAuth.Providers/src/AspNet.Security.OAuth.ArcGIS/project.json(35,41): error NU1001: The dependency System could not be resolved.
/ssd/src/netcore/AspNet.Security.OAuth.Providers/src/AspNet.Security.OAuth.ArcGIS/project.json(37,56): error NU1001: The dependency System could not be resolved.
/ssd/src/netcore/AspNet.Security.OAuth.Providers/src/AspNet.Security.OAuth.ArcGIS/project.json(36,30): error NU1001: The dependency System could not be resolved.
/ssd/src/netcore/AspNet.Security.OAuth.Providers/src/AspNet.Security.OAuth.ArcGIS/project.json(35,41): error NU1001: The dependency System could not be resolved.
/ssd/src/netcore/AspNet.Security.OAuth.Providers/src/AspNet.Security.OAuth.ArcGIS/project.json(37,56): error NU1001: The dependency System.Core could not be resolved.
/ssd/src/netcore/AspNet.Security.OAuth.Providers/src/AspNet.Security.OAuth.ArcGIS/project.json(36,30): error NU1001: The dependency System.Core could not be resolved.
/ssd/src/netcore/AspNet.Security.OAuth.Providers/src/AspNet.Security.OAuth.ArcGIS/project.json(35,41): error NU1001: The dependency System.Core could not be resolved.
/ssd/src/netcore/AspNet.Security.OAuth.Providers/src/AspNet.Security.OAuth.ArcGIS/project.json(37,56): error NU1001: The dependency System.Core could not be resolved.
/ssd/src/netcore/AspNet.Security.OAuth.Providers/src/AspNet.Security.OAuth.ArcGIS/project.json(36,30): error NU1001: The dependency System.Core could not be resolved.
/ssd/src/netcore/AspNet.Security.OAuth.Providers/src/AspNet.Security.OAuth.ArcGIS/project.json(35,41): error NU1001: The dependency System.Core could not be resolved.
/ssd/src/netcore/AspNet.Security.OAuth.Providers/src/AspNet.Security.OAuth.ArcGIS/project.json(35,41): error NU1001: The dependency Microsoft.CSharp could not be resolved.
/ssd/src/netcore/AspNet.Security.OAuth.Providers/src/AspNet.Security.OAuth.ArcGIS/project.json(37,56): error NU1001: The dependency System.Net.Http could not be resolved.
/ssd/src/netcore/AspNet.Security.OAuth.Providers/src/AspNet.Security.OAuth.ArcGIS/project.json(37,56): error NU1001: The dependency System.Security could not be resolved.
/ssd/src/netcore/AspNet.Security.OAuth.Providers/src/AspNet.Security.OAuth.ArcGIS/project.json(37,56): error NU1001: The dependency System.Xml could not be resolved.
/ssd/src/netcore/AspNet.Security.OAuth.Providers/src/AspNet.Security.OAuth.ArcGIS/project.json(37,56): error NU1001: The dependency System.Xml.Linq could not be resolved.
/ssd/src/netcore/AspNet.Security.OAuth.Providers/src/AspNet.Security.OAuth.ArcGIS/project.json(36,30): error NU1001: The dependency System.ComponentModel.Composition could not be resolved.
/ssd/src/netcore/AspNet.Security.OAuth.Providers/src/AspNet.Security.OAuth.ArcGIS/project.json(37,56): error NU1001: The dependency System.ComponentModel.Composition could not be resolved.
Compilation failed.
    0 Warning(s)
    21 Error(s)

**Comment by PinpointTownes** [comment]
I suppose you don't have Mono on your machine? Note that it's required to be able to compile .NET Desktop 4.5.1 assemblies.
