### ISSUE TITLE
Did you plan to add support for oauth1.0?

### ISSUE THREAD

**Issue by arielcloud** [aspnet-contrib/AspNet.Security.OAuth.Providers#114]
thanks!

**Comment by PinpointTownes** [comment]
Nope, there's no plan to introduce a generic OAuth1 provider since it's almost completely dead. If you need to target a legacy server, I'd recommend copying the implementation used by the Twitter provider: https://github.com/aspnet/Security/tree/dev/src/Microsoft.AspNetCore.Authentication.Twitter

**Comment by arielcloud** [comment]
thanks!

note that the description in nuget is:
"ASP.NET Core middleware that enables an application to support Twitter's **OAuth 2.0** authentication workflow."

and if I understand you - it should be OAuth 1.0

**Comment by PinpointTownes** [comment]
@arielcloud haha, nice catch. I opened a ticket for you: https://github.com/aspnet/Security/issues/962 :+1:

**Comment by arielcloud** [comment]
I'm implementing a QuickBooks provider (OAuth 1.0, I started from the twitter code).
If I'll open a PR, will you want to add this? or should i add it as external nuget package?
