### ISSUE TITLE
Add Autodesk provider

### ISSUE THREAD

**Issue by hotchkj** [aspnet-contrib/AspNet.Security.OAuth.Providers#120]
Autodesk has a public OAuth workflow for https://developer.autodesk.com for our Forge platform and we have internal code that supports the type of middleware that this repo offers.

Before I begin the process of us setting that up to be externally contributed to here, I wanted to check a little more formally in an issue that this is still the right repo, and if there's anything specific other than the main contributing guidelines we should be aware of.

Thanks in advance!

**Comment by PinpointTownes** [comment]
Hey @hotchkj,

> I wanted to check a little more formally in an issue that this is still the right repo

Assuming Autodesk supports the OAuth2 authorization code flow (AFAICT, it does), yep, this is the right repo.

> and if there's anything specific other than the main contributing guidelines we should be aware of.

Nope, but feel free to ping me if you need more details or have any question.

Thanks!

**Comment by PinpointTownes** [comment]
Done (more than 2 months ago :trollface:).
