### ISSUE TITLE
OAuth.Reddit sends redirect_uri as encoded

### ISSUE THREAD

**Issue by MHolst1** [aspnet-contrib/AspNet.Security.OAuth.Providers#129]
Not sure where to override it, but when authenticating with Reddit, the query string includes my redirect_uri but encoded, so authentication fails when the URL is sent to Reddit.

e.g. http://localhost is http%3A%2F%2Flocalhost

**Comment by PinpointTownes** [comment]
I'm not sure to understand how it's a problem, as it's what the specification requires: 

> The client constructs the request URI by adding the following parameters to the query component of the authorization endpoint URI using the "application/x-www-form-urlencoded" format, per Appendix B:

>
```
GET /authorize?response_type=code&client_id=s6BhdRkqt3&state=xyz
    &redirect_uri=https%3A%2F%2Fclient%2Eexample%2Ecom%2Fcb HTTP/1.1
Host: server.example.com
```

https://tools.ietf.org/html/rfc6749#section-4.1.1

Could you please share the exact error you're seeing?

**Comment by MHolst1** [comment]
Yep, it's the "you sent an invalid request — invalid redirect_uri parameter" error that reddit sends when the redirect_uri doesn't match what you have on file with them..  If I manually take that same string and replace the encoding with actual slashes, etc., the authentication succeeds.

**Comment by MHolst1** [comment]
After a little more testing it looks like the "&" is missing after the redirect_uri (when adding in the redirect_uri myself I was adding the ampersand)

**Comment by PinpointTownes** [comment]
Please share the exact URL the Reddit middleware redirects you to, and the redirect_uri you associated with your Reddit app.

**Comment by MHolst1** [comment]
After a little more testing it looks like the "&" is missing after the redirect_uri (when adding in the redirect_uri myself I was adding the ampersand)

To clarify, my query string looks like 

&redirect_uri=http%3A%2F%2Flocalhost%3A59826%2Fsignin-reddit

when it should look like 

&redirect_uri=http%3A%2F%2Flocalhost%3A59826%2F&signin-reddit"

My redirect Uri is "http://localhost:59826/".

I was previously incorrect in thinking that the encoding was the issue.  It's the missing ampersand (adding it myself leads to Reddit's "allow access" screen)

**Comment by PinpointTownes** [comment]
Your issue is actually way more simpler... you're just using the wrong `redirect_uri`.

The default callback path is set to `/signin-reddit`, so your `redirect_uri` should be `http://localhost:59826/signin-reddit`.

**Comment by MHolst1** [comment]
Aha!  Now I see, thank you very much for taking the time to help me!
