### ISSUE TITLE
Add Reddit provider

### ISSUE THREAD

**Issue by jerriep** [aspnet-contrib/AspNet.Security.OAuth.Providers#13]

**Comment by tparnell8** [comment]
I can grab this...

**Comment by PinpointTownes** [comment]
Implemented: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/37d32d1af5a127f1dd89d4ef6b3cf4697d4f0866

Thanks for your contribution @tparnell8 :+1:
