### ISSUE TITLE
Github provider: UserEmailsEndpoint in GitHubAuthenticationOptions readonly?

### ISSUE THREAD

**Issue by codeclash** [aspnet-contrib/AspNet.Security.OAuth.Providers#130]
I want to use the [Github provider](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/tree/dev/src/AspNet.Security.OAuth.GitHub) for **Github Enterprise** (= Github on premise, not github.com, see [Api](https://developer.github.com/v3/enterprise/)), and can override all the [default endpoints](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/dev/src/AspNet.Security.OAuth.GitHub/GitHubAuthenticationDefaults.cs#L38-L48), **except** for the `UserEmailsEndpoint`, which for a reason not obvious to me is [**readonly**](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/dev/src/AspNet.Security.OAuth.GitHub/GitHubAuthenticationOptions.cs#L31) in `GitHubAuthenticationOptions`:

``` csharp
/// <summary>
/// Gets or sets the address of the endpoint exposing
/// the email addresses associated with the logged in user.
/// </summary>
public string UserEmailsEndpoint { get; } = GitHubAuthenticationDefaults.UserEmailsEndpoint;
```
Is there any reason to this? Why can't I just override that endpoint like the others?

**Comment by PinpointTownes** [comment]
Sounds like an oversight. Feel free to send a PR to fix that 👍

**Comment by PinpointTownes** [comment]
Merged: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/3ab1ca90ff491c5541432461600ae97a0c5ebcc6 :tada: 

Thanks for the fix.
