### ISSUE TITLE
AuthenticationProperties.RedirectUri not respected

### ISSUE THREAD

**Issue by lwansbrough** [aspnet-contrib/AspNet.Security.OAuth.Providers#133]
Maybe I'm just misunderstanding the implementation. I'm trying to add additional query parameters to the `redirect_uri` parameter at runtime. This is allowed according to the OAuth 2.0 spec. My goal is to add a `returnUrl` parameter to the redirect URI so that I can bounce the user from `/auth/callback` (the default redirect URI) back to the page they were on before they logged in.

I'm attempting to accomplish this with the following line:

`return Challenge(new AuthenticationProperties { RedirectUri = redirectUri }, MyCustomAuthenticationDefaults.AuthenticationScheme);`

For the implementation of the middleware, I just used one of the existing implementations in this repo and customized it a bit.

What I get instead of `/auth/callback?returnUrl=http%3A%2F%2Flocalhost%3A49646%2Ftest` is just `/auth/callback` -- so is the `RedirectUri` being ignored?

**Comment by PinpointTownes** [comment]
> I'm trying to add additional query parameters to the redirect_uri parameter at runtime. This is allowed according to the OAuth 2.0 spec.

That's not how it's implemented by the ASP.NET Core OAuth2 generic middleware (and more generally, by most clients). Instead, it stores the `returnUrl` in the `state` parameter.
