### ISSUE TITLE
LinkedIn provider fields throw exception

### ISSUE THREAD

**Issue by StummeJ** [aspnet-contrib/AspNet.Security.OAuth.Providers#136]
Using the `AddRange()` on the `LinkedInAuthenticationOptions.Fields` HashSet throws a FileNotFound exception:
```
System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Packaging, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'NuGet.Packaging, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
```
Changing it to the `Add()` method fixes the exception.  We were trying to add given name, surname, and profile picture url claims which are added by default to the official Google OAuth 2.0 provider. 

I am curious why the LinkedIn provider is the only one that has this `Fields` set compared to the standard pattern of adding optional claims via the `OnCreatingTicket` delegate.

**Comment by PinpointTownes** [comment]
> Using the AddRange() on the LinkedInAuthenticationOptions.Fields HashSet throws a FileNotFound exception:

Is `AddRange()` a NuGet extension? I wouldn't recommend using it.

> I am curious why the LinkedIn provider is the only one that has this Fields set compared to the standard pattern of adding optional claims via the OnCreatingTicket delegate.

Actually, it's not. The FB middleware does exactly the same thing. You can find more information here: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/95

**Comment by StummeJ** [comment]
Should it return the givenName and surname claims by default then?  I know fb does this.

**Comment by PinpointTownes** [comment]
Sounds like a reasonable demand. Go ahead and submit a PR to fix that :+1:

**Comment by PinpointTownes** [comment]
I went ahead and added the first and last names to the default fields list: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/7a019e2b81011c27a504b88e42c32d9329d27138.
