### ISSUE TITLE
Support chinese social website login

### ISSUE THREAD

**Issue by zhengchun** [aspnet-contrib/AspNet.Security.OAuth.Providers#138]
Hello, do you have any plans to support chinese social website login? like the following website: 
[QQ](http://wiki.open.qq.com/wiki/mobile/OAuth2.0%E7%AE%80%E4%BB%8B)
[Weibo](http://weibo.com/)
[Wechat](https://web.wechat.com/?lang=en_US)
These are Chinese Social Media sites and support OAuth login for the external website.

**Comment by PinpointTownes** [comment]
Hey,

> do you have any plans to support chinese social website login? like the following website:

This repository is open to contributions, so feel free to submit a PR to support these providers :smile:

**Comment by zhengchun** [comment]
OK,I got it:smile:

**Comment by PinpointTownes** [comment]
Done: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/948151c231f1a9d14b3580f1b3b6e5a3a282ec6e

@zhengchun thanks!
