### ISSUE TITLE
Migrate solution and projects to new format

### ISSUE THREAD

**Issue by StummeJ** [aspnet-contrib/AspNet.Security.OAuth.Providers#139]
Seems like all of the cool kids (aka aspnet) are moving to the new project format `csproj`.  Once you have the new sdk and tools installed its next to impossible to open the project.

**Comment by PinpointTownes** [comment]
Done: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/1d97a85f9e95ea8de011287983af5ef0a07c6098
