### ISSUE TITLE
Add Salesforce provider

### ISSUE THREAD

**Issue by jerriep** [aspnet-contrib/AspNet.Security.OAuth.Providers#14]

**Comment by abhinavnigam** [comment]
I am taking this.

**Comment by amattie** [comment]
@abhinavnigam You start working on this recently? I don't mind taking it, but I don't want to duplicate efforts.

**Comment by PinpointTownes** [comment]
@amattie FYI, the yeoman generator needs a serious update, you may have to manually fix the resulting `project.json` to work correctly with .NET CLI. Feel free to take a look at the other providers, as they have all been updated for RC2.

**Comment by amattie** [comment]
Awesome timing. Thanks. I was trying to pin to RC1 to fix, but working backwards from something that's working with RC2 is easier.

**Comment by PinpointTownes** [comment]
Yeah, don't try to target RC1, I'm even pretty sure CI would never pass with DNX-dependents packages (`release` targets the incoming RC2 bits while `dev` currently targets RC3/RTM) :smile:

**Comment by PinpointTownes** [comment]
Merged, thanks: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/14618f683087936a784b1191215f857583ae880f :clap:
