### ISSUE TITLE
Is there a way to set the scopes from an mvc controller?

### ISSUE THREAD

**Issue by Gronsak** [aspnet-contrib/AspNet.Security.OAuth.Providers#146]
I'm currently working with the EVEOnline provider and I want to let the user choose what scopes to use due to it giving access to sensitive information and the functionality it opens up on my site being entirely optional.

So is there an easy way to set different scopes for every authentication request?

**Comment by PinpointTownes** [comment]
Moved to https://github.com/aspnet/Security/issues/1139.
