### ISSUE TITLE
Add a Discord Provider

### ISSUE THREAD

**Issue by ablankholm** [aspnet-contrib/AspNet.Security.OAuth.Providers#152]
Had to set this up for a project I'm working on. Will submit a pull request.

Homepage:
https://discordapp.com/

OAuth Docs:
https://discordapp.com/developers/docs/topics/oauth2

**Comment by ablankholm** [comment]
Submited as [https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/153](#153). 

Let me know if anything else is needed.

**Comment by PinpointTownes** [comment]
Done: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/fe436f3cb1d8f36ed1ca54669ce55ce43eb66fde.
