### ISSUE TITLE
Add an Amazon provider

### ISSUE THREAD

**Issue by martincostello** [aspnet-contrib/AspNet.Security.OAuth.Providers#156]
_Originally raised as aspnet/Security#1204_

I recently implemented support for Amazon login in a project by building on top of the OAuth NuGet package.

Would there be any interest in accepting a PR to make an implementation of that available in this repo like there is for Facebook, Twitter etc.? I can't see an existing one, or one in progress in the issues or PR list.

I thought I'd ask before starting the PR, rather than just submit it out of the blue.

**Comment by PinpointTownes** [comment]
Sure, feel free to send a PR :+1:

**Comment by PinpointTownes** [comment]
Done: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/12cc086ea470d9d9689aef823475c5dd886a8049.
