### ISSUE TITLE
version 1.0.0-rc1-final is not installable

### ISSUE THREAD

**Issue by joaomatossilva** [aspnet-contrib/AspNet.Security.OAuth.Providers#159]
I can't install version 1.0.0-rc1-final on a fresh vanilla asp.net core app.
It complaints it can't find the package AspNet.Security.OAuth.Extensions. And rightfully so, that package has been delisted from Nuget.

**Comment by joaomatossilva** [comment]
Hum.. just saw 034deed now... so I guess it's a matter or time (or next deploy)

**Comment by kevinchalet** [comment]
Thanks for reporting this bug. It was fixed a few hours ago and new packages will be pushed tomorrow: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/158.

**Comment by kevinchalet** [comment]
Unfortunately the fix introduced yesterday doesn't work as intended: the NuGet reference is correctly skipped, but the `AddOptional` extension is not embedded and the `AspNet.Security.OAuth.Extensions` assembly reference is not removed.

I obviously need more time to determine how to fix the bug we're seeing in the marvelous .csproj world (it used to work fine with project.json-based tooling), but in the meantime, I'll upload the extensions package to NuGet.org so you can use the rc1-final packages.

**Comment by joaomatossilva** [comment]
Maybe this is related to https://github.com/NuGet/Home/issues/4853
