### ISSUE TITLE
Add StackExchange provider

### ISSUE THREAD

**Issue by jerriep** [aspnet-contrib/AspNet.Security.OAuth.Providers#16]

**Comment by PinpointTownes** [comment]
FYI, StackExchange also supports OpenID 2.0 :confused: 

You can see https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers/blob/dev/samples/Mvc.Client/Startup.cs for a working sample using the generic OpenID 2.0 authentication middleware.

```csharp
app.UseOpenIdAuthentication("StackExchange", options => {
    options.AuthenticationScheme = "StackExchange";
    options.Caption = "StackExchange";
    options.Authority = new Uri("https://openid.stackexchange.com/");
    options.CallbackPath = new PathString("/signin-stackexchange");
});
```

**Comment by SH2015** [comment]
So does that mean we cant implement AOuth 2 with this provider ?

**Comment by PinpointTownes** [comment]
No no, you can create an OAuth2 provider for StackExchange (it supports both OpenID2 and OAuth2).

Here's the documentation: https://api.stackexchange.com/docs/authentication :smile:

**Comment by SH2015** [comment]
Cool , thanks

**Comment by kappa7194** [comment]
Anyone working on this?

**Comment by SH2015** [comment]
I am working on DropBox for now  , but currently I am having a hard time building the project successfully ,I was getting build errors and after installing DNX  I started getting xproj not defied .

**Comment by PinpointTownes** [comment]
Done: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/113
