### ISSUE TITLE
Can't login with Github

### ISSUE THREAD

**Issue by twenzel** [aspnet-contrib/AspNet.Security.OAuth.Providers#161]
After setting up the GitHub OAuth App and using your GitHub Provider, I can see the Github login/consent screen. After "authorize" click and github redirects to my callback url I get following error from my server:

> An unhandled exception occurred while processing the request.
> 
> IOException: Unable to read data from the transport connection. The connection was closed before all data could be read. Expected 2074 bytes, read 0 bytes.
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> 
> HttpRequestException: Error while copying content to a stream.
> System.Net.Http.HttpContent+<LoadIntoBufferAsyncCore>d__48.MoveNext()
> 
> AggregateException: Unhandled remote failure. (Error while copying content to a stream.)
> Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRemoteCallbackAsync>d__6.MoveNext()

The query was:

> http://localhost:5000/signin-github?code=39c13a76f92bc6903127&state=CfDJ8O60hsWRg19DjZa3U8jxOnKLlZptd3Mq5-m7kHgzz7ctznLw-dTkGP0Ij6Q9WM6-ebiDTXRlpvNWy72luwH_FJtEzwarEIvXmYL77ex5jy_-LYs6nghJkIPqpUeTi8gyg6suesBQrJ6qJys6eEWb1wz2TEbBq8JK3txwBNkvs8xanff7WA-Few5e7rx42w7FuZ-GFmqNIP6EpAQs_fsfaL7TKaBaCQL-C2JjBgSwSlT9K1PKiz9ex5pNp6YDCqLAMewotwMZCv9IceLVZ39wa7kqc6a86jyjohBDDVtWjCaz28oRa1Yt9Trvex7xdd5eiBQ5s5Hf6EPyLhiNrVsjPmvCYSRGGQDvRP5_oSxje2G5vL_sVzxXYucFOjHINm7LdMSoJHKjNL08RDbw-tnVwgQWvptCKDQUUTNfYV2KhJN4J3F4Heuu9SIdPScwXv2hwHid2WFu4X097LJEZmat6ohm7-KBdERVsRMPvjyikeqj8awZqLVUyUek_aceyj7rPrL4sRgdwNGVV7KF-m-xrp1AKKb_fGfUZGvfljUbSNdEQyumjOAiFy0mWn8CKxkQiEtcVoMBkOBduyGDl3CoeP7TR3f6RJuEnWeEyUiqyxa8_FMsrchRF7Mr5B7-TUYSv4DYtu2TPkqJ3v20Vayc2c_Fyzml7KrIi6rpiTNQ35faKhy04UwkGL5J-2hmYZO4-1PTeaivkMJzAtwmO1uV2GSBYdxPbtMIkHDyT4iIi0torp7bcoz8zOgEz0vDnBQEqRYHNFScnehLU6-OZhnqXiY-5nbRcwYgpxklYooSMmMF2Ja7L4C7-OLtwiXTWjQhucu--FLFtpKWpRHNOKEWTVFWMEluHOI5vImJDuwpFGYF3BA6zf1ZoEw_f1pdrTiX3JRMTrn_gPOYgE8r9nS4WVxRvlvpjzPVJKpdYeBRUib_Pr72RNMEsu_ZheDJVuEKgS_B_ZncPjDAIjOlwBIvHjMRiYOzHMBEK4r9d3LFcUM-L7DhzrHoC2-cEkomAd2pqDjKpZG5W97NyjkHlyXfJ6YxH20BkmMBW4YIdP7i2XIlCHp4aEG89rSmoT4cN9rs2NfOycXNnXSI0bVUN8_KeI_0UnmIYwEtVWfSwGoj7NH2abXYdOJVf6oOpA1_l-1CWHnGUP8fcjK0ZYjJLiVRhqAzuQWzseA5gwPL34YYbfiPztolJKTNMMbIScD_G1ch2FZkUAri7Gbck6i18fFLAvrvpu4MwExvaBDcLJNBnF5xfaoCwuHZzND1fPNEYMXq3g

What is my mistake?

**Comment by kevinchalet** [comment]
Interesting. Can you reproduce this issue with other social providers? If so, it might be caused by a firewall issue.

**Comment by twenzel** [comment]
No, at the moment only GitHub is not working. Google Provider is working.
