### ISSUE TITLE
An unhandled exception occurred while processing the request in asp.net core

### ISSUE THREAD

**Issue by snail9367** [aspnet-contrib/AspNet.Security.OAuth.Providers#164]
I have an Asp.net core app which have a feature of OAuth. I set AppID, SecretKey and redirectUrl Like this.
app.UseWeChatAuthentication(new DevZH.AspNetCore.Builder.WeChatOptions()
            {
                AppId = Configuration.GetConnectionString("WechatAppId"),
                AppSecret = Configuration.GetConnectionString("WechatAppSecret"),
                CallbackPath = "/wechat/callback",
                Scope = { "snsapi_login" },      
            });

But the redirect url is not working on local and azure with below error.

Exception: The oauth state was missing or invalid.
Unknown location
AggregateException: Unhandled remote failure. (The oauth state was missing or invalid.)

**Comment by kevinchalet** [comment]
This project doesn't have a WeChat authentication middleware (at least, not yet) so this is likely the wrong place for this bug report.
