### ISSUE TITLE
Adding some LinkedIn fields causes an InvalidCastException

### ISSUE THREAD

**Issue by AlvinStanescu** [aspnet-contrib/AspNet.Security.OAuth.Providers#167]
I attempted to add `api-standard-profile-request` and `site-standard-profile-request` to the fields to retrieve, however as soon as I did that, I was getting an `InvalidCastException: Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken.`

This is due to to the .Value<string> cast failing inside `LinkedInAuthenticationHelper.GetSiteStandardProfileRequest` and `LinkedInAuthenticationHelper.GetApiStandardProfileRequest`.

We should rather follow the pattern set above and convert the `JObject` (if not null) to a string.

**Comment by AlvinStanescu** [comment]
Raised PR #166 to fix this issue.

**Comment by kevinchalet** [comment]
Thanks for reporting this bug, @AlvinStanescu :+1: 

> We should rather follow the pattern set above and convert the JObject (if not null) to a string.

Using `ToString()` will store the complex "request" node as a JSON string, which is not something we usually do in the other providers.

How common are these properties? If they are not commonly used, we could remove the helpers and leave them as an exercise for the end user. If they are worth keeping, maybe we should only extract the URL from the complex JSON node and ignore the headers?

**Comment by jerriep** [comment]
@AlvinStanescu I am not familiar with this, and not set up right now to test it either. Can you please post the resulting JSON which LinkedIn returns when you request that `api-standard-profile-request` permission and also what the JSON result looks like when you **don't** request it?

**Comment by AlvinStanescu** [comment]
@PinpointTownes I don't think these properties are particularly common, I ended up using the public profile URL instead.

@jerriep Sure, by adding `apiStandardProfileRequest` we get the following field added to the profile JSON:

`"apiStandardProfileRequest": {
    "headers": {
      "_total": 1,
      "values": [{
        "name": "x-li-auth-token",
        "value": "name:_Tai"
      }]
    },
    "url": "https://api.linkedin.com/v1/people/D4RHsXYgKr"
  },`

You can also see this in _apigee_ by going [here](https://apigee.com/console/linkedin), picking _Retrieve Profile Data_ and using `https://api.linkedin.com/v1/people/~:(id,num-connections,picture-url,first-name,last-name,location,industry,headline,summary,specialties,positions,site-standard-profile-request,api-standard-profile-request,public-profile-url)?format=json` as the URL. 

When you **don't** request it (by adding it to `LinkedInAuthenticationOptions.Fields`), it simply doesn't get added to the output JSON which can be seen on apigee, hence leading to a successful authentication.

**Comment by jerriep** [comment]
> If they are worth keeping, maybe we should only extract the URL from the complex JSON node and ignore the headers?

Did a quick test, and the problem with this is that making the request to that URL does not seem to work if you do not pass along the correct headers. Actually, I could not even get it to work even when passing along those headers, but I do not have time to play with it and figure it out.

Personally, I would vote for leaving it as an exercise for the user, though it may mean that we will now be breaking things.

BTW, this is a discussion we've had before ;) https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/95

**Comment by kevinchalet** [comment]
> Personally, I would vote for leaving it as an exercise for the user, though it may mean that we will now be breaking things.

Let's do that, then :+1: 

@AlvinStanescu could you please update your PR to remove the 2 helpers? Thanks!

**Comment by kevinchalet** [comment]
Thanks for your contribution. Per discussion, we concluded it was better to simply remove these helpers, which was done as part of 91e709c.
