### ISSUE TITLE
How can I implement a provider with the length of `state` parameter limited

### ISSUE THREAD

**Issue by huww98** [aspnet-contrib/AspNet.Security.OAuth.Providers#168]
I'm going to implement a provider to perform authentication for websites showing inside the WeiXin (aka WeChat) app (different from the existing WeiXin provider). The length of `state` parameter is limited to 128 bytes. However, the length of string provided by [`Options.StateDataFormat.Protect(properties)`](https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OAuth/OAuthHandler.cs#L214) is about 200 to 300 bytes, which results in `state parameter too long` error.

I came up with a solution that I can store the actual `properties` object in the memory and put a GUID in the `state` parameter.

I suppose I can build a class implementing the `ISecureDataFormat<AuthenticationProperties>` interface, and provide a instance to `OAuthOptions.StateDataFormat` property. Then I need to have a `Dictionary` with GUID keys and `AuthenticationProperties` object values in my class.

Please tell me whether this is the right way. I'm not experienced in this.

**Comment by huww98** [comment]
Or I should use `IMemoryCache`?

**Comment by kevinchalet** [comment]
> Please tell me whether this is the right way.

It's an ugly hack, but if your provider doesn't support >128 bytes `state` parameters, that's pretty much your only option.

**Comment by huww98** [comment]
I have successfully implemented it using `IMemoryCache`. May I open a pull request?

**Comment by huww98** [comment]
After I add refrence to `Microsoft.Extensions.Caching.Abstractions`, I get some warnings:

````
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Detected package downgrade: NETStandard.Library from 1.6.1 to 1.6.0
[...\AspNet.Security.OAuth.Providers\src\AspNet.Security.OAuth.WeixinWebpage\AspNet.Security.OAuth.WeixinWebpage.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  AspNet.Security.OAuth.WeixinWebpage (>= 1.0.0-rc2) -> Microsoft.Extensions.Caching.Abstractions (>= 1.1.2) -> NETStandard.Library (>= 1.6.1)
[...\AspNet.Security.OAuth.Providers\src\AspNet.Security.OAuth.WeixinWebpage\AspNet.Security.OAuth.WeixinWebpage.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  AspNet.Security.OAuth.WeixinWebpage (>= 1.0.0-rc2) -> NETStandard.Library (>= 1.6.0)
[...\AspNet.Security.OAuth.Providers\src\AspNet.Security.OAuth.WeixinWebpage\AspNet.Security.OAuth.WeixinWebpage.csproj]
````

How can I deal with this? Should I refrence the lower version of `Microsoft.Extensions.Caching.Abstractions`, or should I update the `NetStandardImplicitPackageVersion` to 1.6.1?

After I update `NetStandardImplicitPackageVersion` to 1.6.1, it seems everything works OK.
