### ISSUE TITLE
Port the social providers to the new ASP.NET Core 2.0 authentication stack

### ISSUE THREAD

**Issue by kevinchalet** [aspnet-contrib/AspNet.Security.OAuth.Providers#170]

**Comment by martincostello** [comment]
Will a final `1.0.0` be published to NuGet before this?

**Comment by kevinchalet** [comment]
@martincostello not sure. The OpenID generic provider - that shares the same versioning as this repository - relies on AngleSharp, that doesn't yet offer a 1.0.0 version :cry:

**Comment by kinosang** [comment]
I wanna to know where should I start the jobs? Is it okay to start working on the `dev` branch? or should we start a new branch for it?

**Comment by runxc1** [comment]
Also wondering about this as I need a Strava login for asp.net core 2.0

**Comment by ntemirov** [comment]
I need vkontakte authentication for asp.net core 2.0. Can I help you?

**Comment by kinosang** [comment]
I'm starting working on it, would you like to create a new branch such as `2.0` because I can't port all those providers at once.

BTW, I'll pay attention to the problems you pointed at aspnet-contrib/AspNet.Security.OpenId.Providers#35.

**Comment by sergeushenecz** [comment]
Hello, everyone.Can I know when you to porting to asp.net core 2.0 VK provider?

**Comment by 0xNF** [comment]
Hey all, I ported the Spotify provider service to the ASP.NET Core 2.0 stack. It's modeled after [Microsoft's own implementations](https://github.com/aspnet/Security/tree/dev/src/Microsoft.AspNetCore.Authentication.MicrosoftAccount) of their Facebook and MicrosoftAccount authorizations.

The problem is that it's a homeless amalgam, and I don't know where to put it. It uses Microsoft's namespaces and dependencies, and thus requires nothing from the other parts of this project, although that could obviously be changed in a future patch. 

Is there a 2.0 branch in the works for this project, or otherwise some place that I can push this? Would be a shame to keep it to myself.

**Comment by kinosang** [comment]
@0xNF that's why I ask for a new branch.

**Comment by vishalmgiri** [comment]
Please update us on Asp.net Core 2 Support.
I am also willing to support it.

**Comment by kevinchalet** [comment]
I created a new [`experimental` branch](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/tree/experimental) and ported the [GitHub provider to ASP.NET Core 2.0](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/tree/experimental/src/AspNet.Security.OAuth.GitHub).

If you want to help migrate the other providers, please use it as a starting point so we keep everything consistent.

Feel free to include multiple providers in a single PR but please push separate commits using the ` Migrate the XYZ provider to ASP.NET Core 2.0` message pattern.

**Comment by kinosang** [comment]
#173 for:

* [x] ArcGIS
* [x] Asana
* [x] Autodesk
* [x] BattleNet
* [x] Discord
* [x] Dropbox
* [x] Imgur
* [x] Paypal
* [x] Reddit
* [x] Twitch
* [x] Vimeo
* [x] Weibo
* [x] Weixin
* [x] WordPress
* [x] Yahoo
* [x] Yandex

Help wanted:

- ~[Yahoo](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/8eea098da7f446425e1a5a11a85eae6a3b0ea568/src/AspNet.Security.OAuth.Yahoo/YahooAuthenticationHelper.cs#L29) (don't know which is the best way to extract claims from the response)~
- ~Imgur (the same problem as Yahoo)~

**Comment by martincostello** [comment]
I've already ported the Amazon provider in the repo where I originally wrote that code, so will port that over sometime this week.

**Comment by Vertigo093i** [comment]
I'm going to start migrating Vkontakte and yet unreleased Odnoklassniki (#163) providers.

BTW, @PinpointTownes, how should I deal with the latter? Should I merge the original branch or just start over by adding ported code?

And the last but not least. Most of us require real-life live testing/using new already ported providers. Would you be so kind to reveal this project's AppVeyor NuGet feed URL and/or build configuration? This will help in testing builds even before opening pull requests.

**Comment by Moza805** [comment]
Just PR'd an updated Strava authenticator into experimental branch #177 . Heads up to @runxc1 in case you want to check it out

**Comment by martincostello** [comment]
PR to update the Amazon provider in #179.

**Comment by kinosang** [comment]
Hello @PinpointTownes, how's it going?

**Comment by agoretsky** [comment]
@PinpointTownes can you provide any ETA?

**Comment by kevinchalet** [comment]
> @PinpointTownes can you provide any ETA?

I reviewed all the submitted PRs and asked the contributions to include a few changes. @kinosang's PR is almost ready and will be merged ASAP.

**Comment by AlvinStanescu** [comment]
Migrated the LinkedIn provider in PR #183, please review.

**Comment by mkhrapunov** [comment]
VK auth is available in https://github.com/mkhrapunov/AspNet.Security.OAuth.VK

**Comment by kinosang** [comment]
I'll start working on other providers after get my computer repaired.

**Comment by chi-up** [comment]
@mkhrapunov  where were you before =) I just finished my version, spent a lot of time =)

**Comment by Vertigo093i** [comment]
OK and VK providers (for both 1.0 and 2.0) are finally available: https://github.com/Digillect/AspNetCoreOAuthProviders. As well as in NuGet.

**Comment by kevinchalet** [comment]
FYI: of the 47 providers, 22 have already been ported to 2.0 and there's a PR for a 23rd one (Vkontakte).

The updated list can be found here: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/182#issue-261667945.

**Comment by kevinchalet** [comment]
> Great news: the 46 aspnet-contrib OAuth2 social providers have been migrated to #aspnetcore 2.0. Special thanks to everyone who helped and kudos to Chino Chang who ported 37 providers! The packages can be downloaded from our #myget feed: https://www.myget.org/F/aspnet-contrib/api/v3/index.json

https://twitter.com/PinpointTownes/status/935240112954400769

**Comment by MV10** [comment]
@PinpointTownes Should the readme be updated to mention Core 2.0, or are you waiting until you move the packages out of RC status?
