### ISSUE TITLE
Yahoo does not support localhost callback

### ISSUE THREAD

**Issue by isaacrlevin** [aspnet-contrib/AspNet.Security.OAuth.Providers#176]
Creating a Yahoo App does not allow you to have a Callback of Localhost

![image](https://user-images.githubusercontent.com/8878502/30649920-8bfa466c-9def-11e7-86b8-b3908204aa53.png)

I have been able to get around this by using [ngrok](https://ngrok.com/) to expose localhost to the internet, but that is a pain. It would be great if this process somehow circumvented this constraint (possibly using oob).

**Comment by kevinchalet** [comment]
There's unfortunately nothing we can do in the provider itself, that uses the URL host as the callback domain like any other OAuth provider in ASP.NET Core.

@Tratcher what would be the recommendation to work around this annoying behavior? Using the machine DNS name or its IP address instead of localhost?

**Comment by runxc1** [comment]
You can always edit your Hosts file and setup your debugging environment to listen to a url rather than just localhost.

**Comment by Vertigo093i** [comment]
Instead of doing magics with hosts it is much easier to use special domain `localtest.me`. Any host (of any level) within it resolves to `127.0.0.1`.

**Comment by Tratcher** [comment]
MSA used to have the same problem and people used the same workarounds as described above.

**Comment by isaacrlevin** [comment]
@Vertigo093i so you would need to have IIS locally for this than? Due to the fact that specifying a port invalidates callback url. So the workaround is

- Have IIS Installed
- Create IIS site that points to port 80 and point your app to use that for debugging
- Create Yahoo App with http://localtest.me as Callback

That make sense?

**Comment by Vertigo093i** [comment]
> Due to the fact that specifying a port invalidates callback url.

Therefore Yahoo doesn't like the port portion, not the `localhost` itself? Then the answer is yes, one should use only a default port (80).

I hope even IISExpress can be configured to use http://myhost.localtest.me/ (but haven't tried it personally). But then it (and VS) must be started as an administrator to be able to bind to port 80.

But the better long-term solution is to contact Yahoo support for them to fix this.
AFAIR, somedays I've heard of another providers with such limitations for `localhost`.

**Comment by isaacrlevin** [comment]
@Vertigo093i no it needs something like http://somesite.extension so they are basically checking on the form validation if the string is in that structure. Pretty trash as I expect it wouldn't work for internal sites (http://intranet comes to mind). Oh well, I can move forward with the localme approach. Such a pain!

**Comment by isaacrlevin** [comment]
@Vertigo093i  Localtest.me did not work.... 

![image](https://user-images.githubusercontent.com/8878502/30654360-a13b3336-9dfb-11e7-84a7-af5188cf3241.png)


![image](https://user-images.githubusercontent.com/8878502/30654412-c97cc5c6-9dfb-11e7-9ffa-f522a0f18dce.png)

**Comment by Vertigo093i** [comment]
Shouldn't the redirect uri be in the format as at you very first original screenshot? I mean contains `signin-yahoo`. Or things got changed in .NET Core 2.0?

**Comment by isaacrlevin** [comment]
I don't think this is a Core issue. Even if I take out the `signin-yahoo` part of the uri it still gives this screen. If I set the redirect url to a ngrok endpoint it works just fine.

**Comment by Vertigo093i** [comment]
Then this is definitely a Yahoo issue. And I don't know how to avoid it...

**Comment by kevinchalet** [comment]
Closing, as there's not much we can do to work around this arbitrary Yahoo limitation in the provider itself.

**Comment by isaacrlevin** [comment]
For anyone that finds this, lvh.me works but you have to do dumb stuff like deploy your local site to localhost:80, that Deployment Support checkbox when you install the Core workload in VS and have lvh.me as the Callback when you setup the Yahoo App. Works well when done however.
