### ISSUE TITLE
Add Twitch provider

### ISSUE THREAD

**Issue by jerriep** [aspnet-contrib/AspNet.Security.OAuth.Providers#18]

**Comment by tparnell8** [comment]
I can take this one...

**Comment by PinpointTownes** [comment]
Thanks Tommy :+1: 

I added the `work in progress` label to make sure no one works on the same provider. Feel free to ping me if you need help.

**Comment by PinpointTownes** [comment]
Merged: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/dbba66ec007f8b4f849048d1be5c79c2f06090f8 :tada:
