### ISSUE TITLE
Potential Issue with Slack provider

### ISSUE THREAD

**Issue by jerriep** [aspnet-contrib/AspNet.Security.OAuth.Providers#184]
A couple of things related to the Slack provider which I think needs to be addressed:

1. When getting the user profile, the `https://slack.com/api/auth.test` method is called, and not the `https://slack.com/api/users.identity` method which is suggested by the **Sign in with Slack** document (see https://api.slack.com/docs/sign-in-with-slack#request_info)

2. The second, and more serious issue is that the `NameIdentifier` claim is set to the User's ID. See https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/c8c923a5b6149fa7693bd3a54bbcbc988fc1a56e/src/AspNet.Security.OAuth.Slack/SlackAuthenticationHandler.cs#L51 and https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/c8c923a5b6149fa7693bd3a54bbcbc988fc1a56e/src/AspNet.Security.OAuth.Slack/SlackAuthenticationHelper.cs#L22-L30

    This can potentially cause issues, as the Slack documentation states that the User ID is not guaranteed to be globally unique across all teams. See the note under the **Response** heading in this document: https://api.slack.com/methods/users.identity

@mjknowles You developed this initially. Any thoughts on these?

@PinpointTownes Not sure how we should handle this as it is a breaking change. But also, not fixing it can cause serious issues down the line as well.

**Comment by kevinchalet** [comment]
Nice catch @jerriep!

> @PinpointTownes Not sure how we should handle this as it is a breaking change. But also, not fixing it can cause serious issues down the line as well.

Agreed, we should fix that before releasing the 1.0/2.0 final packages (it will indeed break apps but I believe security wins).

IMHO, here's what we should do:

  - Add a new `urn:slack:user_id` claim and use it to store the "unsafe" user identifier.
  - Introduce a new helper method responsible of computing a "unique" identifier (e.g `GetUniqueIdentifier()`). It could be as simple as concatenating the team and user identifiers.
  - Use the new helper to compute the claim value used for `ClaimTypes.NameIdentifier`.

**Comment by jerriep** [comment]
You probably mean to register `urn:slack:user_id`, not `urn:slack:team_id`, right?

And sure I can fix this one

**Comment by kevinchalet** [comment]
> You probably mean to register `urn:slack:user_id`, not `urn:slack:team_id`, right?

Yeah, sorry :sweat_smile:

**Comment by kevinchalet** [comment]
This was fixed in both the 1.0 and 2.0 RC2 versions.
