### ISSUE TITLE
Add Untappd provider

### ISSUE THREAD

**Issue by jerriep** [aspnet-contrib/AspNet.Security.OAuth.Providers#19]

**Comment by tparnell8** [comment]
@rodkings and I did the Owin implementation. I'm sure one of us can get this done (and we talk somewhat often)

**Comment by rodkings** [comment]
I might be able to touch this very soon. Have you did anything @tparnell8?

**Comment by serber** [comment]
Related PR: #121

**Comment by PinpointTownes** [comment]
Done: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/025a5a0fea26c34980d902343f2cf6c474da6f0e

@serber thanks!

**Comment by TerribleDev** [comment]
awesome thanks @serber
