### ISSUE TITLE
Generic OAUTH Provider Request

### ISSUE THREAD

**Issue by pha3l** [aspnet-contrib/AspNet.Security.OAuth.Providers#196]
Perhaps I've missed something, but I'm wondering if  there are currently any plans for including a "generic" provider included with this package?  We are considering .NET Core for an upcoming project, but it needs to implement external authentication through ADFS OAuth.  I haven't found any examples of how to do this, and I think it would be a useful feature for this package.\

Many thanks!

**Comment by jerriep** [comment]
ASP.NET Core has a generic one out of the box

See https://github.com/aspnet/Security/blob/f8711a2da3fdf6b250d528136c6e9d8ecf78062b/samples/SocialSample/Startup.cs#L175-L209 for sample code

**Comment by jerriep** [comment]
Actually, you may also want to look at https://github.com/aspnet/Security/blob/dev/samples/SocialSample/Startup.cs#L125-L144 which seems to demonstrate how to use it with Azure AD. May be useful in your case

**Comment by pha3l** [comment]
Thank you, I will give this a try!

**Comment by kevinchalet** [comment]
Closing as I believe @jerriep answered your question. Don't hesitate to re-open if you need additional details.
