### ISSUE TITLE
Paypal OAuth login returns (invalid client_ID or redirect_uri)

### ISSUE THREAD

**Issue by asadsahi** [aspnet-contrib/AspNet.Security.OAuth.Providers#198]
Hi Guys,

Having trouble integrating with Paypal oauth. Keep on getting above error. I have also got a question on stackoverflow, but not getting much help for it.

https://stackoverflow.com/questions/47436262/paypal-oauth-login-returns-invalid-client-id-or-redirect-uri

Here is my setup:

```
 .AddPaypal(options =>
               {
                   options.ClientId = Startup.Configuration["Authentication:Paypal:ClientId"];
                   options.ClientSecret = Startup.Configuration["Authentication:Paypal:ClientSecret"];
               })
```

and paypal applcation setup is this:

![image](https://user-images.githubusercontent.com/3470892/33167845-d0138254-d036-11e7-948a-e63a6891fe59.png)

![image](https://user-images.githubusercontent.com/3470892/33167913-ffd3c4ae-d036-11e7-8b1d-e65456992fc7.png)

Here is error on screen:

![image](https://user-images.githubusercontent.com/3470892/33167971-2f452070-d037-11e7-8130-29b4d63ef81e.png)

and this is the url sent on challange to Paypal:

```
https://www.paypal.com/webapps/auth/protocol/openidconnect/v1/authorize?client_id=AXBk9TrDdQ5rPiYnOMt9Gwd6KF5WkVZwlRAro5A8bMKrCrEPe4RNKHZkEfuiszFe_kGHXN85JHr75EA3&scope=openid%20profile%20email&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Fsignin-paypal&state=CfDJ8MrLCpontb5BpF_XK8aS5v2ZloqcJevGj2CsUOPB9VdVd63zq-GY2t44aZPAi6-94UbUxH2-LnTTQ7AxPTSpj63Vdp7gfJdr7PYFRirvJHmVzY7R_6cslWFhwp2Qu5t0tg6W56BcPtALBQ2vDVP1HbENp2QeTHm9BPYVLT10ZYSdR9xnOIiMyKCDubRKYEaAeABNGAi-vyldUu140GpIAHx9pNuTy-wUP3YMP2sFshNuYMefO8yQI8-uTgQzkFhNAEFOKqmxkl3bdPSCWQv8iIEzQ-ZF1sn0WYwSOXXRzuQzSVA8QPsLmcYD68i2cqPE2LwAWqCwSlbxDyh8bHtrOOswgzIAd2QSOAYSz9hghcTPx4uNARiiv0_HvMrtlzFKDWKsQucZadWafi7RQz_kO8dC1N2IgdW9KCBaQDCJyWLC-SD5n0TaKdg4hSHiCQT9yDVDExm7-aq8QHIOhs3PkzH6BGfRtkaKQLswdaKax8Cp5_ve2zJ-xwxDayF2S_WsVXfwBx_EJpCYT3ERCbKWSbyWtIpy9sEQDln2uTPiwokqQS9TEaU1cm8Dn0rMD6TdoxKp7hy4vw5HzKXusvOPaSHnc7eaKDolPpbuZjF4yRhFrtL76pJSsy7tzUcgLiJntA
```

**Comment by kinosang** [comment]
the `redirect_uri` parameter your application send to PayPal is `http://localhost:5000/signin-paypal`, you can modify the configuration of the return url on PayPal or edit your `launchSettings.json`.

**Comment by asadsahi** [comment]
@kinosang this was my recent attempt to use with local IP since twitter had some similar issues in the past, but I have tried with IP and localhost matching on both client and paypal side, but error is still same.

**Comment by kinosang** [comment]
the PayPal provider does not support for sandbox environment, you should config `AuthorizationEndpoint`, `TokenEndpoint` and `UserInformationEndpoint` to test your application in sandbox.

**Comment by asadsahi** [comment]
@kinosang would you be able to send the paypal authentication middleware configuration for sandbox which you reckon to try. Shall I keep **http://127.0.0.1:5000/signin-paypl** as callback url?

**Comment by kinosang** [comment]
@asadsahi 

```csharp
 .AddPaypal(options =>
               {
                   options.ClientId = Startup.Configuration["Authentication:Paypal:ClientId"];
                   options.ClientSecret = Startup.Configuration["Authentication:Paypal:ClientSecret"];
                   options.AuthorizationEndpoint = "https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/authorize";
                   options.TokenEndpoint = "https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice";
                   options.UserInformationEndpoint = "https://api.sandbox.paypal.com/v1/identity/openidconnect/userinfo?schema=openid";
               })
```

**Comment by asadsahi** [comment]
@kinosang thanks.

I have changed paypal callback url to **http://localhost:5000/signin-paypal** and modified the middleware config as you suggested. Will give it some time to pick paypal changes and try again.

**Comment by asadsahi** [comment]
Ok, with config slightly different error:

```
We're sorry about that
Looks like this action is not supported. Please return and report this error so that we can support it in the future. (invalid scope)
```

This is the information exposedon paypal side.

![image](https://user-images.githubusercontent.com/3470892/33169219-b51c449a-d03b-11e7-8539-2aedf72641df.png)


Error screen:

![image](https://user-images.githubusercontent.com/3470892/33169242-d07aa9a2-d03b-11e7-9bbc-2465bca0194e.png)

**Comment by kinosang** [comment]
It seemed that the sandbox does not support for some of the scopes, I have no idea to solve it.

**Comment by asadsahi** [comment]
@kinosang there is no benefit/usage of sadbox then :)

Let me try with live settings. I am guessing I just need to configure clientid and clientsecret in that case.

**Comment by asadsahi** [comment]
Nope, same error with production settings as well:

![image](https://user-images.githubusercontent.com/3470892/33169556-072733a2-d03d-11e7-994f-f5cf060f06d1.png)

**Comment by kinosang** [comment]
Enable `Personal Information` on PayPal side, it may solve this problem.

**Comment by asadsahi** [comment]
@kinosang I think its the same issue with production as well:

with this middleware setup:

```
   .AddPaypal(options =>
                  {
                      options.ClientId = Startup.Configuration["Authentication:Paypal:ClientId"];
                      options.ClientSecret = Startup.Configuration["Authentication:Paypal:ClientSecret"];
                    //   options.AuthorizationEndpoint = "https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/authorize";
                    //   options.TokenEndpoint = "https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice";
                    //   options.UserInformationEndpoint = "https://api.sandbox.paypal.com/v1/identity/openidconnect/userinfo?schema=openid";
                  })
```

and **http://localhost:5000/signin-paypal** as redirect url, got same error for scopes

**Comment by asadsahi** [comment]
ok, let me try enabling personal information.

**Comment by kinosang** [comment]
and re-check your client_id

**Comment by asadsahi** [comment]
@kinosang you are genius. It works :+1: 

So two things here:
 We have to enable following scopes on paypal side:

![image](https://user-images.githubusercontent.com/3470892/33170215-69bb03e8-d03f-11e7-9cdf-0c0a3a509642.png)

Maybe we can fine tune the address information scopes, but email is the one perhaps we were missing.

So here is my final paypal oauth setting:

```
  // https://developer.paypal.com/developer/applications
               .AddPaypal(options =>
                  {
                      options.ClientId = Startup.Configuration["Authentication:Paypal:ClientId"];
                      options.ClientSecret = Startup.Configuration["Authentication:Paypal:ClientSecret"];
                      if (hostingEnv.IsDevelopment())
                      {
                          options.AuthorizationEndpoint = "https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/authorize";
                          options.TokenEndpoint = "https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice";
                          options.UserInformationEndpoint = "https://api.sandbox.paypal.com/v1/identity/openidconnect/userinfo?schema=openid";
                      }
                  })
```

As you suggested we need to set few extra configuration for sandbox otherwise it doesn't work.

**Comment by soofian** [comment]
I have merchant's client id and client secret. I want to get an access token and refresh token from my C# code. Code given on [https://github.com/paypal/sdk-core-dotnet](https://github.com/paypal/sdk-core-dotnet) is not working and giving object reference not set to an instance error. Can any one please help ? My SDK version is 1.9.1.2.

**Comment by Vladinho10** [comment]
ATTENTION !!!!!  I tried almost 6 hours. Finally I found the solution. 
Just check 'Full name' 
and send GET request to 
https://www.sandbox.paypal.com/signin/authorize?

with these queries
flowEntry=static&
client_id=[ my Client ID from created application ]&
scope=openid profile email&
redirect_uri=[ http%3A%2F%2Flocalhost%3A3001%2Fmy%2Fredirect%2Furl this is http://localhost:3001/my/redirect/url ]&
response_type=code


![Screenshot from 2019-06-07 12-31-39](https://user-images.githubusercontent.com/33626746/59091455-6c460e00-8920-11e9-9cb0-47bdb75446c9.png)

**Comment by Mike-E-angelo** [comment]
Apologies for resurrecting this thread but I am running into the same issue.  It appears that when this issue was originally opened `localhost` was a valid value for `redirect_uri`.  Currently, however, I get an error if I attempt to use `localhost`:

![](https://i.imgur.com/kFaOvQB.png)

`127.0.0.1` seems to work, however.  I did try calling `https://www.sandbox.paypal.com/signin/authorize/` as per @Vladinho10's suggestion but no dice, unfortunately.

Any further suggestions/insight would be greatly appreciated.

**Comment by Mike-E-angelo** [comment]
OK so after some poking and prodding, I got the following `redirect_uri`'s to work:

`http://<custom.domain>:<port>/signin-paypal`
`http://127.0.0.1:<port>/signin-paypal`
`https://<custom.domain>:44301/signin-paypal`

For `<custom.domain>` entries, they required an entry in the HOSTS file (Windows 10 here), along with this `.vs\<project>\config\applicationhost.config` (Visual Studio 2019) modifications for IIS express:

```
<bindings>
    <binding protocol="http" bindingInformation="*:<port>:*" />
    <binding protocol="https" bindingInformation="*:44301:*" />
</bindings>
```

So it would seem that `localhost` has been banned as a valid host, and even while `127.0.0.1` is allowed, when it is actually validated by `https://www.sandbox.paypal.com/connect/` it cannot be used in conjunction with an `https` protocol value.

In my case, when using `127.0.0.1`, only `http://127.0.0.1:<port>` works and is successfully validated by `https://www.sandbox.paypal.com/connect/`, even though it allowed me to enter `https://127.0.0.1:44301` (and is considered invalid upon validation). 🤷‍♂️

**Comment by KovtunOleg** [comment]
This bug can appear even if your setup is correct, but you just changed something in your PayPal admin panel and after sometime the error will be gone. Usually it takes up to 6 hours.
