### ISSUE TITLE
Add VisualStudio provider

### ISSUE THREAD

**Issue by jerriep** [aspnet-contrib/AspNet.Security.OAuth.Providers#20]

**Comment by Gekctek** [comment]
This api requires that the callback api be not localhost AND https. I cant figure out a way to test this on my machine. I have a placeholder redirect uri configured. If it wasnt https i would just redirect the host but i dont know if that will work with https. Any suggestions for doing actual testing on this api without manually ripping it apart and testing the individual components?

I tried [this](http://benjii.me/2014/11/run-iis-express-on-port-443-using-ssl-and-wildcard-subdomains) but cant get it to work. I dont know if it has to do with this is asp.net5/dnx

**Comment by jerriep** [comment]
You can use this blog post as a starting point:
https://www.twilio.com/blog/2014/03/configure-windows-for-local-webhook-testing-using-ngrok.html

The only thing they don't cover in there is the HTTPS, but you should be able to figure that out.

Also note that the location for the IIS Express configuration file has changed in VS 2015

It is not located at `%USERPROFILE%\My Documents\IISExpress\config\applicationhost.config` anymore as they state in that particular blog post. It is now located under your project folder, in `.vs\config\applicationhost.config `

**Comment by Gekctek** [comment]
Ya it seems https works much differently and I cant figure it out besides deploying it to somewhere that actually has a https url

**Comment by PinpointTownes** [comment]
Related PR: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/99

**Comment by PinpointTownes** [comment]
Done: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/17f23cd1f0f30d69d0ebbc34409c58b6a750d962.
