### ISSUE TITLE
Using LinkedIn Provider

### ISSUE THREAD

**Issue by williambowsher** [aspnet-contrib/AspNet.Security.OAuth.Providers#200]
Can you please let me know how I add the Client Secret and Client Id for LinkedIn OAuth provider.

I have tried using the same mechanism as Google, Twitter etc, but the are no properties on the Config object.

Cheers

**Comment by kinosang** [comment]
Almost all providers from this repository use `ClientId` and `ClientSecret`.

Google, Twitter, Facebook and Microsoft providers are provided by `aspnet` project, they use "unusual" mechanism.

**Comment by williambowsher** [comment]
Thats what I was hoping but I have just download the v1.0.0-rc1-final from Nuget and when I try an initialise it as per the example i get the following

![linkedin issue](https://user-images.githubusercontent.com/22028391/33476321-e10598a8-d681-11e7-9c35-2375fce4497b.jpg)

**Comment by kinosang** [comment]
Didn't reproduce the issue, even with asp.net core 1.0 and asp.net core 2.0.

Are you using asp.net core 1.0? If you are using asp.net core 2.0, you should use `v2.0.0-*` and `services.AddAuthentication().AddLinkedIn()`.

For some reason, the 2.0 pre-release packages are only available on [myget](https://www.myget.org/gallery/aspnet-contrib.) at this time.

**Comment by williambowsher** [comment]
No Asp.Net Core 2

**Comment by kinosang** [comment]
Sample codes in README.md are outdated. Have a look at the sample project.

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/b2928043e7357d0271923f8dc1799c83deefdb1b/samples/Mvc.Client/Startup.cs#L40-L45

For more information about breaking changes on asp.net core 2.0, see aspnet/Announcements#262 and http://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x.

**Comment by williambowsher** [comment]
The version will be the problem, I will download the V 2 from myget 

Thanks.
