### ISSUE TITLE
AspNet.Security.OAuth.Providers for ASP.NET Core 2.0

### ISSUE THREAD

**Issue by asvishnyakov** [aspnet-contrib/AspNet.Security.OAuth.Providers#202]
Hi! As I can see, you're migrating AspNet.Security.OAuth.Providers to ASP.NET Core 2.0. Have you any plans to release new NuGet package for that? At least as early preview...

**Comment by kinosang** [comment]
see #170

>> Great news: the 46 aspnet-contrib OAuth2 social providers have been migrated to #aspnetcore 2.0. Special thanks to everyone who helped and kudos to Chino Chang who ported 37 providers! The packages can be downloaded from our #myget feed: https://www.myget.org/F/aspnet-contrib/api/v3/index.json
>
> https://twitter.com/PinpointTownes/status/935240112954400769

**Comment by asvishnyakov** [comment]
@kinosang yes, but there is no nuget package update. Why?

**Comment by kinosang** [comment]
@asvishnyakov because they are not fully tested.

see #182 

> We'll give folks a few days (maybe 1 week?) to try them before pushing them to NuGet.org.

**Comment by kevinchalet** [comment]
The `2.0.0-rc2-final` packages are being built by the CI service and will be automatically pushed to MyGet.org.
Unless a last minute bug is reported, these are the binaries that will be uploaded to NuGet.org next week.

**Comment by kevinchalet** [comment]
The OpenID2 and OAuth2 providers for 1.0 and 2.0 have been pushed to NuGet.org.

**Comment by martincostello** [comment]
Are the final `2.0.0` packages going to be released to NuGet?

**Comment by kevinchalet** [comment]
Soon (tm).

**Comment by kevinchalet** [comment]
https://twitter.com/PinpointTownes/status/1008812623884967936
