### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by jeremywhittington** [aspnet-contrib/AspNet.Security.OAuth.Providers#206]
I have installed AspNet.Security.OAuth.Discord 2.0.0-rc2-final in an asp.net core 2.0 application and added this code to Startup.cs.

```
services.AddAuthentication().AddDiscord(options =>
            {
                options.ClientId = "********";
                options.ClientSecret = "********";
            });
```

When I click the discord login or add another service button it takes me to the discord page. But when I click on the Authorize button nothing happens and I get a http 400 error in the console.

I have added the website url and my localhost url to My Apps under discord. I've also tried adding /signin-discord to the url just in case.

**Comment by kevinchalet** [comment]
Logs?

**Comment by jeremywhittington** [comment]
[discordapp.com-1513527568175.log](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/files/1565822/discordapp.com-1513527568175.log)

**Comment by jeremywhittington** [comment]
By the way the Steam oauth module works fine.

**Comment by kevinchalet** [comment]
I meant the ASP.NET Core logs.

**Comment by jeremywhittington** [comment]
The error is happening on the client side and I think on discord's site. Here are the logs from the debug output. Is there something specific you need?

> Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 POST http://localhost:44331/Account/ExternalLogin application/x-www-form-urlencoded 199
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Message","time":"2017-12-17T16:37:38.7571105Z","tags":{"ai.operation.parentId":"|d5925908-41268bad3b5a9415.","ai.internal.sdkVersion":"aspnet5c:2.1.1","ai.location.ip":"127.0.0.1","ai.application.ver":"1.0.0.0","ai.cloud.roleInstance":"JEREMY-PC","ai.internal.nodeName":"JEREMY-PC","ai.operation.id":"d5925908-41268bad3b5a9415","ai.operation.name":"POST /Account/ExternalLogin"},"data":{"baseType":"MessageData","baseData":{"ver":2,"message":"Request starting HTTP/1.1 POST http://localhost:44331/Account/ExternalLogin application/x-www-form-urlencoded 199","severityLevel":"Information","properties":{"ContentLength":"199","Host":"localhost:44331","ContentType":"application/x-www-form-urlencoded","CategoryName":"Microsoft.AspNetCore.Hosting.Internal.WebHost","Scheme":"http","DeveloperMode":"true","Path":"/Account/ExternalLogin","AspNetCoreEnvironment":"Development","Method":"POST","Protocol":"HTTP/1.1"}}}}

**Comment by jeremywhittington** [comment]
I ran fiddler and I dont see any calls going back to my website.

> # | Result | Protocol | Host | URL | Body | Caching | Content-Type | Process | Comments | Custom
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
91 | 400 | HTTPS | discordapp.com | /api/v6/oauth2/authorize?client_id=390351160244174858&redirect_uri=https%3A%2F%2Flocalhost%3A44331%2Fsignin-discord&response_type=code&scope=&state=CfDJ8Ck6vu5lUjBBop05YHwGO7CDDdMbB30X6fcoapoJZMvmmjj7aLSsblZmfKDVWvtVik4t0UVYT7rKylQeGXeMF3HN4Xan70tQxUBFLiBhwPYv8bV5HB4ApNP_w8aKFOu0hTtoVdGSADUhv0QpiIJ-xew8UTZJKGgVxVZZ2lwEC62fN7PMgs7utMjjeSICoLhq7J1muUeDkl_XRE0StX9oKyUmEZyX-imtDj2sy-kiMWfr76F4Qwjt3-DFNzroZ2NGaF-m1_02z_uY6-eRjbwcy6gVhu4cl-RFFJNNikc8iw1- | 37 |   | application/json | chrome:85860 |   |

**Comment by kevinchalet** [comment]
Try to add a scope to see if it helps?
If it still doesn't work, I'm afraid you'll have to ping the Discord folks as the logs you provided are not really helpful.

**Comment by jeremywhittington** [comment]
Property or indexer 'OAuthOptions.Scope' cannot be assigned to -- it is read only

**Comment by jeremywhittington** [comment]
Does this provider work for you? Have you set any values other than ClientId and ClientSecret? Did you add anything other than https://mydomain/signin-discord in your "My Apps" settings? Have you tried this in asp.net core 2.0? Do I need to create a discord bot for any reason?

**Comment by kevinchalet** [comment]
> Property or indexer 'OAuthOptions.Scope' cannot be assigned to -- it is read only

It's a collection...

> Does this provider work for you?

It worked when I merged the PR that added it. I don't use Discord so not sure if it's still working. That said, if the error is caused by Discord's servers, it's probably not a bug in our code.

**Comment by jeremywhittington** [comment]
Adding options.Scope.Add("identify"); fixed the issue. You may want to update your documentation.

**Comment by kevinchalet** [comment]
> Adding options.Scope.Add("identify"); fixed the issue. You may want to update your documentation.

Better, submit a PR with the fix.

**Comment by jeremywhittington** [comment]
I dont know how to submit a PR. If you can walk me through this I can try to help.

**Comment by kinosang** [comment]
@jeremywhittington I've already submit the patch via #208.

You can have a look at https://help.github.com/articles/creating-a-pull-request/ for How PR works.

**Comment by kevinchalet** [comment]
PR merged. @kinosang thanks!
