### ISSUE TITLE
Discord Add Guild Scope

### ISSUE THREAD

**Issue by jeremywhittington** [aspnet-contrib/AspNet.Security.OAuth.Providers#209]
The Discord oauth2 api has a guild scope where you can get a list of servers a user has joined. I'm trying to get my head around how I would extend the Discord OAuth Provider to add functionality to capture this.

I see the DiscordAuthenticationHandler.CreateTicketAsync that calls the UserInformationEndpoint to get user information. But I have never tried to add to an existing github repo that wasnt mine.

Another way I have thought to approach this is just to make the call to the api myself during the authorization process but I dont see anyway to get access to the oauth2 token. Its being handled in the OAuth Provider only.

Any guidance would be appreciated.

**Comment by kinosang** [comment]
Add the scope when you config the provider, and use the `OnCreatingTicket` event.

**Comment by jeremywhittington** [comment]
I was successfully able to do this by adding the following.

**Startup.cs**

```
options.Events = new OAuthEvents
{
	OnCreatingTicket = async context =>
	{
		Claim guildClaim = await DiscordExtensions.GetGuildClaims(context);
		context.Identity.AddClaim(guildClaim);
	}
};
```


**DiscordExtensions.cs**


```
public static async Task<Claim> GetGuildClaims(OAuthCreatingTicketContext context)
{
	var request = new HttpRequestMessage(HttpMethod.Get, "https://discordapp.com/api/users/@me/guilds");
	request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
	request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", context.AccessToken);

	var response = await context.Backchannel.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, CancellationToken.None);
	if (!response.IsSuccessStatusCode)
	{
		throw new Exception("failed to get guilds");
	}

	var payload = JArray.Parse(await response.Content.ReadAsStringAsync());
	Claim claim = new Claim("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/guilds", payload.ToString(),ClaimValueTypes.String);
	return claim;
}
```
