### ISSUE TITLE
AspNetCore 2.0 ClaimActions

### ISSUE THREAD

**Issue by jeremywhittington** [aspnet-contrib/AspNet.Security.OAuth.Providers#210]
How would you add additional ClaimActions with AspNetCore 2.0? I would like to add claims to get other values when the UserInformationEndpoint is called.

Discord sends back by default the discriminator and avatar but those are not being stored.

I have tried several methods to add the ClaimActions in the Discord options settings in Startup.cs but cant figure out the right way to do it.

For example: 
options.ClaimActions.Add(new ClaimAction("{http://schemas.xmlsoap.org/ws/2005/05/identity/claims/discriminator","http://www.w3.org/2001/XMLSchema#string"));

Gives me the error "Cannot create an instance of the abstract class or interface 'ClaimAction'". Im poking around to figure out what the right class is but havent found it yet.

**Comment by jeremywhittington** [comment]
To do this would I wire up OnCreatingTicket event and manually parse and add the claim?

**Comment by kinosang** [comment]
no need for `OnCreatingTicket `, just use `options.ClaimActions.MapJsonKey` for Json result from Discord API, in otherwise you should create a derived class from `ClaimAction`.

**Comment by kevinchalet** [comment]
@Tratcher do you know by any chance if there's already some documentation about the "claims actions" thingy?

**Comment by jeremywhittington** [comment]
Trying to use MapJsonKey in Startup.cs returns the error "'ClaimActionCollection' does not contain a definition for 'MapJsonKey'".

```
services.AddAuthentication().AddDiscord(options =>
{
	options.ClientId = "CLIENTID";
	options.ClientSecret = "CLIENTSECRET";
	options.Scope.Add("email");
	options.ClaimActions.MapJsonKey(ClaimTypes.Name,"Name");
}
```

I am still using the MyGet AspNet.Security.OAuth.Discord 2.0.0-rc2-final. Could this be the issue?

**Comment by Tratcher** [comment]
Not much. File a doc bug and we'll add it.

**Comment by kevinchalet** [comment]
@Tratcher https://github.com/aspnet/Docs/issues/5106.

I'm closing this thread as there's not much we can do on our side. @jeremywhittington let us know if you're still hitting this issue.
