### ISSUE TITLE
Redirect not working to get Authorization Code 

### ISSUE THREAD

**Issue by sohaibjaved44** [aspnet-contrib/AspNet.Security.OAuth.Providers#211]
I have tried this solution for Linkedin, it redirects to "/" root but when I am trying to read query string parameters "Code" and "Status" etc it never redirects to said url.
I have updated [this](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/dev/samples/Mvc.Client/Controllers/AuthenticationController.cs) controller by adding a function named "signin-linkedin" to receive redirect response as below 

`
[HttpPost("~/signin")]
        public async Task<IActionResult> SignIn([FromForm] string provider)
        {            
            if (string.IsNullOrWhiteSpace(provider)){
                return BadRequest();
            }
            if (!await HttpContext.IsProviderSupportedAsync(provider)) {
                return BadRequest();
            }
            return Challenge(new AuthenticationProperties { RedirectUri = "/signin-linkedin" }, provider);
        }

        [HttpGet("~/signin-linkedin")]
        public IActionResult signinlinkedin(string code, string status, string error, string error_description)
        {
            return code;
        }`
but it's not redirecting to this function.

**Comment by kevinchalet** [comment]
The callback part is handled by the LinkedIn authentication middleware itself. Don't create a callback action, it's useless and invalid.

Give the sample a try. The LinkedIn handler works exactly like the other social providers (e.g Google)

**Comment by sohaibjaved44** [comment]
Ok thanks, but in the sample provided is there any way to get authorization code, status etc? as I need to call api for access token after it

**Comment by kevinchalet** [comment]
> Ok thanks, but in the sample provided is there any way to get authorization code, status etc? as I need to call api for access token after it

The authorization code is automatically redeemed by the handler itself. To store the access token in the final authentication cookie, set `SaveTokens` in the options.
