### ISSUE TITLE
AspNet.Security.OAuth.Instagram doesn't fill the claims?

### ISSUE THREAD

**Issue by ghost** [aspnet-contrib/AspNet.Security.OAuth.Providers#212]
I've updated the [sample project](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/tree/dev/samples/Mvc.Client) to use the [Instagram provider](https://www.nuget.org/packages/AspNet.Security.OAuth.Instagram/2.0.0-rc2-final) with this config:
```csharp
 public void ConfigureServices(IServiceCollection services)
        {
            services
                .AddAuthentication(options =>
                {
                    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                })
                .AddCookie()
                .AddInstagram(options =>
                {
                    options.ClientId = "****";
                    options.ClientSecret = "*****";
                });
``` 
Authentication works well, but there is no claims in `Context.User.Claims` and no `User.Identity.Name` is displayed [in this page](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/dev/samples/Mvc.Client/Views/Home/Index.cshtml#L5)

am i missing something? thx in advance

**Comment by kevinchalet** [comment]
/cc @yannicsmeets as he wrote the Instagram provider.

You should at least get the user identifier and name: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/dev/src/AspNet.Security.OAuth.Instagram/InstagramAuthenticationOptions.cs#L31-L32.

Have you tried with the ASP.NET Core 1.x version? If both don't work, the userinfo endpoint schema may have changed.

**Comment by kinosang** [comment]
Sorry, @PinpointTownes @nicolocodev, it's my fault. I'll create a pr to fix it.

BTW, please don't hesitate to let me know if there is any mistake about the migrations from Asp.Net Core 1.0 to Asp.Net Core 2.0.
