### ISSUE TITLE
Yahoo does not allow callbacks with Yahoo in the name

### ISSUE THREAD

**Issue by isaacrlevin** [aspnet-contrib/AspNet.Security.OAuth.Providers#213]
Was this tested creating a Yahoo App?

![image](https://user-images.githubusercontent.com/8878502/35929338-4457a9b8-0bfd-11e8-983f-643bddf45a3c.png)

I believe the Yahoo Provider needs some updates to it (for instance localhost is not supported, will need to be something like lvh.me).

**Comment by kevinchalet** [comment]
/cc @jerriep as he wrote the initial version and may be able to shed some light.

> for instance localhost is not supported

You've already opened a ticket about that: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/176. The conclusion is still the same: it's a Yahoo limitation and we can't do anything in the provider itself.

Concerning the callback path, that's extremely unfortunate (and another insane decision from the Yahoo folks). I'm not opposed to change the default callback path if it can help. Suggest new names and we'll see.

**Comment by kinosang** [comment]
You can use `lvh.me` for the field. It's ask for `Callback Domain` not the `Callback URL`.

**Comment by isaacrlevin** [comment]
@kinosang So what do i put in for CallbackPath in the AddYahoo() extension to get this to work?

**Comment by kinosang** [comment]
@isaac2004 you can leave it for default.

**Comment by isaacrlevin** [comment]
Ok, I was able to get it to work, seems like Yahoo is a pain sadly. Thanks for the help!

**Comment by kevinchalet** [comment]
> Ok, I was able to get it to work, seems like Yahoo is a pain sadly.

Did you have to replace the default callback path or did it work OOTB?

**Comment by isaacrlevin** [comment]
If you set the callback to the root when you create the app, and leave the callback default in your configuration, it works OOTB
