### ISSUE TITLE
Desktop Apps?

### ISSUE THREAD

**Issue by gehnster** [aspnet-contrib/AspNet.Security.OAuth.Providers#215]
Hey, I was wondering since this packages namespace is under AspNet if it only works while using ASP.NET Core or would you be able to say get this package to easily work using like a Windows Forms app or something? You'd need to spin up a small http server for the callback, and I suppose find a way to hide the secret key, but still. This is specifically related to the EVE Online provider for the kinda usage I'm thinking of.

Thanks

**Comment by kevinchalet** [comment]
Hey,

Nah, these providers are not really good candidates for desktop apps (unless your desktop app is just a web view that renders an ASP.NET Core app :sweat_smile:).

I'd suggest going with something like https://github.com/IdentityModel/IdentityModel.OidcClient2 for desktop apps.

Cheers.

**Comment by gehnster** [comment]
Thanks!
