### ISSUE TITLE
Why is Fields a get only property

### ISSUE THREAD

**Issue by rfrerebe** [aspnet-contrib/AspNet.Security.OAuth.Providers#218]
Hello,

I am new to this repo, I had a question.

Here :
https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/b2928043e7357d0271923f8dc1799c83deefdb1b/src/AspNet.Security.OAuth.LinkedIn/LinkedInAuthenticationOptions.cs#L57
Field property is get only
Is there any reason for that ?
If it allowed set, devs in general (an me in particular) could choose which claims they want.

It seems to be the same across the repo (Amazon, ...)

Anyway, I will send a PR adding some fields in the meantime

Rémy

**Comment by kinosang** [comment]
It's a `HashSet`, it means that you can use `HashSet<T>.Add(T)` to add an element to this set, and use `HashSet<T>.Remove(T)` to remove it.

**Comment by rfrerebe** [comment]
Thanks for your help

Yep, I also just found it ...
my bad
UnionWith did the trick for me, because Add can only add one item

I hope it helps someone with the same issue.
