### ISSUE TITLE
Twitch OAuth2 provider not signing in correctly

### ISSUE THREAD

**Issue by celluj34** [aspnet-contrib/AspNet.Security.OAuth.Providers#223]
Hello;

I am trying to implement the Twitch OAuth2 login flow, and I have tried to follow the sample in this solution. I am only using Twitch to log in, I do not have any other method currently. In the simplest solution I can create, I always get an error stating `No authenticationScheme was specified, and there was no DefaultSignInScheme found.` This is demonstrably incorrect as I am able to get to the Twitch login page and log in successfully.

When I run the sample project and add twitch with my clientId and clientSecret I get the same error. Google works, Twitter works, Github also fails but it looks like for a separate issue.

The error is being thrown from `Microsoft.AspNetCore.Authentication.AuthenticationService.SignInAsync()`. If I try to set the DefaultScheme or SignInScheme to `TwitchAuthenticationDefaults.AuthenticationScheme`, then I get other errors about not being able to set either of those properties to the same value.

I'm not sure where else to go from here. I would like to use this extension as it saves me a lot of work, but I can't in its current state, whether that be on the Microsoft/Security team or the one maintaining this project.

Let me know if there's any more info I can provide to help finding a solution.

**Comment by kevinchalet** [comment]
> If I try to set the DefaultScheme or SignInScheme to TwitchAuthenticationDefaults.AuthenticationScheme, then I get other errors about not being able to set either of those properties to the same value.

Using the OAuth2 providers as the default sign-in scheme is not a legal operation. The default sign-in scheme is usually an instance of the cookie handler.

> When I run the sample project and add twitch with my clientId and clientSecret I get the same error.

That likely means there's an error in your provider as they all work the same way.

> Github also fails but it looks like for a separate issue.

Yeah, the `redirect_uri` associated with the client app was updated. I'll remove it from the samples.

**Comment by celluj34** [comment]
> That likely means there's an error in your provider as they all work the same way.

But I haven't made any changes to it, plus I'm using the example project in this repository. The only lines of code I added were the .AddTwitchAuth(...) with my clientId and clientSecret.
