### ISSUE TITLE
Strava provider doesn't work with extra scopes

### ISSUE THREAD

**Issue by anderaus** [aspnet-contrib/AspNet.Security.OAuth.Providers#225]
Using the Strava provider and adding the `write` scope

``` C#
.AddStrava(options =>
{
    options.ClientId = "xyz";
    options.ClientSecret = "xyzxyz";
    options.Scope.Add("write");
});
```

gives this auth url:

`https://www.strava.com/oauth/authorize?client_id=xyz&scope=public%20write&response_type=code&redirect_uri=xyz&state=xyz`

Which returns an `invalid scope` response due to two issues:
- Strava expects a comma-separated list of scopes
- Strava doesn't tolerate the `public` scope set if any other scope is also used

According to [the documentation](https://developers.strava.com/docs/authentication/), these are the only valid scope values:

`public`
`write`
`view_private`
`view_private,write`

**Comment by kevinchalet** [comment]
Thanks for reporting this bug (and for submitting the PR) :+1:

**Comment by kevinchalet** [comment]
Fixed.
