### ISSUE TITLE
GitHiub - GetExternalLoginInfoAsync returns null in asp.net core 2.0

### ISSUE THREAD

**Issue by Corstiaan84** [aspnet-contrib/AspNet.Security.OAuth.Providers#228]
I want to connect to GitHub using OAuth in aspnet core 2.0. I have the following setup.

Startup.cs:

    'services.AddDbContext<DbContext>(options =>
                options.UseNpgsql(Configuration.GetConnectionString("DefaultConnection"))
            );

            services.AddIdentity<User, Role>()
            .AddEntityFrameworkStores<DbContext>()
            .AddDefaultTokenProviders();
            
            services.AddMvc(options => options.OutputFormatters.Add(new HtmlOutputFormatter()));
            services.AddAntiforgery(x => x.HeaderName = "X-XSRF-TOKEN");

            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            })
            .AddCookie()
            .AddGitHub(options =>
            {
                options.ClientId = "xxxxxxxxxx";
                options.ClientSecret = "xxxxxxxxxxxxxxx";
                options.CallbackPath = new PathString("/auth/callback/GitHub");
            })'

Controller:

    '[HttpGet("{provider}")]
        public IActionResult Index(string provider)
        {
            return Challenge(new AuthenticationProperties() { RedirectUri = Url.Action("CallBack", "Auth") }, provider);
        }

    [HttpGet("callback")]
        public async Task<IActionResult> CallBack()
        {
            var info = await _signInManager.GetExternalLoginInfoAsync(); // <== this is always NULL
            return Redirect("~/");
        }'

The auth flow gets completed correctly and without errors. However, the line

    var info = await _signInManager.GetExternalLoginInfoAsync();

always yields null.

There are some leads scattered around the web but none seem to scratch my itch.

Thoughts? Am I missing a setting somewhere? Probably...

Thanks!

**Comment by kevinchalet** [comment]
I'm tempted to think that's because you're manually creating the `AuthenticationProperties` instead of using `_signInManager.ConfigureExternalAuthenticationProperties()`.

@Tratcher @HaoK do you happen to know if there's some (basic) documentation about that?

**Comment by HaoK** [comment]
`GetExternalLoginInfoAsync` is hardcoded to look for the IdentityConstants.External cookie, while your github is targetted at its own `AddCookie()` instance, so indeed there is no external identity in this case.

**Comment by HaoK** [comment]
The general idea is if you are trying to control authentication via your own AddAuthentication + defaults, you probably don't want to use SignInManager, its tightly coupled to the authentication cookies that identity adds.

You can try using AddIdentityCore if you want to avoid using SignInManager and have your own auth functionality.

**Comment by Corstiaan84** [comment]
@PinpointTownes @HaoK thank you for looking into this :-).

@PinpointTownes I have already tried using '_signInManager.ConfigureExternalAuthenticationProperties()' but without any results.

@HaoK Thank you for the insight. My experience with this asp.net core feature is still limited. Can you provide a short sample?

**Comment by AQutaishat** [comment]
in my case, i had to enable SSL, once i enabled SSL it returned info correctly, to enable SSL, right click on the project --> properties --> Debug --> check (Enable SSL) in web server strings section. i am using core 3.0
