### ISSUE TITLE
Error Authenticating Discord

### ISSUE THREAD

**Issue by BillChirico** [aspnet-contrib/AspNet.Security.OAuth.Providers#231]
Hello,

I am recieivng the following error on callback of Discord:

`HttpRequestException: An error occurred while retrieving the user profile.`

Is there any way I can debug this?

Thanks
- Bill

**Comment by BillChirico** [comment]
I was able to fix the issue by adding the ``identify`` scope. Even though it appears that the Discord provider is adding this scope by default.

``Scope.Add("identify");``

Is the scope not properly being added by default?

**Comment by anderaus** [comment]
It seems the `identify` scope was added as default in [this commit](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/d65db1e255d41f51bb413e1edfc15f979ac82a85#diff-988f5ffe95f8da158b7d6428bdaf6eae) on 23 Dec 2017. As far as I know it's currently only available in the [nightly build](https://www.myget.org/feed/aspnet-contrib/package/nuget/AspNet.Security.OAuth.Discord).

**Comment by BillChirico** [comment]
@anderaus That makes sense. Thank you!

**Comment by kevinchalet** [comment]
Yep, the fix will be included in the RTM release (shipping next month). In the meantime, manually adding the scope is the best workaround. Otherwise, you can use the nightly builds, as @anderaus said.
