### ISSUE TITLE
Receiving "An error occurred while retrieving the user profile.", when I use the new Twitch Api Endpoints.

### ISSUE THREAD

**Issue by Banafys** [aspnet-contrib/AspNet.Security.OAuth.Providers#232]
Twitch V5 api is currently deprecated and will be removed in August 2018.

> The domain dedicated to Twitch authentication is https://id.twitch.tv. (Previous visitors of this page will note that URLs were updated, to replace https://api.twitch.tv/kraken with https://id.twitch.tv. Code that uses the old, kraken domain for Twitch authentication will continue to work until the end of 2018, when we remove Twitch API v5 functionality. Twitch API v5 is currently deprecated.)
 [Twitch dev doc](https://dev.twitch.tv/docs/authentication/)

When I use the new endpoints, I receive "An error occurred while retrieving the user profile." 

`
     .AddTwitch(twitchOptions => {
                    twitchOptions.ClientId = "<removed>";
                    twitchOptions.ClientSecret = "<removed>";
                    twitchOptions.AuthorizationEndpoint = "https://id.twitch.tv/oauth2/authorize";
                    twitchOptions.TokenEndpoint = "https://id.twitch.tv/oauth2/token";
                    twitchOptions.UserInformationEndpoint = "https://api.twitch.tv/helix/users";
                });
`

**Comment by kevinchalet** [comment]
Enable logging. Logs should contain useful information (assuming the Twitch API returns something interesting).

**Comment by Banafys** [comment]
Reading through the console output I saw the following object:
`
{"error":"Unauthorized","status":401,"message":"Must provide a valid Client-ID or OAuth token"}
`
Looking at the network calls, I saw the request to the authorize endpoint and it's response. I don't see a request to the token endpoint.  I checked and the client-ID  and token endpoint are correct.

I switched the configuration to use the V5 api and everything worked fine.

**Comment by kevinchalet** [comment]
The scheme name has changed between the two versions: https://dev.twitch.tv/docs/authentication/#sending-user-access-and-app-access-tokens

It's something we'll have to change in the provider itself. Would you like to send a PR? **If so, please open it against the `release` branch** so we adopt the same change in both the 1.0 and 2.0 versions.

**Comment by kevinchalet** [comment]
Fixed.
