### ISSUE TITLE
Salesforce - The oauth state was missing or invalid

### ISSUE THREAD

**Issue by justinhelgerson** [aspnet-contrib/AspNet.Security.OAuth.Providers#236]
I can't seem to get past this exception when using the Salesforce OAuth package:

> Exception: The oauth state was missing or invalid.
> 
>     Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRequestAsync>d__12.MoveNext()
>     System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>     System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>     Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext()
>     System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>     Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

My `Startup.cs` class is fairly generic:

```
public class Startup {
        public Startup(IConfiguration configuration) {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services) {
            services.AddMvc();

            services.AddAuthentication(options => {
                options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            })
            .AddCookie(options => {
                options.LoginPath = "/signin";
                options.LogoutPath = "/signout";
            })
            .AddSalesforce(salesforceOptions => {
                salesforceOptions.ClientId = "real-client-id-is-here";
                salesforceOptions.ClientSecret = "real-secret-is-here";
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env) {
            if (env.IsDevelopment()) {
                app.UseBrowserLink();
                app.UseDeveloperExceptionPage();
            } else {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseStaticFiles();
            app.UseAuthentication();
            app.UseMvc(routes => {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }
```

I've been starting to dig into the source code for the OAuth handler, but I'm not sure why it's not able to read the state (or why it considers it invalid).  Salesforce is in fact returning a state parameter in the callback:

> https://localhost:44384/signin-salesforce?code=aPrxzp43SUYOZpHHFKio3l3Y3YUl6JV8a78QcATZYv14ygc5Jr5f4iHEPk1lCnMjiZW65_1BOw==&state=CfDJ8DJf4Bm-ZqJErpelQNxzmFbtI601Cob4p5K6XXuHoT0kXQhA4x7H8ql2cQs0kW78zatwipZ3ROgmd87f-k7GiITu39ugRTFAprQJgEiGkvDe_qRR40re1e3vabvJ5DzHOdTqygfi3Xi1jupZxk9wm350caczN2sjuXk2znqdEUmPXGRlIGDzmVA91xhVVDXATdKJn1_gqHY5kJYTlsFk1ybqf8RLGcn3nuulFJ1A3COW

Any suggestions would be appreciated.

**Comment by kevinchalet** [comment]
We don't do anything special in the Salesforce handler for the `state` parameter, so everything should be handled by the base ASP.NET Core OAuth2 handler.

Consider opening a ticket here so the ASP.NET folks can point you to the right direction: https://github.com/aspnet/Security

**Comment by justinhelgerson** [comment]
Thanks for the response @PinpointTownes.  I figured it was worth asking here in case there was a working example of the Salesforce provider that proved I was missing something simple.  I opened an issue and referenced this.

**Comment by kevinchalet** [comment]
Closing, as it looks like you found the root cause of your issue :tada:
