### ISSUE TITLE
Add Yammer provider

### ISSUE THREAD

**Issue by jerriep** [aspnet-contrib/AspNet.Security.OAuth.Providers#24]

**Comment by Rahul-Ec27** [comment]
I can pick this one

**Comment by trenoncourt** [comment]
Is there any news about the Yammer provider ?

**Comment by PinpointTownes** [comment]
@trenoncourt nope, no news. Would you like to contribute?

**Comment by trenoncourt** [comment]
I'll try to add Yammer next week ;), how to contribute ?

**Comment by PinpointTownes** [comment]
Jerrie wrote a great guide listing everything you need to start contributing: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/dev/CONTRIBUTING.md :smile:

**Comment by trenoncourt** [comment]
ok i read that, thank you.

**Comment by serber** [comment]
I send pull request for this issue

**Comment by PinpointTownes** [comment]
Related PR: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/98

**Comment by PinpointTownes** [comment]
Done: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/a55647ff227d05a4c6d6f2831b16ab80de90a62d.

@serber thanks for your great contribution! :+1:
