### ISSUE TITLE
Twitch Provider not working 

### ISSUE THREAD

**Issue by zAfLu** [aspnet-contrib/AspNet.Security.OAuth.Providers#242]
Since the 3789cfb36f1da6726c10aaec42538da2b986088b commit the Twitch Provider is broken. 

- Userendpoint should be "https://api.twitch.tv/helix/users/" 

- Claims are not working

- Scope should be Scope.Add("user:read:email");

**Comment by kevinchalet** [comment]
Thanks for the PR. Please also send a PR against the release branch (for 1.0) and I’ll make sure it’s part of RTM.

/cc @kinosang

**Comment by zAfLu** [comment]
Will try, need to merge my test setup to 1.0 :) Need some time. Will update his issue as fast as i can fix it

**Comment by kevinchalet** [comment]
Thanks! FYI, we ship next week, so you still have some time left :smile:

**Comment by kinosang** [comment]
Sorry for the mistakes. I didn't fully test the provider when I commit these changes.

**Comment by zAfLu** [comment]
btw the twitch provider is tested in Core 2.1 ^^

**Comment by zAfLu** [comment]
#244 tested with .Net Framework 4.5.1 

Our .Net Core 1.0 installation is broken so we couldn't test it :/

**Comment by kevinchalet** [comment]
Fixed, thanks!
