### ISSUE TITLE
Bitbucket - after flow, user not authenticated and zero claims

### ISSUE THREAD

**Issue by dazinator** [aspnet-contrib/AspNet.Security.OAuth.Providers#246]
on bitbucket.org, I created an Oauth consumer:

![image](https://user-images.githubusercontent.com/3176632/41792569-34140a6a-7651-11e8-8e44-649723ce879b.png)

Note: The callback url matches the callbackpath that the bitbucket oath provider expects i.e `/signin-bitbucket`

On startup I am configuring the bitbucket auth provider, with the secret, and scopes etc:

```

  // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(
                    Configuration.GetConnectionString("DefaultConnection")));
            services.AddDefaultIdentity<IdentityUser>()
                .AddEntityFrameworkStores<ApplicationDbContext>();

            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

            services.AddAuthentication(options =>
            {
                options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            })

           .AddCookie(options =>
           {
               options.LoginPath = "/login";
               options.LogoutPath = "/signout";
           })                        

           .AddBitbucket(options =>
           {
               options.ClientId = "*******";
               options.ClientSecret = "*******";
               options.Scope.Add("email");
               options.Scope.Add("account");
               options.Scope.Add("repository:admin");
             //  options.CallbackPath = "/signin-bitbucket"; // no need to set as this is the default.
              // options.
           });

            services.AddMvc();

        }


```

When I launch the app and sign in using bitbucket, I can see the flow completes (bitbucket asks me whether I want to grant the app access to my bitbucket account and I say yes, and I am redirected back to my app) but all I see is an unauthenticated user.

![image](https://user-images.githubusercontent.com/3176632/41793071-e7548824-7652-11e8-9b82-be850cce78ea.png)

What could I be missing?

Thanks

**Comment by dazinator** [comment]
And here are logs from debug output:

> Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 POST http://localtest.me/signin application/x-www-form-urlencoded 29
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Route matched with {action = "SignIn", controller = "Authentication", page = "", area = ""}. Executing action Website.Controllers.AuthenticationController.SignIn (website)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executing action method Website.Controllers.AuthenticationController.SignIn (website) with arguments (Bitbucket) - Validation state: Valid
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action method Website.Controllers.AuthenticationController.SignIn (website), returned result Microsoft.AspNetCore.Mvc.ChallengeResult in 2692.2875ms.
Microsoft.AspNetCore.Mvc.ChallengeResult:Information: Executing ChallengeResult with authentication schemes (Bitbucket).
AspNet.Security.OAuth.Bitbucket.BitbucketAuthenticationHandler:Information: AuthenticationScheme: Bitbucket was challenged.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action Website.Controllers.AuthenticationController.SignIn (website) in 2817.9616ms
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 2859.4444ms 302 
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localtest.me/signin-bitbucket?state=*********--***********&code=*********  
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.0\System.Collections.NonGeneric.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.0\System.Security.Principal.Windows.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler:Information: AuthenticationScheme: Identity.External signed in.
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 2202.0282ms 302 
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localtest.me/  
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Route matched with {action = "Index", controller = "Home", page = "", area = ""}. Executing action website.Controllers.HomeController.Index (website)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executing action method website.Controllers.HomeController.Index (website) - Validation state: Valid
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action method website.Controllers.HomeController.Index (website), returned result Microsoft.AspNetCore.Mvc.ViewResult in 0.0308ms.
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor:Information: Executing ViewResult, running view Index.
The thread 0x37c4 has exited with code 0 (0x0).
The thread 0x4624 has exited with code 0 (0x0).
The thread 0x36b4 has exited with code 0 (0x0).
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor:Information: Executed ViewResult - view Index executed in 13755.0397ms.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action website.Controllers.HomeController.Index (website) in 13819.9341ms

**Comment by dazinator** [comment]
Also note, after completing the flow, querying the database I do not see any user created. I was also not prompted to enter any name / email address for the new user account etc which I found odd.

**Comment by kevinchalet** [comment]
I'm tempted to say you're trying to add ASP.NET Core Identity to our default MVC sample, which doesn't use Identity but the cookie handler directly.

Identity uses a dual-cookie system: an external cookie - used to store the external provider identity until the user creates a user profile - and an application cookie.

The logs indicate the Bitbucket authentication part works (`Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler:Information: AuthenticationScheme: Identity.External signed in.`) so it's likely not an issue on our side.

If you need assistance with Identity, I suggest opening a new thread here: https://github.com/aspnet/Identity

**Comment by dazinator** [comment]
> Identity uses a dual-cookie system: an external cookie - used to store the external provider identity until the user creates a user profile - and an application cookie.

ah ok that explains a lot :-)
It looks like I successfully have the external cookie but am missing the rest of the flow that then allows user to create a profile proper :-)

![image](https://user-images.githubusercontent.com/3176632/41795157-ad60214e-7659-11e8-9b7f-8c4d930da1b0.png)

Will close this thanks for the pointer.
