### ISSUE TITLE
Unable to get email address claim from Yahoo provider

### ISSUE THREAD

**Issue by thdblood** [aspnet-contrib/AspNet.Security.OAuth.Providers#249]
I'm using **IdentityServer4** and needs to have external authentication. I need to get profile and email claims from the idp and I am able to do so with Google, Facebook and MS Live ID. However, I am unable to get the email claim in Yahoo.

In my Yahoo API app I specify **API Permissions** to **Profiles (Social Directory)** and selected ***Read/Write Public and Private***

In IdentityServer4 app I have specified the scope to include **sdpp-w** which supposedly should include the email address as an additional claim as stated in this [documentation][1].

Here's a snippet of my code:

**Startup.cs**

    services.AddAuthentication()
              .AddGoogle(options =>
              {
                  options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                  options.ClientId = Configuration.GetValue<string>("ExternalProviders:GoogleClientId");
                  options.ClientSecret = Configuration.GetValue<string>("ExternalProviders:GoogleSecretKey");
              })
              .AddFacebook(options =>
              {
                  options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                  options.AppId = Configuration.GetValue<string>("ExternalProviders:FacebookAppId");
                  options.AppSecret = Configuration.GetValue<string>("ExternalProviders:FacebookSecretKey");
                  options.CallbackPath = Configuration.GetValue<string>("ExternalProviders:FacebookCallbackPath");
              })
              .AddMicrosoftAccount("Microsoft", "Windows Live ID", options =>
              {
                  options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                  options.ClientId = Configuration.GetValue<string>("ExternalProviders:WindowsClientId");
                  options.ClientSecret = Configuration.GetValue<string>("ExternalProviders:WindowsSecretKey");
                  options.CallbackPath = Configuration.GetValue<string>("ExternalProviders:WindowsCallbackPath");
              })
              .AddYahoo(options =>
              {
                  options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                  options.Scope.Add("openid,sdpp-w");
                  options.ClientId = Configuration.GetValue<string>("ExternalProviders:YahooClientId");
                  options.ClientSecret = Configuration.GetValue<string>("ExternalProviders:YahooSecretKey");
                  options.CallbackPath = Configuration.GetValue<string>("ExternalProviders:YahooCallbackPath");
              });

**Config.cs**

    // scopes define the resources in your system
        public static IEnumerable<IdentityResource> GetIdentityResources()
        {
            return new List<IdentityResource>
            {
                new IdentityResources.OpenId(),
                new IdentityResources.Profile(),
                new IdentityResources.Email()
            };
        }

    // clients want to access resources (aka scopes)
        public static IEnumerable<Client> GetClients()
        {
            // client credentials client
            return new List<Client>
            {
                new Client
                {
                    ClientId = "mvc.manual",
                    ClientName = "MVC Manual Client",
                    AllowedGrantTypes = GrantTypes.Hybrid,
                    AllowAccessTokensViaBrowser = true,
                    ClientSecrets =
                    {
                        new Secret("secret".Sha256())
                    },

                    RedirectUris = { "https://mywebsite/account/signin-callback" },
                    PostLogoutRedirectUris = { "https://mywebsite/signout-callback" },

                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        IdentityServerConstants.StandardScopes.Email,
                        "api2"
                    },
                    AllowOfflineAccess = true
                }
            };
        }

Did Yahoo stopped providing email claims? Or am I missing something here?

  [1]: https://developer.yahoo.com/oauth2/guide/openid_connect/decode_id_token.html#additional-claims=

**Comment by kevinchalet** [comment]
`options.Scope.Add("openid,sdpp-w");` is not valid.

Use a `Add` call per scope instead of trying to separate them manually (and FWIW, scopes are space-separated, not comma-separated).

**Comment by thdblood** [comment]
@PinpointTownes thanks for the quick response. I appreciate it :)

Sorry I am relatively new to IdentityServer. Is there any documentation that I can refer to for these specific rules? So far, I have only based on the [Mvc.Client](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/tree/dev/samples/Mvc.Client) sample from this site, with which the only basis for adding scope is AddGithub, where added scope is colon separated. And the [Yahoo API docu](https://developer.yahoo.com/oauth2/guide/openid_connect/getting_started.html#getting-started-setup=) for getting started which states that scopes can be delimited by space or comma.

Also, I have tried adding the scopes separately:

    .AddYahoo(options =>
    {
        options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
        options.Scope.Add("openid");
        options.Scope.Add("sdpp-w");
        options.ClientId = Configuration.GetValue<string>("ExternalProviders:YahooClientId");
        options.ClientSecret = Configuration.GetValue<string>("ExternalProviders:YahooSecretKey");
        options.CallbackPath = Configuration.GetValue<string>("ExternalProviders:YahooCallbackPath");
    });

But I'm still not getting the email claim.

**Comment by kevinchalet** [comment]
We don't map the email claim by default.

I don't remember exactly how it is formatted by Yahoo, but something like `options.ClaimActions.MapCustomJson(ClaimTypes.Email, profile => (string) profile["emails"].First?["value"]);` might work. If it doesn't, you'll have to browse the documentation or intercept the JSON response and see how it's serialized.

**Comment by iojancode** [comment]
Based on @PinpointTownes and @thdblood I successfully got the Email claim like this:

```
options.Scope.Add("openid");
options.ClaimActions.MapCustomJson(ClaimTypes.Email, profile => (string) profile["emails"].First?["handle"]);
```
