### ISSUE TITLE
[Question] - obtaining access token and refresh tokens

### ISSUE THREAD

**Issue by dazinator** [aspnet-contrib/AspNet.Security.OAuth.Providers#253]
I am using the bitbucket provider, and after the login flow, I have an authenticated user logged into my sample website - which is great.

However, I would like to make a server side call to the bitbucket rest api on the next page to get a list of the users bitbucket repositories for display. The trouble is, i'd like to have the refresh token for the user at that point, so I that I can get an access token on the fly and make that rest call. As far as I can see the bitbucket provider doesn't make this available? (I can't see a refresh or access token in the users claims anywhere - not sure where else it would be..?) - so I am thinking currently I would need to initiate my own oauth flow a second time, to get access to a refresh token - is this right?

**Comment by kevinchalet** [comment]
Related: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/250.

This sample should put you on the right track: https://github.com/aspnet/Security/blob/master/samples/SocialSample/Startup.cs#L454

**Comment by dazinator** [comment]
Thanks!

In case it helps anyone else, for a new mvc website (with the scaffolded identity code) the location where you can get access to these tokens is in the `ExternalLoginModel.cs`:

![image](https://user-images.githubusercontent.com/3176632/42656622-b3a9e3be-8617-11e8-9e93-63e12011bf16.png)

After the redirect occurs, I believe they are lost, so if you want to persist them, you have to do it here.
