### ISSUE TITLE
Microsoft.AspNetCore.Authentication.OAuth version

### ISSUE THREAD

**Issue by zAfLu** [aspnet-contrib/AspNet.Security.OAuth.Providers#257]
Hi guys,

i made a PL (https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/256) to improve the Twitch Provider. While make these changes I figured out that I need to do some additional work on this PR if you guys have any plans to update **Microsoft.AspNetCore.Authentication.OAuth** to 2.1.x

So, my question is have you guys any plans on this atm?

**Comment by vsopko** [comment]
@PinpointTownes?

**Comment by martincostello** [comment]
The providers already support both 2.0, 2.1 and 2.2.

If a _specific_ provider has issues that you don't seem to be able to resolve, please raise an issue describing the problem and we can see if it's a bug that needs fixing.
