### ISSUE TITLE
Plz share Salesforce authentication and authroization

### ISSUE THREAD

**Issue by pessimca** [aspnet-contrib/AspNet.Security.OAuth.Providers#260]
I am looking for Salesforce authentication provider. Could you plz share an example with OAuth providers.

**Comment by martincostello** [comment]
The code for a Salesforce provider is available here:

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/tree/dev/src/AspNet.Security.OAuth.Salesforce

A NuGet package containing the last release of the provider can be found here:

https://www.nuget.org/packages/AspNet.Security.OAuth.Salesforce/
