### ISSUE TITLE
LicenseUrl is deprecated

### ISSUE THREAD

**Issue by xperiandri** [aspnet-contrib/AspNet.Security.OAuth.Providers#264]
https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg

Looks like you need to change it to `<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>` in `packages.props`

**Comment by martincostello** [comment]
Updated in https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/280/commits/790d017ff349f41745d8f2a1da883560c87b1573 as part of #280.

**Comment by martincostello** [comment]
Fixed by d03ee2b8efa4537d2b643ea9335ec1c6665f8faf in #290.
