### ISSUE TITLE
How to use Weibo login correctly

### ISSUE THREAD

**Issue by GreenShadeZhang** [aspnet-contrib/AspNet.Security.OAuth.Providers#274]
When I used this library, I used the Weibo part in the instance, but in the end I couldn't achieve the final effect, so I wanted to ask if anyone had ever used Weibo, or what they needed to pay attention to when using it.

**Comment by kinosang** [comment]
If you do not have access to email scope, remove it from the scope list while configure the provider.

```csharp
...
                .AddWeibo(options =>
                {
                    options.ClientId = "AppKey HERE";
                    options.ClientSecret = "AppSecret HERE";

                    options.Scope.Remove("email");
                })
...
```

**Comment by GreenShadeZhang** [comment]
Okay, I did what you said. There seems to be no problem, but I use the following example of the code to find out whether to log in, no data to return, so I'm not sure if it has been verified to log in. So what data can I use to determine if I logged in successfully.
`  @if (User?.Identity?.IsAuthenticated ?? false)
    {
        <h1>Welcome, @User.Identity.Name</h1>
        <p>
            @foreach (var claim in Context.User.Claims)
            {
                <div>@claim.Type: <b>@claim.Value</b></div>
            }
        </p>
        <a class="btn btn-lg btn-danger" href="/signout?returnUrl=%2F">Sign out</a>
    }
`
