### ISSUE TITLE
Evernote Support

### ISSUE THREAD

**Issue by jculverwell** [aspnet-contrib/AspNet.Security.OAuth.Providers#288]
Does anyone know if it should be possible to support Evernote https://dev.evernote.com/doc/articles/authentication.php , I believe its based on oauth1.0?

**Comment by martincostello** [comment]
Looking at the code for [Microsoft provider OAuth handler,](https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/OAuth/src/OAuthHandler.cs) which appears to be based on OAuth 2.0, and the [Twitter handler](https://github.com/aspnet/AspNetCore/blob/28d44af91a249c9229ba1bbe543898bdbbe4a871/src/Security/Authentication/Twitter/src/TwitterHandler.cs#L168) which explicitly uses OAuth 1.0, I would _think_ that it would need a more custom handler to be supported, as all the existing providers in this repo build on top of the Microsoft OAuth 2.0 base class.

**Comment by martincostello** [comment]
Closing for the same reasons as described by https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/150#issuecomment-289106098.

You would need to implement your own Evernote provider for OAuth 1.0.
