### ISSUE TITLE
StackExchange: ArgumentNullException: Value cannot be null

### ISSUE THREAD

**Issue by unruledboy** [aspnet-contrib/AspNet.Security.OAuth.Providers#289]
Usage:
          .AddStackExchange(options =>
              {
                  options.ClientId = "the-client-id-from-stack-exchange";
                  options.ClientSecret = "the-secret-from-stack-exchange";
              });

Exception after approved the request:

An unhandled exception occurred while processing the request.
ArgumentNullException: Value cannot be null.
Parameter name: value
System.Text.Encodings.Web.TextEncoder.Encode(string value)

Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()

ArgumentNullException: Value cannot be null.
 Parameter name: value
System.Text.Encodings.Web.TextEncoder.Encode(string value)
Microsoft.AspNetCore.WebUtilities.QueryHelpers.AddQueryString(string uri, IEnumerable<KeyValuePair<string, string>> queryString)
Microsoft.AspNetCore.WebUtilities.QueryHelpers.AddQueryString(string uri, IDictionary<string, string> queryString)
AspNet.Security.OAuth.StackExchange.StackExchangeAuthenticationHandler.CreateTicketAsync(ClaimsIdentity identity, AuthenticationProperties properties, OAuthTokenResponse tokens)
Microsoft.AspNetCore.Authentication.OAuth.OAuthHandler<TOptions>.HandleRemoteAuthenticateAsync()
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()

Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by kevinchalet** [comment]
You probably forgot to set the API key in the SE options, which causes this line to be null: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/dev/src/AspNet.Security.OAuth.StackExchange/StackExchangeAuthenticationHandler.cs#L41

We'll need to add some validation stuff to ensure we throw a better exception when the API key is not properly set.

**Comment by martincostello** [comment]
Changed in #294 to throw a `InvalidOperationException` with a message of `"No site was specified for the Site property of StackExchangeAuthenticationOptions."`.
