### ISSUE TITLE
More on documentation

### ISSUE THREAD

**Issue by unruledboy** [aspnet-contrib/AspNet.Security.OAuth.Providers#295]
During the testing of the providers, I often found myself in the situation as: I don't know where to apply for the API id/secret, I spent fair amount of time googling here and there.

It would be great to have a wiki page or some sort, for each provider, provides a link to a tutorial or some sort for the developer to start with.

**Comment by martincostello** [comment]
This is a good idea, I did a similar thing myself as part of reverse-engineering the API responses for #292.

The only downside is that the documentation will likely drift over time, but a bullet point list that just goes to the entry point to the docs for each provider might be useful as a starting point for people.

We'd certainly not want to maintain our own parallel documentation though.
