### ISSUE TITLE
LinkedIn Authentication Failed: An error occurred while retrieving the user profile

### ISSUE THREAD

**Issue by luniv04** [aspnet-contrib/AspNet.Security.OAuth.Providers#300]
I am trying to use this article [ASP.NET Core 2.0: Authentication Using LinkedIn](https://social.technet.microsoft.com/wiki/contents/articles/51464.asp-net-core-2-0-authentication-using-linkedin.aspx) and follow it step by step to try an authenticate using LinkedIn.  There are a few differences that I would like to point out.  I am using Visual Studio 2019.  I am using ASP.NET Core 2.2.  I am also using **<PackageReference Include="AspNet.Security.OAuth.LinkedIn" Version="2.0.1" />** and not **<PackageReference Include="AspNet.Security.OAuth.LinkedIn" Version="2.0.0-rc2-final" />**.

When I run the application, everything seems to work pretty good at first.  I click on the LinkedIn button and I am transferred to LinkedIn.  I enter my credentials and submit them.  A redirect is performed to my locally hosted application.  But then something goes wrong.  The application just doesn't quite accept the response.

Within the method `OnRemoteFailure = loginFailureHandler => {...}` my breakpoint is getting hit.  There is some problem authenticating.  When I look into the context of `loginFailureHandler.Failure` I can see the following error message {"An error occurred while retrieving the user profile."}.

I did see this similar [issue](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/232), but my situation seems to be a little different.  I did try looking at the response from LinkedIn with Fiddler and there was nothing useful.  I am not sure if there are any other logs that I can get into to see useful information.

Any ideas would be greatly appreciated.  Running through the article literally takes just 5 minutes but it doesn't work.

**Comment by martincostello** [comment]
This is likely the same issue as #277 which is being fixed in #298.

**Comment by luniv04** [comment]
Thanks for the super quick response.  I will try getting that branch building and testing later today to see if those code changes with that PR fix my issue or not.

**Comment by luniv04** [comment]
I have tested it out and I am getting a different error.  I think there is a logical issue with the PR on #298.  Specifically in _AspNet.Security.OAuth.Providers\src\AspNet.Security.OAuth.LinkedIn\LinkedInAuthenticationOptions.cs_ on line 45 _ClaimActions.MapCustomJson(Claims.PictureUrls, user => string.Join(",", GetPictureUrls(user)));_ where GetPictureUrls can return a null value.  I am getting an ArgumentNullException for the Parameter name: values.

**Comment by luniv04** [comment]
I added my comment in the #298 PR.

**Comment by luniv04** [comment]
This PR seems to get me past my issue.

**Comment by ajitgoel** [comment]
I am having the same issue and I am using ASP.Net Core 2.2 and AspNet.Security.OAuth.LinkedIn version 2.0.1. There is no prerelease version available also. How can I get the changes listed above? 

Update: This issue can be fixed by adding https://www.myget.org/F/aspnet-contrib/api/v3/index.json as a package source in Visual Studio and downloading the latest stable build(2.1.0). 
Thank you Martin Costello

**Comment by kevinchalet** [comment]
The 2.1.0 packages were just pushed to NuGet.org: https://twitter.com/PinpointTownes/status/1136691785193926656

Kudos to @martincostello for the time he dedicated to this release! 👏
