### ISSUE TITLE
Use QueryHelpers.AddQueryString(string, string, string) more

### ISSUE THREAD

**Issue by martincostello** [aspnet-contrib/AspNet.Security.OAuth.Providers#307]
In a few providers, the `QueryHelpers.AddQueryString(string, string, string)` method isn't used to append a single query string parameter, meaning we're allocating a dictionary unnecessarily in a few places.

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/aad5420654c65b5fb9908ddf298dbab17076338c/src/AspNet.Security.OAuth.Baidu/BaiduAuthenticationHandler.cs#L37-L40

We should do a sweep of the all provider to simplify the code where relevant.

**Comment by kevinchalet** [comment]
I'm all for simplifying things, but don't expect any measurable perf' gain here: the method accepting 2 string parameters internally creates an array and calls the same private method as the one we were previously using: https://github.com/aspnet/AspNetCore/blob/master/src/Http/WebUtilities/src/QueryHelpers.cs#L21 🤣

**Comment by martincostello** [comment]
Yeah I wasn't expecting anything Earth-shattering in terms of perf, just making things a bit neater 😃
