### ISSUE TITLE
Add CONTRIBUTING file

### ISSUE THREAD

**Issue by kappa7194** [aspnet-contrib/AspNet.Security.OAuth.Providers#31]
GitHub supports a CONTRIBUTING file containing guidelines for contributions, it will be automatically displayed when opening issues, pull request and so on.

It would be useful to list there the requirements (e.g. http://www.jerriepelser.com/blog/calling-contributors-for-oauth-providers — "How to do this").

See https://github.com/blog/1184-contributing-guidelines for details.

**Comment by PinpointTownes** [comment]
It's actually a **very** good idea, thanks for suggesting it :+1: 

I'll ping @jerriep and see if we can reuse his blog post to add a  `CONTRIBUTING.md` file in all the aspnet-contrib projects.

**Comment by jerriep** [comment]
Of course, feel free to use it as a starting point and then we can refine it as we go along.

**Comment by tparnell8** [comment]
Also,

can we use a `.vsssettings` file instead of something resharper specific? I wrote [this blog post](https://blog.tommyparnell.com/vs-2015-getting-resharper-experiance-without-resharper/) recently and since I have abandoned resharper. Also I spend half of my time in ubuntu on monodevelop so..I never have resharper anymore. Plus resharper is a paid product which could alienate people who wish to contribute to this library, that cannot get access to such software.

**Comment by jerriep** [comment]
Of course. The main thing which may be different from what most people are used to is that the opening braces are at the end of the line. 

I am not familiar with the .vsssettings file, so if you can create one and submit a PR it would be great

**Comment by tparnell8** [comment]
Just curious...any reasons why we are coding java style?

**Comment by jerriep** [comment]
Haha, not sure :) @PinpointTownes can answer that one. 

He's the boss and I'm marching to his tune ;)

**Comment by PinpointTownes** [comment]
> Just curious...any reasons why we are coding java style?

Well, K&R was the main coding style in MSFT until ASP.NET MVC 3 :smile: 
Personally, I kept using it as it's a perfect compromise between code clarity and code length, but I guess it's a matter of personal preference.

> can we use a .vsssettings file instead of something resharper specific?

Sure, I can upload mine if you want. But I guess you'll have to manually import it and that it will override your global configuration? Or maybe a plugin like CodeMaid has something built-in for project settings?

**Comment by kappa7194** [comment]
>But I guess you'll have to manually import it and that it will override your global configuration?

Yes, you're going to rewrite the local settings for the whole Visual Studio:

![image](https://cloud.githubusercontent.com/assets/1249988/9735300/14dc9b10-563a-11e5-8254-28be14ad4d0c.png)

>can we use a .vsssettings file instead of something resharper specific?

I don't think there's a way to set coding preferences per-project instead of "per-everywhere".

>I wrote this blog post recently and since I have abandoned resharper.

:unamused:

ReSharper is the single most useful productivity extension and memory hog for Visual Studio (totally unbiased opinion).

>I am not familiar with the .vsssettings file, so if you can create one and submit a PR it would be great

That's a possible solution: you set the guidelines (in the CONTRIBUTING file, in a ReSharper configuration file, in a CodeMaid configuration file, and so on) and everybody codes where and how they like but the pull-requests must conform to the given guidelines to be accepted (they are checked by someone with ReSharper).

**Comment by jerriep** [comment]
Is there not an open source utility that does something like this? 

I am not too familiar with it, but I believe in the JavaScript world JSLint will check this for you. But I am speaking under correction.

**Comment by kappa7194** [comment]
>Is there not an open source utility that does something like this?

>I am not too familiar with it, but I believe in the JavaScript world JSLint will check this for you. But I am speaking under correction.

One I know is [CodeMaid].

Oh, don't forget about [Code Analysis]:

![image](https://cloud.githubusercontent.com/assets/1249988/9735509/ac9823c4-563b-11e5-9974-02acddfffe38.png)

It's not as thorough as StyleCop (RIP) but it's still useful.

Beware that I don't know if it's available in every edition of Visual Studio (it's there in 2015 Community Edition).

[CodeMaid]: http://www.codemaid.net/
[Code Analysis]: https://msdn.microsoft.com/en-us/library/3z0aeatx.aspx

**Comment by jerriep** [comment]
Ahh, OK yes I see @PinpointTownes mentioned CodeMaid above as well as well as you in your post. Sorry...

Yes, then we should set up CodeMaid so people can run it over their code before they commit. That would be the easiest.

**Comment by tparnell8** [comment]
CodeMaid is **definitely** fine. Anything that lowers the barrier to entry is where its at.

**Comment by tparnell8** [comment]
@kappa7194 https://www.nuget.org/packages/StyleCop.Analyzers/1.0.0-beta009

**Comment by jerriep** [comment]
Have a look at this as well. It is used by the dotnet team:

http://blogs.msdn.com/b/dotnet/archive/2015/02/09/automatic-code-formatter-released-to-github.aspx

**Comment by PinpointTownes** [comment]
> That's a possible solution: you set the guidelines (in the CONTRIBUTING file, in a ReSharper configuration file, in a CodeMaid configuration file, and so on) and everybody codes where and how they like but the pull-requests must conform to the given guidelines to be accepted (they are checked by someone with ReSharper).

I never merge a PR as-is. PRs are always cherry-picked and verified: if code style fixes are needed, they are immediately applied and squashed before being pushed. It takes a bit of time, but we're sure we don't have inconsistent providers :smile: 

I'll take a look at CodeMaid and give it a try. In the meantime, don't worry about sending a PR with inconsistent code styling, it will be fixed at some point before merging :smile: 

@tparnell8 does it now work with DNX (ASP.NET 5) apps? The last time I tried, they were not supported.

**Comment by jerriep** [comment]
The comments from you guys about Resharper have made me re-evaluate its use in my development. I simply love Resharper, but with VS 2015 Microsoft has taken massive leaps forward in providing many of the things which I used Resharper for. And yes,

The community is also adding a lot of stuff of top of that using the Roslyn compiler.

So I am going to experiment for the next week or so and see whether I can get by without using Resharper.

**Comment by jerriep** [comment]
I'll start working of putting together documentation for contributors

**Comment by tparnell8** [comment]
Resharper is like a drug, once you get over the 2 day hump everything seems fine. Also there are a fantastic assortment of open source extensions that really improve the editing experience of VS, without the performance implications of resharper (I notice it really slows down my editor).

**Comment by PinpointTownes** [comment]
CONTRIBUTING.md added: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/385393e3db05730456b91d36b92362d1e36eca53

Concerning the code style thing, I'm convinced it should be mitigated by the new Yeoman generator added by @jerriep.

**Comment by jerriep** [comment]
I am sad (or mayby happy?) to that my attempt to go without Resharper lasted mere hours... I could see a marked improvement in the speed on the IDE when I turned Resharper off, but I just found it too hard to go without it... :(

**Comment by tparnell8** [comment]
what feature(s) were you missing that you 'had to have'

**Comment by tparnell8** [comment]
The only thing I miss is the resharper intellisense. TBH their intellisense is ungodly amazing, but I have learned some tricks to improve the regular VS intellisense.

**Comment by jerriep** [comment]
Yeah, their intellisense was one of the major ones. The ability to just type any part of the identifier and it will list it for you - even when it is in a namespace which is not referenced yet. The VS camel humps are good, but it does not come close to Resharper.

I also use a lot of other code fixes which I could not quite find equivalents for. Like declaring a field and then instantly have Resharper initialize it through the constructor. 

I should actually turn it off again and then make detailed notes about the things which frustrates me to go without. It would make good material for a blog post ;)

**Comment by tparnell8** [comment]
hmm I forgot about that one the .ctor initialize we could make a VS plugin...

The VS intellisense won't auto complete the non referenced classes, but if you type the whole name of a Type that is not referenced you have like a 1/3 that it will lightbulb for a using statement.

If you document what you don't have/like I/we can try to make extensions for it. I'd mostly like to improve the experience for people whom do not have access to resharper.

**Comment by jerriep** [comment]
Sure, I will do the experiment again and write a blog post with a nice click-bait title like "I turned Resharper off for a week and you will NEVER guess what happened next..." ;)

**Comment by tparnell8** [comment]
Alrighty

**Comment by tparnell8** [comment]
it would be cool if you could ref my [blog post](https://blog.tommyparnell.com/vs-2015-getting-resharper-experiance-without-resharper/) ;)

**Comment by jerriep** [comment]
Oh cool, I also subscribed to your RSS feed so I can monitor it for potential content for ASP.NET Weekly

**Comment by tparnell8** [comment]
sweet I have 2 posts I have already written, I think both will be relevant, I will be publishing one in a day or two and the other the following week.
