### ISSUE TITLE
Consider throwing an exception when additional userinfo requests fail

### ISSUE THREAD

**Issue by kevinchalet** [aspnet-contrib/AspNet.Security.OAuth.Providers#313]
Currently, the GitHub/BitBucket/Weibo providers don't throw when an error occurs while retrieving the email address associated with the user account (which can't be done via the "normal" userinfo endpoint).

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/7b906829dc24fda3d0b23be21a69b62d2e236e48/src/AspNet.Security.OAuth.GitHub/GitHubAuthenticationHandler.cs#L82-L92

Retrospectively, it wasn't really a good approach, as it may result in incomplete information. In this case, failing immediately would be better as it would force users to retry signing in.

The LinkedIn provider already does the right thing, so we should adopt a similar pattern.

@martincostello worth doing that as part of 2.1.0?

**Comment by martincostello** [comment]
This sounds like a reasonable change - I wonder, is it worth shipping 2.1.0 first, and then doing this in a 2.1.1?

I'm just a bit wary of the scope keeping creeping a little bit more, then a little it more... 😃

**Comment by kevinchalet** [comment]
It will be my only demand, I promise 😄

**Comment by martincostello** [comment]
Cool - are you going to fix this, or do you want me to do it?

I'll also need to port the few commits to dev since I cut the `rel/2.1.0` branch over to there too.

**Comment by martincostello** [comment]
We can close this now 2.1.0's shipped now, right?

**Comment by kevinchalet** [comment]
Oh yeah (not sure why GH didn’t close it when the PR was merged 😕)
