### ISSUE TITLE
Support for Apple Sign-in

### ISSUE THREAD

**Issue by leastprivilege** [aspnet-contrib/AspNet.Security.OAuth.Providers#314]
I think it's about time that this repo also supports Apple Sign-in.

Please implement ;)

https://github.com/IdentityServer/IdentityServer4/issues/3312#issuecomment-498566609

**Comment by martincostello** [comment]
I wondered how long until someone asked about this... 😄 

I haven't read up on the implementation details yet - is it OAuth 2.0 based?

**Comment by kevinchalet** [comment]
> Please implement ;)

Well, you know how it works 😄 

> I haven't read up on the implementation details yet - is it OAuth 2.0 based?

Yeah, it's an OpenID Connect code flow with a non-standard client authentication logic, inspired by OIDC's `private_key_jwt` method. Oh, and there's no discovery endpoint (but there's a JWKS doc' at https://appleid.apple.com/auth/keys)

**Comment by martincostello** [comment]
Fun - I might take a look at the weekend and see how long it takes my eyes to bleed 😄

**Comment by leastprivilege** [comment]
https://developer.okta.com/blog/2019/06/04/what-the-heck-is-sign-in-with-apple

**Comment by martincostello** [comment]
@leastprivilege Thanks!

**Comment by blowdart** [comment]
Auth0 broke down how the client ID works

https://auth0.com/blog/what-is-sign-in-with-apple-a-new-identity-provider/

**Comment by martincostello** [comment]
Skeleton 💀 implementation begun in #318.

**Comment by dbevan-kabam** [comment]
@martincostello, just trying this and I'm getting `System.Exception: An error was encountered while handling the remote login. ---> System.Exception: The oauth state was missing or invalid.`
I also get this on your sample app https://github.com/martincostello/SignInWithAppleSample.
Maybe something has changed their end or I'm doing something incorrectly?

**Comment by martincostello** [comment]
@dbevan-kabam I've seen some mention in others' blog posts about the scopes being set on the first request for a user causing issues (at least, I think it was the scopes), but I couldn't replicate it myself.

You could try clearing the scopes and seeing if that fixes it?

https://github.com/martincostello/SignInWithAppleSample/blob/20191322779c989c98ac1d0e50442526c52b2125/src/SignInWithApple/Apple/AppleAuthenticationOptions.cs#L31-L32

**Comment by martincostello** [comment]
Releases of the Apple provider are available for ASP.NET Core 2.x and ASP.NET Core 3.0 in MyGet:
  * https://www.myget.org/feed/aspnet-contrib/package/nuget/AspNet.Security.OAuth.Apple/2.2.0-preview-0891
  * https://www.myget.org/feed/aspnet-contrib/package/nuget/AspNet.Security.OAuth.Apple/3.0.0-release.19473.83

**Comment by zicjin** [comment]
Can we get a jwt simple?

**Comment by martincostello** [comment]
@zicjin There’s some examples in the tests: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/dev/test/AspNet.Security.OAuth.Providers.Tests/Apple/bundle.json#L30

**Comment by martincostello** [comment]
Publishing the 2.2.0 and 3.0.0 versions of this package may be delayed, as [another user](https://www.nuget.org/profiles/oakley) has uploaded a prerelease version of the package to NuGet.org so we won't have permission to publish additional versions without either a rename or them transferring ownership and/or granting co-ownership of the package.

I've reached out to the user via the "Contact owners" feature in NuGet.org.

> You sent the following message via NuGet Gallery:
> User martin_costello <email address> sends the following message to the owners of Package 'AspNet.Security.OAuth.Apple 2.1.1-preview'.
> 
> Hi,
> 
> Would you please consider transferring the package Id to the aspnet-contrib organisation/user (or making it a co-owner) please?
> 
> We're unable to publish the final 2.2 and 3.0 versions of this package as the package Id has been claimed by you.
> 
> Regards, Martin

/cc @PinpointTownes

**Comment by kevinchalet** [comment]
We received a package ownership request last month for the Apple package. I just accepted it so we should be able to push new versions without hitting permission issues.

**Comment by martincostello** [comment]
Packages for _Sign In with Apple_ are now available for ASP.NET Core 2.1+ and 3.0 in NuGet.org:

  * [AspNet.Security.OAuth.Apple 2.2.0](https://www.nuget.org/packages/AspNet.Security.OAuth.Apple/2.2.0)
  * [AspNet.Security.OAuth.Apple 3.0.0](https://www.nuget.org/packages/AspNet.Security.OAuth.Apple/3.0.0)

**Comment by suencien** [comment]
Hi guys, does anyone have reference to ASP.NET Web Forms version with OpenId Connect?
