### ISSUE TITLE
Add imgur provider

### ISSUE THREAD

**Issue by kappa7194** [aspnet-contrib/AspNet.Security.OAuth.Providers#32]
See https://github.com/RockstarLabs/OwinOAuthProviders/pull/110

**Comment by kappa7194** [comment]
I haven't used ASP.NET 5 yet, so things will be… interesting. :scream:

**Comment by PinpointTownes** [comment]
@kappa7194 thanks for suggesting this new provider :+1: 

> I haven't used ASP.NET 5 yet, so things will be… interesting. :scream:

If you need help with ASP.NET 5, feel free to ping us here or on Gitter: https://gitter.im/aspnet-contrib/AspNet.Security.OAuth.Providers :heart: 

One thing to remember with aspnet-contrib projects is that we always reference the latest (nightly) ASP.NET 5 packages, so make sure to update your DNX runtime using `dnvm upgrade -u` and your ASP.NET packages to match the DNX version.

**Comment by PinpointTownes** [comment]
Implemented: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/7fba20fc50a4fa188101ace9bb4923b6ff273fdf

Thanks for your contribution @kappa7194! :tada:
