### ISSUE TITLE
Nextcloud Provider Test issue

### ISSUE THREAD

**Issue by zAfLu** [aspnet-contrib/AspNet.Security.OAuth.Providers#320]
Hello, 

first of all, sorry for not using any of the issue templates but I guess my issue doesn’t fit in any of these. :)
 I’m using Nextcloud and I thought it would be a good idea do write a provider. I wrote one today and now I’m struggling a bit with the provider test. If you are familiar with nextcloud you know that your mostly find self-hosted instances. So, I need to removed the default values for AuthorizationEndpoint, TokenEndpoint and UserInformationEndpoint to make sure everyone is forced to include his own server endpoints. This means we do not have any default endpoints for the bundle.json. 

So my question: What can I do? Just skip the Test and build a PR or any other ideas? 

Code: https://github.com/zAfLu/AspNet.Security.OAuth.Providers/commit/aaecd85f4cd930fbed1858a84de6e0fd4fc7f709

**Comment by martincostello** [comment]
If that’s the case that the endpoints have to be provided by the integrator, you should set them to _something_ in the tests and then set up the responses based on those.

**Comment by zAfLu** [comment]
Something like 
```
  "items": [
    {
      "uri": "https://yourdomain.tld/apps/oauth2/api/v1/token",
      "method": "POST",
      "contentFormat": "json",
      "contentJson": {
        "access_token": "secret-access-token",
        "token_type": "access",
        "refresh_token": "secret-refresh-token",
        "expires_in": "300"
      }
    },
```
?

**Comment by martincostello** [comment]
`https://nextcloud.local/{whatever}`?

**Comment by zAfLu** [comment]
Will have a look on this later. Thanks mate
