### ISSUE TITLE
How to get fields like Location after linkedin autetication?

### ISSUE THREAD

**Issue by TheAkiraxD** [aspnet-contrib/AspNet.Security.OAuth.Providers#323]
I see some configurations in the `LinkedInAuthenticationOptions`, for example,  it's adding the "r_liteprofile" to the scope. Also, in the `LinkedInAuthenticationConstants` file the Location field is shown as obsolete. So, how exactly can I retrieve basic profile fields (example: Location) after the user signin with LinkedIn?

**Comment by martincostello** [comment]
In the v2 LinkedIn API you need to change the scope to request the full profile, then you should have access to the location.

See the documentation here:

  1. [Field Selections](https://docs.microsoft.com/en-us/linkedin/shared/integrations/people/profile-api?context=linkedin/consumer/context#field-selections)
  1. [Location Fields](https://docs.microsoft.com/en-us/linkedin/shared/references/v2/profile/location)

**Comment by AtaaEddin** [comment]
is there other way to auth and get user information from consecutive requests to linkedIn API. becuase i don't want to store user info in cookies and login the user. I just want the user data.
