### ISSUE TITLE
Where do you put the default scope?

### ISSUE THREAD

**Issue by tparnell8** [aspnet-contrib/AspNet.Security.OAuth.Providers#34]
In the Owin project we put a default scope in the options file (like this one from the github plugin)

https://github.com/tparnell8/OwinOAuthProviders/blob/master/Owin.Security.Providers/GitHub/GitHubAuthenticationOptions.cs#L134

where do we put the default scope, for basic login and user read permissions?

**Comment by PinpointTownes** [comment]
This is still supported: simply add `Scope.Add("user")` in `GitHubAuthenticationOptions`.

That said, we generally limit the requested scope to the bare minimum needed for authentication, so not seeing this practice in the ASP.NET 5 middleware is not surprising :+1:

**Comment by tparnell8** [comment]
Got it thanks!

**Comment by jerriep** [comment]
Yeah, on the OWIN side I got a lot of flack from some users about being too aggressive with the scopes I requested. And they were right.

So please ensure you limit scopes to the bare minimum needed to get the basic user information so you can populate the correct claims for ASP.NET Identity

**Comment by tparnell8** [comment]
of course, I only asked because last I looked (and things could be different now) twitch.tv required a scope declaration even if it was the most basic scope in their tree.

**Comment by jerriep** [comment]
:+1:
