### ISSUE TITLE
Add a SPA guide (integration w/ angular) (a solution is in the post)

### ISSUE THREAD

**Issue by BasHamer** [aspnet-contrib/AspNet.Security.OAuth.Providers#341]
**Is your feature request related to a problem? Please describe.**
utilizing this solution in a SPA is a little bit tricky due to the POST behavior in the sample. It is easily fixed by adjusting the get endpoint

**Describe the solution you'd like**

in the controller
```
....
 [HttpGet("~/signin")]
        public async Task<IActionResult> SignIn()
        {
            if (HttpContext.Request.Query.Any(x => x.Key == "provider"))
                return await SignIn(HttpContext.Request.Query.First(x => x.Key == "provider").Value);
            return View("SignIn", await HttpContext.GetExternalProvidersAsync());
        }

        [HttpPost("~/signin")]
        public async Task<IActionResult> SignIn([FromForm] string provider)
        {
.....
```

in angular

```
.....

  github(): void {
    this.postSignin('GitHub');
  }

  private postSignin(provider: string) {
    window.location.href = '/signin?provider='+provider;
  }
.....
```

**Describe alternatives you've considered**
Creating a form w post actions does not work as angular hijacks the form; using the post-action fails as the 302 is hard to handle.

**Additional context**
The code is pretty trivial but if you go down the path of making a POST work you can spend hours with redirects etc. Redirecting to the ASP page creates styling challenges and duplication.

Feel free to close this if adding this to the samples in out of scope.

**Comment by martincostello** [comment]
I'm not familiar with SPAs and any potential security implications of doing the flow via a GET rather than a POST.

I'll defer to the other contributors for opinions on this suggestion.

**Comment by BasHamer** [comment]
For reference, here is an example of the threads you end up in trying to get a post to work: https://github.com/angular/angular/issues/15165
The technical aspects are not as important, but it is easy to glance the frustration from the thread.

**Comment by fjod** [comment]
also this https://github.com/dotnet/aspnetcore/issues/7079
looks like this package is not supposed to work with SPA

**Comment by kevinchalet** [comment]
It has nothing to do with the aspnet-contrib social providers - that work exactly like the Facebook/Google/Twitter providers developed by Microsoft - it's how OAuth 2.0 works: you can't initiate an authorization flow from the "JS side" and expect the server-side authentication handlers will magically work in this configuration.

If you want to use token authentication with a remote social provider in your SPA, consider creating your own authorization server your SPA will communicate with. I wrote a blog post about that: https://kevinchalet.com/2020/02/18/creating-an-openid-connect-server-proxy-with-openiddict-3-0-s-degraded-mode/
