### ISSUE TITLE
2.2.0 release

### ISSUE THREAD

**Issue by martincostello** [aspnet-contrib/AspNet.Security.OAuth.Providers#344]
New providers added to `dev` since `2.1.0` are:

  1. Apple (#318)
  1. GitLab (#329)
  1. Nextcloud (#325)
  1. Shopify (#326)

Before merging `dev-3.0.0` into `dev` and then creating the `rel/3.0.0` branch, I guess we should publish a new 2.x release for these 4 new providers.

What release should that be, `2.1.1` or `2.2.0`?

I'm guessing the latter as this is adding new functionality. Thoughts?

**Comment by martincostello** [comment]
I've pushed up a [`rel/2.2.0` branch](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/tree/rel/2.2.0) to support the new providers for ASP.NET Core 2.2.

**Comment by martincostello** [comment]
`2.2.0` packages here: https://ci.appveyor.com/project/aspnet-contrib/aspnet-security-oauth-providers/builds/27888066/artifacts

**Comment by martincostello** [comment]
And example metadata (Arcade changes aren't in `rel/2.2.0`):

![image](https://user-images.githubusercontent.com/1439341/66227229-aa87ea00-e6d4-11e9-961f-da6805c7dfdf.png)

**Comment by martincostello** [comment]
Release notes and tag prepared in GitHub.

**Comment by martincostello** [comment]
Just need @PinpointTownes to push the packages to NuGet.org when he has some time available 😃

**Comment by kevinchalet** [comment]
@martincostello it's at the top of my todo list. They'll be pushed to NuGet.org this week 😄

**Comment by kevinchalet** [comment]
The 2.2.0 packages are now on NuGet.org 🎉
