### ISSUE TITLE
Apple SignIn returns invalid_client

### ISSUE THREAD

**Issue by will84512** [aspnet-contrib/AspNet.Security.OAuth.Providers#353]
I've been getting an error back after authentication from the Apple login. The error that I'm getting is: 

```
Exception: OAuth token endpoint failure: Status: BadRequest;Headers: Server: Apple
Date: Wed, 16 Oct 2019 15:35:48 GMT
Connection: keep-alive
Cache-Control: no-store
Pragma: no-cache
;Body: {"error":"invalid_client"};
Unknown location

Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
```

Using version 2.2.0 of AspNet.Security.OAuth.Apple
Seems to pass to Apple's side and authenticate OK, then fails on the Return URL with the above error. 

The service is setup as:
`services.AddAuthentication().AddApple(appleOptions =>
            {
                appleOptions.ClientId = Configuration["Authentication:Apple:ClientId"];
                appleOptions.ClientSecret = Configuration["Authentication:Apple:Secret"];
                appleOptions.KeyId = Configuration["Authentication:Apple:KeyId"];
            });`
With the ClientSecret entered as the string from the AuthKey.p8 file from Apple.

I'm trying to figure out if its an issue with the Apple setup, the OAuth calls or the app itself. Has anyone else experienced the same issue? Or have I missed some part of the setup?

Apple App ID, Service and Keys appear to be setup OK on their site.

**Comment by martincostello** [comment]
Sign In with Apple is a little different, and the client secret is built dynamically from the key file and some other parameters, you’re not given a static client secret to use. You can see an example of configuring the Apple provider here:

https://github.com/martincostello/SignInWithAppleSample/blob/5e6d92f3845d7b3d9759b3965e2ea30e7d0928d8/src/SignInWithApple/Startup.cs#L37-L46

**Comment by will84512** [comment]
Excellent! All working now, thanks so much and keep up the good work! 👍🏻

**Comment by kotishwerreddy** [comment]
https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/503

please help us we are also facing same issue.
