### ISSUE TITLE
add a option to lower case returnUrl for salesforce

### ISSUE THREAD

**Issue by wjzhou** [aspnet-contrib/AspNet.Security.OAuth.Providers#357]
**Is your feature request related to a problem? Please describe.**
The salesforce's return url seems to be case sensitive. When the wrong case is used for the base path, it would return
```error=redirect_uri_mismatch&error_description=redirect_uri%20must%20match%20configuration``` 

**Describe the solution you'd like**
Add an option to force lower case the returnUrl

**Additional context**
Salesforce only allows the domain part to be case-insensitive, (which is correct according to the standard). But I don't think this is what the end user expected. Also it is very hard for the developer to figure out why it doesn't work...

**Comment by martincostello** [comment]
Personally I think it's better to not "munge" the configuration and potentially hide mis-configurations from the user.

Even if we did provide the option, I don't think it would be the default, so once working out what the issue was (even if that's difficult), you'd still need to make a code change to fix it, so you might as well just fix the configuration to have the right case instead.

**Comment by wjzhou** [comment]
The problem is that the wrong-case base url is from end user, not from my configuration.

In my case, the end-user entered the wrong case url manually...

E.g. I deployed the app to
https:/example.com/app1

But the end-user manually type the url, and they typed it as 
https:/example.com/**App1** 

The callback url would be generated as https:/example.com/**App1**/salesforce-signin, which salesforce returned that redirect_uri_mismatch error message.

For now, I use the following as a workaround.
```
                o.Events.OnRedirectToAuthorizationEndpoint = async (context) =>
                {   
                    context.RedirectUri = toLowerCasePath(context.RedirectUri ) ;
                    await origOnRedirectToAuthorizationEndpoint(context);
                };
```

Which is kind of ugly, because I have to parse the uri and change only the path part and leave the base64 part alone.

I understand your reasoning. Please feel free to close this issue.
