### ISSUE TITLE
Yandex authorization doesn't work anymore

### ISSUE THREAD

**Issue by impworks** [aspnet-contrib/AspNet.Security.OAuth.Providers#359]
**Describe the bug**
After a successful authorization via Yandex, an exception is thrown in
```
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
```

**Steps To reproduce**
1. Authorize via Yandex
2. Wait until you are redirected to `/signin-yandex` on your app

**Expected behaviour**
Authorization succeeds.

**Actual behaviour**
```
System.Exception: An error occurred while retrieving an access token.

System.Exception: An error was encountered while handling the remote login. ---> System.Exception: An error occurred while retrieving an access token.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**System information:**
 - OS: Windows 10 (But happens in a docker container too)
 - Library Version: 2.0.1, 2.2.0
 - .NET version: .NET Core 2.2

**Comment by martincostello** [comment]
Are you able to enable more detailed logging and provide some HTTP request details of what’s going on internally so we can rule out an error from the service?

**Comment by impworks** [comment]
My app sends a request to Yandex API (all personal info replaced by &lt;PLACEHOLDERS&gt;):

```
GET https://oauth.yandex.ru/authorize?client_id=<CLIENTID>&scope=login%3Aemail%20login%3Abirthday%20login%3Ainfo&response_type=code&redirect_uri=https%3A%2F%2Flocalhost%3A44396%2Fsignin-yandex&state=<STATE>
```

Response:

```
HTTP/1.1 302 Found
Server: nginx
Date: Wed, 04 Dec 2019 07:43:23 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 818
Connection: keep-alive
Content-Security-Policy: default-src 'none'; style-src yastatic.net 'unsafe-inline' 'unsafe-eval'; script-src 'self' yastatic.net yandex.st mc.yandex.ru 'unsafe-eval' 'unsafe-inline' 'nonce-157bf3d8-5715-4e5e-9e64-28589f2fc61c'; img-src yastatic.net mc.yandex.ru yandex.st data: *.captcha.yandex.net avatars.mds.yandex.net avatars.mdst.yandex.net clck.yandex.ru yapic.yandex.ru img.yandex.ru; font-src data: yastatic.net; object-src yastatic.net; media-src *.captcha.yandex.net data:; connect-src 'self' passport.yandex.ru mc.yandex.ru; frame-src 'self' yandex.st; child-src 'self' yandex.st; report-uri https://csp.yandex.net/csp?from=oauth&yandex_login=<LOGIN>&yandexuid=<UID>
X-Frame-Options: SAMEORIGIN
X-Download-Options: noopen
X-Content-Type-Options: nosniff
Surrogate-Control: no-store
Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate
Pragma: no-cache
Expires: 0
X-DNS-Prefetch-Control: off
X-XSS-Protection: 1; mode=block
Location: https://localhost:44396/signin-yandex?state=<STATE>&code=<CODE>
Vary: Accept
X-Robots-Tag: noindex
```
So I get successfully redirected to `https://localhost:44396/signin-yandex` and then the exception is thrown.

My `AuthorizationBuilder` init code looks like this:

```
auth.AddYandex(opts =>
{
    opts.ClientId = id;
    opts.ClientSecret = secret;
    opts.Scope.AddRange(new [] { "login:email", "login:birthday", "login:info" });
    opts.ClaimActions.MapJsonKey(ClaimTypes.DateOfBirth, "birthday");
});
```

Tried commenting everything else except setting `ClientId` and `ClientSecret` - nothing has changed.

**Comment by impworks** [comment]
Hello @martincostello, is there any other info I need to provide to help figure out the reason?

**Comment by martincostello** [comment]
Can you enable HTTP logging in your app and see what requests are exchanged server-side during `signin-yandex`?

Other than logs, there's no much I can do without having to set up an entire Yandex app and user (I've never used Yandex, I don't even know what it is) and debugging it myself, which I'd also need to free time to do.

**Comment by martincostello** [comment]
The error is coming from here:

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/5e193d4c0ce5e4a0b2fb51e487dbf0c89df9f2ef/src/AspNet.Security.OAuth.Yandex/YandexAuthenticationHandler.cs#L79-L89

If you provide the error message that we log, we'll be able to see the response body and the non-2xx status code returned.

**Comment by impworks** [comment]
Sorry, my bad. The logging revealed a bug in my own code which used an incorrect secret key.
