### ISSUE TITLE
Add Fitbit provider

### ISSUE THREAD

**Issue by jerriep** [aspnet-contrib/AspNet.Security.OAuth.Providers#36]

**Comment by jerriep** [comment]
@jmloeffler Indicated he will pick this one up

**Comment by jmloeffler** [comment]
Yep, I am working on it.  I've got it working already but want to spend a little more time testing and ran out of hours in the day.

**Comment by jerriep** [comment]
No problem. I just tagged you to make sure no-one else picks it up.

Take your time with getting it done :)

**Comment by jmloeffler** [comment]
I've noticed that we've got values in the providers for the clientid and secret in the Startup.cs of the sample app.  Are those legit values?  I would normally leave these blank and comment out the section so the provider isn't active until someone provides values.

**Comment by jerriep** [comment]
They were legit at the time of merging the PR so that @PinpointTownes could easily test, since he did not have to go and create an app just to test. I deleted mine in the meantime, and you should do the same.

But it is not a very good practice to leave those in. We should come up with something else. The important thing is that @PinpointTownes must be easily able to test PRs

**Comment by PinpointTownes** [comment]
@jerriep I totally agree :+1: 

FYI: I already removed all the `app.Use*Authentication` calls (except GitHub/Twitter/Google) from the MVC sample since they were no longer working.

**Comment by PinpointTownes** [comment]
Merged, thanks! https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/1836930e7d5812b0e4321014241f6488115d05d8
