### ISSUE TITLE
No way to force https redirect uri when running in http behind reverse proxy with X-Forwarded-Proto https

### ISSUE THREAD

**Issue by damccull** [aspnet-contrib/AspNet.Security.OAuth.Providers#365]
**Describe the bug**
Discord provider generates http links for the redirect url when the app is run in http mode. This is undesirable when running behind a reverse proxy in http mode. The rest of aspnetcore respects the X-Forwarded-Proto header and generates https links, from what I can tell, but this discord provider is sending the link "http://mydomain.com/signin-discord" to the discord app endpoint.

**Steps To reproduce**
* Run an http site behind a reverse proxy that handles https redirects and passes the https scheme via X-Forwarded-Proto.
* Set up discord to redirect back to https://mydomain.com/signin-discord
* Click the link to sign in with discord and watch as it complains about a bad url

**Expected behaviour**
Expect to see an https link generated and sent to discord.

**Actual behaviour**
An http link is generated and send to discord to redirect back to.

**System information:**
 - OS: Ubuntu 18.04.3 hosting docker image built from mcr.microsoft.com/dotnet/core/aspnet:3.1 (no mods except adding my code to run)
 - Library Version  3.0.*
 - .NET version core 3.1

**Additional context**
I'm using traefik as the reverse proxy. I would like to see a way to either force https or have it detect that I'm using https even though it's not set up to host in https.

**Comment by martincostello** [comment]
From having a quick look at the Discord provider’s code, we don’t appear to have any code related to generating the URL’s scheme.

That would suggest what you’re asking for is common to all of the OAuth based providers built on top of the generic provider Microsoft provides as part of ASP.NET Core, so if needed to be catered for would be better done there to benefit all apps, not just the Discord provider.

I can look further when I have access to a a proper computer (it’s the holiday season), but I would assume that either the way to do this involves configuration of the base OAuth configuration/MVC, or its not a supported scenario in-general in the Microsoft auth’n security libraries.

**Comment by martincostello** [comment]
One or both of these may be the solution. I’ve definitely had to use the `KnownProxies` option in the past for production apps with upstream TLS termination and sat behind HAProxy.

https://stackoverflow.com/a/57426345/1064169

https://github.com/IdentityServer/IdentityServer4/issues/2598#issuecomment-518521424

**Comment by damccull** [comment]
Well, not the best solution, but a way to force this is to force the app as a whole to use https for every request:
```
app.Use((context,next) => {
    context.Request.Scheme = "https";
    return next();
});
```

I also tried app.UseForwardedHeaders from the HttpOverrides middlware with appropriate options. That didn't work either. Only way I found was to enforce the https scheme globally.

**Comment by martincostello** [comment]
I believe `KnownProxies`/`KnownNetworks` is the supported way for security reasons, otherwise clients could specify the `X-Forwarded-For-*` headers themselves and spoof them.

For the production app I work on we know the IP ranges for the proxy instances in our VPC and specifically allow-list them.

**Comment by damccull** [comment]
Thanks, I'll look that up. Is that perhaps why my app seemed to be ignoring them? Because I didn't set a known proxy?

**Comment by martincostello** [comment]
I think so. If you turn up the logging level I think you’ll see output showing that the headers are being intentionally ignored as it’s from an “untrusted” source.

**Comment by martincostello** [comment]
There’s some information about it in this issue: https://github.com/aspnet/AspNetCore/issues/8471

**Comment by martincostello** [comment]
And here’s the middleware code that checks things and emits the logs: 

https://github.com/aspnet/AspNetCore/blob/654140736c714903c5b39f15b49e884d08afaebb/src/Middleware/HttpOverrides/src/ForwardedHeadersMiddleware.cs#L236

**Comment by damccull** [comment]
Awesome. Thanks. I've got this working so I'll go ahead and close this. I'll keep looking at the info you sent, but I finally found this link https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1#forward-the-scheme-for-linux-and-non-iis-reverse-proxies which explains that I need to clear the knownproxies and knownnetworks list because they only allow loopback proxies by default. I'll check into adding authorized networks and proxies specifically next.

Thanks for all your help!

**Comment by johmarjac** [comment]
> Awesome. Thanks. I've got this working so I'll go ahead and close this. I'll keep looking at the info you sent, but I finally found this link https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1#forward-the-scheme-for-linux-and-non-iis-reverse-proxies which explains that I need to clear the knownproxies and knownnetworks list because they only allow loopback proxies by default. I'll check into adding authorized networks and proxies specifically next.
> 
> Thanks for all your help!

Thanks, I read that article further down and they meanwhile have written there for non-iis servers that knownproxies have to be cleared. And now it works without that global https scheme rewrite as well! Awesome. I am so glad I found this issue here.
