### ISSUE TITLE
Feature Request: Ability to set the "prompt" field of an oauth2 request

### ISSUE THREAD

**Issue by damccull** [aspnet-contrib/AspNet.Security.OAuth.Providers#367]
**Is your feature request related to a problem? Please describe.**
At least discord, and possibly some other providers, requires users choosing to sign in with that provider to authorize every time, even after the initial registration and authorization. Discord's API documentation mentions setting the 'prompt' to none to avoid that authorization request except in certain required circumstances (which, I assume, means initially authorizing an app). Currently, there's no easy or visible way to set the 'prompt' field of the oauth2 request.

I've seen mention of setting it via options.Prompt for the Azure AD provider, but none of the others I've looked at in this project have that option available. 

**Describe the solution you'd like**
I'd like to be able to set OauthOptions.Prompt to "none" or another valid string and have it pass that selected value as part of the oauth request. Using constants would be fine, too.

**Describe alternatives you've considered**
I've done some googling on how to modify the url in the request before it leaves my site, but to no avail.

**Comment by lukefulliton** [comment]
I will spend some time looking into the feasibility of this feature request, assuming the maintainers are okay with your proposed feature.

**Comment by lukefulliton** [comment]
I wanted to follow up here on my status.  I am just about finished with a potential implementation of this feature request.  I hope to have a pull-request submitted in the next few days.  Thanks

**Comment by kinosang** [comment]
maybe a PR to Microsoft.AspNetCore.Authentication.OAuth or a common OpenIdConnectOptions derived from OAuthOptions. cuz many providers support prompt
