### ISSUE TITLE
Add Deezer OAuth 2.0 Provider

### ISSUE THREAD

**Issue by tolbxela** [aspnet-contrib/AspNet.Security.OAuth.Providers#369]
I am going to implement an OAuth 2.0 Provider with the Deezer API
Documentation: [Deezer API / OAuth](https://developers.deezer.com/api/oauth)

**Comment by tolbxela** [comment]
I suppose, you will close the Issue. Or should I do it?

**Comment by martincostello** [comment]
I'll close it down when #373 is merged 👍

**Comment by martincostello** [comment]
Resolved by #373.
