### ISSUE TITLE
Add Last.fm Provider

### ISSUE THREAD

**Issue by tolbxela** [aspnet-contrib/AspNet.Security.OAuth.Providers#371]
I am going to implement an Last.FM Provider. 
The standard is not defined in the docs, but it looks very like OAuth 2.0.
Documentation: [Last.fm Web Services - Authentication API](https://www.last.fm/api/authspec)

**Comment by tolbxela** [comment]
Should it be named `AspNet.Security.OAuth.Last.fm` or `AspNet.Security.OAuth.Lastfm`?

**Comment by martincostello** [comment]
I would have thought `AspNet.Security.OAuth.LastFM`

**Comment by tolbxela** [comment]
> I would have thought `AspNet.Security.OAuth.LastFM`

The service is named Last.fm, so no big FM
I will take without dot
`AspNet.Security.OAuth.Lastfm`

**Comment by martincostello** [comment]
I went with FM to keep it a separate word and also because it’s a play on words of Frequency Modulation used in radio.

I’m not hung up on which one of the two, but I don’t think we want the one with the dot (Last.fm) as then it looks like a subnamespace.

**Comment by tolbxela** [comment]
> I went with FM to keep it a separate word and also because it’s a play on words of Frequency Modulation used in radio.
good point. 
I bet, Last.fm had big FM letters before. That's why I wrote it so in the issue. But now they write it small.

But we still can write it big. BattleNet is also in real lowercase.

> I’m not hung up on which one of the two, but I don’t think we want the one with the dot (Last.fm) as then it looks like a subnamespace.
Yep, I thought the same

Anyway, we can change it quick later.

**Comment by tolbxela** [comment]
I am not sure now if Last.fm Auth is really OAuth 2.0 conform. It looks more like OAuth 1.0 at second sight. There is no client secret and it uses api signature, as it possibly was in OAuth 1.0. 
But there is also a way to obtain access token after creating a user session.
I am not so confident with the protocols really. 

Should I try to implement the provider despite of it?

**Comment by martincostello** [comment]
> Should I try to implement the provider despite of it?

Sure, feel free to try it out, but if it diverges too much from what most of the providers in this repo do, then we _might_ not accept it as a PR.

The Microsoft Twitter provider is OAuth 1.x I believe, and that's different to the other ones for Microsoft Accounts, Facebook and Google that they provide if you look at the base types of their respective handlers:

https://github.com/aspnet/AspNetCore/blob/2b7e994b8a304700a09617ffc5052f0d943bbcba/src/Security/Authentication/Twitter/src/TwitterHandler.cs#L22

https://github.com/aspnet/AspNetCore/blob/2b7e994b8a304700a09617ffc5052f0d943bbcba/src/Security/Authentication/Facebook/src/FacebookHandler.cs#L20

https://github.com/aspnet/AspNetCore/blob/2b7e994b8a304700a09617ffc5052f0d943bbcba/src/Security/Authentication/Google/src/GoogleHandler.cs#L19

https://github.com/aspnet/AspNetCore/blob/2b7e994b8a304700a09617ffc5052f0d943bbcba/src/Security/Authentication/MicrosoftAccount/src/MicrosoftAccountHandler.cs#L21

**Comment by tolbxela** [comment]
> Sure, feel free to try it out, but if it diverges too much from what most of the providers in this repo do, then we _might_ not accept it as a PR.

I wanted to do it anyway, since I need it in my project. 

Thanks for your tips!

**Comment by kevinchalet** [comment]
Added the `help wanted` label, in case someone else would be interested in contributing.

**Comment by kevinchalet** [comment]
I took a look at the Last.FM docs and it looks like they use a completely custom protocol (it's not even OAuth 1.0): https://www.last.fm/api/authspec

It's not something we'll be able to maintain here, so closing.
