### ISSUE TITLE
Not able to get the access token from GitHub

### ISSUE THREAD

**Issue by sarensw** [aspnet-contrib/AspNet.Security.OAuth.Providers#374]
I'm trying to get the access token after logging in to GitHub, in order to use octokit.net to query user related information. Logging in works and I can see the usual claims. But I'm not able to find the access token. 

So far, I checked the history of the GitHub provider in this repository and saw that in 2015, there was a 'SaveTokens' property which was eventually removed later in favor of 'SaveTokensAsClaims'. However, this was also removed but I couldn't find any explanation why (or what the correct way is now). 

I also found #253 and  #228 but I do not fully understand where '_signInManager' comes from and how to use 'GetExternalLoginInfoAsync()'. From what I saw, this is somehow cookie related.

(Or is there another way to use octokit.net for user related info with this GitHub OAauth provider).

**Comment by martincostello** [comment]
There is still a `SaveTokens` property, but it's in the base class: [`RemoteAuthenticationOptions.SaveTokens`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.remoteauthenticationoptions.savetokens?view=aspnetcore-1.1).

My understanding is that if you set `SaveTokens` to `true` when configuring the GitHub provider, the tokens will be available to you.

**Comment by sarensw** [comment]
`SaveTokens` is only valid for asp.net core 1.0 and 1.1 according to the docs. It does not exist in 3.0

**Comment by martincostello** [comment]
I opened up the sample project locally on the `dev` branch to check before I sourced the docs link, and it's there and happily compiles:

![image](https://user-images.githubusercontent.com/1439341/72665803-cc974500-3a03-11ea-9668-03ca649c8d0c.png)


![image](https://user-images.githubusercontent.com/1439341/72665800-ba1d0b80-3a03-11ea-9e7b-7a9167843a59.png)

**Comment by sarensw** [comment]
@martincostello You are right. It works. Thank you.
