### ISSUE TITLE
Yeoman generator

### ISSUE THREAD

**Issue by tparnell8** [aspnet-contrib/AspNet.Security.OAuth.Providers#38]
it might be good to make a Yeoman generator to scaffold the basic project template

**Comment by jerriep** [comment]
Yeah, interesting idea. I was also thinking about maybe doing something with SideWaffle, but I think Yeoman makes more sense. One can just feed in some variables and it will generate most of the code for you.

**Comment by jerriep** [comment]
I'll start working on this one...

**Comment by PinpointTownes** [comment]
Done: https://github.com/aspnet-contrib/generator-aspnet-oauth
