### ISSUE TITLE
I cant find  about "AspNet.Security.OAuth.Providers.alipay"

### ISSUE THREAD

**Issue by codeman-git** [aspnet-contrib/AspNet.Security.OAuth.Providers#380]
I cant find  about "AspNet.Security.OAuth.Providers.alipay",it is  not give?

**Comment by martincostello** [comment]
A Pull Request to add Alipay is open here, but it is not yet merged: #362

**Comment by codeman-git** [comment]
> A Pull Request to add Alipay is open here, but it is not yet merged: #362

OK,I find  thanks！
