### ISSUE TITLE
Apple: DefaultAppleKeyStore is added as a singleton and doesn't refresh keys

### ISSUE THREAD

**Issue by ghost** [aspnet-contrib/AspNet.Security.OAuth.Providers#383]
**Describe the bug**
The following store is registered as a singleton [DefaultAppleKeyStore](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/451d8b91284bdd2df568b141b661b909d90728eb/src/AspNet.Security.OAuth.Apple/AppleAuthenticationExtensions.cs#L80)

and it never refreshes the keys, once it has loaded apples signing keys

 ```
        public override async Task<byte[]> LoadPublicKeysAsync([NotNull] AppleValidateIdTokenContext context)
        {
            if (_publicKey == null)
            {
                _publicKey = await LoadApplePublicKeysAsync(context);
            }

            return _publicKey;
        }
```

This causes the validation to fail when apple rotates their signing key, as they did yesterday.

**Steps To reproduce**
1) Start application
1) Wait for Apple to Rotate Signing Keys
1) Do sign in with apple and see token verification fails

**Expected behaviour**
* Token is verified
  * Keys should be updated regularly or Keys should be updated when token was signed with an unknown key.

**Actual behaviour**
1) Loaded keys are kept until program/website is restarted
1) Tokens fails verification until program/website is restarted

**System information:**
 - OS: Linux
 - Library Version 3.0.0
 - .NET version 3.1.1

**Comment by martincostello** [comment]
I'll look at fixing this for the next release by coming up with a way for the singleton to refresh the keys via some mechanism.

**Comment by martincostello** [comment]
@sawcmk PR with proposed fixed opened in #384.

**Comment by ghost** [comment]
> @sawcmk PR with proposed fixed opened in #384.

That will make sure it recovers. I haven't been able to find any documentation from apple, about how they rotate their certificates, if they have a grace period before they promote new certificates to be the signing certificate or just promote new certificates instantly.

Let's try this and see how it goes next time they rotate.

**Comment by martincostello** [comment]
Comparing the current response from that endpoint compared to when I wrote the tests, it looks like they've done 2 key rotations so far, as the response has 3 now where the test content I copied has only one.

Do you think 15 minutes is a reasonable default?

Also if this doesn't fix it properly, the time can be set to zero as a mitigation until I could do a more comprehensive fix. It's also possible to replace the default key store implementation in DI before registering the provider to do something else.

**Comment by martincostello** [comment]
I've merged the PR for inclusion with the next release. Please open a new issue if the new solution doesn't fully resolve the problem.

**Comment by ghost** [comment]
Thanks 👍

**Comment by martincostello** [comment]
This fix is now available from NuGet.org: https://www.nuget.org/packages/AspNet.Security.OAuth.Apple/3.1.0
