### ISSUE TITLE
Apple Signin redirects to a blank page 404 Error

### ISSUE THREAD

**Issue by javaadpatel** [aspnet-contrib/AspNet.Security.OAuth.Providers#390]
**Describe the bug**
I've added the `.AddApple` nuget package and extension method but when I complete the apple sign in flow, at the last step when it asks to "Continue", it then redirects to a blank screen. When I look at the network tab, I see that it tried to make a POST request to https://mydomain.com/identity/signin-Apple, since I set the `CallbackPath` to `/identity/signin-Apple` but this gives a 404 error. 

![image](https://user-images.githubusercontent.com/22832462/75539768-787c7900-5a23-11ea-8359-3b0f0af94d65.png)

**Steps To reproduce**
Validate the domain in the apple developer portal and add the redirect urls. Add apple authentication using .AddApple with the required settings in your solution. Try login with apple

**Expected behaviour**
Login with apple redirects back to calling application and produces a token

**Actual behaviour**
Login with apple redirects but then gives a 404 error so the browser is stuck on a blank page

**Comment by martincostello** [comment]
Have you reconfigured something? The default callback path should be to `signin-apple` (lower case a, and I don’t think it has the `identity` path segment either).

Also have you added the auth middleware in the appropriate place in your Startup similar to how things are configured in the sample application?

**Comment by javaadpatel** [comment]
I did reconfigure for the callback path using the AppleAuthenticationOptions.CallbackPath. I'm using identity server in my solution so in the `ConfigureServices` method I've added `UseIdentityServer`.

I've already setup this solution and its working with other providers such as Facebook and Google.

**Comment by martincostello** [comment]
I’m not sure how this interacts with Identity Server as it’s not a configuration I’ve used, but the Apple provider builds on top of the same base class as the Facebook and Google providers.

I don’t have access to a computer at the moment so can’t investigate, but at first glance this seems like a configuration mismatch between one of either the Identity Server middleware and Authorization services or the callback configuration in the Apple Developer Portal.

**Comment by javaadpatel** [comment]
I've configured the reply urls in the apple developer portal like this:

![image](https://user-images.githubusercontent.com/22832462/75541044-e2961d80-5a25-11ea-918f-815c14c99328.png)

**Comment by martincostello** [comment]
Can you share the code you’re using to configure the provider and middleware?

My suspicion is that there’s a missing step somewhere so that the middleware knows to listen with the identity prefix and is registered at `signin-apple`.

**Comment by javaadpatel** [comment]
I've cut out alot of my business related logic, this is my Startup.cs:
```

namespace MYSERVICE.Identity
{
    public class Startup
    {
        public Startup(IConfiguration configuration, IHostingEnvironment hostingEnvironment, ILogger<Startup> logger)
        {
            Configuration = configuration;
            HostingEnvironment = hostingEnvironment;
            _logger = logger;
        }

        public IConfiguration Configuration { get; }
        public IHostingEnvironment HostingEnvironment;
        private readonly ILogger<Startup> _logger;

        public void ConfigureServices(IServiceCollection services)
        {
            #region identity server setups
            services
                .AddIdentityServer((options) =>
                {
                    options.UserInteraction.LoginUrl = "/Identity/Account/Login";
                    options.UserInteraction.LogoutUrl = "/Identity/Account/Logout";
                    options.UserInteraction.ConsentUrl = "/Identity/Consent/Index";
                    options.UserInteraction.ErrorUrl = "/Identity/Home/Error";

                    options.Events.RaiseSuccessEvents = true;
                    options.Events.RaiseFailureEvents = true;
                    options.Events.RaiseErrorEvents = true;
                    options.Events.RaiseInformationEvents = true;
                });

            Console.WriteLine($"Completed Identity Server setup...");
            #endregion

            //mvc
            services.AddMvc();

            //DPAPI
            services
                .AddDataProtection()
                .SetApplicationName(Configuration[MYSERVICESGeneral.ApplicationName])
                .PersistKeysToStackExchangeRedis(IdentityRedisConnection, Configuration[MYSERVICESRedisConfiguration.DPAPIKeyName]);

            //session and server side cache setups
            services.AddSession(options =>
            {
                options.Cookie.Name = ".MYSERVICE.Identity.Session";
                options.IdleTimeout = TimeSpan.FromMinutes(20);
            });

            services.AddOidcStateDataFormatterCache();

            var builder = services.AddAuthentication(options =>
                {
                    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    options.DefaultChallengeScheme = "MYSERVICE.Identity.Internal";
                })
                .AddCookie(options =>
                {
                    options.ExpireTimeSpan = TimeSpan.FromMinutes(60);
                    options.Cookie.Name = "MYSERVICE.Identity";
                    options.SessionStore = new RedisCacheTicketStore(serviceProvider.GetService<IExtendedDistributedCache>(),
                        serviceProvider.GetService<IDataProtectionProvider>(), serviceProvider.GetService<ILogger<RedisCacheTicketStore>>());
                })
                .AddOpenIdConnect("MYSERVICE.Identity.Internal", null, options =>
                {
                })
                .AddOpenIdConnect("azuread", "Microsoft", options =>
                {
                })
                .AddApple(name, displayName, opts =>
                    {
                        opts.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                        opts.CallbackPath = $"/identity/signin-Apple";
                        opts.ClientId = "<client id>"; //identityProvider.ClientID,
                        opts.ClientSecret = "<ClientSecret>"
                        opts.TeamId = "<Team Id>"; //identityProvider.TeamId
                        opts.KeyId = "<KeyId>"; 
                    });
                );

            //register JwtSecurityTokenHandler for Apple Authentication
            services.AddTransient<JwtSecurityTokenHandler>();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, InitializationService initializationService, INotificationService notificationService)
        {
            if (env.IsDevelopment())
            {
                app.UseBrowserLink();
                app.UseDeveloperExceptionPage();
                //display detailed error's coming from within Identity Server, for debugging purposes only.
                IdentityModelEventSource.ShowPII = true;
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                IdentityModelEventSource.ShowPII = false;
            }

            app.UseSession();
            app.UseIdentityServer();

            app.UseAuthentication();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "areas",
                    template: "{area:exists}/{controller=Application}/{action=Index}/{id?}"
                  );

                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}");

                routes.MapRoute(
                    name: "api",
                    template: "api/{controller}/{action}/{id?}");

                routes.MapRoute(
                   name: "applecertificates",
                   template: "/.well-known/apple-developer-domain-association.txt",
                   defaults: new { controller = "Home", action = "AppleCert" });
            });
        }
    }
}

```

**Comment by martincostello** [comment]
What version of ASP.NET Core is this targeting?

**Comment by javaadpatel** [comment]
Its using .net core 2.2

**Comment by martincostello** [comment]
Ok. Based just on what I can see there, the only things the _might_ be problems are that you’re using a static client secret and nothing to generate one from the certificate (though I wouldn’t have thought that would cause this problem) and or maybe the auth middleware needs to be configured before Identity Server.

Otherwise I’m not sure, and I won’t have the time to try and debug this further with something myself for several days at least.

**Comment by javaadpatel** [comment]
Looking at my container logs I see this:
```
Application started. Press Ctrl+C to shut down.
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Exception: An error was encountered while handling the remote login. ---> System.Exception: OAuth token endpoint failure: Status: BadRequest;Headers: Server: Apple
Date: Fri, 28 Feb 2020 10:36:47 GMT
Connection: keep-alive
Cache-Control: no-store
Pragma: no-cache
;Body: {"error":"invalid_client"};
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync()
   at MYSERVICE.Identity.Startup.<>c.<<Configure>b__17_1>d.MoveNext() in /src/MYSERVICE.Identity/Startup.cs:line 619
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by martincostello** [comment]
That would suggest that the client secret is the issue then. You need to make the private key bytes available to provider some how so it can generate a client secret for you derived from the key.

Take a look at the sample application for an example of doing that: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/f064daa42ec8ae3f96c2a15b7fe2ef6a061f782b/samples/Mvc.Client/Startup.cs#L69-L70

I also have a sample app for Sign In with Apple: https://github.com/martincostello/SignInWithAppleSample

**Comment by javaadpatel** [comment]
I used this: https://github.com/pingidentity/pingone-customers-sample-scripts/tree/master/ClientSecretGenerator jar executable to generate the client secret. Okay awesome, thanks for that, I'll use the `UsePrivateKey` method and see what happens

**Comment by javaadpatel** [comment]
I've set these two properties on my apple authentication options:
```
 opts.PrivateKeyBytes = async (keyId) => {
                            return await assetRepository.DownloadBlobAsByteArrayAsync("appleprivatekey.p8");
                        };
                        opts.GenerateClientSecret = true;
```

What should be inside the .p8 file, mine has
```
-----BEGIN PRIVATE KEY-----
MIGTAgEA....
-----END PRIVATE KEY-----
```

but i am receiving an error when trying to generate the client secret:
```
System.Exception: An error was encountered while handling the remote login. ---> Interop+Crypto+OpenSslCryptographicException: error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error
   at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.CreateAlgorithmLinuxOrMac(Byte[] keyBlob, String password)
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.CreateAlgorithm(Byte[] keyBlob, String password)
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.GenerateNewSecretAsync(AppleGenerateClientSecretContext context)
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.GenerateAsync(AppleGenerateClientSecretContext context)
   at AspNet.Security.OAuth.Apple.AppleAuthenticationEvents.<>c.<<-ctor>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at AspNet.Security.OAuth.Apple.AppleAuthenticationEvents.GenerateClientSecret(AppleGenerateClientSecretContext context)
   at AspNet.Security.OAuth.Apple.AppleAuthenticationHandler.ExchangeCodeAsync(String code, String redirectUri)
   at AspNet.Security.OAuth.Apple.AppleAuthenticationHandler.HandleRemoteAuthenticateAsync(Dictionary`2 parameters)
   at AspNet.Security.OAuth.Apple.AppleAuthenticationHandler.HandleRemoteAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync()
   at myapp.Startup.<>c.<<Configure>b__17_1>d.MoveNext() in /src/myapp/Startup.cs:line 619
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
```

**Comment by martincostello** [comment]
You need to remove the padding and the new lines. The built-in extension method already does that for you:

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/f064daa42ec8ae3f96c2a15b7fe2ef6a061f782b/src/AspNet.Security.OAuth.Apple/AppleAuthenticationOptionsExtensions.cs#L36-L52

**Comment by javaadpatel** [comment]
Is the built in method `.UsePrivateKey` ? and is there a way to pass bytes into that instead of returning IFileInfo?

**Comment by martincostello** [comment]
No, the built-in one just takes the key ID to find the file based on the default file download Apple provides.

If you’re doing something custom with different file names and/or not using files on disk, then you’ll need to trim the bytes in the same way before returning them so the key can be loaded.

**Comment by javaadpatel** [comment]
I'm now using the extension method like this:
```
  opts.UsePrivateKey((keyId) =>
                        {
                            assetRepository.DownloadBlobAsFileAsync("appleprivatekey.p8").GetAwaiter().GetResult();
                            if (!File.Exists("appleprivatekey.p8"))
                                throw new FileNotFoundException("Cannot find the key file");

                            return fileProvider.GetFileInfo("appleprivatekey.p8");
                        });
```

but i'm still receiving an exception in the GenerateNewSecretAsync method:
```
 Failed to generate new client secret for the Apple authentication scheme.
Interop+Crypto+OpenSslCryptographicException: error:0D08303A:asn1 encoding routines:ASN1_TEMPLATE_NOEXP_D2I:nested asn1 error
   at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.CreateAlgorithmLinuxOrMac(Byte[] keyBlob, String password)
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.CreateAlgorithm(Byte[] keyBlob, String password)
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.GenerateNewSecretAsync(AppleGenerateClientSecretContext context)
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.GenerateAsync(AppleGenerateClientSecretContext context)
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Exception: An error was encountered while handling the remote login. ---> Interop+Crypto+OpenSslCryptographicException: error:0D08303A:asn1 encoding routines:ASN1_TEMPLATE_NOEXP_D2I:nested asn1 error
   at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.CreateAlgorithmLinuxOrMac(Byte[] keyBlob, String password)
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.CreateAlgorithm(Byte[] keyBlob, String password)
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.GenerateNewSecretAsync(AppleGenerateClientSecretContext context)
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.GenerateAsync(AppleGenerateClientSecretContext context)
   at AspNet.Security.OAuth.Apple.AppleAuthenticationEvents.<>c.<<-ctor>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at AspNet.Security.OAuth.Apple.AppleAuthenticationEvents.GenerateClientSecret(AppleGenerateClientSecretContext context)
   at AspNet.Security.OAuth.Apple.AppleAuthenticationHandler.ExchangeCodeAsync(String code, String redirectUri)
   at AspNet.Security.OAuth.Apple.AppleAuthenticationHandler.HandleRemoteAuthenticateAsync(Dictionary`2 parameters)
   at AspNet.Security.OAuth.Apple.AppleAuthenticationHandler.HandleRemoteAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync()
   at myapplication.Startup.<>c.<<Configure>b__17_1>d.MoveNext() in /src/myapplication/Startup.cs:line 632
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
```

**Comment by martincostello** [comment]
Does your key still contain `-----BEGIN PRIVATE KEY-----` in it? If it does, you need to remove it as-per the built-in extension method, or it won't load.

**Comment by javaadpatel** [comment]
It does still have the -----BEGIN PRIVATE KEY-----, I thought the extension method `.UsePrivateKey` took that into account and I just had return the complete file that was downloaded from the Apple Developer portal?

**Comment by martincostello** [comment]
~The extension method takes a delegate that accepts the Key Id. That's not what your implementation is doing, you're setting the key Id to the content of the file?~

**Comment by martincostello** [comment]
Sorry I've misread the code - the random snippets were confusing me.

**Comment by martincostello** [comment]
New question - what _operating system_ are you trying to do this on?

As this is the 2.2.x codebase, not 3.x, there's differences in the implementation there for handling `.p8` files as they're only supported on Windows. If you're using Linux or macOS, you need to use `.pfx` files.

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/07dcbacac99e7418c281d32b51365a551f0f423d/src/AspNet.Security.OAuth.Apple/Internal/DefaultAppleClientSecretGenerator.cs#L96-L121

Alternatively as 2.2 is no longer supported by Microsoft and no longer receives security fixes, I'd recommend updating to .NET Core 3.1 so you continue to get security fixes as well as the ability to use `.p8` files on any platform.

There's some more context about this in the blog post I wrote for the original prototype of the provider I wrote last year: https://blog.martincostello.com/sign-in-with-apple-prototype-for-aspnet-core/

**Comment by javaadpatel** [comment]
I see that makes a big difference then because I'm running this as a linux container. I'll try and convert the `.p8` file into a `.pfx` and test to see what happens. Ideally, I'd move to 3.1 but don't have bandwidth to make the switch right now. 

Thanks for the article link, will read through it now.

**Comment by javaadpatel** [comment]
Took your advice and migrated to .net core 3.1, can confirm that apple sign in is working now. I saw that you're requesting scope `name` and `email` but those don't appear in the tokens, from your blog post I'm assuming that's because Apple hasn't implemented the UserInfo endpoint?

Thanks for all the help with this, greatly appreciated.

**Comment by martincostello** [comment]
It's correct that the user information endpoint hasn't been implemented by Apple. However they do return you the name and email, but _only_ on the first ever request for that user through Sign in with Apple (which is annoying).

If you're happy it's working, log into your Apple ID you're using to test and delete the association with your app (I forget exactly _where_ you do this). Then log in to your test app again with the same Apple ID and you'll get the name and email address again then.

The way Apple have implemented it, you only have one chance to get the name or email address and if you miss it then it's gone forever unless the user deletes the association with your app.

As this is all working now, I'm going to close this issue. Glad I could help you get it working!

**Comment by iojancode** [comment]
> If you're happy it's working, log into your Apple ID you're using to test and delete the association with your app (I forget exactly _where_ you do this). Then log in to your test app again with the same Apple ID and you'll get the name and email address again then.

here https://appleid.apple.com/account/manage

**Comment by aquakul** [comment]
3 years later and I having an issue similar to the Title but the resolution probably not the same. Are we supposed to implement the 'signin-apple' callback path as a static html in our project

**Comment by kevinchalet** [comment]
@aquakul no, with the aspnet-contrib providers, the callback path is always implemented for you. Are you sure there's no error in the logs?

**Comment by aquakul** [comment]
Nothing. Attached is a screenshot

<img width="930" alt="Image20230812131444" src="https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/assets/8684187/1cdf664a-b3f9-42b5-80d7-f51a8fc5543e">


Also  below is a sample of the code to add Apple Authentication Provider. 

authServices.AddApple(o =>
{
    o.ClientId = appleOptions.ClientId;
    o.KeyId = appleOptions.KeyId;
    o.TeamId = appleOptions.TeamId;
    o.UsePrivateKey((keyId) => appleOptions.PrivateKeyProvider);
    o.CallbackPath = appleOptions.CallbackPath;
    o.SignInScheme = IdentityServer4.IdentityServerConstants.ExternalCookieAuthenticationScheme;
});

**Comment by kevinchalet** [comment]
I meant the server/ASP.NET Core logs... 😅

**Comment by aquakul** [comment]
Ah I get it  :).  Below is the error log /stacktrace. 

2023-08-13 20:13:54.202 +10:00 [ERR] Failed to generate new client secret for the Apple authentication scheme.
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The system cannot find the file specified.
   at System.Security.Cryptography.CngKeyLite.ImportKeyBlob(String blobType, ReadOnlySpan`1 keyBlob, Boolean encrypted, ReadOnlySpan`1 password)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8(ReadOnlySpan`1 keyBlob)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.CreateAlgorithm(Byte[] keyBlob)
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.GenerateNewSecretAsync(AppleGenerateClientSecretContext context)
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.GenerateAsync(AppleGenerateClientSecretContext context)


The P8 file is there where it is supposed to be. I am running on IIS, So i provided READ access to the App Pool Identity to read the Key file.  I tried running the same piece of code that is used to load the Key and it seems fine.
