### ISSUE TITLE
Discord oauth fails with localhost login

### ISSUE THREAD

**Issue by xXBuilderBXx** [aspnet-contrib/AspNet.Security.OAuth.Providers#394]
**Describe the bug**
Discord has updated some of their oauth stuff which has caused localhost login to not work anymore, this has previously worked before.
The error comes up as Correlation failed and the console shows a warning of '.AspNetCore.Correlation.Discord.XXXXXXX' cookie not found.

**Steps To reproduce**
1. Setup asp.net blazor with the Discord oauth sample and Discord app.
2. Try to login using localhost/signin
3. Click authorize on the oauth page

**Expected behaviour**
This has previously worked before and was able to let you login with no other issues.

**Actual behaviour**
When you authorize the oauth it takes you to the dev error page with Correlation failed and An error was encountered while handling the remote login.

**System information:**
 - OS: Windows 10
 - Library Version: 3.0.0
 - .NET version: .net core 3.1

**Additional context**
This works fine for a normal website domain with https.

**Comment by kevinchalet** [comment]
Are you sure it's a Discord change and not a same-site issue? What's the browser you're using?

**Comment by xXBuilderBXx** [comment]
@kevinchalet looks like the issue seems to be caused by Firefox because Chrome and other chromium browsers work fine with localhost oauth.

**Comment by xXBuilderBXx** [comment]
Done some looking and found that setting this on the AddDiscord service fixes the issue.

options.CorrelationCookie.SameSite = Microsoft.AspNetCore.Http.SameSiteMode.Lax;

**Comment by kevinchalet** [comment]
Good to know, thanks for investigating!
