### ISSUE TITLE
LinkedIn Logout Not Working

### ISSUE THREAD

**Issue by suraj-kumbhar-maersk** [aspnet-contrib/AspNet.Security.OAuth.Providers#395]
**Describe the bug**
I am using .NetCore 2.1.
I can login using this npm and successfully redirect to back to my application as well.

**Steps To reproduce**
Not able logout from LinkedIn

**Expected behaviour**
It Should be able to logout form LinkedIn as well

**Comment by kevinchalet** [comment]
It's not something we support and AFAICT, none of the handlers built on top of `OAuthHandler` implements logout support. Logout is not even standardized in the OAuth 2.0 world as it's an authorization and not an authentication protocol, so it would be hard to implement that in a completely generic way in `OAuthHandler`.

**Comment by suraj-kumbhar-maersk** [comment]
Thanks @kevinchalet for quick response. So is it confirm that we can log in as External user into the application but we cannot logout from linked through that application?

**Comment by kevinchalet** [comment]
Correct.

**Comment by suraj-kumbhar-maersk** [comment]
And What about Other providers Google,Facebook etc. i didnt try it yet but just want to confirm before starting on it!

**Comment by martincostello** [comment]
Typically you'd use something like `SignInManager<T>.SignOutAsync()` (if you're using ASP.NET Core Identity) from a controller to log the current user in your app out of your application. You can't force a log out from the other provider though (e.g. forcing LinkedIn itself to be logged out).

**Comment by suraj-kumbhar-maersk** [comment]
Thanks @martincostello . Yes I tried this SignInManager.SignOutAsync(), but its not working, not able to logged out from LinkedIn. In other way in .net core 2.1 would help me.

**Comment by kevinchalet** [comment]
> And What about Other providers Google,Facebook etc. i didnt try it yet but just want to confirm before starting on it!

No, the Google and Facebook ASP.NET Core providers use `OAuthHandler` and don't support logout.

Logout is primarily useful when you have your own authorization/authentication server. In most other cases, it's just a source of annoyance for your users (why would you force me to log out of my LinkedIn account when logging out of your app?)

**Comment by kevinchalet** [comment]
Speaking of Google, they support OpenID Connect (for which front-channel and back-channel logout are fully standard things), but if you take a look at their discovery document (https://accounts.google.com/.well-known/openid-configuration), you'll see they don't expose any `end_session_endpoint` that would allow a client app to terminate a Google session on behalf of the user... very likely for the reason I mentioned.

**Comment by suraj-kumbhar-maersk** [comment]
> > And What about Other providers Google,Facebook etc. i didnt try it yet but just want to confirm before starting on it!
> 
> No, the Google and Facebook ASP.NET Core providers use `OAuthHandler` and don't support logout.
> 
> Logout is primarily useful when you have your own authorization/authentication server. In most other cases, it's just a source of annoyance for your users (why would you force me to log out of my LinkedIn account when logging out of your app?)

Because I can LogOut from the app but when i clicked on Log in with linkedin, token gets generated and i can directly into my system because linkedin cookies are stored in browser so that it authenticate automatically and further process in my app allows that user to enter into the system.
And We cannot remove browser cookies programatically!

**Comment by kevinchalet** [comment]
In the OIDC world, what you describe is usually solved by adding `prompt=login` to the authorization request, so that the identity provider can show a login page even if the user is already logged in. Last time I checked, this was not supported by LinkedIn.

If you really want to log your users out of their LinkedIn session, you can still redirect them to https://www.linkedin.com/sales/logout. But it's a nasty thing to do, and as a user, I wouldn't like that (at all).

**Comment by suraj-kumbhar-maersk** [comment]
for me as well. Thanks @kevinchalet and @martincostello.

**Comment by suraj-kumbhar-maersk** [comment]
> In the OIDC world, what you describe is usually solved by adding `prompt=login` to the authorization request, so that the identity provider can show a login page even if the user is already logged in. Last time I checked, this was not supported by LinkedIn.
> 
> If you really want to log your users out of their LinkedIn session, you can still redirect them to https://www.linkedin.com/sales/logout. But it's a nasty thing to do, and as a user, I wouldn't like that (at all).

I just do a small patchy workaroud on this, if someone really wants to logout we can open a javascript popup windows and close it after few seconds. We can do this after we logout from our application then try this.

**window.open("https://www.linkedin.com/sales/logout", "_blank",);**
