### ISSUE TITLE
Replace Sign in with Apple DefaultAppleClientSecretGenerator's `_clientSecret` with `IMemoryCache`

### ISSUE THREAD

**Issue by foriequal0** [aspnet-contrib/AspNet.Security.OAuth.Providers#396]
I want to use it with multiple `ClientId`. I don't use default OAuth callback handler, and I make `*Context` and call `AppleAuthentication*`'s interfaces myself.  
But `DefaultAppleClientSecretGenerator` strongly assumes that there's only one `ClientId` per app, and it is registered as singleton service.
Since I don't have access to the `Internal.Default*` classes. I've made my copy of it and modified it to use `IMemoryCache` to handle multiple `ClientId`.

**Describe the solution you'd like**
Use `IMemoryCache` rather than de facto global singleton like `_clientSecret`

**Describe alternatives you've considered**
Disable client secret cache?

**Additional context**
I already have code so I can make a PR.

**Comment by martincostello** [comment]
Resolved by #484. Changes are available from version `5.0.0-rc.2.20516.57` in our MyGet feed and will be part of the 5.0.0 release.
