### ISSUE TITLE
Add DeviantArt provider

### ISSUE THREAD

**Issue by jerriep** [aspnet-contrib/AspNet.Security.OAuth.Providers#4]

**Comment by tparnell8** [comment]
I wrote the DeviantArt provider for the OwinOauth repo, so I guess I can take this as well.

**Comment by PinpointTownes** [comment]
Thanks Tommy :+1: 

I added the `work in progress` label to make sure no one works on the same provider. Feel free to ping me if you need help.

**Comment by tparnell8** [comment]
I believe this issue can be closed

**Comment by PinpointTownes** [comment]
Yup, indeed :+1:
