### ISSUE TITLE
3.1.0 release

### ISSUE THREAD

**Issue by martincostello** [aspnet-contrib/AspNet.Security.OAuth.Providers#400]
I've created the relevant branches and draft release notes for the 3.1.0 releases of AspNet.Security.OAuth.Providers and AspNet.Security.OpenId.Providers and there's candidate 3.1.0 packages in the MyGet feed.

  * https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/tree/rel/3.1.0
  * https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers/tree/rel/3.1.0

Anything else that needs doing @kevinchalet before we push packages to NuGet.org and close the releases?

**Comment by kevinchalet** [comment]
Looks like we have an issue with Source Link and deterministic builds. Our 3.0 release didn't have any issue, so I guess it appeared when updating Arcade:

3.1.0:

![image](https://user-images.githubusercontent.com/6998306/78594368-77234500-7848-11ea-9185-d79c951e72bd.png)

3.0.0:

![image](https://user-images.githubusercontent.com/6998306/78594549-cff2dd80-7848-11ea-977b-fe5c8ce52c6a.png)

**Comment by kevinchalet** [comment]
It's actually a bug in the .NET SDK: https://github.com/dotnet/sourcelink/issues/572.

**Comment by martincostello** [comment]
So I guess for now we just need to manually put the property into Directory.Build.props?

**Comment by kevinchalet** [comment]
Yeah. I created https://github.com/openiddict/openiddict-core/pull/935 to fix the bug in the OpenIddict repo. If it works well, I'll send PRs against the release branches of both the OpenID and OAuth 2.0 aspnet-contrib repos.

**Comment by kevinchalet** [comment]
@martincostello I'm still seeing a weird error... I'll give it another try tomorrow.

**Comment by kevinchalet** [comment]
Allllllllllllright, after many failed attempts, I think I found a way to pass SourceLink validation in NuGet Package Explorer:

![image](https://user-images.githubusercontent.com/6998306/78623439-eff5c180-7887-11ea-8025-fe28d3cf62b6.png)

Unfortunately, implementing the suggested workaround is not enough (the error related to the `AssemblyInfo.cs` file disappeared, but not the other one) and we'll have to migrate to a newer version of Arcade (very likely because our version doesn't include https://github.com/dotnet/arcade/commit/527179abfbb5cd738035c4ac2d2566c571ce85db).

Do you have any concern moving to Arcade 5.0.0-beta for our 3.1.0 release? I agree it probably sounds a bit weird, but I can't think of a better approach.

**Comment by martincostello** [comment]
> Do you have any concern moving to Arcade 5.0.0-beta for our 3.1.0 release? I agree it probably sounds a bit weird, but I can't think of a better approach.

I guess we'll have to 😄

**Comment by kevinchalet** [comment]
FYI, I merged the changes made in the release branch into `dev` and made sure `StabilizePackageVersion` was left untouched.

**Comment by martincostello** [comment]
Have cherry-picked #406 into the release.

**Comment by kevinchalet** [comment]
Looks like there's nothing left to do for this release. Should we publish the 3.1.0 packages?

**Comment by martincostello** [comment]
Yep I think we're done if you're happy with the fixes for the NuGet packages for the SourceLink stuff.

The release notes for the release should be up-to-date so it and the tag just needs publishing whenever you're ready to go.

**Comment by martincostello** [comment]
As well as the fix for #407 before this finally ships, the conversation in that issue also reminded me we need to release a 2.2.1 too.

If you're happy for me to do the publishing this time if you're busy, I can sort the releases out on Monday.

**Comment by kevinchalet** [comment]
> If you're happy for me to do the publishing this time if you're busy, I can sort the releases out on Monday.

Sounds like a perfect plan, thanks a lot! 👏

**Comment by martincostello** [comment]
* [2.2.1 packages](https://ci.appveyor.com/project/aspnet-contrib/aspnet-security-oauth-providers/builds/32276851)
  * [3.1.0 packages](https://ci.appveyor.com/project/aspnet-contrib/aspnet-security-oauth-providers/builds/32276838/artifacts)

Will give them a check-over in NuGet package explorer tomorrow to check things look OK before pushing to NuGet.org on Monday.

**Comment by martincostello** [comment]
@kevinchalet Quick question - do you publish the release so the tag builds, and then publish _those_ packages, or do you publish the most recent builds' packages to NuGet and then publish the release and ignore the build from the tag?

**Comment by kevinchalet** [comment]
Both options are fine, as what matters most is the identifier of the latest commit (since it's persisted in the package itself and used as the `AssemblyInformationalVersion`).

**Comment by martincostello** [comment]
@kevinchalet Releases for 2.2.1 and 3.1.0 of this repo, plus 3.1.0 for OpenID have been published, and all the NuGet packages should now be available from NuGet.org. 🥳 

I'll leave you the honour of announcing the releases to the wider community 😃

**Comment by kevinchalet** [comment]
![](https://media.giphy.com/media/39iLwpbpJJCpLgOict/giphy.gif)
