### ISSUE TITLE
Support for Okta OAuth

### ISSUE THREAD

**Issue by Cellivar** [aspnet-contrib/AspNet.Security.OAuth.Providers#403]
I've found this nuget package to be extremely useful for supporting various OAuth providers. Alas I find that Okta is not part of the list yet!

They have a quick walkthrough blogpost for how to add OAuth support to an aspnet app: https://developer.okta.com/blog/2019/07/12/secure-your-aspnet-core-app-with-oauth

And some decent documentation: https://developer.okta.com/docs/reference/api/oidc/

**Comment by martincostello** [comment]
Most of our providers are contributed by the community. If you’d like to raise a PR to add support for Okta we’d be happy to review it 🙂

**Comment by Cellivar** [comment]
Ah cool, I'll look at some other PRs and see if I have time to get it added.

**Comment by martincostello** [comment]
Cool - if you use the _new provider_ tag to query the PRs you should find plenty of examples.

Most providers are fairly trivial to add if they follow the usual OAuth 2.0 setup.

**Comment by martincostello** [comment]
An Okta provider will be available from NuGet.org as part of the next release.

In the meantime, you can use a prerelease version from our [MyGet feed](https://www.myget.org/feed/aspnet-contrib/package/nuget/AspNet.Security.OAuth.Okta).

**Comment by martincostello** [comment]
The Okta provider is now available from NuGet.org: https://www.nuget.org/packages/AspNet.Security.OAuth.Okta/

**Comment by Cellivar** [comment]
Thanks for following up, I appreciate the notice.
