### ISSUE TITLE
Builds are breaking

### ISSUE THREAD

**Issue by tparnell8** [aspnet-contrib/AspNet.Security.OAuth.Providers#41]
look at #40 the builds are breaking. I presume its due to a change in Korebuild

**Comment by PinpointTownes** [comment]
I ping @davidfowl on JabbR and I'm waiting for his answer but it definitely sounds like a Sake issue. I'll mark this issue as external.

**Comment by tparnell8** [comment]
is it possible to pin to an older version of Korebuild for now?

**Comment by PinpointTownes** [comment]
Fixed: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/e32a75910797eb2f6f9c3a3119a440cc9f4dd331 :tada:
