### ISSUE TITLE
Add documentation for ArcgisPortal

### ISSUE THREAD

**Issue by geopamplona** [aspnet-contrib/AspNet.Security.OAuth.Providers#416]
**Is your feature request related to a problem? Please describe.**
I want use library with own instance of ArcGIS Portal.

**Describe the solution you'd like**
I dont know how to use library with ArcGIS Portal or my own instance of ArcGIS Portal, so I need some documentation. I see examples but there are not ArcGIS Portal examples or similar.

Thanks !

**Comment by martincostello** [comment]
The provider should be configured like any of the others we have examples for (we have over 60 providers, so showing them all in the sample project when they're 99% the same would be a bit over the top). It's really only the `AddXXXX` methods that differ for most of the providers, unless they have any quirks or additional requirements (which I don't think ArcGIS does).

```csharp
.AddArcGIS(options =>
{
    options.ClientId = "your client id";
    options.ClientSecret = "your client secret";
})
```

If you're looking for documentation about ArcGIS itself, that's something we wouldn't duplicate here. The link in the README points to their OAuth2.0 documentation and that's about all that's really related to how the code here works and should integrate with it.

Anything else (like how to generate a key, set up an integration etc.) isn't something we can support and document for so many providers.

Hope that helps.
