### ISSUE TITLE
Add SuperOffice provider

### ISSUE THREAD

**Issue by AnthonyYates** [aspnet-contrib/AspNet.Security.OAuth.Providers#418]
Request to add SuperOffice provider to the repo.
#417

**Comment by martincostello** [comment]
The SuperOffice provider is now available from NuGet.org: https://www.nuget.org/packages/AspNet.Security.OAuth.SuperOffice/

Thanks for your contribution 🎉

**Comment by AnthonyYates** [comment]
Thanks @martincostello and @kevinchalet! Thanks for all the help, Cheers!
