### ISSUE TITLE
Twitch Authentication will no longer work after 11th of May 2020

### ISSUE THREAD

**Issue by JayDee23** [aspnet-contrib/AspNet.Security.OAuth.Providers#419]
I'm using the Twitch Provider in order to authentificate via twitch. 
Since several weeks, everything was fine. Until I got this evening following message
"Client ID and OAuth token do not match" with a stacktrace I unfortunately haven't copied.

I furthermore found this blogentry:

https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916

They are switching a timed window on and off, that was the reason why it didn't worked for serveral house.   But after the 11th of may  noone could login anymore with the current code. 

Maybe a person with knowledge could take a look at the OAuth-Provider.
The next window is May 6th, 11am - May 7th, 11am PST

**System information:**
Windows 10
.Net Core 3.1
AspNet.Security.OAuth.Twitch v 3.1.0

**Comment by martincostello** [comment]
Thanks for letting us know @JayDee23 - I’ll take a look into this later today. I can’t promise a timeline for a new version compatible with the change, but I’ll try to at least get something into the dev branch and available from our MyGet feed before the 100% switch over.

**Comment by martincostello** [comment]
Thanks to @kinosang there's a fix available in this version of the provider from our NuGet feed: https://www.myget.org/feed/aspnet-contrib/package/nuget/AspNet.Security.OAuth.Twitch/3.1.1-preview.20255.36

Could you test this out @JayDee23 during the next "brownout" of the Twitch API on the 6th May please? If you have no issues, we can publish 3.1.1 with the fix ahead of the 11th May permanent change.

**Comment by JayDee23** [comment]
Wow, you are fast. Of course I will test this tomorrow. No Problem. Maybe a bit later, 'cause I'm from europe. Great. Thank you <3

**Comment by martincostello** [comment]
No problem - according to the blog post it starts at 11am PST on the 6th May, so would be mid/late afternoon for Europe.

**Comment by JayDee23** [comment]
I can confirm that 3.1.1-preview.20255.36  works like a charm during the  current timewindow.
I crosschecked with a backup of my code with 3.1.0 package which does currently not work.

Thank you very much for this excellent support. @kinosang 

PS: In addition the preview worked yesterday out of the timewindow, so it seems not neccessary to wait until 11th of may.


Stack Trace from browser window:


`
**HttpRequestException: An error occurred while retrieving the user profile.**

    AspNet.Security.OAuth.Twitch.TwitchAuthenticationHandler.CreateTicketAsync(ClaimsIdentity identity, AuthenticationProperties properties, OAuthTokenResponse tokens) in TwitchAuthenticationHandler.cs
    Microsoft.AspNetCore.Authentication.OAuth.OAuthHandler<TOptions>.HandleRemoteAuthenticateAsync()
    Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()

**Exception: An error was encountered while handling the remote login.**
```    Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
    Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
    Wangkanai.Detection.Hosting.ResponsiveMiddleware.InvokeAsync(HttpContext context, IResponsiveService responsive)
    Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
    Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
    Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```



`

**Comment by martincostello** [comment]
Great - thanks for confirming @JayDee23!

I’ll look into shipping a 3.1.1 release with the fix soon (_probably_ tomorrow).

**Comment by JayDee23** [comment]
Included Stacktrace just for historical reason :)

**Comment by VesselOfCreation** [comment]
Good job guys. Will you also be making a fix for the Core 2 version? Would really appreciate it.

**Comment by martincostello** [comment]
I have pushed the branches for versions 2.2.2 and 3.1.1 containing this fix to MyGet.

I'll look at pushing the same packages to NuGet.org tomorrow.

  * [2.2.2 build](https://ci.appveyor.com/project/aspnet-contrib/aspnet-security-oauth-providers/builds/32740385)
  * [3.1.1 build](https://ci.appveyor.com/project/aspnet-contrib/aspnet-security-oauth-providers/builds/32740610)

**Comment by martincostello** [comment]
Versions 2.2.2 and 3.1.1 containing this fix have been pushed to NuGet.org.

  * [AspNet.Security.OAuth.Twitch 2.2.2](https://www.nuget.org/packages/AspNet.Security.OAuth.Twitch/2.2.2) ([release notes](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/releases/tag/2.2.2))
  * [AspNet.Security.OAuth.Twitch 3.1.1](https://www.nuget.org/packages/AspNet.Security.OAuth.Twitch/3.1.1) ([release notes](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/releases/tag/3.1.1))
