### ISSUE TITLE
Consider using IdentityModel's ConfigurationManager in the Apple provider

### ISSUE THREAD

**Issue by kevinchalet** [aspnet-contrib/AspNet.Security.OAuth.Providers#421]
Apple now supports standard OIDC provider discovery (https://appleid.apple.com/.well-known/openid-configuration), so we could muchly simplify our keys retrieval and caching story by using IdentityModel's `ConfigurationManager`.

Since it will likely require adopting API breaking changes, it's probably something that will have to wait until 5.0.

Related: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/417#issuecomment-624648902

**Comment by martincostello** [comment]
Ah nice to see them embrace some standards 😄

**Comment by martincostello** [comment]
Something to look into for .NET 6.0 now.

**Comment by martincostello** [comment]
Will be included in the 6.0.0 release later this year.
