### ISSUE TITLE
Sign in with Apple throws exception if the user hits cancel from Apple's website

### ISSUE THREAD

**Issue by dbevan-kabam** [aspnet-contrib/AspNet.Security.OAuth.Providers#424]
**Describe the bug**
If a user cancels the sign in request an exception is thrown instead of the user going to the AccessDeniedPath.

**Steps To reproduce**
Setup sign in with Apple, follow the navigation prompts until you're signed in with Apple and presented with the option `Do you want to continue using ... with your Apple ID`. Select Cancel instead of continue

**Expected behaviour**
The user should be redirected to the url defined in the AccessDeniedPath for the Apple config

**Actual behaviour**
An exception is thrown
System.Exception: An error was encountered while handling the remote login.\n ---> System.Exception: user_cancelled_authorize\n   --- End of inner exception stack trace ---\n   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()\n   at IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync()\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)","ConnectionId":"0HLVJD6C0HTKG","TraceIdentifier":"0HLVJD6C0HTKG:00000001","EventId":{"Id":13,"Name":"ApplicationError"},"SourceContext":"Microsoft.AspNetCore.Server.Kestrel","RequestId":"0HLVJD6C0HTKG:00000001","RequestPath":"/signin-apple"

**System information:**
 - OS: Windows 10
 - Library Version AspNet.Security.OAuth.Apple:3.1.1
 - .NET version  
       Version:   3.1.200
       Commit:    c5123d973b

**Additional context**
Config looks like this:
```c#
                auth.AddApple(options =>
                {
                    options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                    options.ClientId = externalProviders.Apple.ClientId;
                    options.KeyId = externalProviders.Apple.KeyId;
                    options.TeamId = externalProviders.Apple.TeamId;
                    options.UsePrivateKey(keyId =>
                    {
                        using var fileProvider = new Microsoft.Extensions.FileProviders.PhysicalFileProvider("/");
                        return fileProvider.GetFileInfo(externalProviders.Apple.P8CertificateFileName);
                    });
                    options.Scope.Add("name");
                    options.AccessDeniedPath = GetDeniedRoute("apple");
                });
```

**Comment by dbevan-kabam** [comment]
Note, I should have said that this is being used with Identity Server 4 so that may be throwing some extra issues in. I have Discord hooked up too and cancel works as expected from them.

**Comment by kevinchalet** [comment]
Apple doesn't return a standard `access_denied` code, but a custom `user_cancelled_authorize`, that cannot be used with the default logic implemented by the generic OAuth handler.

If we want to support that, we'll need to override `HandleRemoteAuthenticateAsync()` and manually call `HandleAccessDeniedErrorAsync(properties)` from there when receiving a `user_cancelled_authorize` error.

**Comment by martincostello** [comment]
I just tested it out with my example site and got the error, so it's not related to anything to do with IdentityServer4: https://signinwithapple.azurewebsites.net/

I'll take a look into what Kévin suggests over the weekend and come up with a fix.

**Comment by dbevan-kabam** [comment]
Thanks @martincostello I really appreciate your work on this, hand rolling it was such a pain, you've saved me days of work easily.

**Comment by martincostello** [comment]
Fix in #425.

**Comment by martincostello** [comment]
Until 3.1.2 ships, you can pick up this fix from our MyGet feed: [AspNet.Security.OAuth.Apple 3.1.2-preview.20259.34](https://www.myget.org/feed/aspnet-contrib/package/nuget/AspNet.Security.OAuth.Apple/3.1.2-preview.20259.34)

**Comment by martincostello** [comment]
The 3.1.2 release containing this fix is now available from NuGet.org: https://www.nuget.org/packages/AspNet.Security.OAuth.Apple/
