### ISSUE TITLE
Migrate to new Discord domain

### ISSUE THREAD

**Issue by Herdo** [aspnet-contrib/AspNet.Security.OAuth.Providers#426]
Discord moved from their "old" domain `discordapp.com` to their new `discord.com`.
The developers communicated that the APIs need to be migrated to the new endpoints.
![grafik](https://user-images.githubusercontent.com/651191/81967348-13e0bb80-961b-11ea-9231-98a7d35b9c12.png)
Source: https://discordapp.com/channels/81384788765712384/381871767846780928/706955962711539724

Therefore, the OAuth 2.0 endpoints should be migrated prior the 7th November 2020 to `discord.com`.
The CDN endpoints should still point to `cdn.discordapp.com`.

**Comment by martincostello** [comment]
Thanks for the heads-up @Herdo - I’ll like at including the change in the next release.

**Comment by Herdo** [comment]
No problem. I'll open a PR with the changes.

**Comment by martincostello** [comment]
Even better 😀

**Comment by martincostello** [comment]
Resolved by #427.

**Comment by martincostello** [comment]
Version 3.1.2 of the provider, which uses the new domain, is now available from NuGet.org: https://www.nuget.org/packages/AspNet.Security.OAuth.Discord/
