### ISSUE TITLE
Instagram login : "Oops, an error occurred." after login page

### ISSUE THREAD

**Issue by alessandro-gns** [aspnet-contrib/AspNet.Security.OAuth.Providers#430]
Hi,
i have installed the package "AspNet.Security.OAuth.Instagram" 3.1.1 inside a net core 3.1 project.
Is a Oauth identity server 4 project with login throw Facebook, Google and Twitter all correctly configurated.
I can't figure out to use Instagram too and i try to install and configure the  package as foolow:

Startup.cs

`.AddInstagram(options =>
                {
                    options.ClientId = Configuration.GetSection("InstagramSettings:ClientID").Get<string>();
                    options.ClientSecret = Configuration.GetSection("InstagramSettings:ClientSecret").Get<string>();
                    options.AuthorizationEndpoint = "https://api.instagram.com/oauth/authorize";
                    options.SaveTokens = true;
                    options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                });`
I generate the ClientID anche ClientSecret from Developer console in Facebook accordly with documentation that move the manage of th login inside that in section "Products --> Instagram --> Basic display"

When i try to login the Instagram Login Page correctly load and after the login submit i obtain the follow URL redirect with error : "Oops, an error occurred."

`https://www.instagram.com/oauth/authorize?client_id=XXXXXXX&scope=basic&response_type=code&redirect_uri=https://XXXXXXXXXXXXXX&state=CfDJ8MwJeGVEvs9JvM-4MKP2C-pWN_U20Qe3F52UJbhgbVAnjnYETHHKkIBplilUXf7BtFuXDDDO8khFIaYjjzz8DO6CH4sISNRyQgYvyqCojFtac2ijP30EQDDkYqJ_Ht320IoUN6pOQig4_WjP7FsEeI15wQ1rUtGmNRXtHhr3PcSvirMZAIP3nDzFz4pd8XLaypw7gJ4yPHs80SgUSp4AveTKZgz2XQbDWXyUksHTVEvrjOd0Y9FVDYLwNXVu6b0bVCdczzHSj2wlQaJWG22-0Qm96CfjGAlZCvbKqIjz7J7J`

I read a lot of problem from instagram API and the generic error doesn't help really.
What's is wrong in that configuration? i don't see any reason

**Comment by martincostello** [comment]
You shouldn’t need to manually set the API endpoint like that, it’s built in (unless they changed us and no one’s raised an issue that it’s out of date).

In the first instance, try turning up the logging level and see if your app logs anything interesting in the responses from the Instagram API.

As a guess, have you also appropriately configured the appropriate allowed callback URLs in the Instagram developer console and/or correctly configured any extra scopes that might be needed?

**Comment by alessandro-gns** [comment]
i have already try with no AuthorizationEndpoint set in startup but the error wa the same.
I have set the allowed callback inside the Facebook developer console (at the end of march the API was moved there).

In AddInstagram the Scope is read-only so i can't set anyway but how showed into the url is set to "basic" by default i think and for the login workflow it's the only needed.

Inside my logs nothing useful is show. the last page visited is the URL i write in the question so don't return to my application after Instragram login

**Comment by martincostello** [comment]
You configuration _sounds_ like it's correct - without any further detail there's no much we can do to help you troubleshoot if the error is coming from the Instagram service, rather than after it calling back to your app.

**Comment by alessandro-gns** [comment]
I have use fiddler to understand the url calls.
I found that 500 server error:
```
`HTTP/1.1 500 Internal Server Error
Content-Type: text/html; charset=utf-8
Vary: Accept-Language, Cookie
Content-Language: en
Date: Wed, 03 Jun 2020 14:18:33 GMT
Strict-Transport-Security: max-age=31536000
Cache-Control: private, no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: Sat, 01 Jan 2000 00:00:00 GMT
X-Frame-Options: SAMEORIGIN
content-security-policy: report-uri https://www.instagram.com/security/csp_report/; default-src 'self' https://www.instagram.com; img-src https: data: blob:; font-src https: data:; media-src 'self' blob: https://www.instagram.com https://*.cdninstagram.com https://*.fbcdn.net; manifest-src 'self' https://www.instagram.com; script-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://*.cdninstagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' https://*.www.instagram.com https://www.instagram.com 'unsafe-inline'; connect-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://*.cdninstagram.com https://api.instagram.com https://i.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd blob:; worker-src 'self' blob: https://www.instagram.com; frame-src 'self' https://instagram.com https://www.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com; object-src 'none'; upgrade-insecure-requests
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
x-aed: 15
Access-Control-Expose-Headers: X-IG-Set-WWW-Claim
Set-Cookie: csrftoken=fF0TVtlZuWsJAf7BfVr75QOs87XlCkjC; Domain=.instagram.com; expires=Wed, 02-Jun-2021 14:18:33 GMT; Max-Age=31449600; Path=/; Secure
Date: Wed, 03 Jun 2020 14:18:33 GMT
X-FB-TRIP-ID: 1679558926
Connection: keep-alive
Content-Length: 25

Oops, an error occurred.
`
```

I don't have other way to understand that at the moment.

**Comment by martincostello** [comment]
If the HTTP 500 is coming from Instagram, I suggest you open a support ticket with them to investigate.

**Comment by martincostello** [comment]
Closing as there's been no further activity, but we've been made aware that the current Instagram API is being deprecated at the end of September 2020, so we'll be issuing a new version of the provider that integrates with the new APIs before then (see #441).
