### ISSUE TITLE
Patreon sign in throws a "invalid_scope" exception

### ISSUE THREAD

**Issue by Ryhon0** [aspnet-contrib/AspNet.Security.OAuth.Providers#432]
**Describe the bug**
When I add the Patreon sign in to my project using `AddPatreon` attempting to sign in using Patreon will throw a `invalid_scope` exception

**Steps To reproduce**
* Add the Patreon OAuth provider to a website
* Start the website
* Attempt to sign in using Patreon

**Expected behaviour**
Website takes you to the Patreon website to authorize an application

**Actual behaviour**
Website throws a `invalid_scope` exception at an unknown location

**System information:**
 - OS: Manjaro Linux 
 - Library Version: 3.1.1
 - .NET version: Core SDK 3.1.103, AspNetCore runtime 3.1.4

**Additional context**
Other providers work perfectly. Doesn't work any API version of the Patreon application.

<details><summary>Exception details</summary>
<p>

```
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: invalid_scope
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

</p>
</details>

**Comment by martincostello** [comment]
Looking at the code for the default scopes the provider adds, they match the documented scopes here: https://docs.patreon.com/#step-2-making-the-log-in-button

What happens if you call `options.Scope.Clear()` as part of configuring the provider in your app?

**Comment by martincostello** [comment]
The relevant code:

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/02e50174cc7cd418c3653152ada6de640fad9fe3/src/AspNet.Security.OAuth.Patreon/PatreonAuthenticationOptions.cs#L29-L31

**Comment by Ryhon0** [comment]
Calling `options.Scope.Clear()` still throws the same exception

**Comment by martincostello** [comment]
I’m afraid I’m not really sure then. If no scopes are even being sent to Patreon, I’m not sure how they could be invalid.

Have they recently made changes to their servers that don’t match the documentation and/or specs the provider was originally written against?

**Comment by Ryhon0** [comment]
Hm, [the website says you can use the V1 scopes in V2 API](https://docs.patreon.com/#using-apiv2-with-apiv1). 
I've cleared the scope and added the V2 scopes instead and it works
```cs
options.Scope.Clear();
options.Scope.Add("identity");
options.Scope.Add("identity[email]");
options.Scope.Add("identity.memberships");
options.Scope.Add("campaigns");
options.Scope.Add("campaigns.members");
options.Scope.Add("campaigns.members[email]");
options.Scope.Add("campaigns.members.address");
```

**Comment by martincostello** [comment]
Ok, so given that v2 is still in beta, this sounds like a bug on Patreon’s end if they’re breaking v1 requests.

That said, this raises the point that we’ll need to migrate the provider to use the v2 API at some point.

**Comment by AraHaan** [comment]
I mean depending on what the provider uses the api for I think it could not hurt to do some fixups on it and flat out not request v1 resources as they will get removed eventually on their end.

**Comment by martincostello** [comment]
That's the idea of #433 - to stop using v1 and move to v2.

**Comment by AraHaan** [comment]
oh and @martincostello think you can help me with #434 too?
