### ISSUE TITLE
Add Slack provider

### ISSUE THREAD

**Issue by mjknowles** [aspnet-contrib/AspNet.Security.OAuth.Providers#45]
I'll start working on this one. :+1:

**Comment by PinpointTownes** [comment]
Thanks @mjknowles! :fries:

**Comment by PinpointTownes** [comment]
Done: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/4ff22aee4fb2b0e9bb521e953af5b74ca618157e

@mjknowles thanks for your contribution :smile:
