### ISSUE TITLE
Redirect uri is not correct for WeixinAuthenticationHandler with proxy server

### ISSUE THREAD

**Issue by StarkShang** [aspnet-contrib/AspNet.Security.OAuth.Providers#457]
I am using IdentityServer4 and AspNet.Security.OAuth.Weixin package for weixin external login, and I have configured as metioned in

> https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-3.1#forward-request-information-with-a-proxy-or-load-balancer
> https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1

The urls in Discovery Endpoint of IdentityServer4 are correct, but the generated return_uri for weixin challenge is still http://localhost:5000. Both the scheme and the host are not set as expected(https://example.com)

What can I do to fix this problem
@kinosang @saber-wang @zhengchun

**Comment by saber-wang** [comment]
return_ Uri is the runtime URL

**Comment by kinosang** [comment]
unrelated to this project

Google `Asp.Net Core reverse proxy` then you'll find why and how.

**Comment by StarkShang** [comment]
I do not understand exactly. @saber-wang 

I got the message from logger as follows:
> HandleChallenge with Location: https://open.weixin.qq.com/connect/qrconnect?appid=wx036de4b259014956&scope=snsapi_login,snsapi_userinfo&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Fapi%2Fv1%2Flogin%2Foauth%2Fwechat&state=CfDJ8EdEd_wx52FMlsOpNdrTL4MMvjsISzjY_hdIjltqN1Di42hT2X0EaA2fYinkIiXOiL6NhXAmKH8aT4akdzf3ORppWGUEe_CnKapyqCnxYyiROfMpMDcs9XesdLDIONGruq_4NxeHe-MVFks1zjfEBCsOpBEoLkv1kO-xhr1uvHHL40rqM-h1ODP4DTG27nhdVDZNr0GdZBTkmsR1darYmhY; and Set-Cookie: .AspNetCore.Correlation.Weixin.0nv1Y-TQFbEWxzgXJo0NZA_TwxztPhuSMo36eVNwhVU=N; expires=Fri, 10 Jul 2020 03:07:27 GMT; path=/api/v1/login/oauth/wechat; samesite=none; httponly.

The redirect_uri is generated by configuration in Startup.cs as follows:

```csharp
services.AddAuthentication()
            .AddWeixin(options => {
                    options.ClientId = "wx036de4b259014956";
                    options.ClientSecret = "";
                    options.CallbackPath = "/api/v1/login/oauth/wechat";
            })
```

But I don't know how the scheme and the host  are configured.

Moreover, configuration in controller for RedirectUri of AuthenticationProperties not work. Does this redirectUri differ from the redirect_uri metioned above? Does this redirectUri included in state?
```csharp
return Challenge(new AuthenticationProperties { RedirectUri = "https://example.com" }, dto.Provider);
```

**Comment by saber-wang** [comment]
@StarkShang 
```
var props = new AuthenticationProperties
                {
                    RedirectUri = Url.Action(nameof(Callback)),
                    Items =
                    {
                        { "returnUrl", **returnUrl** },
                        { "scheme", provider },
                    }
                };
                return Challenge(props, provider);
```

Splicing in returnurl

**Comment by StarkShang** [comment]
thanks a lot~ @saber-wang
