### ISSUE TITLE
SuperOffice doesn't include ClaimTypes.NameIdentifier or ClaimTypes.Email.

### ISSUE THREAD

**Issue by AnthonyYates** [aspnet-contrib/AspNet.Security.OAuth.Providers#464]
### SuperOffice

When signed in with SuperOffice provider, the ClaimTypes.NameIdentifier or ClaimTypes.Email claims are missing from the identity.

### Expected behavior

Would expect ClaimTypes.NameIdentifier or ClaimTypes.Email to be included for better .Net Identity support.

**Comment by martincostello** [comment]
This change is now available in release [3.1.4](https://www.nuget.org/packages/AspNet.Security.OAuth.SuperOffice/3.1.4) of the provider.
