### ISSUE TITLE
Plex

### ISSUE THREAD

**Issue by looselyhuman** [aspnet-contrib/AspNet.Security.OAuth.Providers#466]
Is anyone working on a provider for plex.tv?  Limited documentation from Plex [here](https://forums.plex.tv/t/authenticating-with-plex/609370).

It looks pretty non-standard.  If nobody is working on one I'll give it a shot.

**Comment by martincostello** [comment]
Hi @looselyhuman - no, I'm not aware of anyone working on a Plex provider.

If you'd like to contribute one, feel free to raise a PR.

**Comment by looselyhuman** [comment]
> Hi @looselyhuman - no, I'm not aware of anyone working on a Plex provider.
> 
> If you'd like to contribute one, feel free to raise a PR.

Okie doke, thanks @martincostello . Wish me luck! I haven't written code for real in about 5 years...

**Comment by looselyhuman** [comment]
Looks like this won't be doable unless Plex makes some changes. They're not to OAuth spec right now. Auth flow is unusual, and the token system is a little inconsistent. I am talking to a dev there to see if there's a roadmap or alternate "hidden" api/workflow.
