### ISSUE TITLE
Can I use the AspNet.Security.OAuth.Apple with Identity Server 4?

### ISSUE THREAD

**Issue by nthandu** [aspnet-contrib/AspNet.Security.OAuth.Providers#467]
Hello all,

I am trying to implement the Sign In within our Identity Server 4-based identity solution.

I have implemented using it as another OpenId connect provider but it's not working as expected.  Token is expiring or the validation is failing. It's something I need to verify.

I am just wondering if I could use the AspNet.Security.OAuth.Apple package instead of setting up my own config.

If it works, are there any configurations I need to be aware of such as setting up the scopes?

Thanks,
Naresh

**Comment by martincostello** [comment]
The Apple provider hasn't been _specifically_ designed to work with IdentityServer 4, but more as a stand-alone OAuth provider like the other OAuth providers that Microsoft provide with ASP.NET Core itself (like the Google and Microsoft providers).

Documentation for the provider can be found here, which includes some links off to other articles about implementing it in various different ways: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/dev/docs/sign-in-with-apple.md

**Comment by thandunaresh** [comment]
Thanks for a quick response.

_It's not designed_, does it means it would not work with solutions like Identity Server? My understanding here is, as any other Sign In provider for example using Google with Identity Provider. I maybe completely wrong.



```csharp
.AddOpenIdConnect("Apple", async options =>
                {
                    options.ResponseType = "code";
                    options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                    options.DisableTelemetry = true;
                    options.Scope.Clear();
                    options.Scope.Add("name");
                    options.Scope.Add("email");
                    options.Configuration = new OpenIdConnectConfiguration
                    {
                        AuthorizationEndpoint = "https://appleid.apple.com/auth/authorize",
                        TokenEndpoint = "https://appleid.apple.com/auth/token"
                    };
                    options.ClientId = "<service id>";
                    options.Events.OnAuthorizationCodeReceived =  context =>
                    {
                        context.TokenEndpointRequest.ClientSecret = AppleSignInTokenGenerator.CreateNewToken();
                        return Task.CompletedTask;
                    };
                    options.TokenValidationParameters.ValidIssuer = "https://appleid.apple.com";
                    var jwks = await new HttpClient().GetStringAsync("https://appleid.apple.com/auth/keys");
                    options.TokenValidationParameters.IssuerSigningKeys = new JsonWebKeySet(jwks).Keys;
                    options.ProtocolValidator.RequireNonce = false;
                });

public static class AppleSignInTokenGenerator
    {
        public static string CreateNewToken()
        {
            const string iss = "<apple dev team account id>"; 
            const string aud = "https://appleid.apple.com";
            const string sub = "<service id>"; 
            const string privateKeyContentn = "private key content";
            var cngKey = CngKey.Import(Convert.FromBase64String(privateKeyContentn), CngKeyBlobFormat.Pkcs8PrivateBlob);
            var handler = new JwtSecurityTokenHandler();
            var token = handler.CreateJwtSecurityToken(
                issuer: iss,
                audience: aud,
                subject: new ClaimsIdentity(new List<Claim>
                {
                    new Claim("sub", sub)
                }),
                expires: DateTime.UtcNow.AddMinutes(30), // expiry can be a maximum of 6 months => generate one per request, or one and then re-use until expiration
                issuedAt: DateTime.UtcNow,
                notBefore: DateTime.UtcNow,
                signingCredentials: new SigningCredentials(new ECDsaSecurityKey(new ECDsaCng(cngKey)), SecurityAlgorithms.EcdsaSha256));
             return handler.WriteToken(token);
        }
    }

```

That's my existing code, I have followed few blogs(one of yours) to write the above code.

Thanks

**Comment by martincostello** [comment]
That's just me being cagey and saying that it _might_ work, or it _might_ not 😄 - I don't have any experience myself of implementing/working with IdentityServer itself.

I've had a quick glance over the code at a glance and it seems correct without going over it with a fine-tooth-comb.

The thing I'd maybe pay a bit more attention to as part of your debugging is that the keys are being loaded (and maybe disposed of, some of the types implement `IDisposable`) properly and that there's no clock skew happening somewhere with the validity between your system(s) and Apple's servers.

Also some of the way you're loading the keys looks to be Windows-specific, so might cause issues if you tried to run the code on a Linux server.

**Comment by nthandu** [comment]
Thanks again for quickly responding.

I was hoping to make improvements to keys loading once the workflows are working correctly, at the moment I am hosting this on a Windows server.

Yes, I will need to debug this bit more deeply to understand where it's going wrong.

Thanks

**Comment by paulers** [comment]
I've been trying to get this package to work with Identity Server 4 as well (3.1.4), but without success. The External/Callback is failing to authenticate right at the start: `await HttpContext.AuthenticateAsync(IdentityServer4.IdentityServerConstants.ExternalCookieAuthenticationScheme)`. No failure message is returned so it's impossible to see what's going wrong.

I wonder if anyone else has run into this.

**Comment by martincostello** [comment]
Have you tried turning on debug logging and reading through the logs? Even if you don't get any information on the user-facing/developer-facing error page during the OAuth flow, there's usually some further detail in the logs.

**Comment by paulers** [comment]
Let me give that a shot and report back. Been trying to hook into various event handlers in Startup.cs, but nothing in there either.

**Comment by paulers** [comment]
Turns out an additional property is required when setting up in Startup.cs.
```csharp
.AddApple("Apple", options =>
{
    options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
    options.ClientId = Configuration["Provider:Apple:ClientId"];
    options.KeyId = Configuration["Provider:Apple:KeyId"];
    options.TeamId = Configuration["Provider:Apple:TeamId"];
    options.UsePrivateKey((keyId) => Environment.ContentRootFileProvider.GetFileInfo($"AuthKey_{Configuration["Provider:Apple:KeyId"]}.p8"));
});
```
The SignInScheme is required and has to match the same scheme present in External/Callback:
```csharp
var result = await HttpContext.AuthenticateAsync(IdentityServer4.IdentityServerConstants.ExternalCookieAuthenticationScheme);
```

Works like a charm now.
