### ISSUE TITLE
Unable to recieve Identity.External cookie with AspNet.Security.OAuth.Apple.

### ISSUE THREAD

**Issue by Rumbeer** [aspnet-contrib/AspNet.Security.OAuth.Providers#468]
Hi,
I am using AspNet.Security.OAuth.Apple package version 2.2.2 to sign in with Apple ID as external provider.

But I don't receive Identity.External cookie when I am redirected back to my application and `Microsoft.AspNetCore.Identity.SignInManager.GetExternalLoginInfoAsync` returns `null` instead of the information about external login.

I have a DotVVM application so my code looks like this:
```c#
services.AddAuthentication()
    .AddApple(options =>
    {
        options.ClientId = configuration["Apple:SignIn:ClientId"];
        options.KeyId = configuration["Apple:SignIn:KeyId"];
        options.TeamId = configuration["Apple:SignIn:TeamId"];
        options.SignInScheme = IdentityConstants.ExternalScheme;
        options.Events = new AppleAuthenticationEvents()
        {
            OnRedirectToAuthorizationEndpoint = context =>
            {
                DotvvmAuthenticationHelper.ApplyRedirectResponse(context.HttpContext, context.RedirectUri);
                return Task.CompletedTask;
            },
            OnRemoteFailure = context =>
            {
                
                context.HandleResponse();
                if (context.Request.Query.TryGetValue("error", out var error))
                {
                    context.Response.Redirect($"/login-apple?error={error}");
                }
                else
                {
                    context.Response.Redirect($"/login-apple");
                }

                return Task.CompletedTask;
            }
        };
        options.UsePrivateKey(
            (keyId) =>
                env.ContentRootFileProvider.GetFileInfo($"AuthKey_{keyId}.p8"));
    });
```

After some debugging I have found out that I recieve an error from the method `ExchangeCodeAsync` in `AppleAuthenticationHandler.HandleRemoteAuthenticateAsync`:
```
OAuth token endpoint failure: Status: BadRequest;Headers: Server: Apple
Date: Fri, 21 Aug 2020 15:25:16 GMT
Connection: keep-alive
Cache-Control: no-store
Pragma: no-cache
;Body: {"error":"invalid_client"};
```

However when I try to step through this method in debugger it somehow fixes my issue so I added a 5 second delay to the event `OnGenerateClientSecret` which also seems to solve it:

```c#
OnGenerateClientSecret = async context =>
{
    var provider = context.HttpContext.RequestServices.GetService<AppleClientSecretGenerator>();
    context.Options.ClientSecret = await provider.GenerateAsync(context);
    await Task.Delay(TimeSpan.FromSeconds(5));
},
```

But it is not an ideal fix so any help would be appreciated.

Thanks.

**Comment by martincostello** [comment]
That does sound like a strange issue. I'll not familiar with DotVVM so I'm not sure how the OAuth handlers fit into that. Is there maybe something somewhere not being awaited elsewhere that's causing the request to proceed before the key has been generated fully?

Are you able to update to the latest 3.1 handler? As 2.2 and 3.0 are no longer supported by Microsoft, if this was a bug in the provider code it's not something that will get fixed by us in the 2.2 provider branch.

**Comment by Rumbeer** [comment]
Thanks for the reply. I will try to reproduce it on MVC application.

**Comment by Rumbeer** [comment]
Sorry for the delay. I couldn't reproduce this issue on MVC application but it persists on DotVVM application even with the version 3.1 so the problem probably lies in DotVVM.
