### ISSUE TITLE
An unhandled exception occurred while processing the request. 

### ISSUE THREAD

**Issue by MrChuJiu** [aspnet-contrib/AspNet.Security.OAuth.Providers#473]
Nuget  AspNet.Security.OAuth.QQ  3.1.3
Edge  Browser OK

Google Browser Error
An unhandled exception occurred while processing the request.
Exception: Correlation failed.
Unknown location

Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()

**Comment by martincostello** [comment]
Please enable debug logging and provide some log details in this issue for us to look at.

Otherwise there's no way for us to know what could be wrong or know whether or not it's an issue in the provider, with your configuration, or with the QQ service itself.

From "Correlation failed", this would suggest to me an issue with your configuration, such as to do with cookies and SameSite:

https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/

**Comment by ltm0203** [comment]
```
WARN  2020-10-02 20:29:04,224 [41   ] ecurity.OAuth.QQ.QQAuthenticationHandler - '.AspNetCore.Correlation.QQ.lJ6EVI8Fsn9DENNb9uXqiN9yMpG01oKxpOwvxfqE0M0' cookie not found.
ERROR 2020-10-02 20:29:04,225 [41   ] nostics.DeveloperExceptionPageMiddleware - An unhandled exception has occurred while executing the request.
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Correlation failed.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by martincostello** [comment]
This sounds likely to be related to SameSite cookies and the configuration of your application: https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/

**Comment by ltm0203** [comment]
I just use asp.net core identity 

this is my startup code
```csharp
  services.AddSession(options =>
            {
                 
                // Set a short timeout for easy testing.
                options.IdleTimeout = TimeSpan.FromDays(1);
                 options.Cookie.HttpOnly = false;
                //options.Cookie.IsEssential = true;
            });
```

![image](https://user-images.githubusercontent.com/7875527/94926318-2e94cd80-04f3-11eb-9f18-09365fa3ef86.png)

Shut down the httponly

**Comment by kinosang** [comment]
@ltm0203 with asp.net core 3.1, you should set the SameSite policy for cookies. See here for more information: https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-3.1

**Comment by ltm0203** [comment]
> @ltm0203 with asp.net core 3.1, you should set the SameSite policy for cookies. See here for more information: https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-3.1

hi @kinosang  I have configured several options, but still cannot run successfully. Do you have any other suggestions? Or there are still problems with my configuration.

```csharp
services.AddAuthentication().AddQQ(options =>
                    {
                        options.ClientId = configuration.GetValue<string>("Authentication:External:QQ:ClientId");
                        options.ClientSecret = configuration["Authentication:External:QQ:ClientSercet"];
                                  }
                ).AddCookie(options =>
                {
                    options.Cookie.SameSite = SameSiteMode.None;
                    options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
                    options.Cookie.IsEssential = true;
                }); 

```

```csharp
  app.UseRouting();

            app.UseCookiePolicy();

            app.UseAuthentication();
```

**Comment by kinosang** [comment]
@ltm0203 

You have to configure `ApplicationCookie` (if you use the Asp.Net Identity), `ExternalCookie` (for 3rd login) and `CookieAuthenticationOptions` (for 2FA, and etc)

**Comment by ltm0203** [comment]
@martincostello 

You may not believe it. It is a qq problem. The key of my production environment can be used normally. The development environment uses localhost to report an error. . .

Thank you for your comments and support.

**Comment by Google-image-search-colb** [comment]
@kinosang https://stackdev.space/questions/assistance-needed-for-managing-exceptions-in-aspnet-c-program
