### ISSUE TITLE
Discord: .AspNetCore.Identity.Application always set to expire when session ends

### ISSUE THREAD

**Issue by kendrome** [aspnet-contrib/AspNet.Security.OAuth.Providers#474]
**Describe the bug**
Using Discord OAuth provider, and the cookie expiration is always set to when the session ends. Tried all of the following...

```
.AddDiscord(options => {
    options.ClientId = "***";
    options.ClientSecret = "***";
    options.Events = new Microsoft.AspNetCore.Authentication.OAuth.OAuthEvents {
        OnTicketReceived = context => {
            context.Properties.IsPersistent = true;
            context.Properties.ExpiresUtc = DateTimeOffset.UtcNow.AddDays(30);
            context.Properties.AllowRefresh = true;
            return Task.FromResult(0);
        }
    };
```

```
.AddCookie(options => {
    options.SlidingExpiration = true;
    options.Cookie.Expiration = TimeSpan.FromDays(30);
})
```

```
services.PostConfigure<CookieAuthenticationOptions>(options => {
    options.ExpireTimeSpan = TimeSpan.FromDays(30);
    options.SlidingExpiration = true;
});
```

**System information:**
 - OS: Window 10
 - Library Version 3.1.3
 - .NET version 3.1.4

**Comment by martincostello** [comment]
Have you tried `ConfigureApplicationCookie()` or `ConfigureExternalCookie()`?

https://github.com/martincostello/alexa-london-travel-site/blob/02e66413021a7c84cc792ccc1f5ab300f940b64c/src/LondonTravel.Site/Extensions/IdentityServiceCollectionExtensions.cs#L39-L41

**Comment by kendrome** [comment]
```
            services.ConfigureApplicationCookie(options => {
                options.ExpireTimeSpan = TimeSpan.FromDays(30);
                options.Cookie.Name = "egg9000cookie.app";
            });
```
Seems to partially work, it lets me change the cookie name, but the cookie still expires when the session ends in Chrome and Firefox. Also tried the exact code you linked to in the blob and still same issue.

**Comment by martincostello** [comment]
I'm not entirely sure then - this is functionality from ASP.NET Core that the provider builds on top of, it's not part of the Discord provider itself.

The configuration I linked to is what I use for the Amazon (and other) providers in my site and the session cookie has the specified lifetime and persists across browser sessions.

**Comment by kendrome** [comment]
So it seems I had to set the `options.Cookie.MaxAge = TimeSpan.FromDays(30);` and that finally worked. I'm not sure exactly why.
