### ISSUE TITLE
Determine whether we should stop using embedded PDBs

### ISSUE THREAD

**Issue by kevinchalet** [aspnet-contrib/AspNet.Security.OAuth.Providers#475]
@martincostello all the aspnet-contrib OAuth 2.0/OpenID 2.0 providers currently ship with the PDBs embedded in the assemblies themselves, which makes deployments a bit bigger (something like +~10%, AFAICT).
That's because Arcade defaults to `embedded` PDBs when `OfficialBuild` is not set (and it's not something we use, as we hit issues with the automatic symbols upload to MSFT that requires authentication).

Instead, should we use `portable` and the new `snupkg` format? If we shipped our PDBs as `snupkg` files, we could push them to NuGet.org.

**Comment by martincostello** [comment]
Makes sense to me - that's what I do for my own libs.

**Comment by martincostello** [comment]
Do you want me to sort this out for the OpenID and OAuth repos if you're changing OpenIddict?

**Comment by kevinchalet** [comment]
I don't mind taking care of this, but I'm not sure whether we'll need to also update the build GH workflow to push the .snupkg to MyGet and NuGet or if `dotnet push` is smart enough to push them automatically 😕

**Comment by kevinchalet** [comment]
Crap, for some reasons, enabling `snupkg` seems to cause a `NU5017: Cannot create a package that has no dependencies nor content` error when a package doesn't have any package reference: https://github.com/openiddict/openiddict-core/pull/1105/checks?check_run_id=1161635421#step:6:250

**Comment by martincostello** [comment]
> I don't mind taking care of this, but I'm not sure whether we'll need to also update the build GH workflow to push the .snupkg to MyGet and NuGet or if `dotnet push` is smart enough to push them automatically 😕

_C'est magique_ ✨ 

It'll automatically do it if it finds the `.snupkg` file next to package you're publishing.

**Comment by martincostello** [comment]
> Crap, for some reasons, enabling `snupkg` seems to cause a `NU5017: Cannot create a package that has no dependencies nor content` error when a package doesn't have any package reference: https://github.com/openiddict/openiddict-core/pull/1105/checks?check_run_id=1161635421#step:6:250

Weird, never seen that one before!

**Comment by kevinchalet** [comment]
I guess I'll magically solve that by adding another entry to `<NoWarn></NoWarn>` 😅

**Comment by kevinchalet** [comment]
Fuck, not this time, it seems 😭
