### ISSUE TITLE
Weibo  can not get email infomation

### ISSUE THREAD

**Issue by tersonly** [aspnet-contrib/AspNet.Security.OAuth.Providers#477]
**Describe the bug**
the callback Url  always get an error ,  then you can refresh chrome it  will work    

api.weibo.com/oauth2/authorize?client_id=2xxxxxxxx&response_type=code&redirect_uri=http%3A%2F%2F127.0.0.1%3A50000%2Fsignin-weibo

![image](https://user-images.githubusercontent.com/20390658/94436558-2a08a600-01cf-11eb-9e52-d4c96a9c574f.png)

![image](https://user-images.githubusercontent.com/20390658/94436512-19f0c680-01cf-11eb-8f73-61f835e6dac4.png)

**Comment by martincostello** [comment]
The default port for Kestrel is usually `5000` not `50000` - are you sure you've configured it correctly?

Otherwise, based on the information you've provided there's not much to go on to show that there's an issue with the provider, or much to help us get to the bottom of what the issue might be.

**Comment by tersonly** [comment]
the port 5000 is for anthor app ,  this situatio may be   the network  jitter , the email endpoint  return an error  and  I can not find  the document  about  https://api.weibo.com/2/account/profile/email.json ， perhaps  need   apply for interface permission

**Comment by kinosang** [comment]
@tersonly Weibo stops to accept any new application for `email` scope, there's no way to access the email endpoint for new client apps.

**Comment by tersonly** [comment]
thanks a lot
