### ISSUE TITLE
Weixin Recall back 500 err in Edge, in chrome is fine return status Code 302.

### ISSUE THREAD

**Issue by jingxi0109** [aspnet-contrib/AspNet.Security.OAuth.Providers#487]
**Describe the bug**
use the weixin version with MVC client sample code with my appid, signin with QRCode use chrome is fine, but return 302 found.

same operation as  above,  in Microsoft Edge, when scaned the QRCode browser back HTTP ERROR 500,

**System information:**
 Client OS: Windows 10
Server OS Windows 2019 with IIS 
 - .NET Core version 3.1

**Comment by martincostello** [comment]
Can you share some error logs?

Sounds like it might be a SameSite issue though: https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/

**Comment by jingxi0109** [comment]
update, just try it on ipad(ios) use edge and safari it's works well.

**Comment by jingxi0109** [comment]
Dears,after add the SSL all browser is work well.
this issue can close, thanks~
