### ISSUE TITLE
AspNet.Security.OAuth.Providers.SuperOffice package expects incorrect issuer in "stage"-enviroment

### ISSUE THREAD

**Issue by josteink** [aspnet-contrib/AspNet.Security.OAuth.Providers#489]
**Describe the bug**

When using the package `AspNet.Security.OAuth.Providers.SuperOffice`, you are expected to populate the relevant SuperOffice environment to authenticate for (development, stage or production). The provider is then configured with appropriate settings and URLs for that environment.

However, for the stage environment, the package does not work, because the issuer-value which the provider expects is not the actual issuer-value used in this environment.

**Steps To reproduce**

Create a minimal Asp .Net Core application and configure it to use SuperOffice authentication in the SuperOffice stage-environment. Launch app, attempt to authenticate.

````
$ dotnet new web
$ dotnet add package AspNet.Security.OAuth.SuperOffice --version 3.1.4
$ cat Startup.cs
...
  public void ConfigureServices(IServiceCollection services)
  {
      services.AddAuthentication()
              .AddSuperOffice(SuperOfficeAuthenticationDefaults.AuthenticationScheme, options =>
      {
          options.Environment = SuperOfficeAuthenticationEnvironment.Stage;
          // etc etc
      });
  }
...
$ dotnet run
````

**Expected behaviour**

Expected website to use SuperOffice stage environment to provide authenticated user.

**Actual behaviour**

Unable to authenticate user because package expects `"stage.superoffice.com"` as issuer of claims-identity, while real issuer used is `"qaonline.superoffice.com"`.

This can be confirmed independently in the well-known openid-configuration document found here:

https://stage.superoffice.com/login/.well-known/openid-configuration

![image](https://user-images.githubusercontent.com/411338/96413506-07751600-11ec-11eb-91a5-bba49639a764.png)

**System information:**

 - OS: N/A
 - Library Version: 3.1.4
 - .NET version: 3.1.201

**Additional context**

This breaks the release/deployment flow of any application which attempts to follow the DEV, STAGE, PROD deployment flow with the SuperOffice authentication-package, so it would be nice to get it fixed before .NET 5.0 RTM ships.

**Comment by martincostello** [comment]
Thanks for reporting this issue @josteink.

The fix by @AnthonyYates is available from our [MyGet feed](https://www.myget.org/gallery/aspnet-contrib) in package versions `3.1.5-preview.20519.31` and `5.0.0-rc.2.20519.31`.

I'll look at pushing the 3.1.5 release to NuGet.org either today or tomorrow.

**Comment by josteink** [comment]
Great. Thanks for expediting this issue so swiftly!

**Comment by martincostello** [comment]
The fix is now available from [NuGet.org](https://www.nuget.org/packages/AspNet.Security.OAuth.SuperOffice/3.1.5).
