### ISSUE TITLE
Rename KakaoTalk Provider to Kakao

### ISSUE THREAD

**Issue by wplong11** [aspnet-contrib/AspNet.Security.OAuth.Providers#495]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. For example: _I'm always frustrated when [...]_

The name of the Kakao Talk account authentication service has been changed to Kakao Account Authentication. I missed this and misnamed the package. Recently, I am trying to change Kakao Talk to Kakao to match the name.

**Describe the solution you'd like**

Change the package name, method name, and claim id. Then publish a new package and hides the existing package in nuget anymore. There will be no confusion because the number of downloads is small.

If it is agreed that it is a good approach, I will create pr.

**Comment by martincostello** [comment]
A quick search for "Kakao Talk" in Google brings up lots of hits, so is this really necessary?

If people can find it and it works it shouldn't really make any difference now it's shipped.

We haven't renamed the "Visual Studio Online" provided to "Azure Dev Ops", for instance.

**Comment by wplong11** [comment]
Not only the name, but also the concept of service has changed. For example, KakaoTalk's account has been integrated into an account within the Kakao service. Kakao accounts are like Azure accounts, and KakaoTalk has become a subservice like AzureDevOps.
