### ISSUE TITLE
Cant get access_token in Blazor server side application

### ISSUE THREAD

**Issue by negativeeddy** [aspnet-contrib/AspNet.Security.OAuth.Providers#496]
**Describe the bug**
Using the standard Blazor server side VS template with the Twitch provider added, I cannot get the access_token or refresh_token from the authentication providers

**Steps To reproduce**
1. Create Blazor server side template with individual user account authentication
2. Add the Twitch configuration that should save the tokens
```
            services.AddAuthentication().AddTwitch(config =>
            {
                config.ClientId = Configuration["Twitch:ClientId"]; ;
                config.ClientSecret = Configuration["Twitch:ClientSecret"];
                config.Scope.Add("channel:manage:broadcast");
                config.SaveTokens = true;
            })
```
3. follow instructions for [grabbing tokens from HttpContext in Blazor's root host](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-3.1#pass-tokens-to-a-blazor-server-app) file (this has to happen there because all other activity is outside of the HttpContext pipeline and sent over signalr)
4. examine the result from HttpContext.GetTokenAsync("access_token")

**Expected behaviour**
Should see the Twitch access token

**Actual behaviour**
returns null

**System information:**
 - OS: Windows 10
 - Library Version 3.1.6
 - .NET  3.1.9

**Additional context**
One of the main differences I can tell from the MVC sample, besides the MVC vs Blazor hosting model, is that the Blazor template starts up with the default identity management referenced so there are several auth schemes registered. None of them have the tokens in them when I enumerate through them. I did see an older closed issue that mentioned something about other schemes, but I dont want to have to implement all the auth pages in blazor myself if possible.

 I can run the MVC sample with only the change of adding SaveTokens=true and it works correctly.

**Comment by martincostello** [comment]
Closing this as Blazor is outside our supported uses cases and I don't _think_ it's an issue specific to us. If there's evidence to the contrary that this _should_ work with _server-side_ Blazor (client-side wouldn't be secure as it would need the secrets) and it's due to a bug, we can revisit.
