### ISSUE TITLE
Subdomain Support

### ISSUE THREAD

**Issue by kfrancis** [aspnet-contrib/AspNet.Security.OAuth.Providers#499]
I know that subdomains shouldn't be used in oauth, as in the request should come to and from the host without the subdomain, but how can we keep that information through the process and return the user there when it's completed?

For example, the user browses to `https://company.supercoolproduct.com/Account/Login` and goes to use oauth. The provider has and will only have registered `https://supercoolproduct.com/signin` as a redirect URL so if we try `https://company.supercoolproduct.com/signin` then it will fail. What is a method of passing "company" through the process so that the final redirect after acquiring the `access_token` goes back to where they came from?

**Comment by kinosang** [comment]
implement your own sso (OAuth, SAML, and etc, for e.g.) on supercoolproduct.com and use the sso provider at company.supercoolproduct.com
