### ISSUE TITLE
Add Dropbox provider

### ISSUE THREAD

**Issue by jerriep** [aspnet-contrib/AspNet.Security.OAuth.Providers#5]

**Comment by SH2015** [comment]
I will take this provider

**Comment by PinpointTownes** [comment]
@SH2015 nice, thanks! :+1:

**Comment by SH2015** [comment]
You welcome, Tonight I ll start coding it .

**Comment by SH2015** [comment]
The Dropbox provider has been done . but I have two questions 
1- Do I need to add all the user info values or just the id,name,email ? 
2- if the values are sub objects , can I create a subclasses or you want to keep it clean and limited to what we have now from classes ?

**Comment by jerriep** [comment]
I think the general rule is not to go overboard with the information, and stick to the essentials and ones that really make sense otherwise.

Can you perhaps give a link to the API documentation so we can see what is available?

**Comment by jerriep** [comment]
Sorry, found it in your PR: https://www.dropbox.com/developers/core/docs#account-info

I thing you are OK with the ones you added as claims for now (id, email and name). Any other ones which people need they can extract from the payload themselves.

**Comment by SH2015** [comment]
Great.

**Comment by PinpointTownes** [comment]
Done: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/cbe593c39063c006ebd25ac1e21e850a24cea103 :+1:
