### ISSUE TITLE
trying to connect apple login in identity server 4 getting invalid client 

### ISSUE THREAD

**Issue by kotishwerreddy** [aspnet-contrib/AspNet.Security.OAuth.Providers#503]
![image](https://user-images.githubusercontent.com/42269745/100498915-9f6f0380-318b-11eb-9310-a43723e25ba9.png)

Added below code (AspNet.Security.OAuth.Providers - 2.2.0)

 .AddApple(options =>
            {
                options.SignInScheme = IdentityServer4.IdentityServerConstants.ExternalCookieAuthenticationScheme;
                options.ClientId = "com.XXXXXXX.emed";
                options.KeyId = "28XXXXX4D";
                options.TeamId = "56VXXXXXG2";
                options.GenerateClientSecret = true;               
                options.UsePrivateKey((keyId) => HostingEnvironment.ContentRootFileProvider.GetFileInfo($"AuthKey_{keyId}.p8"));
            })

**Comment by martincostello** [comment]
Based on that information my only suggestion is that you've somehow misconfigured the provider, such as a copy-paste error of an ID, or maybe an issue with your p8 file.

Otherwise the manner you're configuring it seems correct in so far as the Apple provider itself (can't see your overall auth config).

.NET 2.2 is out of support, so if your configuration is 100% definitely correct, I can only suggest using the 3.1 or 5.0 providers with a newer ASP.NET Core version to rule out it being some edge-case bug that has since been fixed.

**Comment by kotishwerreddy** [comment]
public void ConfigureServices(IServiceCollection services)
        {

            services.AddCors(options =>
            {
                options.AddPolicy("AllowAll",
                    builder => builder.AllowAnyOrigin()
                    .AllowAnyMethod()
                    .AllowAnyHeader()
                    .AllowAnyOrigin()
                    .DisallowCredentials()
                    .AllowCredentials()
                    );
            });

            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("AConnection")));

            services.AddIdentity<ApplicationUser, IdentityRole>(options =>
            {
                options.Tokens.ChangePhoneNumberTokenProvider = "Phone";
                options.Password.RequiredLength = 8; // personally i'd prefer to see 10+
                options.Password.RequiredUniqueChars = 0;
                options.Password.RequireDigit = false;
                options.Password.RequireLowercase = false;
                options.Password.RequireUppercase = false;
                options.Password.RequireNonAlphanumeric = false;
            })
            .AddEntityFrameworkStores<ApplicationDbContext>()
            .AddDefaultTokenProviders();

            services.AddTransient<IEmailSender, EmailSender>();

            //services.AddAuthentication()
            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = "cookie";
                options.DefaultChallengeScheme = "apple";
            })
               .AddCookie("cookie")


       .AddFacebook("Facebook", facebookOptions =>
        {
            facebookOptions.SignInScheme = IdentityServer4.IdentityServerConstants.ExternalCookieAuthenticationScheme;
            facebookOptions.AppId = "XXXXX";
            facebookOptions.AppSecret = "XXXXXXX";

        })


            .AddApple(options =>
            {
                options.SignInScheme = IdentityServer4.IdentityServerConstants.ExternalCookieAuthenticationScheme;
                options.ClientId = "com.emedevents.emed";
                options.KeyId = "XXXXXX";
                options.TeamId = "XXXXXXX";
                options.GenerateClientSecret = true;
                options.UsePrivateKey((keyId) => HostingEnvironment.ContentRootFileProvider.GetFileInfo($"AuthKey_{keyId}.p8"));
            })



                .AddOpenIdConnect("apple", async options =>
                {
                    options.ResponseType = "code";
                    options.SignInScheme = "cookie";
                    options.DisableTelemetry = true;
                    options.Scope.Clear(); // otherwise I had consent request issues

                    options.Configuration = new OpenIdConnectConfiguration
                    {
                        AuthorizationEndpoint = "https://appleid.apple.com/auth/authorize",
                        TokenEndpoint = "https://appleid.apple.com/auth/token",
                    };

                    options.ClientId = "com.emedevents.emed"; // Service ID
                    options.CallbackPath = "/signin-apple"; // corresponding to our redirect URI

                    options.Events.OnAuthorizationCodeReceived = context =>
                    {
                        context.TokenEndpointRequest.ClientSecret = TokenGenerator.CreateNewToken();
                        return Task.CompletedTask;
                    };

                    // Expected identity token iss value
                    options.TokenValidationParameters.ValidIssuer = "https://appleid.apple.com";

                    // Expected identity token signing key
                    var jwks = await new HttpClient().GetStringAsync("https://appleid.apple.com/auth/keys");
                    options.TokenValidationParameters.IssuerSigningKey = new JsonWebKeySet(jwks).Keys.FirstOrDefault();

                    // Disable nonce validation (not supported by Apple)
                    options.ProtocolValidator.RequireNonce = false;
                })        




            .AddLinkedIn(options =>
            {
                options.ClientId = "XXXXXXX";
                options.ClientSecret = "XXXXXX";
                options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
            });


            services.AddMvc();

            var cert = new X509Certificate2(System.IO.File.ReadAllBytes("idsrv3test.pfx")
                                   , "idsrv3test"
                                   , X509KeyStorageFlags.MachineKeySet |
                                     X509KeyStorageFlags.PersistKeySet |
                                     X509KeyStorageFlags.Exportable);

            //var cert=  LoadCertificate(Convert.ToBoolean(Configuration.GetValue<bool>("IsLocalCertificate")));
            services.AddIdentityServer()
                        .AddSigningCredential(cert)
                        .AddInMemoryPersistedGrants()
                        .AddInMemoryIdentityResources(Config.GetIdentityResources())
                        .AddInMemoryApiResources(Config.GetApiResources())
                        .AddInMemoryClients(Config.GetClients())
                        .AddAspNetIdentity<ApplicationUser>();

            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info { Title = "SAAS Cloud Based Application", Version = "Beta" });
            });

            X509Certificate2 LoadCertificate(bool isLocal)
            {
                X509Certificate2 certs = null;
                if (isLocal)
                {
                    certs = new X509Certificate2(string.Format(@"{0}\bin\idsrv3test.pfx", AppDomain.CurrentDomain.BaseDirectory), "idsrv3test");
                }
                else
                {
                    X509Store certStore = new X509Store(StoreName.My, StoreLocation.CurrentUser);
                    certStore.Open(OpenFlags.ReadOnly);
                    X509Certificate2Collection certCollection = certStore.Certificates.Find(X509FindType.FindByThumbprint, Configuration.GetSection("WEBSITE_LOAD_CERTIFICATES").Value.ToString(), false);
                    if (certCollection.Count > 0)
                    {
                        certs = certCollection[0];
                        certStore.Close();
                        return certs;
                    }
                }
                return certs;
            }
        }


        public static class TokenGenerator
        {
            public static string CreateNewToken()
            {
                const string iss = "56VWA25MG2"; // your accounts team ID found in the dev portal
                const string aud = "https://appleid.apple.com";
                const string sub = "com.emedevents.emed"; // same as client_id

                const string privateKey = "MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQghpdGrK3hR3ELd9YbIG5I83Y4vIPSC9xqLQOcNSgSaBSgCgYIKoZIzj0DAQehRANCAATRr6FA0/XyAI1GU5rf7qYCH7ONMAlyw+d1RalTQ788v50g1/b3YLRagz0NmKBbzcVErRdgQiNuKOaxPXaPFZnq";
                var cngKey = CngKey.Import(Convert.FromBase64String(privateKey), CngKeyBlobFormat.Pkcs8PrivateBlob);

                var handler = new JwtSecurityTokenHandler();
                var token = handler.CreateJwtSecurityToken(
                    issuer: iss,
                    audience: aud,
                    subject: new ClaimsIdentity(new List<Claim> { new Claim("sub", sub) }),
                    expires: DateTime.UtcNow.AddMinutes(5), // expiry can be a maximum of 6 months => generate one per request, or one and then re-use until expiration
                    issuedAt: DateTime.UtcNow,
                    notBefore: DateTime.UtcNow,
                    signingCredentials: new SigningCredentials(new ECDsaSecurityKey(new ECDsaCng(cngKey)), SecurityAlgorithms.EcdsaSha256));

                return handler.WriteToken(token);
            }
        }


        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseCors("AllowAll");
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
                app.UseDatabaseErrorPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            var provider = new FileExtensionContentTypeProvider();
            provider.Mappings[".webmanifest"] = "application/manifest+json";


            app.UseStaticFiles();

            // app.UseAuthentication(); // not needed, since UseIdentityServer adds the authentication middleware
            app.UseIdentityServer();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });

            // Enable middleware to serve generated Swagger as a JSON endpoint.
            app.UseSwagger();

            // Enable middleware to serve swagger-ui (HTML, JS, CSS, etc.), specifying the Swagger JSON endpoint.
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "SAAS Cloud Based Application");
            });
        }
        public class SameCharacterPasswordValidator<TUser> : IPasswordValidator<TUser>
        where TUser : class
        {
            public Task<IdentityResult> ValidateAsync(UserManager<TUser> manager,
                                                      TUser user,
                                                      string password)
            {
                return Task.FromResult(password.Distinct().Count() == 1 ?
                    IdentityResult.Failed(new IdentityError
                    {
                        Code = "SameChar",
                        Description = "Passwords cannot be all the same character."
                    }) :
                    IdentityResult.Success);
            }
        }
    }

**Comment by martincostello** [comment]
It looks like you're mixing the Apple provider with custom OpenID connect code to do the same authentication functions.

As that's nothing to do with the provider in this repo, that's not something we can support you with debugging and trying to get working.

There's a minimal sample application, which works, here you can maybe use a reference to help you get your solution working: https://github.com/martincostello/SignInWithAppleSample

This is unlikely to be a bug in the provider but an issue with your application configuration.

**Comment by kotishwerreddy** [comment]
![image](https://user-images.githubusercontent.com/42269745/100534983-dfd98a80-323a-11eb-8620-a6b81fcac4be.png)




@martincostello : tried multiple ways finally working in local machine.   but when i deployed in VM getting above issue can you please help us.

**Comment by martincostello** [comment]
It's a 500 from your own code. Look at your error logs.
