### ISSUE TITLE
[Question] Callback path not found

### ISSUE THREAD

**Issue by dansiegel** [aspnet-contrib/AspNet.Security.OAuth.Providers#504]
## Description

I have a Blazor WASM .net5 app using AspNet.Security.OAuth.GitHub. Running it locally everything works as expected. When I publish to Azure the authentication fails.

- Initiate Login
- Approve GitHub OAuth App
- Redirect to mydomain.azurewebsites.net/signin-github with token
- Get a page "Sorry, there's nothing at this address."

Watching the log stream I'm not seeing any errors so I'm at a bit of a loss as to how to even begin to debug or fix this...

**Comment by martincostello** [comment]
Can you share some code of how things are set up? We don't have a Blazor sample, and it's not something I've tried myself.

Is the Service Worker associated with the client-side maybe intercepting the URLs to the callback paths and stopping them reaching your server-side code?

**Comment by dansiegel** [comment]
I'll try to get a demo site up either later today or tomorrow
