### ISSUE TITLE
Simplify names

### ISSUE THREAD

**Issue by tparnell8** [aspnet-contrib/AspNet.Security.OAuth.Providers#51]
https://github.com/aspnet/Announcements/issues/67

**Comment by PinpointTownes** [comment]
Reacting to these naming changes is on my todo list :+1: 

That said, I won't align our providers with the new names used by the ASP.NET team for at least 2 reasons:
* This new naming pattern is inconsistent in ASP.NET 5 itself: the OAuth2/OIDC providers have been renamed but the cookies middleware is still named `CookieAuthenticationMiddleware` to avoid type collisions (with the `CookieOptions` in aspnet/HttpAbstractions).
* The risk of having a type collision is too high with these new names: `[Provider]Options` or `[Provider]Extensions` are generic enough to result in weird things if you use a custom client to retrieve data from the provider. I don't want to take this risk.

**Comment by jerriep** [comment]
Yeah, I agree on the risk on name collision being high

**Comment by PinpointTownes** [comment]
Fixed: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/3f58f98b57fae4f1bc37ff51e09f6a08c9b5091e

@jerriep I also fixed the Yeoman generator. Feel free to push a new update when you can :+1:
