### ISSUE TITLE
Native (iOS 13+) Apple SignIn, missing Server Callback

### ISSUE THREAD

**Issue by j-bbr** [aspnet-contrib/AspNet.Security.OAuth.Providers#523]
**Describe the bug**
Using Apple OAuth Provider I want to give authenticated users a self-generated token to access our api 

**Steps To reproduce**
Setup Apple Sigin with the redirect url to our authentication server. Verified that it works when trying to login over the website.

**Expected behaviour**
Once the user authenticates in the app (I am using the basically unchanged Xamarin.Essentials WebAuthenticator Sample) I expect a callback on our backend to generate the token on our side and pass that back to the user. This is tested for other OAuth Providers.

**Actual behaviour**
_A clear and concise description of what actually happened. If an exception occurred, please include a stack trace if available._

User authenticates successfully on the device and receives an Apple ID Token but the server callback is never invoked.

**System information:**
 - OS: [e.g. Windows 10]
 - Library Version [e.g. 2.0.1]
 - .NET version (e.g. output from `dotnet --info`)
.Net Core 5.0 in Linux Docker Container
**Additional context**
_Add any other context about the problem here._

This might be a configuration issue on my side or where additional documentation could be useful. I was under the impression that the server callback configured under the apple id would be invoked for the ios13+ signin process as well. If it doesn't work that way, I maybe need to make an additional call with the Apple Id Token received on the device but I am unsure how I can leverage the already configured Apple OAuth Provider for the authentication then.

**Comment by martincostello** [comment]
If you set `SaveTokens` to `true` on the `AppleAuthenticationOptions` class, then the tokens will be made available as part of the `AuthenticationProperties`. Your server application code can then access token token and do with it as you wish.

This behaviour is inherited in all of our authentication handlers from the `OAuthOptions` class via `RemoteAuthenticationOptions` ([docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.remoteauthenticationoptions.savetokens)).

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/24743fb66bdb350c424e7d7f5e8ed67b3f4a60a1/src/AspNet.Security.OAuth.Apple/AppleAuthenticationHandler.cs#L309-L343

**Comment by j-bbr** [comment]
But the issue I have is that I receive the apple id code and authorization code _just_ on the device (Iphone), I don't quite understand how I can use the above code? At this point my server hasn't been contacted yet. I want to verify on the server that the user has been authenticated by Apple and then let him use our protected resources. My initial assumption was that I would receive the callback on the server but apparently that is not the case. 

My next idea would be to use the authorization code and id_token in a request to our auth server and try to authenticate with the Apple Authentication Handler and grant access in case of success then. I guess I am just a bit unsure whether that's in the scope of this package. If it helps I can contribute to the documentation once that is figured out.

**Comment by martincostello** [comment]
I don't fully understand how our code works in the context of Xamarin (or indeed natively on a device), as the provider is designed for server-side usage using OAuth flow.

It might be something the device does to intercept the call locally on a compatible device to bypass the need to callback to the server. For example if I use Sign In with Apple on a Windows machine, I sign into a webpage, but if I do it on my iPhone it just asks me for Face ID in a native control and I never have to type in any credentials.

We'd welcome updates to the provider documentation to help with this if relevant, but I think this seems to be outside the scope of what the provider here is intended to do?

**Comment by j-bbr** [comment]
I agree that it's probably not in the scope of this package. I think this question might pop up again however since using Apple Sign-In (in the iOS 13+ native way) on iOS devices is, I would imagine, one of the primary use cases of Apple SignIn. I am frankly surprised it hasn't already but I haven't looked too much into the xamarin issues yet. If I do go down the route with the extra request using the authorization code and idtoken from the device I will ask whether a writeup might be relevant for your documentation. Thank you for your help!

**Comment by ugookoro** [comment]
Hello @j-bbr , good day. Are you able to share a snippet of code for the uncovered part of the flow?. I also get the id_token and authorizatioin code from the app, and need to validate that the user was indeed verified on apple's end, and use extract information (name, email perhaps) to give the user access to resources on my server.

**Comment by j-bbr** [comment]
Hi @ugookoro most of the handling is here. You need to generate the Apple Client secret like in the Apple OAuth Provider Code. Make a request to apple servers with the authorization code you got on the client and then you can verify and extract info from the claims with the method below
```
private async Task<Claim[]> VerifyAppleIdToken(string token)
        {
            var tokenHandler = new JwtSecurityTokenHandler();
            var deserializedToken = tokenHandler.ReadJwtToken(token);
            var claims = deserializedToken.Claims.ToArray();

            var expClaim = claims.FirstOrDefault(x => x.Type == AppleConstants.Expiration)?.Value;
            if (expClaim is null || !long.TryParse(expClaim, out var unixSeconds))
                throw new SecurityTokenException($"Token doesn't include valid {AppleConstants.Expiration} Claim");
            var expirationTime = DateTimeOffset.FromUnixTimeSeconds(unixSeconds).DateTime;

            if (expirationTime < DateTime.UtcNow)
                throw new SecurityTokenExpiredException("Expired token");

            var applePublicKeys = await _userValidatorClient.RetrieveKey();
            if (!applePublicKeys.IsSuccessStatusCode)
                throw new InvalidOperationException("Apple Public Key Endpoint isn't reachable");
            var keySet = new JsonWebKeySet(applePublicKeys.Content);

            SecurityKey publicKey = keySet.Keys.FirstOrDefault(x => x.Kid == deserializedToken.Header.Kid);

            var validationParameters = new TokenValidationParameters
            {
                ValidIssuer = _options.AuthenticationBaseAddress,
                IssuerSigningKey = publicKey,
                ValidAudience = _options.ClientId
            };
            tokenHandler.ValidateToken(token, validationParameters, out var validatedToken);

            return claims;
        }
    }
```
