### ISSUE TITLE
Apple Signin Documentation

### ISSUE THREAD

**Issue by j-bbr** [aspnet-contrib/AspNet.Security.OAuth.Providers#525]
**Is your feature request related to a problem? Please describe.**
There are two ways of authenticating an app with Apple, OAuth and the iOS "native" signin workflow. The first one is covered by the Apple OAuth Package, the second is not really addressed here.

**Describe the solution you'd like**
An update to the OAuth2 Apple documentation or integration of code handling the iOS Apple Signin Workflow

**Describe alternatives you've considered**
I've implemented handling of the iOS Signin Workflow in my ASP.Net Core Program and could create a separate repository for that but I would say 80-90 % of the code would be the same than in the Apple OAuth Package (generating client secret, validating tokens)

**Additional context**

The sequence of native iOS Apple Signin workflow is as follows:

1. Receive Authorization Code within App
2. Send Authorization Code to own servers
3. Generate or retrieve cached client secret 
4. Send client secret, client id and authorization code to [Apple Endpoint](https://developer.apple.com/documentation/sign_in_with_apple/generate_and_validate_tokens)
5. Retrieve idtoken, validate token and parse claims for user user information

The parts not covered by the Apple OAuth are sending the request with authorization code and extracting the claims but that would be a very small code addition, however it is true that is not really OAuth related. I am open to adding to the documentation or providing the code supporting the native signin workflow but since it might be out of scope I wanted to ask before creating a pull request. I created an issue #523 for this a few days ago as well

**Comment by martincostello** [comment]
I think this would be a good addition to the documentation.

You could include a code sample for it in the markdown, but I don't think we'd want the feature creep of including it in the provider itself as it's outside the scope of the OAuth flow that the providers are designed for.
