### ISSUE TITLE
Untappd not working

### ISSUE THREAD

**Issue by PatGet** [aspnet-contrib/AspNet.Security.OAuth.Providers#529]
AspNet.Security.OAuth.Untappd is not working.
Reason seems to be that ExchangeCodeAsync needs to work slightly different.
The request needs to be HttpMethod.Get instead of Post and the parameters need to be transmitted as a QueryString according to https://untappd.com/api/docs#authentication

I add this issue and have a PR ready where I will link to this issue.

**Comment by martincostello** [comment]
Fix is now available from [NuGet.org](https://www.nuget.org/packages/AspNet.Security.OAuth.Untappd/5.0.3) - thanks again 🎈
