### ISSUE TITLE
Get users ID on Discord Auth?

### ISSUE THREAD

**Issue by bopsees** [aspnet-contrib/AspNet.Security.OAuth.Providers#534]
I'm having issues finding a way to get the Users ID after auth, I can get their name fine but can't seem to find any parameter for user ID. I looked through the source and I find something about ID but still can't seem to find how to implement.

Please help.

**Comment by martincostello** [comment]
If you configure an event handler on `DiscordOptions` (I forget which one exactly without looking at Intellisense in VS, `OnCreatingTicket` maybe) you can inspect the raw JSON payload from Discord to see if the user Id is in it. If it is, then you can just configure an additional claims mapping on the options for it.

**Comment by bopsees** [comment]
Ah ok, I'll try that out soon. Thanks for the help.

**Comment by bopsees** [comment]
Hello, I've got the ticket setup (it kind of works) but I'm not sure how to get the payload from Discord via this ticket (I can get other stuff like the access token but can't seem to work out how the Response method works). Is there any conversion I need to do, or will I need to write my own part of this with HTTP requests using the access token?

**Comment by martincostello** [comment]
If the user ID isn't available from the [`User`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.oauth.oauthcreatingticketcontext.user) property when the event is fired here, then you'll need to use the token to call the API to get it yourself.

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/b2f3dcc725244cad9f1ac0b41ae15be2ffa13ee8/src/AspNet.Security.OAuth.Discord/DiscordAuthenticationHandler.cs#L76

**Comment by bopsees** [comment]
Yeah it's not available, I've written code before to contact the API with the token in JS (like 2 years ago), I'll look at that and implement it similarly in C#. Thanks for the help though, greatly appreciated!
