### ISSUE TITLE
Add claim?

### ISSUE THREAD

**Issue by bopsees** [aspnet-contrib/AspNet.Security.OAuth.Providers#535]
During a previous issue I was asked about making a new claim if something was appearing, at the time I thought it wasn't being sent in the raw payload, but on further inspection it was and now I'm confused on how to make a claim in the 'OnCreatingTicket' method.

**Comment by martincostello** [comment]
If you need to map an additional claim, then you can just add some custom mappings to the options when you configure the provider. You can see how the options class does this itself for various claims out-of-the-box:

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/b2f3dcc725244cad9f1ac0b41ae15be2ffa13ee8/src/AspNet.Security.OAuth.Discord/DiscordAuthenticationOptions.cs#L50-L61

**Comment by bopsees** [comment]
How would I map this claim's parameters, like MapJsonKey("id", idValue)?

**Comment by martincostello** [comment]
```csharp
.AddDiscord(options =>
{
    options.ConsumerKey = Configuration["ConsumerKey"];
    options.ConsumerSecret = Configuration["ConsumerSecret"];
    options.ClaimActions.MapJsonKey("the name you want for the claim", "the name of the property containing value to map to the claim");
})
```

**Comment by bopsees** [comment]
Thanks! I'll try that now.

**Comment by bopsees** [comment]
From what I've just attempted, is it MapJsonKey("UserID", "id")?

id is the value returned from the raw payload, is this correct as I'm unable to access the claim from the User property

**Comment by martincostello** [comment]
I don't know - can you show what the raw JSON payload you're trying to get the value from looks like?

If it is "id", then you don't need a custom mapping as the provider already maps it:

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/b2f3dcc725244cad9f1ac0b41ae15be2ffa13ee8/src/AspNet.Security.OAuth.Discord/DiscordAuthenticationOptions.cs#L50

Unless you want to give it a different name ("UserID") as an effectively duplicated claim, then you can access it by using the `ClaimTypes.NameIdentifier` constant to get the ID from the claims once the user has signed in.

**Comment by bopsees** [comment]
{"id": "ID", "username": "username", "avatar": "avatar", "discriminator": "5228", "public_flags": 64, "flags": 64, "locale": "en-GB", "mfa_enabled": true, "email": "email", "verified":
true}

**Comment by martincostello** [comment]
Right, so either it's already available without you doing anything by using `ClaimTypes.NameIdentifier` to get it from the claims in your application code, or you can add it _again_ by adding:

```csharp
options.ClaimActions.MapJsonKey("UserID", "id");
```

**Comment by bopsees** [comment]
And if I was to add it via MapJsonKey would it be accessible by doing User.Identity.UserID?

**Comment by martincostello** [comment]
No - in either case, you would query the claims of the user, such as like this:

```csharp
string? userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
```

There's no such property as `UserID` on the [`IIdentity` interface](https://docs.microsoft.com/en-us/dotnet/api/system.security.principal.iidentity?view=net-5.0), which is the return type of the [`Identity` property of the `ClaimsPrincipal` class](https://docs.microsoft.com/en-us/dotnet/api/system.security.claims.claimsprincipal.identity).

**Comment by bopsees** [comment]
Thanks!

After running with this in place, the ID came back without issue. Thanks for the help again!
