### ISSUE TITLE
Visual Studio Will not refresh the token

### ISSUE THREAD

**Issue by jamierytlewski** [aspnet-contrib/AspNet.Security.OAuth.Providers#538]
**Describe the bug**
Everything works great for the first hour, then the token expires and the token will not refresh.

**Steps To reproduce**
Setup a VS OAuth setup, wait an hour and see the token will not refresh.

**Expected behaviour**
Expecting when the token is expired to refresh.

**Actual behaviour**
Token does not refresh

**System information:**
 - OS: Windows 10
 - Library Version 5.0.4
 - .NET version 5.0

**Additional context**
I try to use HttpContext.ChallengeAsync and it won't either. The issue is that VS is returning a 203 instead of a 401 and with the 203 it's not in the proper JSON format.

**Comment by kevinchalet** [comment]
It’s the expected behavior: none of the OAuth 2.0 providers - developed by MSFT or the community - handle the refresh part for you. It’s something you’ll have to do yourself.

**Comment by jamierytlewski** [comment]
@kevinchalet - Thanks for the quick response, what is a good way to handle this? That's where I've been struggling?

**Comment by kevinchalet** [comment]
When using ASP.NET Core Identity, the tokens - including the refresh tokens - can be stored and retrieved using the UserManager. You can then use an OAuth 2.0 client like IdentityModel to make the refresh dance.
