### ISSUE TITLE
MetaMask Provider Please. :) :) :)

### ISSUE THREAD

**Issue by Mike-E-angelo** [aspnet-contrib/AspNet.Security.OAuth.Providers#541]
**Is your feature request related to a problem? Please describe.**

As a cryptocurrency user, I want to connect to an ASP.NET Core website with my [MetaMask Wallet](https://metamask.io/) where my identity is my selected Wallet Address.

**Describe the solution you'd like**

User signs into the MetaMask wallet, and is then signed into the ASP.NET Core website.

**Describe alternatives you've considered**

Building it myself, but that looks like a lot of work. 😁

**Additional context**

Thank you for any consideration.  Also, I am so very happy to see [PayPal authentication support](https://www.nuget.org/packages/AspNet.Security.OAuth.Paypal/) created by you all here.  That will save me a lot of time/headache. 👍

**Comment by juanfranblanco** [comment]
@Mike-E-angelo Nethereum provides an integration with Metamask, now this is specific to Blazor as it requires the interop with the browser extension, working both server side and wasm side. https://github.com/Nethereum/Nethereum.Metamask.Blazor
It provides already a way to validate and existing user, making a signing challenge.

What is missing part of the signing process is to create a custom auth provider as in here. https://codewithmukesh.com/blog/authentication-in-blazor-webassembly/ 

The address validation and authentication is done already for you, now how you map that user to an existing user or new depends how you store them internally in your database and what claims can you attach to them, hence having a custom provider depending on the use case might make sense.

**Comment by Mike-E-angelo** [comment]
Thank you for the context @juanfranblanco.  That looks very close to the experience, thank you for sharing.  So it would seem all that is required for this External Login provider (assuming the Nethereum work is leveraged 😁) is to enable a dedicated page where it can send the sign-in challenge, then upon success, it redirects to a `https://server.com/signin-metamask` page, where it then again redirects back to the original requesting resource (following the other External Login workflows).

**Comment by juanfranblanco** [comment]
@Mike-E-angelo Apologies, i missed your response. Metamask is an extension, so the workflow of redirecting to a page will be unnecessary, and strange UX for current users. The normal process will be to click authenticate with metamask, and handle the process on the same page, as you interact with the extension. As you know users may have different accounts / addresses, so it is common for a user change their current address in a session, and you may want to connect multiple accounts to a user, or bundle them.

**Comment by Mike-E-angelo** [comment]
Doh that is so very true @juanfranblanco.  After having implemented PayPal, there are token endpoints, authorization endpoints, and user information endpoints that are configured by the identity SDK.  MetaMask has none of those entities, as everything is performed on the local browser.

I will have to think about this some more, but it appears that this is the wrong ask for this repository.

**Comment by juanfranblanco** [comment]
Yes you just need the signed message and recover the account, something to tell you what account is selected by the extension to prove it owns the key. In a way is much simpler. The flow, send request to sign message, retrieve signature, recover account from signature, then your flow, create or retrieve user from your db (custom auth), then assign claims.
