### ISSUE TITLE
Coinbase OAuth Provider Support

### ISSUE THREAD

**Issue by Mike-E-angelo** [aspnet-contrib/AspNet.Security.OAuth.Providers#544]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Coinbase offers [an Oauth2 API](https://developers.coinbase.com/api/v2#oauth2-coinbase-connect) and it would be super appreciated to have it integrated with this project.

**Describe alternatives you've considered**
Not really an alternative, but some work around this has been done via @bchavez's great https://github.com/bchavez/Coinbase implementation.

**Additional context**
Thank you for any consideration and all your great work out there. 👍

**Comment by levimatheri** [comment]
I'd like to take this up, thanks!

**Comment by Mike-E-angelo** [comment]
Fantastic!  Thank you so much for all your work out there, @levimatheri, @martincostello, and team!  It is very much appreciated. 🙏

**Comment by martincostello** [comment]
The provider is now available from [NuGet.org](https://www.nuget.org/packages/AspNet.Security.OAuth.Coinbase/) - thanks again for your contributions.
