### ISSUE TITLE
GitLab Provider broken

### ISSUE THREAD

**Issue by S0PEX** [aspnet-contrib/AspNet.Security.OAuth.Providers#545]
**Describe the bug**
When using `AspNet.Security.OAuth.GitLab` the sign-in middleware is broken and results in 
```
Exception: Correlation failed.
Unknown location

Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
```

Another issue is that the default `Scope` is outdated as GitLab only allows these scopes:
`api, read_user, read_api, read_repository...` and therefore the default `openid profile email` are unsupported and should be replaced with `read_user`.

When the scope are correctly set to `read_user` the redirect to GitLab works fine but when allowed and redirected to the fallback url `/signin-gitlab` route fails with an exception.

**Steps To reproduce**
Register GitLab Provider and try to login.
```c#
       services.AddAuthentication(options =>
                {
                    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                }).AddGitLab(options =>
                {
                    options.ClientId = Configuration["Gitlab:ClientId"];
                    options.ClientSecret = Configuration["Gitlab:ClientSecret"];
                    options.Scope.Clear();
                    options.Scope.Add("read_user");
                }).AddCookie();
```

**Expected behaviour**
GitLab fallbacks to `/signin-gitlab` after login which parses the data and successfully authenticates user.

**Actual behaviour**
When redirected to `/signin-gitlab` an exception is thrown.
```
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Correlation failed.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**System information:**
- OS Name:     pop
- OS Version:  20.10
- OS Platform: Linux
- .NET SDKs installed: 5.0.203
- .NET runtimes installed:
	- Microsoft.AspNetCore.App 5.0.6
  	- Microsoft.NETCore.App 5.0.6

Regards Artur

**Comment by martincostello** [comment]
"Correlation failed" is usually an issue with cookies not being stored correctly for the correlation state sent to the remote provider to be able to be checked against the value stored in the cookie for the client.

Check that the correlation cookie is being stored correctly before the browser redirects to GitLab and whether the cookie is present when the browser redirects back to your site.

You should also increase the logging level to debug for the Microsoft authentication components to see what's going on under the hood, which should give you more context on exactly why the correlation is failing.

**Comment by S0PEX** [comment]
Thanks for the fast response.
You were right. It looks like the cookie isn't set correctly as indicated in the log.
` '.AspNetCore.Correlation.chzIOAenxw803HL9LjhM_7hBuFbTKNPvY1b2rsm9cNI' cookie not found.`

I have fixed this issue by setting the same site to `Unspecified`.
This is the working code, if somebody runs into the same error.

```c#
services.AddAuthentication(options => options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme)
            .AddGitLab(options =>
            {
                options.ClientId = Configuration["Gitlab:ClientId"];
                options.ClientSecret = Configuration["Gitlab:ClientSecret"];
                /*options.AuthorizationEndpoint = $"{Configuration["Gitlab:Endpoint"]}/oauth/authorize";
                options.TokenEndpoint = $"{Configuration["Gitlab:Endpoint"]}/oauth/token";
                options.UserInformationEndpoint = $"{Configuration["Gitlab:Endpoint"]}/api/v4/user";*/
                options.Scope.Clear();
                options.Scope.Add("read_user");
                options.CorrelationCookie.SameSite = SameSiteMode.Unspecified;
            })
```

Is there a nicer way of fixing the scope issue as `openid profile email` are not supported ?
As this looks awe-full:
```c#
options.Scope.Clear();
options.Scope.Add("read_user");
```

**Comment by martincostello** [comment]
> Is there a nicer way of fixing the scope issue as `openid profile email` are not supported ?
> As this looks awe-full:
> 
> ```cs
> options.Scope.Clear();
> options.Scope.Add("read_user");
> ```

If you'd like to submit a Pull Request to change the default scopes to just `read_user`, we can include it in the next release of the provider. Then after updating to that newer version you could remove your workaround.

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/dad5906d49eea20886aa35fada099ad8c5043221/src/AspNet.Security.OAuth.GitLab/GitLabAuthenticationOptions.cs#L29-L32
