### ISSUE TITLE
AspNet.Security.OAuth.Apple should save id_token

### ISSUE THREAD

**Issue by baptiste-nv** [aspnet-contrib/AspNet.Security.OAuth.Providers#556]
**Is your feature request related to a problem? Please describe.**
Currently, Apple Sign In access_token is not used anywhere, and only id_token can be validated Apple side. Even if it's done in the library, we may have some architecture pattern where we need to distinguish authentication itself and token validation, so the module should save id_token along with the others tokens

**Describe the solution you'd like**
AppleAuthenticationHandler should save id_token in HandleRemoteAuthenticateAsync()

**Describe alternatives you've considered**
No valid workaround found so far

**Additional context**
N/A

**Comment by martincostello** [comment]
The [`SaveToken`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.remoteauthenticationoptions.savetokens) property on the `AppleAuthenticationHandler` class (which is available for all our providers as they are derived from `RemoteAuthenticationOptions` where it is defined) can be set to `true` to save the token into the claims.

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/0d9f3f21a7561d258b37ceece293df6ed57fc21b/src/AspNet.Security.OAuth.Apple/AppleAuthenticationHandler.cs#L309-L343

**Comment by baptiste-nv** [comment]
Hi @martincostello 

Yes, it's already done on our side.
However, the id_token is not saved in that method, only access_token/refresh_token are.

**Comment by martincostello** [comment]
I'm not entirely sure whether we should or shouldn't store it, but if we were to it would be a trivial change.

For now, you can access the token by using either the `CreatingTicket` event and grabbing it from the context passed to that event.

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/0d9f3f21a7561d258b37ceece293df6ed57fc21b/src/AspNet.Security.OAuth.Apple/AppleAuthenticationHandler.cs#L114

via `context.User.RootElement.GetString("id_token")`, or the `ValidateIdToken` event:

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/0d9f3f21a7561d258b37ceece293df6ed57fc21b/src/AspNet.Security.OAuth.Apple/AppleAuthenticationHandler.cs#L99

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/783757446023d78c253758fd8b879cd8a64c0e0c/src/AspNet.Security.OAuth.Apple/AppleValidateIdTokenContext.cs#L33

**Comment by baptiste-nv** [comment]
Hi @martincostello 

Thank you for your answer, I will test it right away.
I still do think that we should save it, as it's a commonly used token. And starting iOS 13, we can (must) use iOS native authentication that return an ID token. We could then have the same behavior for both OS based and server based authentication. 

Thanks again!

**Comment by baptiste-nv** [comment]
The given workaround work well:
```
options.Events.OnCreatingTicket += OnCreatingTicket;
```
and
```
private static async Task OnCreatingTicket(OAuthCreatingTicketContext context)
{
     var idToken = context.User.GetProperty("id_token").GetString();
     if (!string.IsNullOrWhiteSpace(idToken))
     {
          context.Properties.Items.Add(new KeyValuePair<string, string>("id_token", idToken));
     }
}
```
Thanks again @martincostello

**Comment by martincostello** [comment]
If you'd like to use this change before 5.0.6 is released to NuGet.org, a prerelease version containing the fix can be obtained from our [MyGet feed](https://www.myget.org/feed/aspnet-contrib/package/nuget/AspNet.Security.OAuth.Apple/5.0.6-preview.21304.57).

**Comment by martincostello** [comment]
This fix has now been published to [NuGet.org](https://www.nuget.org/packages/AspNet.Security.OAuth.Apple/5.0.6).
