### ISSUE TITLE
Wrong redirect url to alipay

### ISSUE THREAD

**Issue by hzexe** [aspnet-contrib/AspNet.Security.OAuth.Providers#565]
**Describe the bug**
The client_id shoud be named app_id in the url redirect to alipay.

**Steps To reproduce**
Docs  at
[https://opendocs.alipay.com/open/284/web#URL%20%E6%8B%BC%E6%8E%A5%E8%A7%84%E5%88%99](https://opendocs.alipay.com/open/284/web#URL%20%E6%8B%BC%E6%8E%A5%E8%A7%84%E5%88%99)
and
[https://opendocs.alipay.com/support/01rg6a?ant_source=opendoc_recommend#%E7%94%B5%E8%84%91%E7%BD%91%E7%AB%99%E6%94%AF%E4%BB%98%E5%AE%9D%E7%99%BB%E5%BD%95](https://opendocs.alipay.com/support/01rg6a?ant_source=opendoc_recommend#%E7%94%B5%E8%84%91%E7%BD%91%E7%AB%99%E6%94%AF%E4%BB%98%E5%AE%9D%E7%99%BB%E5%BD%95)

**Expected behaviour**
_A clear and concise description of what you expected to happen._

**Actual behaviour**
_A clear and concise description of what actually happened. If an exception occurred, please include a stack trace if available._

**System information:**
 - OS: debian 9
 - Library Version 5.0.6
 - .NET version net5.0

**Additional context**
Not good idea, but the overload BuildChallengeUrl function in AlipayAuthenticationHandler can work:
```csharp
protected override string BuildChallengeUrl(AuthenticationProperties properties, string redirectUri)
        {
            string url = base.BuildChallengeUrl(properties, redirectUri);
            url += "&app_id=" + Options.ClientId;
            return url;
        }
```

**Comment by LeaFrock** [comment]
[Here](https://github.com/dotnet/aspnetcore/blob/release/5.0/src/Security/Authentication/OAuth/src/OAuthHandler.cs#L299)  in `OAuthHandler.BuildChallengeUrl()` can explain this wrong problem.

There're two ways to fix it.
The first is yours, but you needn't concat strings by self.
``` csharp
        /// <inheritdoc />
        protected override string BuildChallengeUrl(
            [NotNull] AuthenticationProperties properties,
            [NotNull] string redirectUri)
        {
            string challengeUrl = base.BuildChallengeUrl(properties, redirectUri);

            // Add app_id with the same value of client_id
            return QueryHelpers.AddQueryString(challengeUrl, "app_id", Options.ClientId);
        }
```
The other is totally overridding the virtual method. This way should generate the 'standard' url of Alipay doc even though it adds more code lines.
``` csharp
        /// <inheritdoc />
        protected override string BuildChallengeUrl(AuthenticationProperties properties, string redirectUri)
        {
            var scopeParameter = properties.GetParameter<ICollection<string>>(OAuthChallengeProperties.ScopeKey);
            var scope = scopeParameter != null ? FormatScope(scopeParameter) : FormatScope();

            var parameters = new Dictionary<string, string>
            {
                { "app_id", Options.ClientId }, // Replace "client_id"
                { "scope", scope },
                { "response_type", "code" },
                { "redirect_uri", redirectUri },
            };

            if (Options.UsePkce)
            {
                var bytes = new byte[32];
                RandomNumberGenerator.Fill(bytes);
                var codeVerifier = Microsoft.AspNetCore.Authentication.Base64UrlTextEncoder.Encode(bytes);

                // Store this for use during the code redemption.
                properties.Items.Add(OAuthConstants.CodeVerifierKey, codeVerifier);

                var challengeBytes = SHA256.HashData(Encoding.UTF8.GetBytes(codeVerifier));
                var codeChallenge = WebEncoders.Base64UrlEncode(challengeBytes);

                parameters[OAuthConstants.CodeChallengeKey] = codeChallenge;
                parameters[OAuthConstants.CodeChallengeMethodKey] = OAuthConstants.CodeChallengeMethodS256;
            }

            parameters["state"] = Options.StateDataFormat.Protect(properties);

            return QueryHelpers.AddQueryString(Options.AuthorizationEndpoint, parameters!);
        }
```

Since currently I'm not able to test it on Linux OS, would you please test both of the ways on your machine and then make a PR to fix the problem? If you have any questions, you can mention me at this issue.

p.s. This provider takes reference of this [doc](https://opendocs.alipay.com/apis/api_9/alipay.system.oauth.token).

**Comment by hzexe** [comment]
> Since currently I'm not able to test it on Linux OS, would you please test both of the ways on your machine and then make a PR to fix the problem? If you have any questions, you can mention me at this issue.



Both of the ways tested pass before make the PR #566

**Comment by martincostello** [comment]
Thanks for the fix - if you could validate it with the real Alipay service using [`5.0.7-preview.21309.48`](https://www.myget.org/feed/aspnet-contrib/package/nuget/AspNet.Security.OAuth.Alipay/5.0.7-preview.21309.48) from our MyGet feed, then if all good I'll push out 5.0.7 to NuGet.org later today.

**Comment by martincostello** [comment]
Hi @hzexe - did you have a chance to validate the fix?

**Comment by LeaFrock** [comment]
@martincostello All Chineses are celebrating the Dragonboat Festival (14 June) holiday of 3 days. So maybe we have to wait for several days.

@hzexe I'm not disturbing you, just hope that you can test the preview package on Linux OS to ensure this issue totally fixed. If it's OK, the 5.0.7 will be released soon. Thanks in advance!

**Comment by martincostello** [comment]
Thanks for the info @LeaFrock - I wasn't aware of that. Enjoy!

**Comment by martincostello** [comment]
Hi @hzexe - have you been able to validate your fix yet?

**Comment by hzexe** [comment]
> Thanks for the fix - if you could validate it with the real Alipay service using [`5.0.7-preview.21309.48`](https://www.myget.org/feed/aspnet-contrib/package/nuget/AspNet.Security.OAuth.Alipay/5.0.7-preview.21309.48) from our MyGet feed, then if all good I'll push out 5.0.7 to NuGet.org later today.

@martincostello I'm sorry I haven't read email lately.But the build 5.0.7-preview.21309.48 not exist,maybe deleted.
Rebuild a new preview version for net5 please?

**Comment by martincostello** [comment]
@hzexe Here you go: https://www.myget.org/feed/aspnet-contrib/package/nuget/AspNet.Security.OAuth.Alipay/5.0.7-preview.21320.37

**Comment by hzexe** [comment]
@martincostello 
I have test pass the version with real alipay account. 
System information:
Debian 10 (buster)  4.19.146-1 (2020-09-17) x86_64
net5.0 and Microsoft.AspNetCore.Identity.UI 5.0.7
AspNet.Security.OAuth.Alipay 5.0.7-preview.21320.37

**Comment by martincostello** [comment]
Great, thanks for testing.

I'll push the fix to NuGet later today.

**Comment by martincostello** [comment]
The fix is now available from [NuGet.org](https://www.nuget.org/packages/AspNet.Security.OAuth.Alipay/5.0.7) - thanks again 👍
