### ISSUE TITLE
Mixcloud Support

### ISSUE THREAD

**Issue by Mike-E-angelo** [aspnet-contrib/AspNet.Security.OAuth.Providers#568]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Last one, I swear. 😁  After the successful implementation of #544, there is one last provider that I would like to see implemented, and that is Mixcloud:
https://www.mixcloud.com/developers/#authorization

**Describe alternatives you've considered**
You already have SoundCloud (which is fantastic!), and I have some potential customers that use/prefer Mixcloud as well.  It would be great to allow them access via your terrific integration work here.

**Additional context**
Thank you again for all your impressive and diligent work over there. 🙏

**Comment by kevinchalet** [comment]
We typically rely on contributions when it comes to adding new providers. Would you be interested in submitting a PR to add Mixcloud support?

**Comment by Mike-E-angelo** [comment]
Heck yeah, @kevinchalet!  Apologies for using you all as a magic genie. 😁😇  I did take a look at the soundcloud implementation and feel that I can start from there.  Let me see if I can get something for you here in the next week or so.

FWIW/BTW, Soundcloud is no longer creating new applications for their platform.  That is, when attempting to create an application this morning, this is what I was met with:
https://docs.google.com/forms/d/e/1FAIpQLSfNxc82RJuzC0DnISat7n4H-G7IsPQIdaMpe202iiHZEoso9w/closedform

**Comment by martincostello** [comment]
The Mixcloud provider is now available from [NuGet.org](https://www.nuget.org/packages/AspNet.Security.OAuth.Mixcloud/5.0.7) - thanks again for your contribution 🥳
