### ISSUE TITLE
How can AccessToken be retrieved post authentication success with LinkedIn Provider?

### ISSUE THREAD

**Issue by pkskelly** [aspnet-contrib/AspNet.Security.OAuth.Providers#580]
## Issue Description

Using the LinkedIn Provider, I can authenticate a user, but cannot get access or refresh tokens. I am using the ```SaveTokens  = true``` option when configuring but it does not seem to persist the AccessToken.  All documentation I can find indicate that the tokens should exist and be persisted.  But I feel like something has changed and I may be missing something. 

## Steps To reproduce

- Created ASP.NET Core MVC project with `--auth Individual` 
- Added nuget package (5.0.8) for AspNet.Security.OAuth.LinkedIn 
- Configured the provider using

```
                .AddLinkedIn(options =>
                {
                    options.ClientId = Configuration["LinkedIn:ClientId"];
                    options.ClientSecret = Configuration["LinkedIn:ClientSecret"];
                    options.Scope.Add("r_organization_social");
                    options.Scope.Add("w_organization_social");
                    options.Scope.Add("rw_organization_admin");
                    options.SaveTokens = true;                    
                    options.Events = new OAuthEvents
                    {
                        OnCreatingTicket = async context =>
                        {
                                var accessToken = context.AccessToken;   //token is present here when debugging
                                var refreshToken = context.RefreshToken;                          
                    };
                });
 ```
Ran simple test and can authenticate and all claims are filled. The `OnCreatingTicket` delegate is called and the context tokens are available.  However, in other controllers I am unable to use the following to get the access token:

```
 var token = await HttpContext.GetTokenAsync("LinkedIn", "access_token"); 
```

## Expected Behavior

I would  expect that using the code below would  retrieve the token 

```
 var token = await HttpContext.GetTokenAsync("LinkedIn", "access_token"); 
```
 
## Actual Behavior 

Call to above code return `null`

## System information:

 - OS: macOS 11.4 (Big Sur)
 - Library Version 5.0.8
 - .NET version (output from `dotnet --info`)
```
.NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    ef17233f86

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.301/

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  3.1.410 [/usr/local/share/dotnet/sdk]
  5.0.301 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.16 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

## Additional Context 

While digging, I did find the LinkedInAuthenticationHandler.cs file makes a final call to ` return await base.HandleRemoteAuthenticateAsync(); ` and  OAuthHandler looks to still persist the tokens (line 174) but not sure (or cannot find yet) where this gets attached - or if it does any longer - to the HttpContext. 

I added the Microsoft provider and can login fine with that also, but the same behavior is observed.  Really just looking to see if this is see possible using HttpContext.GetTokenAsync() or if I am simply misunderstanding how this should work.

**Comment by martincostello** [comment]
I quickly just tried this with the GitHub provider locally, using `httpContext.GetTokenAsync("GitHub", "access_token")` and I get the access token as expected when I've set `SaveTokens` to `true`.

The [`HttpContext.GetTokensAsync()`](https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Http/Authentication.Abstractions/src/AuthenticationHttpContextExtensions.cs#L202) method is just a convenience for calling the [`IAuthenticationService.GetTokenAsync()`](https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Http/Authentication.Abstractions/src/TokenExtensions.cs#L157) method, which ultimately calls the `AuthenticateAsync()` method and then extracts the token from the authentication properties.

Maybe your sign-in implementation isn't quite working correctly and the claims principal isn't being fully signed-in to your application? That might explain why, as in that scenario I would imagine `AuthenticateAsync()` wouldn't return anything, so you'd end up with `null`.

**Comment by pkskelly** [comment]
Thanks @martincostello!!  

Apologies for what turned out to be a simple fix.  I'll confess I started with a project using `dotnet new mvc --auth Indivdual` and this seems to be related to the problem.  I assume that the issue I am having is related to Microsoft.AspNetCore.Identity.UI components taking control of some of the process (have not and likely will not have time to dig into it).  Is this a likely cause?

Really appreciate you confirming it was a configuration issue.  I backed up and ran the sample then rebuilt an MVC app from scratch with `dotnet new mvc`, no auth setting, added the providers needed,  and everything works great.  I will be writing up a blog post about this and will update in a comment here for others. 

BTW - thanks for your contributions to this project, especially LinkedIn Provider.  This was a lifesaver!

**Comment by pkskelly** [comment]
Thanks again @martincostello!  Blog post for anyone interested can be found here: [https://peteskelly.com/authenticating-linkedin-users-using-asp-net-contrib-oauth-providers/ ](https://peteskelly.com/authenticating-linkedin-users-using-asp-net-contrib-oauth-providers/ )
