### ISSUE TITLE
Why IDE always thrown errors in LineAuthenticationHandler.cs?

### ISSUE THREAD

**Issue by linmasaki** [aspnet-contrib/AspNet.Security.OAuth.Providers#581]
### Provider name
AspNet.Security.OAuth.Line

### Actual behavior
In LineAuthenticationHandler.cs, my IDE(Rider) always thrown errors in this file(see below pic). I checked other provider configurations and no idea what happened?

![Image](https://i.ibb.co/vVKDfTF/2021-07-14-2-58-57.png)

### Expected behavior
In [GitHubAuthenticationHandler.cs ](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/dev/src/AspNet.Security.OAuth.GitHub/GitHubAuthenticationHandler.cs), it looks OK. No errors thrown in IDE.

![Image](https://i.ibb.co/pRMxBBV/2021-07-14-2-57-00.png)

### Additional information

The error description is "The annotation for nullable reference types should only be used in code within a '#nullable' annotations context", I have confirmed the **Nullable** value in the csproj file was enabled.

**Comment by martincostello** [comment]
Rider bug? It's defined in our `Directory.Build.props` file:

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/df24cbf161c57bd49aa76429c441849f193e8ab7/Directory.Build.props#L14

It also works for me in Visual Studio, and works in our continuous integration using the .NET CLI.

**Comment by linmasaki** [comment]
Perhaps you're right. After I updated Rider, the problem disappeared soon.

Thank you for your reply.
