### ISSUE TITLE
Add Zendesk provider

### ISSUE THREAD

**Issue by levimatheri** [aspnet-contrib/AspNet.Security.OAuth.Providers#586]
**Is your feature request related to a problem? Please describe.**
[Zendesk ](https://developer.zendesk.com/documentation/ticketing/working-with-oauth/creating-and-using-oauth-tokens-with-the-api/) uses OAuth 2.0 and I have started to implement it as a provider so that the API can be used simply for authentication in .NET projects.

**Describe the solution you'd like**
Add a new provider for Zendesk.

**Comment by martincostello** [comment]
This provider is now available from NuGet.org: https://www.nuget.org/packages/AspNet.Security.OAuth.Zendesk/5.0.10

Thanks for your contribution @levimatheri 🎉
