### ISSUE TITLE
Discord OAuth Problem while Logging in

### ISSUE THREAD

**Issue by LedgendODST** [aspnet-contrib/AspNet.Security.OAuth.Providers#594]
Hello, 

i've made a ASP MVC Core app on Localhost with Discord 0Auth Login, everything was working fine on it. 
then i wanted to point the app to my Domain, then i started running into errors, and i've been trying to fix this this since 9 Hours now, 

Using Linux on ubuntu 20.04, ASP.NET Core 5, 

Startup.cs
       public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews();

            services.AddAuthentication(options =>
                {
                    options.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                    options.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                })
                .AddCookie()
                .AddJwtBearer(options =>
                {
                    options.TokenValidationParameters = new TokenValidationParameters
                    {
                        ValidateIssuer = false,
                        ValidateAudience = false,
                        ValidateIssuerSigningKey = true,
                        ValidIssuer = Configuration.GetValue<string>("Jwt:Issuer"),
                        ValidAudience = Configuration.GetValue<string>("Jwt:Audience"),
                        IssuerSigningKey =
                            new SymmetricSecurityKey(
                                Encoding.UTF8.GetBytes(Configuration.GetValue<string>("Jwt:EncryptionKey")))
                    };
                })
                .AddDiscord(options =>
                {
                    options.ClientId = Configuration.GetValue<string>("Discord:ClientId");
                    options.ClientSecret = Configuration.GetValue<string>("Discord:ClientSecret");
                    options.AccessDeniedPath = "/Home/DiscordAuthFailed";
                });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseAuthentication();

            app.UseCookiePolicy(new CookiePolicyOptions
            {
                HttpOnly = HttpOnlyPolicy.Always,
                Secure = CookieSecurePolicy.Always,
                MinimumSameSitePolicy = SameSiteMode.Strict
            });
            
            app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
            });
            
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                app.UseHsts();
            }
            //app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapDefaultControllerRoute();
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
            });
        }

Program.cs
        public static void Main(string[] args)
            => CreateHostBuilder(args).Build().Run();

        public static IHostBuilder CreateHostBuilder(string[] args)
            => Host.CreateDefaultBuilder(args)

                //.ConfigureServices((cotnext, services) => 
                  //  services.AddDbContext<iDFContext>())
                
                .ConfigureDiscordBot((context, bot) =>
                {
                    bot.Token = context.Configuration.GetValue<string>("Bot:Token");
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseUrls("http://localhost:5000");
                    webBuilder.UseStartup<Startup>();
                });

Pictures :
![39RyhfMV](https://user-images.githubusercontent.com/55636493/131425257-11425057-51a4-43f6-9e21-dc7b5efca6a6.png)
![nqIlEurR](https://user-images.githubusercontent.com/55636493/131425258-9144c58e-b4f4-48af-b54b-d7723877e4c7.png)

Error Code : 
info: AspNet.Security.OAuth.Discord.DiscordAuthenticationHandler[12]
      AuthenticationScheme: Discord was challenged.
warn: AspNet.Security.OAuth.Discord.DiscordAuthenticationHandler[15]
      '.AspNetCore.Correlation.' cookie not found.
info: AspNet.Security.OAuth.Discord.DiscordAuthenticationHandler[4]
      Error from RemoteAuthentication: Correlation failed..
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "", Request id "": An unhandled exception was thrown by the application.
      System.Exception: An error was encountered while handling the remote login.
       ---> System.Exception: Correlation failed.
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by LeaFrock** [comment]
It seems related to the cookie setting `SameSite`. Use `https` and set cookie `secure;samesite=none;httponly`

See https://stackoverflow.com/questions/50124498/correlation-failed-at-microsoft-aspnetcore-authentication-remoteauthenticationh for reference.

**Comment by LedgendODST** [comment]
> It seems related to the cookie setting `SameSite`. Use `https` and set cookie `secure;samesite=none;httponly`
> 
> See https://stackoverflow.com/questions/50124498/correlation-failed-at-microsoft-aspnetcore-authentication-remoteauthenticationh for reference.

i am sorry i am not good at setup that to a linux server, i've been watching many tutorials about that but nothing of them works, seems like i failed by this tutorial too. well i got something like what you said yesterday...

info: AspNet.Security.OAuth.Discord.DiscordAuthenticationHandler[7]
      Discord was not authenticated. Failure message: Not authenticated
warn: Microsoft.AspNetCore.Http.ResponseCookies[1]
      The cookie '.AspNetCore.Correlation' has set 'SameSite=None' and must also set 'Secure'.
info: AspNet.Security.OAuth.Discord.DiscordAuthenticationHandler[12]
      AuthenticationScheme: Discord was challenged.
warn: AspNet.Security.OAuth.Discord.DiscordAuthenticationHandler[15]
      '.AspNetCore.Correlation.-' cookie not found.
info: AspNet.Security.OAuth.Discord.DiscordAuthenticationHandler[4]
      Error from RemoteAuthentication: Correlation failed..
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "", Request id "": An unhandled exception was thrown by the application.
      System.Exception: An error was encountered while handling the remote login.
       ---> System.Exception: Correlation failed.
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

then  i searched it up on google and found this code as the solution 

            app.UseCookiePolicy(new CookiePolicyOptions
            {
                Secure = CookieSecurePolicy.Always,
                MinimumSameSitePolicy = SameSiteMode.Strict
            });

i don't know how to use https on aspnet.

**Comment by martincostello** [comment]
Closing as external and due to inactivity.

**Comment by thanhtai9606** [comment]
> > It seems related to the cookie setting `SameSite`. Use `https` and set cookie `secure;samesite=none;httponly`
> > See https://stackoverflow.com/questions/50124498/correlation-failed-at-microsoft-aspnetcore-authentication-remoteauthenticationh for reference.
> 
> i am sorry i am not good at setup that to a linux server, i've been watching many tutorials about that but nothing of them works, seems like i failed by this tutorial too. well i got something like what you said yesterday...
> 
> info: AspNet.Security.OAuth.Discord.DiscordAuthenticationHandler[7] Discord was not authenticated. Failure message: Not authenticated warn: Microsoft.AspNetCore.Http.ResponseCookies[1] The cookie '.AspNetCore.Correlation' has set 'SameSite=None' and must also set 'Secure'. info: AspNet.Security.OAuth.Discord.DiscordAuthenticationHandler[12] AuthenticationScheme: Discord was challenged. warn: AspNet.Security.OAuth.Discord.DiscordAuthenticationHandler[15] '.AspNetCore.Correlation.-' cookie not found. info: AspNet.Security.OAuth.Discord.DiscordAuthenticationHandler[4] Error from RemoteAuthentication: Correlation failed.. fail: Microsoft.AspNetCore.Server.Kestrel[13] Connection id "", Request id "": An unhandled exception was thrown by the application. System.Exception: An error was encountered while handling the remote login. ---> System.Exception: Correlation failed. --- End of inner exception stack trace --- at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync() at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
> 
> then i searched it up on google and found this code as the solution
> 
> ```
>         app.UseCookiePolicy(new CookiePolicyOptions
>         {
>             Secure = CookieSecurePolicy.Always,
>             MinimumSameSitePolicy = SameSiteMode.Strict
>         });
> ```
> 
> i don't know how to use https on aspnet.

It's working now! Thank so much :)
