### ISSUE TITLE
Add ESIA provider

### ISSUE THREAD

**Issue by inyutin-maxim** [aspnet-contrib/AspNet.Security.OAuth.Providers#595]
Is your feature request related to a problem? Please describe.
ESIA uses OAuth 2.0 and I would like to implement it as a provider so that the API can be used simply for authentication in .NET projects.

Describe the solution you'd like
Add a new provider for [ESIA](https://digital.gov.ru/ru/activity/directions/13/) [manual](https://digital.gov.ru/ru/documents/6182/)

**Comment by bretbas** [comment]
yes, it's be useful for me too

**Comment by kinosang** [comment]
you can create a PR to contribute the provider.

I'd like to help but I cannot read Русский язык.

**Comment by kinosang** [comment]
@bretbas

~By reading some codes for PHP, I figured that you can just use the Microsoft OpenIdConnect provider.~

I wonder if there's an API to reterive the user ID instead of decoding the JWT token?

**Comment by denis-ivanov** [comment]
https://github.com/xeltan/EsiaNET/tree/master/EsiaNET.AspNetCore.Authentication

**Comment by martincostello** [comment]
As the referenced package has existed from 2020, it makes sense that that is the de-facto provider, so there's no need for us to re-implement and maintain one here.
