### ISSUE TITLE
UriBuilder usage in IPostConfigureOptions implementation for URL generation

### ISSUE THREAD

**Issue by TheUltimateC0der** [aspnet-contrib/AspNet.Security.OAuth.Providers#609]
**Describe the bug**
The code seen here https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/da6e0b3e19001d7e44f027c650bcee0f7f59baf1/src/AspNet.Security.OAuth.Keycloak/KeycloakPostConfigureOptions.cs#L29 will result in the provider being not usable.

As per documentation in https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/dev/docs/keycloak.md

The domain variable should contain the realm and the custom domain of the selfhosted instance like `https://auth.domain.org/auth/realms/SomeRandomRealm`

So you set `options.Domain = "https://auth.domain.org/auth/realms/SomeRandomRealm"`

The path (`/auth/realms/SomeRandomRealm`) of the URL gets overwritten by https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/da6e0b3e19001d7e44f027c650bcee0f7f59baf1/src/AspNet.Security.OAuth.Keycloak/KeycloakPostConfigureOptions.cs#L31

Since you can´t set `options.AuthorizationEndpoint`, `options.TokenEndpoint`, and `options.UserInformationEndpoint` cause it will be irgnored by using `KeycloakAuthenticationDefaults.AuthorizationEndpoint`, `KeycloakAuthenticationDefaults.TokenEndpoint`, and `KeycloakAuthenticationDefaults.UserInformationEndpoint` to build the URL, this provider is basically useless.

**Steps To reproduce**
```
var builder = new UriBuilder("https://my.domain.com/with/some/path/added")
{
    Path = "/the/path/is/overwritten",
    Port = -1,
    Scheme = "https",
};

Console.WriteLine(builder.Uri.ToString());
```

**Expected behaviour**
Output: `https://my.domain.com/with/some/path/added/the/path/is/overwritten`

**Actual behaviour**
Output: `https://my.domain.com/the/path/is/overwritten`

**System information:**
Not relevant

**Additional context**
None

**Comment by TheUltimateC0der** [comment]
@antosubash

**Comment by TheUltimateC0der** [comment]
This also seems to affect Okta, Moodle, Zendesk, and GitHub provider.

**Comment by martincostello** [comment]
Thanks for reporting this.

This seems to have slipped through review with me not noticing the custom path in the documentation, however this is the sort of thing I would have expected to have been flushed out when it was initially implemented when tested against a real Keycloak instance.

Whilst this pattern is used in the other providers you mentioned (and why it would have been suggested to be used for Keycloak too), I'm not aware of those providers supporting custom path prefixes. If any of them do, then it would also be an issue, but for example with GitHub Enterprise and Okta, I'm not aware of it being something you can actually do and you can only have a custom _domain_.

Pending an appropriate fix, this could be worked around by registering a custom `IPostConfigureOptions<T>` in the app which would run after our one, which could the fix-up the paths.

**Comment by TheUltimateC0der** [comment]
Has this project now CI/CD implemented, so if I fix this and send a PR, this will be released automatically to nuget after PR is accepted ?

**Comment by martincostello** [comment]
It has had CI, and CD to MyGet, for quite a long time. Releases go to NuGet when we do a manual release.

Sometimes that's almost immediately after a merge, sometimes it might be some time later if we intend to bundle several changes together.

It also depends on when we're available and have the time to do so.

**Comment by TheUltimateC0der** [comment]
Sad to see that nothing has changed in 2 years (https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/261 for reference). I´ll close this issue, someone else can fix it. I´ll find another solution that has proper CI/CD implemented, and also treats contributors more welcoming.

**Comment by martincostello** [comment]
Your attitude is not helpful or friendly.

I would have happily fixed the issue myself when I had the free time, and then release it when appropriate (which might have been straight away), but I was awaiting a response as to whether you had more information about the bug, or offered to fix it yourself. At no point was there any expectation that _you_ needed to fix it.

Even if we _did_ have instant release to NuGet upon merge (which would be noisy if we pushed a release for any trivial change like a readme update, which is why we _choose_ not to), it would still be dependent on the PR being reviewed by the maintainers, such as myself.

It's currently around 9:30pm where I am, so even if you'd submitted a fix this evening and we did have automatic releases, it's still dependent on my free time to choose to look at any PRs and merge them.

That can take any amount of time; this project does not take precedence over what I choose to do with my personal time, and this project has no Service Level Agreement.

Maybe consider the humans on the other end of your comments next time you interact with people on GitHub, and be more respectful of others' time.

**Comment by TheUltimateC0der** [comment]
My attitude comes from the way this project has treaten me, and has nothing to do with you personally. I appreciate anyones work on these kind of open source projects a lot, given the fact that the world would not run without open source.

I have multiple open source projects to maintain myself, some on github, some on other sites/platforms. So I know that it is your private time that you invest for other people, but you decided to do so yourself by being a maintainer of this project. No one forced you to do so, and also no one forced me to maintain the projects that I maintain. So arguing about that its 9:30pm in your place, and be respectful to others' time is just stupid nonsense. You dont want to invest time into this project after 9:30pm? Simply shut down your laptop/computer, go out with your friends, spend time with your wife/kids, or do something you want.

I have no problem with a PR review taking a few days. You have to find time between your job and your private life, and lets be honest sometimes one simply doesn´t feel like it. And since it is a task, that has to be done by a human, this cannot be automated. But ... guess what can be automated?! Releases!

We are all software developers (some more, some less) here on this plattform, and getting told you don´t automatically release on nuget.org by CI/CD simply because you dont want to clutter nuget releases with no functionality makes me a bit laugh. Simply filter out automated pushes to nuget that do not contain changes on *.cs or *.csproj, $whatever files. Or simply do the other way around, and blacklist changes to *.md files for automated pushes to nuget. Simple as a cake.
