### ISSUE TITLE
Keycloak's "ClientSecret" is mandatory, but Keycloak with access type of "public" has no secret.

### ISSUE THREAD

**Issue by FaridAhamat** [aspnet-contrib/AspNet.Security.OAuth.Providers#610]
**Describe the bug**
If we set the Keycloak to use access type of "public", it will have no secret.

But Validate will fail if there is no "ClientSecret".

**Steps To reproduce**
1. Set a Keycloak server with 'public' access type. This is under the Client settings.

![image](https://user-images.githubusercontent.com/11820522/136410189-0f9947f1-5a07-46a5-ac3e-517911689f6f.png)

2. At ConfigureServices, do not set the ClientSecret.

            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddJwtBearer(o => 
            {
                o.Authority = "http://localhost:8080/auth/realms/vuedemo";
                o.RequireHttpsMetadata = false;
            })
            .AddKeycloak(o => 
            {
                o.ClientId = "hello-vue";
                o.TokenEndpoint = "http://localhost:8080/auth";
            });

**Expected behaviour**
Validate should succeed.

**Actual behaviour**
Validate is throwing exception "The 'ClientSecret' must be provided".

**System information:**
 - OS: Win10
 - Library Version 5.0.15
 - .NET version 5.0.401

**Comment by martincostello** [comment]
This fix for this is for us to use a similar pattern to this from the Apple provider, and override the `Validate()` method in `KeycloakOptions`.

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/da6e0b3e19001d7e44f027c650bcee0f7f59baf1/src/AspNet.Security.OAuth.Apple/AppleAuthenticationOptions.cs#L128-L146

**Comment by martincostello** [comment]
The fix for this issue is now available from [NuGet.org](https://www.nuget.org/packages/AspNet.Security.OAuth.Keycloak/5.0.16) - thanks again 🍰
