### ISSUE TITLE
Discord provider using wrong host

### ISSUE THREAD

**Issue by nmills3** [aspnet-contrib/AspNet.Security.OAuth.Providers#632]
### Provider name

_State which provider(s) you are experiencing an issue with._
Discord

### Expected behavior

_Explain what you expected to happen._
Return Url should be subDomain.myurl.com/signin-discord

### Actual behavior

_Explain what actually happened. If an exception occurred, please include a stack trace if available._
Return Url is being set to 192.168.1.208:9020/signin-discord

### Steps to reproduce

_A concise and repeatable example of how to illustrate the issue._
Run an asp net project using the discord provider behind an nginx reverse proxy

### Additional information

_Any additional information that may be useful, such as the version of the package you are using or the version of .NET Core._
Net core version is 5.0, package verion is 5.0.18, running behind nginx as a reverse proxy

```
server {
    listen 443 ssl;
	
	ssl_certificate /certificates/myurl.com/fullchain.pem;
	ssl_certificate_key /certificates/myurl.com/privkey.pem;
	
    server_name subDomain.myurl.com;
	
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Original-Host subDomain.myurl.com;
	
    location / {
        proxy_pass http://192.168.1.208:9020;
    }	
}
```

**Comment by martincostello** [comment]
This doesn't sound like an issue specific to the Discord provider.

Have you configured your app appropriately to trust the forwarded headers? https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-6.0#use-a-reverse-proxy-server

**Comment by nmills3** [comment]
sorry, this is the first time i've done oauth providers behind a proxy. Ok, so i've got that setup but now it's going to the http version of my url instead of the https version

**Comment by martincostello** [comment]
That sounds like when x-forwarded-proto gets ignored by the app because it doesn't trust the proxied header. If you turn logging for ASP.NET Core up to debug (or maybe it's trace), does it log anything avoid ignoring the forwarded headers?

**Comment by nmills3** [comment]
Ok, i've got the issue fixed now. Thanks for the guide @martincostello it was a big help. sorry for being a bit of a noob

**Comment by martincostello** [comment]
No problem - glad you've got it working 👍
