### ISSUE TITLE
Unable to develop additional OAuth providers

### ISSUE THREAD

**Issue by timothydilbert** [aspnet-contrib/AspNet.Security.OAuth.Providers#641]
**Describe the bug**
 One of the IDaaS we would like to utilise is not listed. I am attempting to develop an OAuth provider for the missing IDaaS, but running into the following error when trying to run dotnet build in the folder of the new OAuth provider:
```
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
/Users/user1/Documents/dev/AspNet.Security.OAuth.Providers/src/AspNet.Security.OAuth.NewProvider/AspNet.Security.OAuth.NewProvider.csproj : error NU1101: Unable to find package AspNet.Security.OAuth.NewProvider. No packages exist with this id in source(s): dotnet-eng, dotnet-public, dotnet-tools, NuGet
  Failed to restore /Users/user1/Documents/dev/AspNet.Security.OAuth.Providers/src/AspNet.Security.OAuth.NewProvider/AspNet.Security.OAuth.NewProvider.csproj (in 1.25 sec).

Build FAILED.

/Users/user1/Documents/dev/AspNet.Security.OAuth.Providers/src/AspNet.Security.OAuth.NewProvider/AspNet.Security.OAuth.NewProvider.csproj : error NU1101: Unable to find package AspNet.Security.OAuth.NewProvider. No packages exist with this id in source(s): dotnet-eng, dotnet-public, dotnet-tools, NuGet
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.29
```

**Steps To reproduce**
1. Clone `AspNet.Security.OAuth.Providers` to the local computer.
2. Copy the `/src/AspNet.Security.OAuth.GitHub` folder, and rename it to 'NewProvider`.
3. Rename all files, classes and namespaces from `Github` to `NewProvider`.
4. Run `dotnet build` on `/src/AspNet.Security.OAuth.NewProvider`.
5. Error is thrown.

**Expected behaviour**
I would expect to run `dotnet build` on the new provider, and the code should compile.

**Actual behaviour**
The abovementioned error is occurring.

**System information:**
 - OS: macOS
 - .NET version 6.0.1

**Additional context**
N/A

**Comment by martincostello** [comment]
To stop the error, add this setting to the csproj file of the new provider you're adding:

https://github.com/martincostello/AspNet.Security.OAuth.Providers/blob/036b234b1079b6992cccb2250a83e00f0c40b664/src/AspNet.Security.OAuth.Twitter/AspNet.Security.OAuth.Twitter.csproj#L8-L11

**Comment by martincostello** [comment]
Related: #633

**Comment by timothydilbert** [comment]
I am now able to compile. Thank you, Martin.

**Comment by rcroft-work** [comment]
Just hit above issue and @martincostello's response resolved the issue.

It be very helpful to have a "Developing a new provider" and add tips/tricks like this one to it?

I am still to debug my provider so tips/tricks w.r.t. debugging a new provider would be helpful as well.
