### ISSUE TITLE
Trovo Support

### ISSUE THREAD

**Issue by NioZero** [aspnet-contrib/AspNet.Security.OAuth.Providers#642]
**Is your feature request related to a problem? Please describe.**
Trovo is a Stream platform that supports [OAuth](https://developer.trovo.live/docs/APIs.html#_3-authentication) and it would be great to support in ASP.NET.

**Describe the solution you'd like**
Added support to Trovo Authentication

**Describe alternatives you've considered**
I will try to implement my own solution for this integration.

**Comment by serber** [comment]
@martincostello, please check PR #645

**Comment by martincostello** [comment]
The new Trovo provider has now been published to [NuGet.org](https://www.nuget.org/packages/AspNet.Security.OAuth.Trovo/6.0.3). Thanks for your contribution @serber 🎈
