### ISSUE TITLE
LinkedIn Login Issue - The redirect_uri does not match the registered value

### ISSUE THREAD

**Issue by kennethlou** [aspnet-contrib/AspNet.Security.OAuth.Providers#648]
Hi,

I am trying to use the OAuth provider for LinkedIn.

In the AutthenticationController.cs, I simply put the localhost as redirect uri:

return Challenge(new AuthenticationProperties { RedirectUri = "https://localhost:44318/" }, provider);

I think I also set up the clientID and clientSecret correctly in the startup.cs.

In the LinkedIn developer Auth>OAuth2.0 settings>Authorized redirect urls for your app, and Settings>Additional Settings>Domain, I also have https://localhost:44318/. In LinkedIn developer>Products, I also selected Sign In with LinkedIn.

However I still keep receiving: 
Bummer, something went wrong.
The redirect_uri does not match the registered value

The OAuth 2.0 > scopes only has. Do you think it is the correct setup?

r_emailaddress
Use the primary email address associated with your LinkedIn account
r_liteprofile
Use your name and photo

Do you exactly know how to resolve the issue?

Regards,
Ken Lou

**Comment by martincostello** [comment]
This seems like some sort of configuration mismatch between your app and LinkedIn rather than an issue with the provider.

* Are you definitely running it on `https://localhost:44318`?
* Have you tried removing the trailing slash?
* Have you tried adding `/signin-linkedin` to the path?

**Comment by kennethlou** [comment]
Thanks for your reply. It seems that I need to add /signin-linkedin to the path and it seems to work again.
