### ISSUE TITLE
Add DigitalOcean provider

### ISSUE THREAD

**Issue by ElanHasson** [aspnet-contrib/AspNet.Security.OAuth.Providers#652]
Please provide a DigitalOcean provider: https://www.digitalocean.com/community/tutorials/how-to-use-oauth-authentication-with-digitalocean-as-a-user-or-developer

Alternative is to implement oAuth myself.

**Comment by ElanHasson** [comment]
I'm happy to take a stab at implementing myself.

**Comment by ElanHasson** [comment]
Done. PR to follow.

**Comment by martincostello** [comment]
The DigitalOcean provider is now available from [NuGet.org](https://www.nuget.org/packages/AspNet.Security.OAuth.DigitalOcean/) - thanks for your contribution @ElanHasson 🍪
