### ISSUE TITLE
Is Blazor supported?

### ISSUE THREAD

**Issue by ClassyCircuit** [aspnet-contrib/AspNet.Security.OAuth.Providers#659]
Is this working also with Blazor?

**Comment by martincostello** [comment]
All the providers in this library depend on the [Microsoft.AspNetCore.Authentication.OAuth](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.OAuth/) NuGet package, which as far as I'm aware is not supported for Blazor scenarios. In which case, we would not support Blazor either. It's certainly not something we test for today.
