### ISSUE TITLE
Question: Guidance on Suspended Accounts?

### ISSUE THREAD

**Issue by Mike-E-angelo** [aspnet-contrib/AspNet.Security.OAuth.Providers#663]
To start with here, I recently deployed a project -- nay, startup! 😁 -- with several providers from this project mentioned (along with what feels like half of NuGet!) in my acknowledgements here:
https://alpha.starbeam.one/about/acknowledgements

Additionally, I go on and on how awesome OAuth/2 is here, giving a shoutout to this project here:
https://www.youtube.com/watch?v=KRmf8IWpOmo&list=PLMq1y8QwgsyoQUspInuhBXiHoXrcKDacb&index=5

That stated, I wanted to explore a problem that I have run into with Oauth/2 and see if I can get some assistance around it.

The problem is around suspended accounts.  For instance, if someone connects to my application via Twitter Oauth (most likely scenario) and then violates a policy on Twitter (that is, the violation does not occur on my application or with its policies), what happens to their connection to my application?  Are they also banned/suspended and not able to authenticate?

This is unclear to me and, with concern, it is also unclear to the Twitter community, as seen here:
https://twittercommunity.com/t/does-a-suspended-account-impact-registered-oauth-applications/167376/

The assumption is that if the hosting provider suspends the account, it also impacts all registered connections along with it.  However, this is not verified in any documentation anywhere and I am having trouble confirming this.  Additionally, the possibility exists that different platforms might handle this in different ways.

As seen in the above link, no one seems to know (again, sort of concerning), so I am branching out here to see if someone here might know or can find someone who knows.  As I mentioned there, I can attempt mitigating by way of faking a suspended account, but no one seems to know anything about that, either.  

If anyone has any experience/guidance around this, it would be greatly appreciated.

Note that as I state in the video to "backup" identity by way of "chaining" another Oauth2 provider (or using two separate accounts: professional/personal), but this adds complexity and would rather avoid that if possible. 

Thank you for any insight/conversation you can provide and keep up the great work out there. 👍

**Comment by kevinchalet** [comment]
> Thank you for any insight/conversation you can provide and keep up the great work out there. 👍

Thanks for the kind words!

I don't know the answer for Twitter specifically but I can answer from a spec/general perspective: neither OAuth 2.0 nor OIDC say anything about this scenario, so it's always implementation-specific.

While you have zero control over what the IdP/authorization server will do in this case, you generally have these 3 options to mitigate this issue _client-side_:
  - Provide an account recovery mechanism, typically using a set of recovery codes (generated using a random number generator suitable for crypto operations)
  - Provide a way to link multiple external accounts
  - Provide a way to bypass the external provider, using e.g an email recovery process to add a new external account ('tho it's not super frequent to support that per-user, it's your last chance option when your client access is revoked by the provider).

As you can guess, the first 2 options offer a very good level of security and can be implemented using ASP.NET Core but that only works if the user made a copy of his recovery codes or linked multiple accounts. The 3rd one is not ideal from a security perspective, but it's often used when you have no other option.

**Comment by Mike-E-angelo** [comment]
Thank you for the suggestions @kevinchalet they are appreciated.

It's funny you mention account recovery as that is where I am gravitating to at present.  I currently allow the user to associate one ore more emails to their account.  I also allow them to connect a 2FA application (via aspnetcore, so awesome). 

So the idea is that if the account is somehow blocked from the provider, I could still provide a way to recover the account using one of the above.

However, I am not sure of the first way of testing this.  Ideally it would be great to have a provider be able to create a testing account where the status can be manually set on the account, and then attempt to login to my local application with that account's credentials.

Unfortunately I see nothing like this anywhere.  Any further suggestions insight would be appreciated if you are aware of anything.

I will mention that I suggest users chain their accounts with another external account (suggestion #2 in your list above).  This is something I already provide (and is actually mentioned in my Identity System video above). However, this is complicated, or complicated enough where I do not think users will readily adopt this (but who knows).  I would rather keep it simple as possible, but I am also not very confident that this is possible.

Finally, another mitigation is to use two accounts: one professional/branding and another one for personal.  This cleanly addresses the issue, but whether users will actually go through this is again yet to be seen.

As you can imagine, it really just takes one account lockout to cause a major PR headache (especially if that account holds monetary value) and that is what I am trying to avoid here.

**Comment by kevinchalet** [comment]
> However, I am not sure of the first way of testing this. Ideally it would be great to have a provider be able to create a testing account where the status can be manually set on the account, and then attempt to login to my local application with that account's credentials. Unfortunately I see nothing like this anywhere. Any further suggestions insight would be appreciated if you are aware of anything.

You could create a minimal OIDC server (e.g based on OpenIddict) and use the MSFT OIDC handler as an equivalent of the providers developed in this repo (they use exactly the same authentication abstractions).

> As you can imagine, it really just takes one account lockout to cause a major PR headache (especially if that account holds monetary value) and that is what I am trying to avoid here.

Oh yeah. It happened to me (as a user) last month: I used Steam authentication with a service that no longer supports it and requires doing an email recovery dance to add a password to the account. The thing is their email service doesn't use DKIM and their emails are flagged as spams and filtered by my domain name provider before they even have a chance to reach my actual mailbox. It's a nightmare 🤣

**Comment by Mike-E-angelo** [comment]
> It's a nightmare 🤣

Exactly what I am trying to avoid here, @kevinchalet. 😁  Thank you for sharing your story.

> You could create a minimal OIDC server (e.g based on OpenIddict) and use the MSFT OIDC handler as an equivalent of the providers developed in this repo (they use exactly the same authentication abstractions).

Apologies but that seems a bit advanced for me at the moment.  Do you have a suggested reference/article/resource I could start with to further investigate?  Or perhaps a repository with a sample server as a starting point?

For further reference/context, I have basically have about 10 OAuth2 providers for my application, 8 of which I have integrated from this repository with a simple one-liner after a basic application registration with the provider.  All worked without fail which is part of the reason I have enjoyed it so much.  So, my experience here is a bit lacking in standing up a server or anything quite so involved.

Ideally, I would like to have a way to impersonate a (test) user and set flags on it to recreate a certain scenario.  This does not seem to be available even from the biggest providers, so that path does not look promising (surprisingly!).

I am also interested in what exactly occurs from an OAuth provider when an account is suspended.  Is there a code that is returned and sent to the `/signin-<provider>` handler, by chance?  If there is something there that I can investigate I would be most interested in exploring this further.

**Comment by martincostello** [comment]
I would _imagine_ that if your account has been suspended, when you logged in on the provider's login form, it would fail to authenticate and tell you that. If it did do that, then you'd never be redirected back to original application's `/signin-{name}` endpoint.

If authentication succeeded but you were "banned", "restricted" (or whatever), then that's possibly something discoverable via something on the user information endpoint response once you get a token, which again would be provider-specific and need custom code in the application to handle.

I don't think there's anything generic that can be done within the OAuth standard, unless it just replied with the `denied` reason with a custom message saying why, in which case there's an existing event you can hook into for that to deal with that scenario in whatever way is appropriate for your application.

**Comment by Mike-E-angelo** [comment]
Thank you very much for taking the time to provide some suggestions and thoughts @martincostello.  

I have to say that am a little shocked that no one anywhere can tell me exactly what to expect here.  I am almost tempted to create a burner account and perform some dubious activities with it and see if I can get a suspension that way.  That was actually my first thought at how to approach this problem, but thought I would get some guidance on how to emulate it instead.  Since that doesn't seem to be an option here, it's concerningly becoming the only option to having a definitive answer to this scenario.

I will update here with any further information I find.  In the meantime, I will close this issue.

**Comment by Mike-E-angelo** [comment]
Quick update here as there has been a breakthrough after long last.  The suggestion was made to create a new account and make use of a "feature" of Twitter whereby if you set your age to under 13 you instantly become suspended.  I actually have experienced this before (when creating a project account and setting its birthday to the creation date) and should have thought of this.

In any case, hopefully, this will help others going forward as I am of the mindset Oauth will be replacing email/password authentication and this is going to become more and more of an issue.

Anyways, more here:
https://twittercommunity.com/t/best-way-to-test-oauth-authentication-with-a-banned-suspended-user/169792/3?u=mikeeee
