### ISSUE TITLE
using session with OnCreatingTicket Event throws exception with session not configured message.

### ISSUE THREAD

**Issue by JhOnNeY** [aspnet-contrib/AspNet.Security.OAuth.Providers#668]
**Describe the bug**
In the OAuth provider OnCreatingTicket event, I am unable to access the current context's session when the user is redirected to the callback path after successfully authenticating with a remote provider.

I am able to access and modify the session in controllers.

I also tried with variations of `context.Response.HttpContext...` and `context.Request.HttpContext...`

This also happens with the steam openid provider.

**Steps To reproduce**
Configuration Code:
```csharp
...

builder.Services.AddSession(options =>
{
    options.IdleTimeout = TimeSpan.FromMinutes(15);
    options.Cookie.HttpOnly = true;
    options.Cookie.IsEssential = true;
});

...

builder.Services.AddAuthentication(options =>
{
    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
})
.AddCookie(options =>
{
    options.LoginPath = "/signin";
    options.LogoutPath = "/signout";

})
.AddDiscord(options =>
{
    // Add all OAuth options for discord
    // This part is working fine
    
    ...
    
    options.Events = new OAuthEvents
    {
        OnCreatingTicket = async context =>
        {
           // gives error "InvalidOperationException: Session has not been configured for this application or request."
           context.HttpContext.Session.SetString("Taco", "Libre");
        }
    };
});

...

app.UseAuthentication();
app.UseAuthorization();
app.UseSession();

...
```
Run the challenge and it will trigger the exception when the user signs in with the remote provider and redirects to the callback path.

**Expected behaviour**
I expect to be able to read and modify the current session properties.

**Actual behaviour**
An exception is thrown:
```
InvalidOperationException: Session has not been configured for this application or request.
Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
Program+<>c+<<<Main>$>b__0_11>d.MoveNext() in Program.cs
+
            context.HttpContext.Session.SetString("Nacho", "Libre");
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**System information:**
 - OS:  Windows 10
 - .NET  Version:   6.0.102

**Comment by kevinchalet** [comment]
It's not a bug: your middleware configuration is invalid for this scenario. Move `app.UseSession()` before `app.UseAuthentication()` and it should work.

**Comment by JhOnNeY** [comment]
Wow 🤦‍♂️ You are right. Thank you!

I suppose that means my other issue will end up being just as simple.
