### ISSUE TITLE
How to skip email confirmation?

### ISSUE THREAD

**Issue by danielniccoli** [aspnet-contrib/AspNet.Security.OAuth.Providers#674]
Hello,

am I able to skip the email address confirmation?

![grafik](https://user-images.githubusercontent.com/2971735/164888666-d7b0d26a-bc59-46c6-919a-ed7a95eea77f.png)

I want my web app to use the information provided in the claims and create the user account without any further interaction from the visitor.

```cs
builder.Services.AddAuthentication().AddGitHub(options =>
{
    IConfigurationSection githubAuthNSection = builder.Configuration.GetSection("Authentication:GitHub");
    options.ClientId = githubAuthNSection["ClientId"];
    options.ClientSecret = githubAuthNSection["ClientSecret"];
    options.Scope.Add("user:email");
});

builder.Services.AddDefaultIdentity<IdentityUser>()
    .AddEntityFrameworkStores<ApplicationDbContext>();
```

**Comment by martincostello** [comment]
This functionality is part of ASP.NET Core Identity, rather than our OAuth providers.

I'm not familiar enough with it to offer some specific advice, but I would imagine there'd be a configuration option for it somewhere.

**Comment by kinosang** [comment]
please consider reading the Asp.Net Core docs before starting use it.

https://docs.microsoft.com/en-us/aspnet/core/security/?view=aspnetcore-6.0
