### ISSUE TITLE
IMemoryCache in Apple auth library

### ISSUE THREAD

**Issue by misha-fm** [aspnet-contrib/AspNet.Security.OAuth.Providers#679]
Hi, @martincostello!

We are using your 'AspNet.Security.OAuth.Apple' library. First of all, thank you for this great lib!

Recently we faced an issue on our load-balanced 2-server cluster, using the library. Looks like, that when initial login request lands on server1, and consequent redirect from apple website lands on server2, we can access a lot of properties for this whole login session.

Our suspicion is that it's related to the fact, the IMemoryCache is used.

Could you please verify, that our assumption is valid? And could you please, why you are using IMemoryCache and not IDistributedCache? Is there any specific reason for this solution?

Thanks in advance!

**Comment by martincostello** [comment]
The `IMemoryCache` is just used to cache a client secret used to authenticate requests to the Sign in with Apple servers until the generated JWT is about to expire:

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/4daeee16aac77a7705db45206668458fdf2916e6/src/AspNet.Security.OAuth.Apple/Internal/DefaultAppleClientSecretGenerator.cs#L34-L53

As this is secret material, it is just kept in memory. Storing secrets in a distributed cache would create the potential for the secret to be leaked to unauthorized parties if the cache is not appropriately access-controlled and secured.

As far as I'm aware, there should be no issue with different servers using different JWTs to authenticate with the Apple servers.
