### ISSUE TITLE
Stripe Connect Support

### ISSUE THREAD

**Issue by Mike-E-angelo** [aspnet-contrib/AspNet.Security.OAuth.Providers#680]
**Is your feature request related to a problem? Please describe.**
Stripe Oauth2 support:
https://stripe.com/docs/connect/oauth-reference

**Describe the solution you'd like**
Amazing AspNetContrib Oauth capability in my application BUT WITH STRIPE 😁

**Describe alternatives you've considered**
NONE

**Additional context**
I am volunteering for this one.  The only ask is that I would like to have someone take a look at [this documentation](https://stripe.com/docs/connect/oauth-reference) and let me know an existing provider here on AspNetContrib that resembles a close approximation to it, and I will give it the same copy/pasta/prettyup treatment I did [with MixCloud](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/568).  

Also, like MixCloud, I also volunteer to support it as I will be using this in [my application](https://alpha.starbeam.one/) for not just identity but deposits/withdrawals. 👍

**Comment by martincostello** [comment]
A quick scan of the linked document makes it _look_ like standard OAuth-y flow to me, there's just a bunch of additional optional fields to do things like pre-fill form fields, see the granted scopes etc.

If you look at the Amazon, Patreon and Twitter providers they have similar functionality to request additional properties as part of HTTP requests in the flow.

I'd have thought Patreon and Shopify would be the closest two providers to Stripe in terms of use case.

**Comment by Mike-E-angelo** [comment]
I'm digging your thinking on that @martincostello.  I'll take a look at both Patreon and Shopify.  Note that I am already partial to Patreon as I am actively using it from this repository as one of my application's supported providers. 😁

**Comment by Mike-E-angelo** [comment]
Checking in on this issue.  I have my eye on this feature still.  I was not able to get to Stripe Payouts for my launch/release, only the Checkout/Payments (which are amazing BTW) which do not require Oauth2.

I have some critical issues/bugs to address and then I will start getting Stripe Payout support in there, at which time I will be looking at this issue. 👍

**Comment by kevinchalet** [comment]
I implemented Stripe OAuth 2.0 support for a client last year and it went flawlessly as no workaround was required (if only all the services could be that easy to integrate 🤣)

The only oddity - but maybe it has changed since - is that while they support access and refresh tokens, they actually recommend using an API key instead of the access token when communicating with their APIs (so the code flow is basically only used for the consent part).

**Comment by Mike-E-angelo** [comment]
OK thank you @kevinchalet for that heads up.  Am I to understand correctly that you mean passing the API key in the URL to the authentication endpoint rather than the access token?  That does seem a bit of an oddity indeed if so.  I guess there's always the client "secret" to keep things secure, but I'd rather use a token than expose the world to the application identifier used to associate me with the service.

In any case, I'll be on the lookout. 👀

**Comment by Mike-E-angelo** [comment]
An update here that I am now (_finally_) actively working on this and should have a PR in the next week or so. 🤞  I will update accordingly.

**Comment by kevinchalet** [comment]
> Am I to understand correctly that you mean passing the API key in the URL to the authentication endpoint rather than the access token?

Nah, I actually meant their non-auth APIs (typically the payment stuff). In a typical app, you'd use the access token retrieved during the authorization dance and flow it via the `Authorization` header using `Authorization: Bearer [access token]`.
It's something that works with Stripe too, but last time I checked, they actually recommended using the API key of your app instead of the access token.

**Comment by Mike-E-angelo** [comment]
> It's something that works with Stripe too, but last time I checked, they actually recommended using the API key of your app instead of the access token.

OK @kevinchalet I am with you now.  I actually do this for my Stripe payments/checkout integration.  Additionally, looking at Stripe Connect, you can see the breakdown for API vs. Oauth2 here:
https://stripe.com/docs/connect/accounts#choosing-approach

That stated, I spent the day learning about Stripe Connect yesterday and it unfortunately isn't anything like I understood it to be. 😞

I was under the impression it was more like PayPal, where everyone has an account, and you use an Oauth2 connection to connect that account to a supporting application, providing it the necessary permissions to successfully operate (typical Oauth2 workflow).

Additionally, PayPal also has consumer and business accounts, and that is how I understood Stripe Connect to be as well.

Unfortunately, Stripe Connect appears to offer business accounts only, and the Oauth2 is used to connect these business accounts together on a per-business basis (as opposed to a singular platform basis such as PayPal's).  This throws a huge wrench in my world as I am needing to use my business account to send money to a basic user account (ala [PayPal Payouts](https://www.paypal.com/merchantapps/appcenter/makepayments/payouts?locale.x=en_US)).

That stated, I am not sure how much of a value creating a provider here is.  It would be for business-to-business connections and seems very specialized rather than a generalized offering for the consumer space like PayPal's that I had in mind.

While I am OK making a contribution that involves something that I am actively using and can subsequently support, I am not so comfortable with committing (and supporting) something that I am not actively using.

I should have done more research before creating this issue, so pardon the thrashing here.  Consider it part of the process to get me amped up in doing it.  If anything, I hope it demonstrates how highly valued I consider this project and its place in the ecosystem.

That stated, I will be closing this issue for now.  If I have something fundamentally misunderstood (always a possibility) then perhaps we can revisit this at a later time.  But I am hoping at the least this issue will serve as a reference point in case someone else wants to tackle it at some point in the future and make sure they understand what Stripe Connect actually is.

Thank you for your patience as I get situated here, and for the opportunity to learn (at my ego's expense 😅😭). 🙏
