### ISSUE TITLE
MapJsonKey not showing in claims

### ISSUE THREAD

**Issue by wthks** [aspnet-contrib/AspNet.Security.OAuth.Providers#682]
I added a new map into the collection

```cs
ClaimActions.MapJsonKey("urn:discord:banner", "banner");
```
but in the ClaimsPrincipial the collection does not have this map.
it only has the discord id, username and discriminator

what am i doing wrong?

**Comment by martincostello** [comment]
The code looks correct.

Have you inspected the JSON returned from Discord to check it actually has a `banner` property in the response and that it has a value if it does?

The claims actions are run here, which is code from the `Microsoft.AspNetCore.Authentication.OAuth` NuGet package, so isn't part of this repository's code.

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/127c5908bbdfc9393f831fd6b7ef1f7ff0d80e8d/src/AspNet.Security.OAuth.Discord/DiscordAuthenticationHandler.cs#L63

**Comment by wthks** [comment]
well. the banner was null in the content, I thought it will also be displayed as null in the claims.. thx
