### ISSUE TITLE
Xamarin forms iOS project with Apple Sign-in and ASP.NET API server as a backend

### ISSUE THREAD

**Issue by NikolaiTsepalov** [aspnet-contrib/AspNet.Security.OAuth.Providers#683]
AspNet.Security.OAuth.Apple 6.0.6

I'm working on a Xamarin forms IOs application.
As the authentication component, I use the "Azure Active Directory B2C, and access a Web API with the resulting tokens".
https://github.com/Azure-Samples/active-directory-b2c-xamarin-native

It did not pass Apple store submission; they want me to use the native "Sign in with Apple".

The closest to the subject blog I found is
https://devblogs.microsoft.com/xamarin/authentication-xamarin-essentials-aspnet/
https://github.com/xamarin/Essentials.git

I was able to configure the client quite easily:
webAuthenticatorResult = await AppleSignInAuthenticator.AuthenticateAsync();
AuthToken = webAuthenticatorResult?.AccessToken ?? webAuthenticatorResult?.IdToken;
I'm getting this authentication token.

The server project uses AspNet.Security.OAuth.Apple, but very old (3. something) version.  In my test, I use the latest 6.0.6

I use the same service configuration as in the sample project:
services.AddAuthentication(o =>
     {
      o.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
     })
     .AddCookie
     ()
     .AddApple(a =>
     {
      a.ClientId = "XXX.Service"; // Looks like at has to be service
      // a.ClientId = "XXX.App"; 
      a.KeyId = "8NWK7GUXXX"; 
      a.TeamId = "A82HCAHXXX";

      a.UsePrivateKey(keyId
       => WebHostEnvironment.ContentRootFileProvider.GetFileInfo($"AuthKey_{keyId}.p8"));
      a.SaveTokens = true;
     });
Looks like the ClientId has to be the service ID, not the client ID.

The main question: is Apple Auth require the use of the MobileAuthController?
https://github.com/xamarin/Essentials/blob/develop/Samples/Sample.Server.WebAuthenticator/Controllers/MobileAuthController.cs

Strange thing:
The first call to my API
https://XXXwebapitest.azurewebsites.net/api/user
Trying to redirect to
https://XXXwebapitest.azurewebsites.net/Account/Login?ReturnUrl=%2Fapi%2Fuser
The default value used by CookieAuthenticationMiddleware PathString("/Account/Login");

I tried two things:

1 Point it to middleware call back:
.AddCookie
     (o=> o.LoginPath = "signin-apple"
      )
2 Changing the Route in the controller to Account/Login, basically trying to use the controller.

The "best" thing I've got so far is the query in the following method: 
protected override string BuildChallengeUrl

If manually used in the browser:
https://appleid.apple.com/auth/authorize?client_id=XXX.SignInWithApple.Service&scope=openid%20email&response_type=code&redirect_uri=https%3A%2F%2FXXXwebapitest.azurewebsites.net%2Fsignin-apple&state=CXXXQ&response_mode=form_post

It shows the web Apple login page, but after entering the password, it gives
https://XXXwebapitest.azurewebsites.net/signin-apple
HTTP ERROR 500
In your example, the AddApple part is commented out
https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/dev/samples/Mvc.Client/Startup.cs

It would be nice if somebody made/pointed to a solid example of using the Xamarin forms iOS project with Apple Sign-in and ASP.NET API server as a backend.

Please help. 
Thanks

**Comment by martincostello** [comment]
I'm afraid I'm not familiar with Xamarin.

If it helps you out, there's a working sample app for Sign In with Apple here you can look at see to see the minimum amount of required code: https://github.com/martincostello/SignInWithAppleSample

**Comment by NikolaiTsepalov** [comment]
I already saw this example; it uses Apple sign-in button on the webpage.
I am using this as the sample for the XAMARIN client:
https://github.com/xamarin/Essentials/tree/develop
I'm already getting the token in it.
I thought you can help with the setting for AddApple on the ASP.NET API server for this scenario.

**Comment by martincostello** [comment]
Sorry, I don't quite follow what you're asking for. Is it getting an API to accept an existing JWT issued by Apple for authentication/authorization (not the OAuth flow itself)?

**Comment by NikolaiTsepalov** [comment]
I am asking how should I set up the AddApple() service  to work in the same way as my previous https://github.com/Azure-Samples/active-directory-b2c-xamarin-native did:

1. On the client, add a token to the HttpClient
var httpAuthClient = new HttpClient();
httpAuthClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

2. On the ASP.NET API server in the Startup.cs file set the auth service (it's literally two lines for B2C, Audience and Authority)
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddJwtBearer(options =>
                    {
                        options.Audience = Configuration[EnvironmentVars.AzureAd.Audience];
                        options.Authority =                       $"https://toppetsapp.b2clogin.com/tfp/{Configuration[AzureAd.ClientId]}/{Configuration[AzureAd.Policy]}/v2.0/";
                    }
                );

3. Get clames I need from the ClaimsPrincipal (User)
				var id = httpRequest.HttpContext.User.GetClaimValue("http://schemas.microsoft.com/identity/claims/objectidentifier"); from resuests

It should be such a common combination: Xamarin client and ASP.NET API server. I was surprised I wasn't able to find any workable examples.

**Comment by martincostello** [comment]
I just had a quick experiment with trying to do this using [my sample site](https://github.com/martincostello/SignInWithAppleSample), and I think I got what you're trying to do working.

In [this commit](https://github.com/martincostello/SignInWithAppleSample/commit/5643b3ceb66419ec03e1991e32833fba6491c773) a second JWT bearer authentication scheme is added to use with requests that have an `Authorization: Bearer ...` HTTP request header based on [this blog post by Rich Strahl](https://weblog.west-wind.com/posts/2022/Mar/29/Combining-Bearer-Token-and-Cookie-Auth-in-ASPNET).

Passing the `id_token` returned [here](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/cbbc7a1cb78ff9898b6110e8c60aae967fd86356/src/AspNet.Security.OAuth.Apple/AppleAuthenticationHandler.cs#L70) to the `/test` endpoint successfully authenticates using the JWT.

```powershell
(iwr https://localhost:5001/test -Headers @{'Authorization'='Bearer eyJ...'} -SkipCertificateCheck).Content
Hi <user identifier>
```

If your Xamarin client already has the equivalent JWT, then an API authorized the same way should be able to authenticate with it using it as a bearer token.

**Comment by NikolaiTsepalov** [comment]
Code never hits the line
string? idToken = tokens.Response!.RootElement.GetString("id_token");
Neither CreateTicketAsync or HandleRemoteAuthenticateAsync are getting called.

I found something suspicious about AppleAuthenticationOptions.
I added a few logs to dump the AppleAuthenticationOptions.
In all cases ClientSecret  = '' is empty.
I addded an Additional check before options.UsePrivateKey: **fi.Exists True**.
I added the P8 file in both wwwroot and the parent folder.

If it's not something obvious for you, maybe I should create a strip-down version of my application and API server for you?

AppleAuthenticationOptions AppleAuthenticationHandler(options, logger, encoder, clock) options.CurrentValue Start 1
  System.String KeyId  = ''
  System.String TeamId  = ''
  System.String ClientId  = ''
  System.String ClientSecret  = ''
  Boolean SaveTokens  = 'False'
AppleAuthenticationOptions AppleAuthenticationHandler(options, logger, encoder, clock) options.CurrentValue End 1
Additional check before options.UsePrivateKey: fi.Exists True
AppleAuthenticationOptions UsePrivateKey Start
 System.String KeyId  = '8NWK7GUM8T'
 System.String TeamId  = 'A82HCAH7UJ'
 System.String ClientId  = 'Design.Dog.Top.Pets'
 System.String ClientSecret  = ''
 Boolean SaveTokens  = 'False'
AppleAuthenticationOptions UsePrivateKey End
AppleAuthenticationOptions AuthenticationModule AddSignInWithApple Start AuthenticationModule.cs end of the Configure<IConfiguration, IServiceProvider>((options, configuration, serviceProvider)");
 System.String KeyId  = '8NWK7GUM8T'
 System.String TeamId  = 'A82HCAH7UJ'
 System.String ClientId  = 'Design.Dog.Top.Pets'
 System.String ClientSecret  = ''
 Boolean SaveTokens  = 'False'
AppleAuthenticationOptions AuthenticationModule AddSignInWithApple End AuthenticationModule.cs

**Comment by NikolaiTsepalov** [comment]
Today I decided to make a fork off your SignInWithAppleSample to use it as a start point:
https://github.com/NikolaiTsepalov/SignInWithAppleSampleX

I've read README.md and 
https://developer.okta.com/blog/2019/06/04/what-the-heck-is-sign-in-with-apple#how-sign-in-with-apple-works-hint-it-uses-oauth-and-oidc

One thing I was doing wrong for sure: the client_id is the service ID:
“Services IDs: the next step, you’ll define the name of the app that the user will see during the login flow, as well as define the identifier which becomes the OAuth client_id.”

Question about Domain Verification file:
Looks like the latest version of the Apple dev site does not have the options for the "Domain Verification file" in the  Web Authentication Configuration.
Am I missing something or this feature was removed?

https://signinwithapplesamplex.azurewebsites.net
After clicking on the sign-in button, it displays the sign-in page.
I can successfully sign in, but after
"Do you want to continue using TopPets SignInWithApple Service with your Apple ID “tXXXXXXXX@yahoo.com”? "
 Redirect shows:
https://signinwithapplesamplex.azurewebsites.net/signin-apple
Status Code: 400; Bad Request

**Comment by martincostello** [comment]
You fork is missing a change to work around this issue: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/684#issuecomment-1143632769

**Comment by martincostello** [comment]
Ah no, it was fine, but you reintroduced the problem by upgrading in this commit: https://github.com/NikolaiTsepalov/SignInWithAppleSampleX/commit/62c2542f1abaf36a3897cbb3ff099b69053811e1

**Comment by NikolaiTsepalov** [comment]
Downgrading to Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="6.17.0"
Didn't help same result

**Comment by martincostello** [comment]
Ok, well now you have a different problem. What do your error logs say?

**Comment by NikolaiTsepalov** [comment]
Where log files are?
in LogFiles eventlog.xml? or in the Transform folder?

**Comment by martincostello** [comment]
Nowhere by default, you'll need to enable logging.

For example, if it's running in Azure App Service, enable logging from the Azure portal and view the log stream.

**Comment by NikolaiTsepalov** [comment]
eventlog.xml has error looks like a error reading p8?
<EventData>
<Data>Category: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware EventId: 1 SpanId: c747dfb010a8ebf3 TraceId: 0e196893b58efbdb3160c4cd80f001c7 ParentId: 0000000000000000 RequestId: 8000d541-0002-ff00-b63f-84710c7967bb RequestPath: /signin-apple An unhandled exception has occurred while executing the request. Exception: System.Exception: An error was encountered while handling the remote login. ---> System.ArgumentException: No supported key formats were found. Check that the input represents the contents of a PEM-encoded key file, not the path to such a file. (Parameter 'input') at Internal.Cryptography.PemKeyImportHelpers.ImportPem(ReadOnlySpan`1 input, FindImportActionFunc callback) at System.Security.Cryptography.ECDsa.ImportFromPem(ReadOnlySpan`1 input) at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.CreateAlgorithm(ReadOnlyMemory`1 pem) at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.GenerateNewSecretAsync(AppleGenerateClientSecretContext context) at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.<>c__DisplayClass5_0.<<GenerateAsync>b__0>d.MoveNext() --- End of stack trace from previous location --- at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory) at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.GenerateAsync(AppleGenerateClientSecretContext context) at AspNet.Security.OAuth.Apple.AppleAuthenticationEvents.<>c.<<-ctor>b__10_0>d.MoveNext() --- End of stack trace from previous location --- at AspNet.Security.OAuth.Apple.AppleAuthenticationEvents.GenerateClientSecret(AppleGenerateClientSecretContext context) at AspNet.Security.OAuth.Apple.AppleAuthenticationHandler.ExchangeCodeAsync(OAuthCodeExchangeContext context) at AspNet.Security.OAuth.Apple.AppleAuthenticationHandler.HandleRemoteAuthenticateAsync(Dictionary`2 parameters) at AspNet.Security.OAuth.Apple.AppleAuthenticationHandler.HandleRemoteAuthenticateAsync() at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync() --- End of inner exception stack trace --- at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync() at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task) </Data>
</EventData>

**Comment by NikolaiTsepalov** [comment]
ok I will enable logging

**Comment by martincostello** [comment]
That error suggests your `.p8` file is invalid or misconfigured.

**Comment by NikolaiTsepalov** [comment]
should I keep
 -----BEGIN PRIVATE KEY-----
 -----END PRIVATE KEY-----
 Or do I need to delete them?

**Comment by martincostello** [comment]
Those are needed in v6.0.0+ of the provider.

**Comment by NikolaiTsepalov** [comment]
yep, I never deleted them...
Do you suggest regenerating a new key?

**Comment by martincostello** [comment]
How are you loading the secret? From a file on disk in the site, through an environment variable or via Key Vault (or something else entirely)?

**Comment by NikolaiTsepalov** [comment]
From the file
And I did set WEBSITE_LOAD_USER_PROFILE to 1

**Comment by martincostello** [comment]
Does the file have the right name to be found by this line of code for your configured key ID?

https://github.com/NikolaiTsepalov/SignInWithAppleSampleX/blob/ae4228dff73e9ef175f458eee3bb30b886cbb11f/src/SignInWithApple/AuthenticationModule.cs#L52

I'm running out of ideas for what might be the problem with your configuration.

**Comment by NikolaiTsepalov** [comment]
8NWK7GUM8T
AuthKey_8NWK7GUM8T.p8
but 8NWK7GUM8T is "KeyId" not team ID

**Comment by NikolaiTsepalov** [comment]
OK let me just regenerate the key...

**Comment by martincostello** [comment]
I edited the comment earlier; I was working from memory and thought it was the team ID before I checked.

**Comment by NikolaiTsepalov** [comment]
It is definitely related to the "cannot find the file specified"
But I added p8 file in both wwwroot and the site folders see attacment
<img width="416" alt="Screen Shot 2022-06-09 at 2 00 57 PM" src="https://user-images.githubusercontent.com/26150523/172945917-bbac0819-9585-4d77-ba94-e7c0af258d7b.png">

"System.Exception: An error was encountered while handling the remote login.
 ---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The system cannot find the file specified.
   at System.Security.Cryptography.CngKeyLite.ImportKeyBlob(String blobType, ReadOnlySpan`1 keyBlob, Boolean encrypted, ReadOnlySpan`1 password)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8(ReadOnlySpan`1 keyBlob)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at Internal.Cryptography.PemKeyImportHelpers.ImportPem(ReadOnlySpan`1 input, FindImportActionFunc callback)
   at System.Security.Cryptography.ECDsa.ImportFromPem(ReadOnlySpan`1 input)
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.CreateAlgorithm(ReadOnlyMemory`1 pem)
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.GenerateNewSecretAsync(AppleGenerateClientSecretContext context)
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.<>c__DisplayClass5_0.<<GenerateAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.GenerateAsync(AppleGenerateClientSecretContext context)
   at AspNet.Security.OAuth.Apple.AppleAuthenticationEvents.<>c.<<-ctor>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at AspNet.Security.OAuth.Apple.AppleAuthenticationEvents.GenerateClientSecret(AppleGenerateClientSecretContext context)
   at AspNet.Security.OAuth.Apple.AppleAuthenticationHandler.ExchangeCodeAsync(OAuthCodeExchangeContext context)
   at AspNet.Security.OAuth.Apple.AppleAuthenticationHandler.HandleRemoteAuthenticateAsync(Dictionary`2 parameters)
   at AspNet.Security.OAuth.Apple.AppleAuthenticationHandler.HandleRemoteAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"

**Comment by NikolaiTsepalov** [comment]
Where can I just "hardcode" the key in the code?

**Comment by martincostello** [comment]
Assign a callback to this property on the options to return it: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/5f311082a46ed519d0d6f7428e7018870657ebe9/src/AspNet.Security.OAuth.Apple/AppleAuthenticationOptions.cs#L90

**Comment by NikolaiTsepalov** [comment]
The "The system cannot find the file specified" message is very misleading.
It has nothing to do with the missing P8 file. After experimenting with the "hardcoded" key, I found what my issue exactly is the issue below:
https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/375
I will look at it and let you know

**Comment by NikolaiTsepalov** [comment]
"The system cannot find the file specified"
https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/375
It definitely was related to the App Service plan.
It cannot be the two lowest plans with the "Shared infrastructure", B1 is the minimum plan.
I think the README file should have this information.

But now, I'm having another bug which is described here:
https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/353
I check your advice:
https://github.com/martincostello/SignInWithAppleSample/blob/5e6d92f3845d7b3d9759b3965e2ea30e7d0928d8/src/SignInWithApple/Startup.cs#L37-L46
But I already have these settings... 
The last line I can reach in the debugger is
return clientSecret;	
Internal\DefaultAppleClientSecretGenerator.cs	Line 50
Error:
AspNet.Security.OAuth.Apple.AppleAuthenticationHandler: Information: Error from RemoteAuthentication: OAuth token endpoint failure: Status: BadRequest;Headers: Server: Apple
Date: Mon, 13 Jun 2022 23:03:01 GMT
Connection: keep-alive
Cache-Control: no-store
Pragma: no-cache
;Body: {"error":"invalid_client"};.
Longer log:
[Invalid client.txt](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/files/8895119/Invalid.client.txt)

Looks like it's a very recent problem for Apple developers
https://developer.apple.com/forums/thread/124521
A lot of ideas but not a single concrete solution

**Comment by martincostello** [comment]
Did you validate the domain your site is using with Apple in their portal?

Do you have the right values configured for the client ID and team ID?

**Comment by NikolaiTsepalov** [comment]
"Did you validate the domain your site is using with Apple in their portal?"
As I mentioned a couple of messages back there is no such a feature as the verified domain anymore look at the screenshots

New:
<img width="803" alt="Screen Shot 2022-06-14 at 10 54 49 AM" src="https://user-images.githubusercontent.com/26150523/173657458-0472f33c-3854-4a5c-8efa-0cd1f78a6785.png">
From the document:
<img width="806" alt="Screen Shot 2022-06-14 at 10 49 25 AM" src="https://user-images.githubusercontent.com/26150523/173657484-719a6b02-aa0c-4b90-a980-93cd0d912eec.png">

If the client ID is incorrect it's never getting a callback from the Apple with the invalid client message

Team Id is an interesting case:
Correct or not I'm getting exactly the same error as I described in the previous comment.

I will take another look at this

**Comment by NikolaiTsepalov** [comment]
With the correct Team ID or not it produces exactly the same log:
[BrokenTeamId.log](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/files/8903454/BrokenTeamId.log)
[CorrectTeamId.log](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/files/8903455/CorrectTeamId.log)

The following exception may be the reason but it happens after the "invalid_client":

2022-06-14 18:51:47.763 +00:00 [Information] Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.AutoValidateAntiforgeryTokenAuthorizationFilter: Antiforgery token validation failed. The required antiforgery cookie ".AspNetCore.Antiforgery.t3FzIQCpEDY" is not present.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The required antiforgery cookie ".AspNetCore.Antiforgery.t3FzIQCpEDY" is not present.
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)

**Comment by martincostello** [comment]
At this stage, I think (without proof to the contrary) we're well into environmental/configuration problems with your setup rather than a bug with the provider itself.

I'm not sure how much support we can give you at this stage without actually being you with access to your infrastructure to physically do the actual act of debugging and (re)configuring things to get it working. Blame Apple for making it so complicated in the first place 😄

My guess regarding the anti-forgery error is that the cookie is being deleted/changed, and re-submitting the form fails because of that. In essence, it's an error caused by the original error so a bit of a red herring.

I have the sample site deployed at `signinwithapple.azurewebsites.net` running on an S1 App Service plan with no issues, which is what makes me think this isn't a _code_ issue (unless it's a very strange edge-case).

I'm not sure what else I can suggest to get it working, other than maybe starting from scratch on a different App Service plan with a newly generated Sign in with Apple application created in the Apple Developer portal and see how you get on in case this is some weird bug on Apple's side.

**Comment by NikolaiTsepalov** [comment]
When last time did you deploy
signinwithapple.azurewebsites.net?
I have a new App Service on azure, but an old client on Apple.
OK I will repeat everything from scratch with screenshots

**Comment by martincostello** [comment]
About 2 hours ago: https://github.com/martincostello/SignInWithAppleSample/actions/runs/2497167303

**Comment by NikolaiTsepalov** [comment]
What about the "Domain Verification file"?
Is it ab obsolete feature or it's somewhere else now?
(two screenshots to messages back)

**Comment by martincostello** [comment]
I think I just got confused with Apple Pay (I have another sample site for that).

**Comment by NikolaiTsepalov** [comment]
Worked from the first attempt:)
Probably to find out what was wrong gonna take another week...
But I did an exhaustive list of screenshots, if you want, I can share with you the Google doc link.
Now just a little thing to add, Xamarin Client

**Comment by NikolaiTsepalov** [comment]
I added your commit
https://github.com/martincostello/SignInWithAppleSample/commit/5643b3ceb66419ec03e1991e32833fba6491c773
to the sample and was able to authenticate the Xamarin client.

For the Xamarin App, the server's appsettings.json  should have ClientId as the App Id, not the Service Id.
So currently, it works for the web OR the client, but I don't care much because I need the API server only for now.

I'm not closing the questions right now because maybe you want to integrate this commit into your sample

**Comment by NikolaiTsepalov** [comment]
Thanks a lot for your help, Martin!
 My app is almost a month in the Apple store.
