### ISSUE TITLE
Is Automatic dead?

### ISSUE THREAD

**Issue by kevinchalet** [aspnet-contrib/AspNet.Security.OAuth.Providers#686]
As part of https://github.com/openiddict/openiddict-core/issues/1451, I'm taking a look at all the providers we support to ensure it will be "easy" to port them to OpenIddict. One of them - Automatic - seems to be dead: all the endpoints point to DNS sub-domains that no longer exist.

@supergibbs you're the one who added this provider back in 2016, do you happen to know whether Automatic is still a thing?

If it's really dead, we should consider removing it from the repo and marking the package as obsolete.

/cc @martincostello

**Comment by supergibbs** [comment]
Hi! Yes, Automatic shutdown and my [original repo is archived](https://github.com/supergibbs/AutomaticSharp).

**Comment by martincostello** [comment]
I've pushed up #689 to remove the provider.

If you'd like to mark the packages as obsolete in NuGet.org @kevinchalet, then we can put it out to pasture and close off this issue.

**Comment by kevinchalet** [comment]
> If you'd like to mark the packages as obsolete in NuGet.org @kevinchalet, then we can put it out to pasture and close off this issue.

Sure, I can do that. Does that sound good enough?

> Automatic ceased operations in May 2020 and thus is no longer supported. For more information, visit https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/686.

**Comment by martincostello** [comment]
LGTM 👍

**Comment by kevinchalet** [comment]
Done: 

![image](https://user-images.githubusercontent.com/6998306/171821054-351e4e55-45b1-4a52-b4bc-e913d611c93c.png)

**Comment by kevinchalet** [comment]
> Hi! Yes, Automatic shutdown and my [original repo is archived](https://github.com/supergibbs/AutomaticSharp).

Thanks for the details, @supergibbs 👍🏻
