### ISSUE TITLE
Weibo provider doesn't  need email scope necessary

### ISSUE THREAD

**Issue by Kurris** [aspnet-contrib/AspNet.Security.OAuth.Providers#692]
### Is your feature request related to a problem? Please describe.

Weibo provider ‘s email endpoint is a high important api on [Weibo open platform ](https://open.weibo.com/wiki/2/account/profile/email),which must to be **Audited** when using **this.Scope.Add("email")** in **WeiboAuthenticationOptions construction**, it makes exception throw “An error occurred while retrieving the email address associated to the user profile.”

### Describe the solution you'd like

Remove **this.Scope.Add("email")** in **WeiboAuthenticationOptions construction** then user add that if he want in
**AddWeibo**

### Describe alternatives you've considered

no

### Additional context

no

**Comment by martincostello** [comment]
Removing this in v6 would be a breaking behavioural change for users who can use the email endpoint, but we could remove this as a default for v7.

**Comment by martincostello** [comment]
This change has been made to our .NET 7 branch and will ship to NuGet.org as the default going forwards in November 2022.

**Comment by Kurris** [comment]
thanks :) 👍
