### ISSUE TITLE
ClaimActions do not affect the email retrieved by the GitHub emails endpoint.

### ISSUE THREAD

**Issue by justi7n** [aspnet-contrib/AspNet.Security.OAuth.Providers#696]
### Describe the bug

When I authenticate per GitHub and want to get the E-Mail of the signed in User which is not public and have a corresponding ClaimAction, then the ClaimAction does not affect the E-Mail.

### Steps To reproduce

1. Add GitHub to the specified AuthenticationBuilder per
```cs
builder.AddGitHub(opts => {
  options.ClaimActions.MapJsonKey(ClaimTypes.Email, "email");
  options.Scope.Add("user:email");
})
```

2.When the User Signs In:

```cs
var authenticateResult = await HttpContext.AuthenticateAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);
var externalUser = authenticateResult.Principal;

if (externalUser.Identity is not ClaimsIdentity externalUserClaims)
  throw new InvalidOperationException("Could not read external user");

var email = externalUserClaims.FindFirst("email")?.Value;

if (string.IsNullOrWhiteSpace(email))
  throw new EmailMissingException();
```

### Expected behaviour

Email should not be empty, ClaimActions should affect it.

### Actual behaviour

ClaimActions won't affect the E-Mail when it is not public (manually inserted per emails endpoint and user:email scope).

**Comment by martincostello** [comment]
You shouldn't need to explicitly map the email claim from the user response (in fact it doesn't come from the user response at all, it's a separate resource, so "email" isn't there).

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/5f311082a46ed519d0d6f7428e7018870657ebe9/src/AspNet.Security.OAuth.GitHub/GitHubAuthenticationHandler.cs#L49-L61

You should only need to add the additional claim [like this](https://github.com/martincostello/alexa-london-travel-site/blob/720063b15db71bc5eebe919248810e6782b73d0f/src/LondonTravel.Site/Identity/AuthenticationBuilderExtensions.cs#L93-L94) and it should work as you'd expect.

The only other thing I can think of looking at your code is that you're using `JwtClaimTypes.Email`, but the provider sets the claim as `ClaimTypes.Email` - do they have the same value? If they don't, then it's looking for the wrong claim name.

**Comment by justi7n** [comment]
> You shouldn't need to explicitly map the email claim from the user response (in fact it doesn't come from the user response at all, it's a separate resource, so "email" isn't there).

Yes, its a seperate resource (`ClaimTypes.Email`), but i'd like to add it as a claim for the claim principal on the app with the claim type `JwtClaimTypes.Email`/`"email"`.

As far as i understand it, the issue is that `context.RunClaimActions()` is run before the adding of the claim when it is retrieved by the email endpoint, isn't it?

**Comment by martincostello** [comment]
That's correct it does after the default claim actions are run. That's so it can only add the email if there wasn't already one mapped by the claims actions.

If you instead use the [`OnCreatingTicket` event](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.oauth.oauthevents.oncreatingticket?view=aspnetcore-6.0) you can customise the principal further before it is returned to the authentication system and re-map the claim there. That event is the final hook run for customisation.

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/5f311082a46ed519d0d6f7428e7018870657ebe9/src/AspNet.Security.OAuth.GitHub/GitHubAuthenticationHandler.cs#L63-L64

**Comment by justi7n** [comment]
Thanks, this worked for me. But I'm not sure whether this should be considered as a workaround or a real solution.

**Comment by martincostello** [comment]
I'm not sure if it's a real problem or not either. The general pattern in OAuth handler implementations (including ASP.NET Core's own ones) seems to be to run them immediately after creating the `OAuthCreatingTicketContext`, which is what we do here.

If it _is_ wrong then changing it at this point would be a breaking behavioural change.

**Comment by kevinchalet** [comment]
Claims actions are only executed on the userinfo response itself, not on the extra response needed to resolve the email address. If you need to use a different claim type for that, you can either implement an `IClaimsTransformation` service or use the events model, which is a first-class citizen and not really a workaround.
