### ISSUE TITLE
How to save the authentication results to database?

### ISSUE THREAD

**Issue by unliftedq** [aspnet-contrib/AspNet.Security.OAuth.Providers#697]
I'd like to to use `AspNet.Security.OAuth.GitHub` to support GitHub account login. And when the authentication completed, I'll check if it's a new user to my application, I'd like to save the entity to database if it's a new user. Where should I put such logic? Is there any good example?

**Comment by kinosang** [comment]
RTFM, https://docs.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-6.0

With Asp.Net Identity: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-6.0&tabs=visual-studio
Without Asp.Net Identity: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/social-without-identity?view=aspnetcore-6.0

**Comment by martincostello** [comment]
This is for you to decide as part of the architecture of your application.

This question is too broad and out of the scope of the support we provide here as it's not specific to our providers, but is a question about the implementation of authentication in a .NET application in general.

I suggest looking at the documentation for [ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity) as a starting point for user management in your application. More specific targeted questions when you're further along could be asked of the community on StackOverflow.

**Comment by unliftedq** [comment]
@kinosang @martincostello Thanks for your feedback, basically, I think there should be done in some callback provided by these OAuth providers. Or is it built in with Asp.Net Identity?

**Comment by kinosang** [comment]
your question is out-of-scoop of aspnet-contrib providers. the provider struct is designed and maintained by the asp.net core team. plz consider submit technology support ticket to Microsoft support team or RTFM.

**Comment by kinosang** [comment]
the providers themselves only deal with the "External Sign-in", and inject claims. use your own codes to do "sign-up" or "sign-in" if you do not use Asp.Net Identity.

https://www.google.com/search?q=asp.net+core+external+provider+without+identity
