### ISSUE TITLE
Add Flickr provider

### ISSUE THREAD

**Issue by jerriep** [aspnet-contrib/AspNet.Security.OAuth.Providers#7]

**Comment by Gekctek** [comment]
Flickr seems to only support OAuth 1a and not OAuth 2 from what I can tell. Is this still something that you would want implemented?

**Comment by jerriep** [comment]
My opinion is that it belongs in this repo, but yeah you would not be able to make use of all the OAuth 2 base classes. You will need to do the heavy lifting yourself.

AFAIK the Twitter provider is also based on OAuth 1a, so you can use that as a starting point.

**Comment by samjudson** [comment]
I should be able to help with this - I wrong the FlickrNet API library, so I know more than anyone should about how Flickr's Oauth works :)

**Comment by serber** [comment]
Flickr also does not support OAuth 2.0
https://www.flickr.com/services/api/auth.oauth.html

**Comment by PinpointTownes** [comment]
@serber thanks!
