### ISSUE TITLE
Add missing code documentation

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet-contrib/AspNet.Security.OAuth.Providers#71]
/cc @jerriep

**Comment by jerriep** [comment]
@PinpointTownes What was your idea in terms of documentation? What level of docs do you want?

**Comment by PinpointTownes** [comment]
Just basic XML documentation, mainly in the IApplicationBuilder extensions: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/dev/src/AspNet.Security.OAuth.ArcGIS/ArcGISAuthenticationExtensions.cs.

**Comment by jerriep** [comment]
Yeah, I can help with that. Can you give me a timeframe of when you want this done?

**Comment by PinpointTownes** [comment]
Thanks! :clap: 

Unfortunately, we have no precise date for ASP.NET Core RC2, but I'd say we have at least 2 weeks for that.

**Comment by jerriep** [comment]
OK. I'm busy migrating to Asia again, but I'll try and fit it in for you somewhere

**Comment by PinpointTownes** [comment]
Thanks Jerrie! :+1:

**Comment by PinpointTownes** [comment]
@jerriep FYI, the RC2 packages are being finalized ATM. Do you think you'll have time to work on the XML documentation?

Thanks :+1:

**Comment by jerriep** [comment]
I will do this tomorrow (Saturday). I have a lot of stuff to catch up on personal projects, so I think it is best to get my head down this weekend and get it all done...

**Comment by PinpointTownes** [comment]
Done: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/9d0725577bd527807fa1dd3ea6fd48259c04b5ff :clap:
