### ISSUE TITLE
Restoring the packages doesn't work

### ISSUE THREAD

**Issue by Haythem** [aspnet-contrib/AspNet.Security.OAuth.Providers#72]
Restoring any of the published packages is no longer working because of the dependency of `System.Dynamic.Runtime`. Please update the project dependencies and rebuild them against the `rc1-final` packages.

**Comment by Haythem** [comment]
Can you please go side by side with Asp.Net packages versions ? I know that the project is WIP but setting the same version is more semantic.

**Comment by PinpointTownes** [comment]
AFAICT, this problem only impacts the GitHub middleware, which is the only one using `System.Dynamic.Runtime`. Sadly, NuGet.org doesn't allow removing a package to republish it, so downloading the right dependency yourself is currently the only option:

https://www.myget.org/F/aspnetvnext/api/v2/package/System.Dynamic.Runtime/4.0.11-rc2-23519

**Comment by PinpointTownes** [comment]
> Can you please go side by side with Asp.Net packages versions ? I know that the project is WIP but setting the same version is more semantic.

Heh no, it has nothing to do with semantic, just with convenience :smile:

I agree it would make your life easier, but it would tie our development timeline to ASP.NET 5's roadmap, which is definitely not what we want (the CLR team shares the same concerns, and so do the Glimpse authors: https://www.nuget.org/packages/Glimpse/2.0.0-beta1)

**Comment by Haythem** [comment]
Thanks for your blazing fast support. I'll add the dependency manually through the `project.json` file. I'll keep you posted.

**Comment by PinpointTownes** [comment]
FYI, I sent a ticket to the NuGet gallery team to remove the buggy package. I hope they will consider it serious enough to accept it.

**Comment by PinpointTownes** [comment]
The NuGet gallery team refused to remove the buggy package. We'll have to push a new version to fix that.

**Comment by jerriep** [comment]
@PinpointTownes Did they explain their reasoning for not allowing removal of packages?

**Comment by somewhatabstract** [comment]
@PinpointTownes That version of `System.Dynamic.Runtime` isn't even available anymore.

**Comment by PinpointTownes** [comment]
> @PinpointTownes Did they explain their reasoning for not allowing removal of packages?

They pretended it would have broken people (which was wrong, as the package couldn't be used correctly, anyway).

The alpha4 package (for RC2) won't be affected, because I pinned the right version when building the packages this time: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/master/src/AspNet.Security.OAuth.GitHub/project.json#L45 :smile:
