### ISSUE TITLE
fix(AspNet.Security.OAuth.Weixin):WeixinAuthenticationHandler BuildChallengeUrl method has a error: state too long

### ISSUE THREAD

**Issue by wuweilaiya** [aspnet-contrib/AspNet.Security.OAuth.Providers#723]
### Describe the bug

WeixinAuthenticationHandler BuildChallengeUrl method has a error: state too long,But I see you guys have solved this problem
![image](https://user-images.githubusercontent.com/30889371/190327977-8c0f48b1-3f30-4b08-9b44-c2b584c2a58d.png)
I think !IsWeixinAuthorizationEndpointInUse() should change to IsWeixinAuthorizationEndpointInUse()，why if(!IsWeixinAuthorizationEndpointInUse())

### System information

- OS: [e.g. Windows 10]
- Library Version [e.g. 6.0.1]
- .NET version (6)

**Comment by LeaFrock** [comment]
It's not a bug. These codes are imported by PR #262. Due to some historical reasons, wechat provides several auth-ways for different web apps. You can read these two docs below,

1、https://developers.weixin.qq.com/doc/oplatform/Website_App/WeChat_Login/Wechat_Login.html (`WeixinAuthenticationDefaults.AuthorizationEndpoint`, which an user should scan a QR Code with his/her device to move on the auth)
2、https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_webpage_authorization.html (Another way for wechat official accounts)

As you can see, the second one, which the original PR aims to, says it limits the size of `state` in 128 bytes, when the default one does not mention it at all.  At the beginning, the codes were all right because the QR API did not (says it) have such a limit. But now the default one has an implicit limit (*I'm not sure whether the max size is 128 bytes*) of `state` because I met the same problem before as yours.

You have two solutions/workarounds,

1、Write your own implementation of `StateDataFormat`，which stores a session(GUID) with the actual content of your `properties` to a db/redis, and replace your current `state` with the session. So only the session is protected and transferred as `state`, and I'm sure it won't trigger the limit. When the `state` is returned by the callback, you can unprotect it and get the previous content by it.

2、Commit (or wait for) a PR to adjust it. But it's actually a break change since you will change the behavior of the default wechat authz-endpoint. 

Since these codes are working well for long versions/years, I'm not sure how big the impact is. We need to be cautious for changes. I'll do a test first when I have free time.

What do you think/suggest on this issue? @kinosang @saber-wang

**Comment by LeaFrock** [comment]
Well, I've done a test and find that the QR API also limits the length of `redirect_uri`.

The following is my query of sign-in URL:

![1665223811498](https://user-images.githubusercontent.com/20787265/194702392-caef2e9e-afc5-42d3-b247-d581796f5e1f.png)

And the page tells `redirect_uri param error`,

![1665223588215](https://user-images.githubusercontent.com/20787265/194702220-83ee2d9d-5896-42b4-ae86-1ce7f71e8887.png)

So if your state is too long, the way you want still does not work @15168440402 .

p.s. I find the [codes](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/6.0.11/src/AspNet.Security.OAuth.Weixin/WeixinAuthenticationHandler.cs#L34) in `HandleRemoteAuthenticateAsync` can do a small optimization. I'll make a PR to improve it.

**Comment by wuweilaiya** [comment]
@LeaFrock Thank you for your reply,I solved the problem by adopting your plan one.
![image](https://user-images.githubusercontent.com/30889371/195779231-d5ffd372-5637-489d-b8eb-1b0404261b1e.png)

**Comment by LeaFrock** [comment]
It's nothing.  If you can, please share your implementation of `StateDataFormat`, which may help others trapped in this issue. Or you just close this issue as it's been solved by you 😄.

**Comment by wuweilaiya** [comment]
1.Implement ISecureDataFormat<AuthenticationProperties>
![image](https://user-images.githubusercontent.com/30889371/195816512-4791149a-2351-4f21-b0ce-fc288b0ec3c2.png)
2.WeixinAuthenticationOptions.StateDataFormat = PropertiesDataFormatCache
![image](https://user-images.githubusercontent.com/30889371/195817057-4f433484-45fc-494a-a860-10dd20a86d22.png)

**Comment by martincostello** [comment]
Could you please post the code rather than screenshots of the code? People can then just copy and paste it, rather than have to type it all out by hand from reading the image.

**Comment by LeaFrock** [comment]
Well, I reorganize the codes based on @15168440402 .

```csharp
    public abstract class CachedStateDataFormat : ISecureDataFormat<AuthenticationProperties>
    {
        private const string CacheKeyPrefix = "AnyWordsYouLike:";

        public CachedStateDataFormat(IDataProtectionProvider provider)
        {
            Protector = provider.CreateProtector(typeof(CachedStateDataFormat).FullName);
        }

        protected IDataProtector Protector { get; }

        protected TimeSpan ExpiredTimeSpan { get; } = TimeSpan.FromMinutes(10);

        protected static string GetCacheKey(string guid) => CacheKeyPrefix + guid;

        public string Protect(AuthenticationProperties data) => Protect(data, default);

        public abstract string Protect(AuthenticationProperties data, string purpose);

        public AuthenticationProperties Unprotect(string protectedText) => Unprotect(protectedText, default);

        public abstract AuthenticationProperties Unprotect(string protectedText, string purpose);
    }

    internal class RedisCachedStateDataFormat : CachedStateDataFormat
    {
        private readonly DistributedCacheEntryOptions _cacheOpt;
        private readonly IDistributedCache _cache;

        public RedisCachedStateDataFormat(
            IDistributedCache cache,
            IDataProtectionProvider provider) : base(provider)
        {
            _cache = cache;
            _cacheOpt = new() { AbsoluteExpirationRelativeToNow = ExpiredTimeSpan };
        }

        public override string Protect(AuthenticationProperties data, string purpose)
        {
            var protector = Protector;
            if (!string.IsNullOrEmpty(purpose))
            {
                protector = protector.CreateProtector(purpose);
            }

            string uid = Guid.NewGuid().ToString("N");
            string cacheKey = GetCacheKey(uid);
            byte[] userData = PropertiesSerializer.Default.Serialize(data);
            _cache.Set(cacheKey, userData, _cacheOpt);

            return protector.Protect(uid);
        }

        public override AuthenticationProperties Unprotect(string protectedText, string purpose)
        {
            if (protectedText == null)
            {
                return default;
            }
            var protector = Protector;
            if (!string.IsNullOrEmpty(purpose))
            {
                protector = protector.CreateProtector(purpose);
            }

            try
            {
                var uid = protector.Unprotect(protectedText);
                if (string.IsNullOrEmpty(uid))
                {
                    return default;
                }
                string cacheKey = GetCacheKey(uid);
                var userData = _cache.Get(cacheKey);
                if (userData is null)
                {
                    return default;
                }
                _cache.Remove(cacheKey);
                return PropertiesSerializer.Default.Deserialize(userData);
            }
            catch
            {
                // TODO something ...
                return default;
            }
        }
    }

    internal class MemoryCachedStateDataFormat : CachedStateDataFormat
    {
        private readonly IMemoryCache _cache;

        public MemoryCachedStateDataFormat(
            IMemoryCache cache,
            IDataProtectionProvider provider) : base(provider)
        {
            _cache = cache;
        }

        public override string Protect(AuthenticationProperties data, string purpose)
        {
            var protector = Protector;
            if (!string.IsNullOrEmpty(purpose))
            {
                protector = protector.CreateProtector(purpose);
            }

            string uid = Guid.NewGuid().ToString("N");
            string cacheKey = GetCacheKey(uid);
            _cache.Set(cacheKey, data, ExpiredTimeSpan);

            return protector.Protect(uid);
        }

        public override AuthenticationProperties Unprotect(string protectedText, string purpose)
        {
            if (protectedText == null)
            {
                return default;
            }
            var protector = Protector;
            if (!string.IsNullOrEmpty(purpose))
            {
                protector = protector.CreateProtector(purpose);
            }

            string uid;
            try
            {
                uid = protector.Unprotect(protectedText);
            }
            catch
            {
                // TODO something ...
                return default;
            }
            if (string.IsNullOrEmpty(uid))
            {
                return default;
            }
            string cacheKey = GetCacheKey(uid);
            if (!_cache.TryGetValue(cacheKey, out AuthenticationProperties data))
            {
                return default;
            }
            _cache.Remove(cacheKey);
            return data;
        }
    }
```
