### ISSUE TITLE
AspNet.Security.OAuth.Apple 6.0.11 - "invalid_client" error after sign in on web application

### ISSUE THREAD

**Issue by appimpact** [aspnet-contrib/AspNet.Security.OAuth.Providers#724]
### Describe the bug

After recently (can't pinpoint since when), we've started to receive "invalid_client" on web applications that have Sign in with Apple implemented.

We didn't change anything related to Client ID, Team ID, Key ID or anything else and all applications have stopped to work at the same time.

We've read instructions on how to load .p8 key from string, but error still happens.

Sign in flow works partially:
* Users are taken properly to sign in screen of Apple
* Once the sign in is completed, users are correctly asked to provide consent to our application(s)
* Once the consent is given, we receive BadRequest with invalid_client in error property

### Steps To reproduce

In `ConfigureServices` method of `Startup.cs`, we add Apple authentication with placeholder values:

```
authBuilder.AddApple(options =>
{
	options.ClientId = "[CLIENT_ID]";
	options.ClientSecret = "[CLIENT_SECRET]";
	options.TeamId = "[TEAM_ID]";
	options.KeyId = "[KEY_ID]";
	options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
	options.Events = new AppleAuthenticationEvents
	{
		OnRemoteFailure = CreateRemoteFailureCallback(WellKnownVendor.Apple)
	};
});
```

Later in `Configure` method of `Startup.cs` we change placeholder values with actual values loaded from database.
`appleConfiguration` object contains all mandatory information and is used to replace placeholder values:

```
AppleAuthenticationOptions options = appleOptionsMonitor.Get(AppleAuthenticationDefaults.AuthenticationScheme);

options.ClientId = appleConfiguration.ClientId;
options.ClientSecret = null;
options.TeamId = appleConfiguration.AppleTeamId;
options.KeyId = appleConfiguration.AppleKeyId;

options.PrivateKey = async (_, _) =>
{
	return await Task.FromResult(appleConfiguration.AppleKey.Replace("\r","").AsMemory());
};

```

At the end, we call:

`appBuilder.UseAuthentication();`

### Actual behaviour

System.Exception: OAuth token endpoint failure: Status: BadRequest;Headers: Server: Apple\r\nDate: Mon, 26 Sep 2022 20:10:39 GMT\r\nConnection: keep-alive\r\nCache-Control: no-store\r\nPragma: no-cache\r\n;Body: {\"error\":\"invalid_client\"};

### System information

- OS: Windows 10
- Library Version: 6.0.11
- .NET version: 6.0.9

**Comment by martincostello** [comment]
My initial guess would be that you’re not mutating the “right” instance of the options to assign the correct values once you’ve fetched them from the database.

is the hash code of the two options objects identical?

I would also suggest trying an options callback like in the code example linked below to update the options to defer the configuration. In the case below it’s so that the configuration can be used after it’s fetched and bootstrapped from Azure Key Vault.

https://github.com/martincostello/SignInWithAppleSample/blob/bb2aacc8eb5bcd89564ccd34fe8e83d84bb46947/src/SignInWithApple/AuthenticationModule.cs#L27-L54

**Comment by appimpact** [comment]
@martincostello  Does not look like that is an issue.

We have removed post configuration and hardcoded values at the start:

```
authBuilder.AddApple(options =>
{
	options.ClientId = "XXXXXX";
	options.ClientSecret = string.Empty; // AT: Must remain, otherwise error is thrown.
	options.TeamId = "XXXXXXXXXX";
	options.KeyId = "XXXXXXXXXX";
	options.GenerateClientSecret = true;
	options.PrivateKey = async (_, _) =>
	{
		string key = "-----BEGIN PRIVATE KEY-----XXXXXXXXX-----END PRIVATE KEY-----";
		return await Task.FromResult(key.AsMemory());
	};

	options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
	options.Events = new AppleAuthenticationEvents
	{
		OnRemoteFailure = CreateRemoteFailureCallback(WellKnownVendor.Apple)
	};
});

```

Now we get different error:

```
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The system cannot find the file specified.\r\n   at System.Security.Cryptography.CngKeyLite.ImportKeyBlob(String blobType, ReadOnlySpan`1 keyBlob, Boolean encrypted, ReadOnlySpan`1 password)\r\n   at System.Security.Cryptography.CngPkcs8.ImportPkcs8(ReadOnlySpan`1 keyBlob)\r\n   at System.Security.Cryptography.CngPkcs8.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)\r\n   at System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)\r\n   at Internal.Cryptography.PemKeyImportHelpers.ImportPem(ReadOnlySpan`1 input, FindImportActionFunc callback)\r\n   at System.Security.Cryptography.ECDsa.ImportFromPem(ReadOnlySpan`1 input)\r\n   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.CreateAlgorithm(ReadOnlyMemory`1 pem)\r\n   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.GenerateNewSecretAsync(AppleGenerateClientSecretContext context)\r\n   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.<>c__DisplayClass5_0.<<GenerateAsync>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)\r\n   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.GenerateAsync(AppleGenerateClientSecretContext context)\r\n   at AspNet.Security.OAuth.Apple.AppleAuthenticationEvents.<>c.<<-ctor>b__10_0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at AspNet.Security.OAuth.Apple.AppleAuthenticationEvents.GenerateClientSecret(AppleGenerateClientSecretContext context)\r\n   at AspNet.Security.OAuth.Apple.AppleAuthenticationHandler.ExchangeCodeAsync(OAuthCodeExchangeContext context)\r\n   at AspNet.Security.OAuth.Apple.AppleAuthenticationHandler.HandleRemoteAuthenticateAsync(Dictionary`2 parameters)\r\n   at AspNet.Security.OAuth.Apple.AppleAuthenticationHandler.HandleRemoteAuthenticateAsync()\r\n   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
```

**Comment by martincostello** [comment]
Are you running in Azure App Service by any chance?

The user profile has to be loaded in order for the private key to be loaded into the process: https://github.com/martincostello/SignInWithAppleSample#azure-app-service-deployment

Otherwise Windows will throw file not found errors.

**Comment by appimpact** [comment]
@martincostello  You are a demigod at least.

With LoadUserProfile set to true in IIS, sign in was successful.

Do you mind keeping issue still open for a while so that we can confirm that our original code works as well?

It could be that we've missed this option:
options.GenerateClientSecret = true;

And once we added it, we got this file not found error - didn't know it is related to LoadUserProfile.

**Comment by appimpact** [comment]
@martincostello  Our order of execution def does not work properly.
We got different error related to validation of audience, so you were right there as well, we probably did have two instances of options class.

With your example on using .Configure method, we've managed to mitigate that error so everything works perfectly now.

Thank you so much for your assistance. 👍  :)

**Comment by martincostello** [comment]
No problem, glad you've gotten it working.
