### ISSUE TITLE
Patreon Error:  '.AspNetCore.Correlation.<ID>' cookie not found.

### ISSUE THREAD

**Issue by Mike-E-angelo** [aspnet-contrib/AspNet.Security.OAuth.Providers#726]
### Describe the bug

In addition to #725 there was a prior error that I was investigating that led to that one.  This one involves the following message when Patreon is challenged:

```
 '.AspNetCore.Correlation.<Identifier>' cookie not found.
```

### Steps To reproduce

Sign-in with Patreon account (deployed version here: https://alpha.starbeam.one/Identity/Account/Login?ReturnUrl=%2F)

### Expected behaviour

User can sign in

### Actual behaviour

User cannot sign in

### System information

- OS: Windows 10
- Library Version : 6.0.11
- .NET version (e.g. output from `dotnet --info`) `net6.0` hosted in Azure AppService

### Additional context

I did do a search on this error and it appears that this may be due to configuration.  However, I again can login successfully with the account that created the Patreon account as per #725.  In some capacity the entire workflow does work, so it does not appear to be a configuration issue.

Nonetheless, I am using the following to configure my Patreon Oauth2 application:
https://github.com/DragonSpark/Framework/blob/master/DragonSpark.Identity.Patreon/ConfigureAuthentication.cs

(Very straight forward but thought I would share)

**Comment by martincostello** [comment]
From anecdotal memory, these correlation cookie issues are often related to SameSite configuration issues.

**Comment by Mike-E-angelo** [comment]
Thank you for your reply @martincostello that is what I found with searching as well.  The perplexing part about this is that I am able to sign in with at least one account successfully.  If it was due to SameSite wouldn't that impact all accounts?

**Comment by kevinchalet** [comment]
An error mentioning the antiforgery cookie used by the base OAuth 2.0 handler is always the sign of an invalid configuration. As @martincostello said, an invalid same-site value is a potential root cause, but other reasons include a cookie lifetime that is too short or an invalid ASP.NET Core Data Protection (e.g the master keys are not correctly persisted).

Closing, as there's sadly nothing we can do on our end.

**Comment by alfeg** [comment]
Just to help those who will encounter same issue - check that Your site is running HTTPS. Those correlation cookies cannot be passed in via non secure protocol
