### ISSUE TITLE
GetExternalLoginInfoAsync returns null

### ISSUE THREAD

**Issue by DevTsjollin** [aspnet-contrib/AspNet.Security.OAuth.Providers#728]
GetExternalLoginInfoAsync from discord oauth returns null

**Comment by martincostello** [comment]
This is likely to be a bug in your code. 

However, there's no way to be able to tell either way as you have provided no example code or steps to reproduce.

Please provide a reproducible example of how your application is using the provider and in which circumstances you observe the unintended behaviour.
