### ISSUE TITLE
SuperOffice provider: UserInfo endpoint doesn't support multiple subdomains

### ISSUE THREAD

**Issue by SuperOfficeDevNet** [aspnet-contrib/AspNet.Security.OAuth.Providers#738]
### Describe the bug

Today, the provider expects the UserInfo endpoint data will come from one *environmental* subdomain, i.e.:

development: https://sod.superoffice.com
stage: https://quonline.superoffice.com.
production: https://online.superoffice.com.

SuperOffice CRM Online has introduced an API cluster that will publish API calls on different subdomains, i.e.:

https://**sod**.superoffice.com/
https://**sod1**.superoffice.com/
https://**sod2**.superoffice.com/

This affects how the UserInfo endpoint resolves and obtains profile-related details. The authorize and token endpoints are not affected.

A [PR](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/739) to fix this issue is in place.

**Comment by kevinchalet** [comment]
> SuperOffice CRM Online has introduced an API cluster that will publish API calls on different subdomains, i.e.:
> 
> https://**sod**.superoffice.com/ https://**sod1**.superoffice.com/ https://**sod2**.superoffice.com/
> 
> This affects how the UserInfo endpoint resolves and obtains profile-related details. The authorize and token endpoints are not affected.

Out of curiosity, why not adopting a more traditional approach with a single address and a reverse proxy setup doing that transparently? It's certainly something we can work around in the aspnet-contrib provider, but this clearly hurts interoperability (e.g the `userinfo` endpoint can't returned as part of the discovery document).

**Comment by SuperOfficeDevNet** [comment]
@kevinchalet Fair question, and it's simply legacy. Our OAuth/OIDC project began without prior knowledge of projects like openiddict and Identity Server. We are now adopting Duende Identity Server, so it shouldn't be too long before I revisit this again and use the more traditional approach.

**Comment by kevinchalet** [comment]
Haha, it's a good reason 🤣 

> We are now adopting Duende Identity Server, so it shouldn't be too long before I revisit this again and use the more traditional approach.

In this case, should we wait until you figure out what the final design will be, in case it would change again?

**Comment by SuperOfficeDevNet** [comment]
> In this case, should we wait until you figure out what the final design will be, in case it would change again?

It's not an easy 'swap and replace' job, so it may take months before we have completed retrofitting Duende Identity Server.

**Comment by SuperOfficeDevNet** [comment]
Request to reopen this issue... PR to follow.

**Comment by martincostello** [comment]
Fixed in #756.

**Comment by martincostello** [comment]
Thanks for you contribution - this fix is now available in the [6.0.15](https://www.nuget.org/packages/AspNet.Security.OAuth.SuperOffice/6.0.15) and [7.0.1](https://www.nuget.org/packages/AspNet.Security.OAuth.SuperOffice/7.0.1) releases.
