### ISSUE TITLE
Add ArcGIS provider

### ISSUE THREAD

**Issue by davetimmins** [aspnet-contrib/AspNet.Security.OAuth.Providers#74]
This was done for the old https://github.com/RockstarLabs/OwinOAuthProviders project so re-implementing here. @jerriep raised an issue for me a while back but I've only just got round to it sorry.

**Comment by PinpointTownes** [comment]
Done: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/af7c69a9ad65a98fbf6ad8057fe607cfc2724bf5 :tada: 

Thanks!

**Comment by rajivverma** [comment]
Hello,
I am unable to get it working.
```
            .AddArcGIS(options =>
            {
                options.ClientId = "<client-id>";
                options.ClientSecret = "<secret>";
            });
```
It gives me `error 400 Invalid redirect_uri`. I can ensure that the redirect URI 'https://localhost:44318/signin-arcgis' is registered into the application setting.

**Comment by rajivverma** [comment]
Please ignore my previous comment, there was a typo in the registered redirect URI. It is working fine!
