### ISSUE TITLE
Discord Provider access token issue

### ISSUE THREAD

**Issue by steveski** [aspnet-contrib/AspNet.Security.OAuth.Providers#740]
### Provider name
Discord

### Expected behavior
From my ASP.NET Core MVC front end I'm hitting my IdentityServer4 instance and using the Discord OAuth Provider to login. I'm then hitting a page in my app whose Controller will hit /users/@me/guilds and with that http call I'm passing the access token which I'm retrieving using `var accessToken = await HttpContext.GetTokenAsync("access_token");` but that returns a JWT which isn't actually supported by Discord API. Does this issue lie with this OAuth provider or with IS4 and in either case can I configure so as to keep the access token as returned by Discord rather than translate to a JWT?

### Actual behavior
When I hit Discord API I'm getting 401 Unauthorised.

### Steps to reproduce
ASP.NET Core MVC front end with and IdentityServer4 site offering external auth for Discord using AspNet.Security.OAuth.Discord.

My IS4 server in the Startup class is adding Discord support with
```
.AddDiscord("Discord", options =>
            {
                options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                options.ClientId = "xxx";
                options.ClientSecret = "yyy";
                options.Scope.Add("guilds");
            })
```

I've defined my MVC client in IS4 server with
```
new Client
            {
                ClientId = "mvctestclient",
                ClientSecrets =
                {
                    new Secret("some_mvc_secret".Sha256())
                },

                AllowedGrantTypes = GrantTypes.Code,
                AccessTokenType = AccessTokenType.Reference,

                // Where to redirect to after login
                RedirectUris =
                {
                    "https://localhost:5002/signin-oidc"
                },

                // Where to redirect to after logout
                PostLogoutRedirectUris = { "https://localhost:5002/signout-callback-oidc" },

                AllowedScopes = new List<string>
                {
                    IdentityServerConstants.StandardScopes.OpenId,
                    IdentityServerConstants.StandardScopes.Profile,
                    IdentityServerConstants.StandardScopes.Email,
                    IdentityServerConstants.StandardScopes.Address,
                    "guilds"
                }

            }
```

and provided an IdentityResource for the Discord guilds:
```
 public static IEnumerable<IdentityResource> IdentityResources =>
        new List<IdentityResource>
        { 
            new IdentityResources.OpenId(),
            new IdentityResources.Address(),
            new IdentityResources.Email(),
            new IdentityResources.Profile(),
            new  IdentityResource()
            {
                Name = "guilds",
                DisplayName = "Discord Guilds",
                Description = "All of the Discord Guilds the user belongs to",
                Required = true,
                Emphasize = true
            }
        };
```

and my client app MVC Controller is
```
public class GuildsController : Controller
    {
        public async Task<IActionResult> Index(CancellationToken cancellationToken)
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

            var uri = new Uri($"https://discord.com/api/v10/users/@me/guilds");

            var response = await client.GetAsync(uri, cancellationToken);

            return View();
        }
    }
```
and I get a 401 on the GetAsync call.
I've tried using `AccessTokenType = AccessTokenType.Reference` and not setting to default to JWT and it's the same in either case.

### Additional information
I've created a public repo with the VS solution https://github.com/steveski/AuthServer.Demo
You need to add you client id and secret and set the solution to start multiple projects.
![image](https://user-images.githubusercontent.com/6404476/198268659-c60866df-18af-4412-8948-aa271de7dee8.png)
 then click the Claims menu and select the Discord button on the signin page.

**Comment by martincostello** [comment]
You _might_ need to set `SaveTokens = true` on the Discord options so that the Discord-specific token is retained in the authentication properties, then you could fetch that rather than get the JWT maybe.

I'm not really familiar with the interactions between our provider and IdentityServerv4 - @kevinchalet might know the answer if `SaveTokens` doesn't sort it for you.

**Comment by kevinchalet** [comment]
`var accessToken = await HttpContext.GetTokenAsync("access_token")` will always return the access token of your identity provider (a JWT for IdSrv), but not the access token of the external provider.

For that, you'd need to tweak IdSrv to store it as a special claim. I'm not familiar with IdSrv so you'll need to check their docs (or ask them for help, but since IdSrv4 will no longer be supported next month, well... 😄)
