### ISSUE TITLE
How do I reach you?

### ISSUE THREAD

**Issue by codematrix** [aspnet-contrib/AspNet.Security.OAuth.Providers#75]
Hi Kevin, I would like to contribute to the aspnet-contrib. You can reach me at ross_pellegrino@hotmail.com. I don't want to flood this message thread with the details of my project. I asked David Fowler but he asked me to contact you. 

Here's our discussion. https://github.com/aspnet/Diagnostics/issues/222
Also, here's a linked to the forked Asp.Net.Diagnostics project.
https://github.com/codematrix/Diagnostics

Thanks,
Ross

**Comment by PinpointTownes** [comment]
Hey @codematrix!

Thanks for your interest in the *aspnet-contrib* initiative.
I'll chat a bit with @davidfowl about your project and ping you tomorrow.

Thanks.

**Comment by codematrix** [comment]
Thanks Kevin!
