### ISSUE TITLE
Implement KOOK provider

### ISSUE THREAD

**Issue by gehongyan** [aspnet-contrib/AspNet.Security.OAuth.Providers#753]
This issue is created to track the work of adding support for the KOOK OAuth2 to this AspNet.Security.OAuth.Providers project.

The KOOK OAuth2 documentation can be found here:
> <https://developer.kookapp.cn/doc/oauth2> (_Simplified Chinese_ only)

The source code of the documentation can be found here:
> <https://github.com/kaiheila/api-docs> (_Simplified Chinese_ only)

Pages related to OAuth2 are listed here:
> OAuth2 Intro: <https://github.com/kaiheila/api-docs/blob/main/docs/zh-cn/oauth2.md> (_Simplified Chinese_ only)
> OAuth API: <https://github.com/kaiheila/api-docs/blob/main/docs/zh-cn/http/oauth.md> (_Simplified Chinese_ only)

**Comment by martincostello** [comment]
Thanks for your contribution - the new provider is now available from [NuGet.org](https://www.nuget.org/packages/AspNet.Security.OAuth.Kook/).
