### ISSUE TITLE
Ping Identity (PingOne)

### ISSUE THREAD

**Issue by drewkill32** [aspnet-contrib/AspNet.Security.OAuth.Providers#757]
### Which provider would you like support added for?

[PingOne](https://www.pingidentity.com/)

### Provider Documentation

[PingOne Adding an Application](https://docs.pingidentity.com/r/en-us/pingone/p1_add_app_worker)

### Are you willing to implement this provider yourself?
Yes

**Comment by martincostello** [comment]
Implemented by #758.

**Comment by martincostello** [comment]
Thanks for your contribution - this provider is now available from [NuGet.org](https://www.nuget.org/packages/AspNet.Security.OAuth.PingOne/7.0.1).
