### ISSUE TITLE
[WorkWeixin] doesn't work with multiple instances

### ISSUE THREAD

**Issue by Jeff-Tian** [aspnet-contrib/AspNet.Security.OAuth.Providers#759]
### Describe the bug

I integrated the WorkWeixin into Duende IdentityServer and deployed it into both Azure with a single instance and Okteto with multiple instances (2 pods). It works as expected in Azure as there is only a single instance. But it does NOT work for the Okteto one as there are 2 pods.

The error happens when the authorization part is done with Work Weixin and then called back:
![image](https://user-images.githubusercontent.com/3367820/215246070-9d90fff5-602f-4434-8034-c54ccedb40be.png)

### Steps To reproduce

1. Go to https://id6-jeff-tian.cloud.okteto.net/Account/Login
2. Select 企业微信
3. Scan the QR Code
4. Wait for the callback and see the error mentioned above

### Expected behaviour

Should log in successfully as with Azure deployment:

1. Go to http://id6.azurewebsites.net/Account/Login
2. Select 企业微信
3. Scan the QR Code
4. Wait for the callback and see the successfully logged-in page

### Actual behaviour

Error happens with https://id6-jeff-tian.cloud.okteto.net/Account/Login

### System information

.NET SDK (reflecting any global.json):
 Version:   6.0.301

### Additional context

Code repo: https://github.com/Jeff-Tian/IdentityServer

**Comment by kinosang** [comment]
Please consider have a look at WeCom Developer Docs, e.g. https://developer.work.weixin.qq.com/document/path/90313#%E9%94%99%E8%AF%AF%E7%A0%81%EF%BC%9A60020

**Comment by Jeff-Tian** [comment]
Thanks @kinosang !

Checked 60020 is related to the trusted IP settings. I compared the 2 apps regarding azure instance and okteto instance. My azure app doesn't require the trusted IP, wierd! But it is external which is not WorkWeixin provider's bug. Thanks again.

| [Azure App](http://id6.azurewebsites.net/Account/Login) in the Work Weixin | [Okteto App](https://id6-jeff-tian.cloud.okteto.net/Account/Login) in the Work Weixin |
| -------------------- | -------------------- |
| <img width="1462" alt="image" src="https://user-images.githubusercontent.com/3367820/215248467-4a0b8f65-594d-4903-b9ee-ada6877445a0.png"> | <img width="1440" alt="image" src="https://user-images.githubusercontent.com/3367820/215248501-f7d58029-3d21-469d-ad61-11b293d5c41a.png"> |

**Comment by Jeff-Tian** [comment]
Hi @kinosang sorry to ask again, but do you know how to get the external IP for a service?

I configured the trusted IP to `35.225.69.73` which was fetched by the `ping id6-jeff-tian.cloud.okteto.net` command.

But still, get the `60020` error.

<img width="941" alt="image" src="https://user-images.githubusercontent.com/3367820/215250066-56b18d88-cda5-49d3-aea0-98f9157d9a54.png">

Thanks in advance!

**Comment by kinosang** [comment]
@Jeff-Tian I have no idea, I haven't used Okteto.

maybe submit a support ticket to them.
