### ISSUE TITLE
ExternalLoginInfo is always null for Dropbox

### ISSUE THREAD

**Issue by darshannahar** [aspnet-contrib/AspNet.Security.OAuth.Providers#78]
I started with default web application template.

I added the below lines in Startup.cs
app.UseDropboxAuthentication(options =>
            {
                options.ClientId = "appId";
                options.ClientSecret = "appSecret";
                options.SaveTokensAsClaims = true;
                options.UserInformationEndpoint = "https://api.dropboxapi.com/1/account/info";
                options.TokenEndpoint = "https://api.dropboxapi.com/1/oauth2/token";
            });

Everything else is as per the default template.

However, in ExternalLoginCallback, await _signInManager.GetExternalLoginInfoAsync() always returns null.

**Comment by darshannahar** [comment]
I think the problem is in the Json keys the dropbox helper is looking for.
https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/dev/src/AspNet.Security.OAuth.Dropbox/DropboxAuthenticationHelper.cs

**Comment by PinpointTownes** [comment]
Hum yeah. According to the Dropbox documentation, the name corresponding to the identifier property is `uid`, not `id`: https://www.dropbox.com/developers-v1/core/docs#account-info

Could you please create a new app for me and send me the credentials via PM on Gitter? Just to make sure the suggested fix really works :smile:

**Comment by darshannahar** [comment]
Thanks. Sure. I will do that PM you the credentials and redirect-url.

**Comment by darshannahar** [comment]
Also dropbox seems to be recommending a different endpoint for api. The documents suggest https://api.dropboxapi.com and the DropboxAuthenticationDefaults.cs  has defaults set to https://api.dropbox.com. Though the default used seem to be working I guess dropbox may be looking to deprecate that in future.

**Comment by PinpointTownes** [comment]
Fixed: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/9e57c22471e9e164080b8936b44cf724c1f8ec7d

Thanks for reporting this bug! (I also replaced the default domain, per your suggestion) :clap:
