### ISSUE TITLE
Determine whether the Kloudless provider is still working

### ISSUE THREAD

**Issue by kevinchalet** [aspnet-contrib/AspNet.Security.OAuth.Providers#787]
Kloudless' APIs all return a HTTP 502 Bad Gateway error and the homepage seems to indicate that the services are no longer offered as the company was acquired by Netskope.

@kYann you're the one who contributed this provider. Do you know by any chance if the Kloudless provider is still working? 😃

**Comment by kYann** [comment]
Sorry I don't use it anymore

**Comment by kevinchalet** [comment]
No worries @kYann. Thanks for taking the time to reply 👍🏻
