### ISSUE TITLE
MyGet.org is down

### ISSUE THREAD

**Issue by martincostello** [aspnet-contrib/AspNet.Security.OAuth.Providers#792]
MyGet.org appears to be completely down (even [its docs site is offline](https://docs.myget.org)) and has been for [coming up to 24 hours](https://status.myget.org/) as of right now. There's no status updates on their Twitter feed at all, and a quick search suggests many frustrated users.

No one seems to know what's happened to it - it's almost as if they ran out of money and just turned it off and walked away.

Considering MyGet is part of the release process for this, and other, repos...what do we do?

Options include:

1. Ride it out - It'll come back up, right? Right??
2. Change to another prerelease package source. GitHub Packages is a _potential option_, but I've found it difficult to use in the past as it doesn't appear to support unauthenticated use (at least, it didn't last time I tried).
3. Not have a prerelease package source at all, but switch to a manual process to publish previews to NuGet.org when warranted.
4. ?

Thoughts @kevinchalet?

**Comment by kevinchalet** [comment]
> MyGet.org appears to be completely down (even [its docs site is offline](https://docs.myget.org)) and has been for [coming up to 24 hours](https://status.myget.org/) as of right now. There's no status updates on their Twitter feed at all, and a quick search suggests many frustrated users.

Yeah, it's very worrying (and it's not the first time there's a massive outage and zero announcement...)

Regarding the options, GitHub Packages not supporting public feeds makes it a very unattractive option. Removing MyGet and pushing previews manually to NuGet isn't very appealing either (additional/unwanted noise in the versions tab and the latest bits are not available immediately anyway...).

Hopefully, it should come back at some point (hopefully 😅). If it doesn't, we should probably consider an alternative, like CloudSmith (used by our friends at OrchardCore): the Pro plan is terribly expensive for a 5GB plan ($89/month 😟), but they do offer a free 25GB plan for OSS projects... if you ask them nicely 😄

**Comment by kevinchalet** [comment]
@martincostello does MyGet work for you? It seems pushing packages works fine, but all you get is a 404 response when you try to download them 😅

**Comment by martincostello** [comment]
I've only had any need to use read operations since it went down, and I've ripped it out of my own repos now so I don't know if push works 😄.

**Comment by kevinchalet** [comment]
I see 🤣 

Thanks.

**Comment by martincostello** [comment]
Status page suggests it's now not a total outage: https://status.myget.org/

**Comment by kevinchalet** [comment]
Given that MyGet is now operating normally, closing.

**Comment by arjung55** [comment]
MyGet still appears to be down—I’m getting a 404 error when trying to retrieve the published artifacts. Is anyone currently looking into this? It’s impacting our organization’s workflow.
Error message:
“A connection attempt failed because the connected party did not properly respond after a period of time, or the established connection failed because the host did not respond (dsi.myget.org:443).”

**Comment by kevinchalet** [comment]
> MyGet still appears to be down

"still" seems excessive to me as the current outage is quite recent (things started going south yesterday, AFAICT).
For a free service, it's not reasonable to expect a 100% availability guarantee.

Now, the real question is: why do you use the nightly builds repository?
