### ISSUE TITLE
Add Foursquare provider

### ISSUE THREAD

**Issue by jerriep** [aspnet-contrib/AspNet.Security.OAuth.Providers#8]

**Comment by abhinavnigam** [comment]
I am picking this

**Comment by PinpointTownes** [comment]
@abhinavnigam thanks! :+1:

**Comment by abhinavnigam** [comment]
Today I had done dnu restore after that getting below error, before that, it works fine.

System.InvalidOperationException: This application requires DNX version 1.0.0-beta8-15665 or newer to run.
Some package reference in MVC Client refer to version 1.0.0-beta8-15679 example -Microsoft.AspNet.Authentication.Google

Done dnvm upgrade -u but getting DNX version 1.0.0-beta8-15654. Can you please help me to get l required dnx version.

**Comment by abhinavnigam** [comment]
Added FourSquare oAuth Provider. Submit the Pull request. Please review and let me know if changes are required.

**Comment by PinpointTownes** [comment]
Done: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/f52afe385f1d672e9c443f420971359b8e36f0ed :+1:
