### ISSUE TITLE
Weixin use qrcode login

### ISSUE THREAD

**Issue by snowchenlei** [aspnet-contrib/AspNet.Security.OAuth.Providers#802]
for AspNet.Security.OAuth.Weixin:
[Wechat_Login](https://developers.weixin.qq.com/doc/oplatform/en/Website_App/WeChat_Login/Wechat_Login.html)
i need Instantiate the following JS object where you need to use Weixin login.
but i don't have state. will weixin redirect to '/signin-weixin' will get error 'The oauth state was missing or invalid.'.how to get/set state

**Comment by kevinchalet** [comment]
Starting the authorization flow browser-side via JS is not a supported scenario in any of the providers. The authorization dance MUST be initiated by the ASP.NET Core app for things to work correctly.

**Comment by snowchenlei** [comment]
> Starting the authorization flow browser-side via JS is not a supported scenario in any of the providers. The authorization dance MUST be initiated by the ASP.NET Core app for things to work correctly.

The page where qrcode is located is a razor page ASP.NET Core. Can you manually get/set the state in the OnGet method of the *.cs code?
