### ISSUE TITLE
I could not authenticate by Linkedin when I redirected to redirect_url after confirm linkedin page authentication

### ISSUE THREAD

**Issue by NaserParhizkar** [aspnet-contrib/AspNet.Security.OAuth.Providers#825]
It seams my problem is by
https://api.linkedin.com/v2/me url
because when I check all steps I able to get token by Postman and when I get information by
https://api.linkedin.com/v2/userinfo
every thing is good.
by the way I attached picture and I have scope openid profile email w_member_social .
Although I read in Microsoft document r_emailaddress or something like this and I don't know where
can I add those scopes.

**Comment by NaserParhizkar** [comment]
![linkedinAuth](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/assets/51522869/23152f2f-fc42-4de4-9b7e-68e5bbc227ff)

**Comment by NaserParhizkar** [comment]
It seams my problem is by 
https://api.linkedin.com/v2/me url 
because when I check all steps I able to get token by Postman and when I get information by 
https://api.linkedin.com/v2/userinfo
every thing is good.
by the way I attached picture and I have scope openid profile email w_member_social .
Although I read in Microsoft document r_emailaddress or something like this and I don't know where 
can I add those scopes.

**Comment by kevinchalet** [comment]
The LinkedIn integration in this repository currently targets the OAuth 2.0 service, not the newer service.

If you want to use the OpenID Connect endpoints, consider using the OpenIddict client and its LinkedIn web provider: https://documentation.openiddict.com/guides/getting-started/integrating-with-a-remote-server-instance.html
