### ISSUE TITLE
Targeting net46

### ISSUE THREAD

**Issue by stap123** [aspnet-contrib/AspNet.Security.OAuth.Providers#85]
Had a read through the repo but couldn't find anything so.

Does this work targeting net46? I have a project that targets net46 and the reference to

"AspNet.Security.OAuth.LinkedIn": "1.0.0-alpha3"

does not work with the error message "... does not support framework .NETFramework,Version=4.6"

Many thanks

**Comment by PinpointTownes** [comment]
All the alpha3 providers target `dnx451` instead of `net451` so you need to target `dnx46` to use them.

DNX being removed in the next version, the beta1 providers (for ASP.NET Core RC2) have been updated to use `net451`.
