### ISSUE TITLE
Sign in with Apple returns 'invalid_client' error for the first try

### ISSUE THREAD

**Issue by vstrizhakov** [aspnet-contrib/AspNet.Security.OAuth.Providers#876]
### Describe the bug

I can observe an issue with Apple provider when trying to sign in with it for the first time after starting the project, however the next attempts are successfull. 

### Steps To reproduce

1. Get the latest sample project for Apple provider: https://github.com/martincostello/SignInWithAppleSample
2. Setup configuration for Apple (Client Id, Key Id, Team Id and Private Key)
3. Launch the project and click 'Sign in with Apple'
4. After redirect to Apple ID authenticate there
5. You'll be redirected back to the callback path which is `/signin-apple`

### Expected behaviour

You should be redirected back to the main page of the project where authenticated user's details are shown:
![image](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/assets/32275531/0fab13f5-9230-45ba-9e4c-766ad6856e5e)

### Actual behaviour

On that page (`/signin-apple`) you'll get an exception which states OAuth provider return the 'invalid_client' error:
![image](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/assets/32275531/e1a67d9f-7ad6-4675-ab46-737ee37e0512)

### System information

- OS: Windows 11
- Library Version: 8.0.0
- .NET 8

### Additional context

After receiving the exception you can return to the main page and click 'Sign in with Apple' again - this time everything would go well.

**Comment by martincostello** [comment]
How exactly are you configuring the app? Env vars, JSON files, Key Vault, ...?

I have the sample project deployed with a mix of env vars and Key Vault with Azure App Service and haven't observed this behaviour.

**Comment by vstrizhakov** [comment]
ClientId, KeyId and TeamId are configured in appsettings.json and private
key .p8 file is placed right in the project folder. I run the project
locally through the ngrok

**Comment by vstrizhakov** [comment]
@martincostello I have an update regarding the issue - seems it is a machine-specific case and the cause is its clock being out of order for a little bit (however, time zone and time itself had been set automatically by Windows). Turning off and then on auto- toggles fixed the issue:
![image](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/assets/32275531/202083b9-5754-49fe-9fd8-344a1c72f800)

Sorry for disturbing you :)

[UPDATE]: Just a little clarification for others having the same problem: local clock affects the JWT token generated for Apple's client secret and its claims 'issued at' and 'valid not before' which seems to Apple recognising such a token as invalid.

**Comment by martincostello** [comment]
Glad you got it fixed - sounds like a classic clock-skew issue.
