### ISSUE TITLE
LinkedIn Authentication Fails

### ISSUE THREAD

**Issue by jni759** [aspnet-contrib/AspNet.Security.OAuth.Providers#900]
### Describe the bug

Created a new LinkedIn App. The default OAuth 2.0 scopes are "openid", "profile", "email", "w_member_social".
AspNet.Security.OAuth.LinkedIn requests "r_emailaddress" and "r_liteprofile" which results in an LinkedIn server error.

### Steps To reproduce

Create a new LinkedIn app and try using it.

### Expected behaviour

To be authenticated

### Actual behaviour

LinkedIn error "Bummer".

### System information

AspNet.Security.OAuth.LinkedIn 8.0.0

**Comment by martincostello** [comment]
#834

**Comment by martincostello** [comment]
This should be resolved by version 8.1.0.
